import { Faculty } from "@/types/university";
import { createDegreeId, createFacultyId } from "./base";

// Cape Peninsula University of Technology (CPUT) - Faculty Data
export const CPUT_FACULTIES: Faculty[] = [
  {
    id: createFacultyId("Faculty of Applied Sciences CPUT"),
    name: "Faculty of Applied Sciences",
    description: "Applied sciences, chemistry, and biotechnology programs",
    degrees: [
      {
        id: createDegreeId("Diploma in Analytical Chemistry CPUT"),
        name: "Diploma in Analytical Chemistry",
        faculty: "Applied Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Analytical chemistry and laboratory techniques",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Analytical Chemist",
          "Quality Control Analyst",
          "Laboratory Technician",
        ],
      },
      {
        id: createDegreeId("Diploma in Biotechnology CPUT"),
        name: "Diploma in Biotechnology",
        faculty: "Applied Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Biotechnology and biological applications",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Biotechnologist",
          "Research Scientist",
          "Quality Control Specialist",
        ],
      },
      {
        id: createDegreeId("Diploma in Food Technology CPUT"),
        name: "Diploma in Food Technology",
        faculty: "Applied Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Food science and technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Food Technologist",
          "Quality Assurance Manager",
          "Product Developer",
        ],
      },
      {
        id: createDegreeId("BTech Chemistry CPUT"),
        name: "Bachelor of Technology in Chemistry",
        faculty: "Applied Sciences",
        duration: "4 years",
        apsRequirement: 26,
        description: "Advanced chemistry and industrial applications",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Chemical Engineer",
          "Process Engineer",
          "Research Scientist",
        ],
      },
      {
        id: createDegreeId("BTech Environmental Health CPUT"),
        name: "Bachelor of Technology in Environmental Health",
        faculty: "Applied Sciences",
        duration: "4 years",
        apsRequirement: 24,
        description: "Environmental health and safety management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Environmental Health Officer",
          "Safety Manager",
          "Health Inspector",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Business and Management Sciences CPUT"),
    name: "Faculty of Business and Management Sciences",
    description: "Business, management, and commerce programs",
    degrees: [
      {
        id: createDegreeId("Diploma in Accounting CPUT"),
        name: "Diploma in Accounting",
        faculty: "Business and Management Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Accounting principles and financial management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Bookkeeper",
          "Accounting Clerk",
          "Financial Assistant",
        ],
      },
      {
        id: createDegreeId("Diploma in Management CPUT"),
        name: "Diploma in Management",
        faculty: "Business and Management Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Business management principles",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Supervisor",
          "Team Leader",
          "Operations Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma in Marketing CPUT"),
        name: "Diploma in Marketing",
        faculty: "Business and Management Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Marketing principles and consumer behavior",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Marketing Assistant",
          "Sales Representative",
          "Brand Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma in Human Resources CPUT"),
        name: "Diploma in Human Resources Management",
        faculty: "Business and Management Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Human resource management and industrial relations",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "HR Assistant",
          "Recruitment Officer",
          "Training Coordinator",
        ],
      },
      {
        id: createDegreeId("BTech Business Administration CPUT"),
        name: "Bachelor of Technology in Business Administration",
        faculty: "Business and Management Sciences",
        duration: "4 years",
        apsRequirement: 24,
        description: "Advanced business administration and management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Business Manager",
          "Operations Manager",
          "Project Manager",
        ],
      },
      {
        id: createDegreeId("BTech Financial Management CPUT"),
        name: "Bachelor of Technology in Financial Management",
        faculty: "Business and Management Sciences",
        duration: "4 years",
        apsRequirement: 26,
        description: "Financial management and investment analysis",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Financial Manager",
          "Investment Analyst",
          "Treasury Officer",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Engineering CPUT"),
    name: "Faculty of Engineering",
    description: "Engineering and technology programs",
    degrees: [
      {
        id: createDegreeId("Diploma in Civil Engineering CPUT"),
        name: "Diploma in Civil Engineering",
        faculty: "Engineering",
        duration: "3 years",
        apsRequirement: 26,
        description: "Civil engineering and construction technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Civil Technician",
          "Construction Manager",
          "Project Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma in Electrical Engineering CPUT"),
        name: "Diploma in Electrical Engineering",
        faculty: "Engineering",
        duration: "3 years",
        apsRequirement: 26,
        description: "Electrical engineering and power systems",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Electrical Technician",
          "Power Systems Engineer",
          "Maintenance Engineer",
        ],
      },
      {
        id: createDegreeId("Diploma in Mechanical Engineering CPUT"),
        name: "Diploma in Mechanical Engineering",
        faculty: "Engineering",
        duration: "3 years",
        apsRequirement: 26,
        description: "Mechanical engineering and manufacturing",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Mechanical Technician",
          "Manufacturing Engineer",
          "Design Engineer",
        ],
      },
      {
        id: createDegreeId("Diploma in Chemical Engineering CPUT"),
        name: "Diploma in Chemical Engineering",
        faculty: "Engineering",
        duration: "3 years",
        apsRequirement: 26,
        description: "Chemical engineering and process technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Chemical Technician",
          "Process Engineer",
          "Plant Operator",
        ],
      },
      {
        id: createDegreeId("BTech Civil Engineering CPUT"),
        name: "Bachelor of Technology in Civil Engineering",
        faculty: "Engineering",
        duration: "4 years",
        apsRequirement: 28,
        description: "Advanced civil engineering and project management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Civil Engineer",
          "Structural Engineer",
          "Project Manager",
        ],
      },
      {
        id: createDegreeId("BTech Electrical Engineering CPUT"),
        name: "Bachelor of Technology in Electrical Engineering",
        faculty: "Engineering",
        duration: "4 years",
        apsRequirement: 28,
        description: "Advanced electrical engineering and automation",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Electrical Engineer",
          "Control Systems Engineer",
          "Power Engineer",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Health and Wellness Sciences CPUT"),
    name: "Faculty of Health and Wellness Sciences",
    description: "Health sciences, nursing, and wellness programs",
    degrees: [
      {
        id: createDegreeId("Diploma in Nursing CPUT"),
        name: "Diploma in Nursing",
        faculty: "Health and Wellness Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Professional nursing qualification",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Staff Nurse",
          "Community Nurse",
          "Clinical Assistant",
        ],
      },
      {
        id: createDegreeId("Bachelor of Nursing CPUT"),
        name: "Bachelor of Nursing",
        faculty: "Health and Wellness Sciences",
        duration: "4 years",
        apsRequirement: 28,
        description: "Comprehensive nursing education and practice",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Registered Nurse",
          "Clinical Nurse",
          "Nurse Manager",
        ],
      },
      {
        id: createDegreeId("Diploma in Radiography CPUT"),
        name: "Diploma in Radiography",
        faculty: "Health and Wellness Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Medical imaging and radiographic technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Radiographer",
          "Medical Imaging Technologist",
          "Radiation Therapist",
        ],
      },
      {
        id: createDegreeId("Diploma in Emergency Medical Care CPUT"),
        name: "Diploma in Emergency Medical Care",
        faculty: "Health and Wellness Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Emergency medical services and paramedic training",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Paramedic",
          "Emergency Medical Technician",
          "Critical Care Practitioner",
        ],
      },
      {
        id: createDegreeId("BTech Biomedical Technology CPUT"),
        name: "Bachelor of Technology in Biomedical Technology",
        faculty: "Health and Wellness Sciences",
        duration: "4 years",
        apsRequirement: 26,
        description: "Biomedical engineering and medical device technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Biomedical Engineer",
          "Medical Device Technician",
          "Clinical Engineer",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Informatics and Design CPUT"),
    name: "Faculty of Informatics and Design",
    description: "Information technology, design, and digital media programs",
    degrees: [
      {
        id: createDegreeId("Diploma in Information Technology CPUT"),
        name: "Diploma in Information Technology",
        faculty: "Informatics and Design",
        duration: "3 years",
        apsRequirement: 24,
        description: "Information technology and computer systems",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 3, isRequired: false },
        ],
        careerProspects: [
          "IT Support Technician",
          "Network Administrator",
          "Systems Analyst",
        ],
      },
      {
        id: createDegreeId("Diploma in Software Development CPUT"),
        name: "Diploma in Software Development",
        faculty: "Informatics and Design",
        duration: "3 years",
        apsRequirement: 24,
        description: "Software programming and application development",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 3, isRequired: false },
        ],
        careerProspects: ["Software Developer", "Programmer", "Web Developer"],
      },
      {
        id: createDegreeId("Diploma in Graphic Design CPUT"),
        name: "Diploma in Graphic Design",
        faculty: "Informatics and Design",
        duration: "3 years",
        apsRequirement: 22,
        description: "Visual communication and graphic design",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: false },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Graphic Designer",
          "Visual Designer",
          "Creative Director",
        ],
      },
      {
        id: createDegreeId("Diploma in Web Design CPUT"),
        name: "Diploma in Web Design and Development",
        faculty: "Informatics and Design",
        duration: "3 years",
        apsRequirement: 22,
        description: "Web design and user experience development",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: false },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Web Designer",
          "UX/UI Designer",
          "Front-end Developer",
        ],
      },
      {
        id: createDegreeId("BTech Information Technology CPUT"),
        name: "Bachelor of Technology in Information Technology",
        faculty: "Informatics and Design",
        duration: "4 years",
        apsRequirement: 26,
        description: "Advanced information technology and system management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: false },
        ],
        careerProspects: [
          "IT Manager",
          "Systems Architect",
          "Technology Consultant",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Education and Social Sciences CPUT"),
    name: "Faculty of Education and Social Sciences",
    description: "Teacher education and social sciences programs",
    degrees: [
      {
        id: createDegreeId("Diploma in Early Childhood Development CPUT"),
        name: "Diploma in Early Childhood Development",
        faculty: "Education and Social Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Early childhood education and development",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "ECD Practitioner",
          "Preschool Teacher",
          "Child Development Specialist",
        ],
      },
      {
        id: createDegreeId("BEd Foundation Phase CPUT"),
        name: "BEd Foundation Phase",
        faculty: "Education and Social Sciences",
        duration: "4 years",
        apsRequirement: 24,
        description: "Teacher education for foundation phase (Grades R-3)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: ["Foundation Phase Teacher", "Primary School Teacher"],
      },
      {
        id: createDegreeId("BTech Education CPUT"),
        name: "Bachelor of Technology in Education",
        faculty: "Education and Social Sciences",
        duration: "4 years",
        apsRequirement: 24,
        description: "Technical and vocational education",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Vocational Teacher",
          "Technical Trainer",
          "Education Coordinator",
        ],
      },
    ],
  },
];
