import { Faculty } from "@/types/university";
import { createDegreeId, createFacultyId } from "./base";

// Central University of Technology (CUT) - Faculty Data
export const CUT_FACULTIES: Faculty[] = [
  {
    id: createFacultyId(
      "Faculty of Engineering and Information Technology CUT",
    ),
    name: "Faculty of Engineering and Information Technology",
    description: "Engineering, technology, and information systems programs",
    degrees: [
      {
        id: createDegreeId("Diploma in Civil Engineering CUT"),
        name: "Diploma in Civil Engineering",
        faculty: "Engineering and Information Technology",
        duration: "3 years",
        apsRequirement: 26,
        description: "Civil engineering and construction technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Civil Technician",
          "Construction Manager",
          "Project Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma in Electrical Engineering CUT"),
        name: "Diploma in Electrical Engineering",
        faculty: "Engineering and Information Technology",
        duration: "3 years",
        apsRequirement: 26,
        description: "Electrical engineering and power systems",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Electrical Technician",
          "Power Systems Engineer",
          "Maintenance Engineer",
        ],
      },
      {
        id: createDegreeId("Diploma in Mechanical Engineering CUT"),
        name: "Diploma in Mechanical Engineering",
        faculty: "Engineering and Information Technology",
        duration: "3 years",
        apsRequirement: 26,
        description: "Mechanical engineering and manufacturing technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Mechanical Technician",
          "Manufacturing Engineer",
          "Design Engineer",
        ],
      },
      {
        id: createDegreeId("Diploma in Information Technology CUT"),
        name: "Diploma in Information Technology",
        faculty: "Engineering and Information Technology",
        duration: "3 years",
        apsRequirement: 24,
        description: "Computer systems and information technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 3, isRequired: false },
        ],
        careerProspects: [
          "IT Support Technician",
          "Network Administrator",
          "Systems Analyst",
        ],
      },
      {
        id: createDegreeId("BTech Civil Engineering CUT"),
        name: "Bachelor of Technology in Civil Engineering",
        faculty: "Engineering and Information Technology",
        duration: "4 years",
        apsRequirement: 28,
        description: "Advanced civil engineering and project management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Civil Engineer",
          "Structural Engineer",
          "Project Manager",
        ],
      },
      {
        id: createDegreeId("BTech Information Technology CUT"),
        name: "Bachelor of Technology in Information Technology",
        faculty: "Engineering and Information Technology",
        duration: "4 years",
        apsRequirement: 26,
        description: "Advanced information technology and systems management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: false },
        ],
        careerProspects: [
          "IT Manager",
          "Systems Architect",
          "Technology Consultant",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Management Sciences CUT"),
    name: "Faculty of Management Sciences",
    description: "Business, management, and commerce programs",
    degrees: [
      {
        id: createDegreeId("Diploma in Accounting CUT"),
        name: "Diploma in Accounting",
        faculty: "Management Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Accounting principles and financial management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Bookkeeper",
          "Accounting Clerk",
          "Financial Assistant",
        ],
      },
      {
        id: createDegreeId("Diploma in Business Management CUT"),
        name: "Diploma in Business Management",
        faculty: "Management Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Business administration and management principles",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Supervisor",
          "Team Leader",
          "Operations Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma in Marketing CUT"),
        name: "Diploma in Marketing",
        faculty: "Management Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Marketing principles and consumer behavior",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Marketing Assistant",
          "Sales Representative",
          "Brand Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma in Human Resources CUT"),
        name: "Diploma in Human Resources Management",
        faculty: "Management Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Human resource management and industrial relations",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "HR Assistant",
          "Recruitment Officer",
          "Training Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma in Public Management CUT"),
        name: "Diploma in Public Management",
        faculty: "Management Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Public administration and government management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Public Administrator",
          "Municipal Officer",
          "Government Official",
        ],
      },
      {
        id: createDegreeId("BTech Business Administration CUT"),
        name: "Bachelor of Technology in Business Administration",
        faculty: "Management Sciences",
        duration: "4 years",
        apsRequirement: 24,
        description:
          "Advanced business administration and strategic management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Business Manager",
          "Operations Manager",
          "Strategic Planner",
        ],
      },
      {
        id: createDegreeId("BTech Financial Management CUT"),
        name: "Bachelor of Technology in Financial Management",
        faculty: "Management Sciences",
        duration: "4 years",
        apsRequirement: 26,
        description: "Financial management and investment analysis",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Financial Manager",
          "Investment Analyst",
          "Treasury Officer",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Health and Environmental Sciences CUT"),
    name: "Faculty of Health and Environmental Sciences",
    description:
      "Health sciences, environmental studies, and agricultural programs",
    degrees: [
      {
        id: createDegreeId("Diploma in Environmental Health CUT"),
        name: "Diploma in Environmental Health",
        faculty: "Health and Environmental Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Environmental health and public health management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Environmental Health Officer",
          "Health Inspector",
          "Public Health Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma in Clinical Technology CUT"),
        name: "Diploma in Clinical Technology",
        faculty: "Health and Environmental Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Clinical laboratory technology and diagnostics",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Clinical Technologist",
          "Laboratory Manager",
          "Diagnostic Specialist",
        ],
      },
      {
        id: createDegreeId("Diploma in Agriculture CUT"),
        name: "Diploma in Agriculture",
        faculty: "Health and Environmental Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Agricultural production and farm management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Agricultural Officer",
          "Farm Manager",
          "Extension Officer",
        ],
      },
      {
        id: createDegreeId("BTech Environmental Health CUT"),
        name: "Bachelor of Technology in Environmental Health",
        faculty: "Health and Environmental Sciences",
        duration: "4 years",
        apsRequirement: 26,
        description: "Advanced environmental health and safety management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Environmental Health Manager",
          "Safety Manager",
          "Public Health Specialist",
        ],
      },
      {
        id: createDegreeId("BTech Clinical Technology CUT"),
        name: "Bachelor of Technology in Clinical Technology",
        faculty: "Health and Environmental Sciences",
        duration: "4 years",
        apsRequirement: 28,
        description: "Advanced clinical laboratory technology and management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Senior Clinical Technologist",
          "Laboratory Director",
          "Research Scientist",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Humanities CUT"),
    name: "Faculty of Humanities",
    description: "Liberal arts, languages, and communication programs",
    degrees: [
      {
        id: createDegreeId("Diploma in Language Practice CUT"),
        name: "Diploma in Language Practice",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 23,
        description: "Language editing, translation, and communication",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: ["Language Practitioner", "Editor", "Translator"],
      },
      {
        id: createDegreeId("Diploma in Journalism CUT"),
        name: "Diploma in Journalism",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 24,
        description: "Print and digital journalism",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: ["Journalist", "Reporter", "News Editor"],
      },
      {
        id: createDegreeId("Diploma in Communication CUT"),
        name: "Diploma in Communication",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 23,
        description: "Communication theory and media studies",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Communications Officer",
          "Media Coordinator",
          "Public Relations Assistant",
        ],
      },
      {
        id: createDegreeId("BTech Language Practice CUT"),
        name: "Bachelor of Technology in Language Practice",
        faculty: "Humanities",
        duration: "4 years",
        apsRequirement: 24,
        description:
          "Advanced language practice and professional communication",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Senior Language Practitioner",
          "Translation Manager",
          "Communication Specialist",
        ],
      },
    ],
  },
];
