import { Faculty } from "@/types/university";
import { createDegreeId, createFacultyId } from "./base";

// Durban University of Technology (DUT) - Faculty Data
export const DUT_FACULTIES: Faculty[] = [
  {
    id: createFacultyId("Faculty of Accounting and Informatics DUT"),
    name: "Faculty of Accounting and Informatics",
    description: "Accounting, finance, and information technology programs",
    degrees: [
      {
        id: createDegreeId("Diploma in Accounting DUT"),
        name: "Diploma in Accounting",
        faculty: "Accounting and Informatics",
        duration: "3 years",
        apsRequirement: 24,
        description: "Accounting principles and financial management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Bookkeeper",
          "Accounting Clerk",
          "Financial Assistant",
        ],
      },
      {
        id: createDegreeId("Diploma in Financial Information Systems DUT"),
        name: "Diploma in Financial Information Systems",
        faculty: "Accounting and Informatics",
        duration: "3 years",
        apsRequirement: 24,
        description: "Financial systems and information technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Financial Systems Analyst",
          "Database Administrator",
          "Financial Consultant",
        ],
      },
      {
        id: createDegreeId("Diploma in Information Technology DUT"),
        name: "Diploma in Information Technology",
        faculty: "Accounting and Informatics",
        duration: "3 years",
        apsRequirement: 24,
        description: "Computer systems and software development",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 3, isRequired: false },
        ],
        careerProspects: [
          "IT Support Technician",
          "Software Developer",
          "Systems Analyst",
        ],
      },
      {
        id: createDegreeId("BTech Accounting DUT"),
        name: "Bachelor of Technology in Accounting",
        faculty: "Accounting and Informatics",
        duration: "4 years",
        apsRequirement: 26,
        description: "Advanced accounting and financial management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Senior Accountant",
          "Financial Manager",
          "Management Accountant",
        ],
      },
      {
        id: createDegreeId("BTech Information Technology DUT"),
        name: "Bachelor of Technology in Information Technology",
        faculty: "Accounting and Informatics",
        duration: "4 years",
        apsRequirement: 26,
        description: "Advanced information technology and systems management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: false },
        ],
        careerProspects: [
          "IT Manager",
          "Systems Architect",
          "Technology Consultant",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Applied Sciences DUT"),
    name: "Faculty of Applied Sciences",
    description: "Chemistry, biotechnology, and applied sciences programs",
    degrees: [
      {
        id: createDegreeId("Diploma in Analytical Chemistry DUT"),
        name: "Diploma in Analytical Chemistry",
        faculty: "Applied Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Chemical analysis and laboratory techniques",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Analytical Chemist",
          "Quality Control Analyst",
          "Laboratory Technician",
        ],
      },
      {
        id: createDegreeId("Diploma in Biotechnology DUT"),
        name: "Diploma in Biotechnology",
        faculty: "Applied Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Biotechnology and biological applications",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Biotechnologist",
          "Research Scientist",
          "Quality Control Specialist",
        ],
      },
      {
        id: createDegreeId("Diploma in Food Technology DUT"),
        name: "Diploma in Food Technology",
        faculty: "Applied Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Food science and processing technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Food Technologist",
          "Quality Assurance Manager",
          "Product Developer",
        ],
      },
      {
        id: createDegreeId("BTech Chemistry DUT"),
        name: "Bachelor of Technology in Chemistry",
        faculty: "Applied Sciences",
        duration: "4 years",
        apsRequirement: 26,
        description: "Advanced chemistry and industrial applications",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Chemical Engineer",
          "Process Engineer",
          "Research Scientist",
        ],
      },
      {
        id: createDegreeId("BTech Biotechnology DUT"),
        name: "Bachelor of Technology in Biotechnology",
        faculty: "Applied Sciences",
        duration: "4 years",
        apsRequirement: 26,
        description: "Advanced biotechnology and bioprocessing",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Senior Biotechnologist",
          "Research Manager",
          "Product Development Manager",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Arts and Design DUT"),
    name: "Faculty of Arts and Design",
    description: "Creative arts, design, and communication programs",
    degrees: [
      {
        id: createDegreeId("Diploma in Graphic Design DUT"),
        name: "Diploma in Graphic Design",
        faculty: "Arts and Design",
        duration: "3 years",
        apsRequirement: 22,
        description: "Visual communication and graphic design",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: false },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Graphic Designer",
          "Visual Designer",
          "Creative Director",
        ],
      },
      {
        id: createDegreeId("Diploma in Fashion Design DUT"),
        name: "Diploma in Fashion Design",
        faculty: "Arts and Design",
        duration: "3 years",
        apsRequirement: 22,
        description: "Fashion design and clothing technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: false },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Fashion Designer",
          "Pattern Maker",
          "Fashion Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma in Interior Design DUT"),
        name: "Diploma in Interior Design",
        faculty: "Arts and Design",
        duration: "3 years",
        apsRequirement: 22,
        description: "Interior design and space planning",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: false },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Interior Designer",
          "Space Planner",
          "Design Consultant",
        ],
      },
      {
        id: createDegreeId("Diploma in Photography DUT"),
        name: "Diploma in Photography",
        faculty: "Arts and Design",
        duration: "3 years",
        apsRequirement: 22,
        description: "Photography and visual media",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: false },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Photographer",
          "Visual Media Specialist",
          "Photo Editor",
        ],
      },
      {
        id: createDegreeId("BTech Design DUT"),
        name: "Bachelor of Technology in Design",
        faculty: "Arts and Design",
        duration: "4 years",
        apsRequirement: 24,
        description: "Advanced design and creative direction",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: false },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Senior Designer",
          "Creative Director",
          "Design Manager",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Engineering and the Built Environment DUT"),
    name: "Faculty of Engineering and the Built Environment",
    description: "Engineering and construction programs",
    degrees: [
      {
        id: createDegreeId("Diploma in Civil Engineering DUT"),
        name: "Diploma in Civil Engineering",
        faculty: "Engineering and the Built Environment",
        duration: "3 years",
        apsRequirement: 26,
        description: "Civil engineering and construction technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Civil Technician",
          "Construction Manager",
          "Project Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma in Electrical Engineering DUT"),
        name: "Diploma in Electrical Engineering",
        faculty: "Engineering and the Built Environment",
        duration: "3 years",
        apsRequirement: 26,
        description: "Electrical engineering and power systems",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Electrical Technician",
          "Power Systems Engineer",
          "Maintenance Engineer",
        ],
      },
      {
        id: createDegreeId("Diploma in Mechanical Engineering DUT"),
        name: "Diploma in Mechanical Engineering",
        faculty: "Engineering and the Built Environment",
        duration: "3 years",
        apsRequirement: 26,
        description: "Mechanical engineering and manufacturing",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Mechanical Technician",
          "Manufacturing Engineer",
          "Design Engineer",
        ],
      },
      {
        id: createDegreeId("Diploma in Chemical Engineering DUT"),
        name: "Diploma in Chemical Engineering",
        faculty: "Engineering and the Built Environment",
        duration: "3 years",
        apsRequirement: 26,
        description: "Chemical engineering and process technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Chemical Technician",
          "Process Engineer",
          "Plant Operator",
        ],
      },
      {
        id: createDegreeId("BTech Civil Engineering DUT"),
        name: "Bachelor of Technology in Civil Engineering",
        faculty: "Engineering and the Built Environment",
        duration: "4 years",
        apsRequirement: 28,
        description: "Advanced civil engineering and project management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Civil Engineer",
          "Structural Engineer",
          "Project Manager",
        ],
      },
      {
        id: createDegreeId("BTech Electrical Engineering DUT"),
        name: "Bachelor of Technology in Electrical Engineering",
        faculty: "Engineering and the Built Environment",
        duration: "4 years",
        apsRequirement: 28,
        description: "Advanced electrical engineering and automation",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Electrical Engineer",
          "Control Systems Engineer",
          "Power Engineer",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Health Sciences DUT"),
    name: "Faculty of Health Sciences",
    description: "Health sciences and medical technology programs",
    degrees: [
      {
        id: createDegreeId("Diploma in Nursing DUT"),
        name: "Diploma in Nursing",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Professional nursing qualification",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Staff Nurse",
          "Community Nurse",
          "Clinical Assistant",
        ],
      },
      {
        id: createDegreeId("Diploma in Radiography DUT"),
        name: "Diploma in Radiography",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Medical imaging and radiographic technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Radiographer",
          "Medical Imaging Technologist",
          "Radiation Therapist",
        ],
      },
      {
        id: createDegreeId("Diploma in Dental Technology DUT"),
        name: "Diploma in Dental Technology",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Dental technology and prosthetics",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Dental Technician",
          "Dental Laboratory Manager",
          "Prosthetic Specialist",
        ],
      },
      {
        id: createDegreeId("BTech Nursing DUT"),
        name: "Bachelor of Technology in Nursing",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 28,
        description: "Advanced nursing practice and management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Registered Nurse",
          "Nurse Manager",
          "Clinical Specialist",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Management Sciences DUT"),
    name: "Faculty of Management Sciences",
    description: "Business management and entrepreneurship programs",
    degrees: [
      {
        id: createDegreeId("Diploma in Business Management DUT"),
        name: "Diploma in Business Management",
        faculty: "Management Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Business administration and management principles",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Supervisor",
          "Team Leader",
          "Operations Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma in Marketing DUT"),
        name: "Diploma in Marketing",
        faculty: "Management Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Marketing principles and consumer behavior",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Marketing Assistant",
          "Sales Representative",
          "Brand Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma in Human Resources DUT"),
        name: "Diploma in Human Resources Management",
        faculty: "Management Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Human resource management and industrial relations",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "HR Assistant",
          "Recruitment Officer",
          "Training Coordinator",
        ],
      },
      {
        id: createDegreeId("BTech Business Administration DUT"),
        name: "Bachelor of Technology in Business Administration",
        faculty: "Management Sciences",
        duration: "4 years",
        apsRequirement: 24,
        description:
          "Advanced business administration and strategic management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Business Manager",
          "Operations Manager",
          "Strategic Planner",
        ],
      },
    ],
  },
];
