import { Faculty } from "@/types/university";
import { createDegreeId, createFacultyId } from "./base";

// Mangosuthu University of Technology (MUT) - Faculty Data
export const MUT_FACULTIES: Faculty[] = [
  {
    id: createFacultyId("Faculty of Engineering MUT"),
    name: "Faculty of Engineering",
    description: "Engineering and technology programs",
    degrees: [
      {
        id: createDegreeId("Diploma in Civil Engineering MUT"),
        name: "Diploma in Civil Engineering",
        faculty: "Engineering",
        duration: "3 years",
        apsRequirement: 26,
        description: "Civil engineering and construction technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Civil Technician",
          "Construction Manager",
          "Project Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma in Electrical Engineering MUT"),
        name: "Diploma in Electrical Engineering",
        faculty: "Engineering",
        duration: "3 years",
        apsRequirement: 26,
        description: "Electrical engineering and power systems",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Electrical Technician",
          "Power Systems Engineer",
          "Maintenance Engineer",
        ],
      },
      {
        id: createDegreeId("Diploma in Mechanical Engineering MUT"),
        name: "Diploma in Mechanical Engineering",
        faculty: "Engineering",
        duration: "3 years",
        apsRequirement: 26,
        description: "Mechanical engineering and manufacturing technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Mechanical Technician",
          "Manufacturing Engineer",
          "Design Engineer",
        ],
      },
      {
        id: createDegreeId("Diploma in Industrial Engineering MUT"),
        name: "Diploma in Industrial Engineering",
        faculty: "Engineering",
        duration: "3 years",
        apsRequirement: 26,
        description: "Industrial engineering and systems optimization",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Industrial Engineer",
          "Systems Analyst",
          "Operations Manager",
        ],
      },
      {
        id: createDegreeId("BTech Civil Engineering MUT"),
        name: "Bachelor of Technology in Civil Engineering",
        faculty: "Engineering",
        duration: "4 years",
        apsRequirement: 28,
        description: "Advanced civil engineering and project management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Civil Engineer",
          "Structural Engineer",
          "Project Manager",
        ],
      },
      {
        id: createDegreeId("BTech Electrical Engineering MUT"),
        name: "Bachelor of Technology in Electrical Engineering",
        faculty: "Engineering",
        duration: "4 years",
        apsRequirement: 28,
        description: "Advanced electrical engineering and automation",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Electrical Engineer",
          "Control Systems Engineer",
          "Power Engineer",
        ],
      },
    ],
  },
  {
    id: createFacultyId(
      "Faculty of Information and Communication Technology MUT",
    ),
    name: "Faculty of Information and Communication Technology",
    description: "Information technology and computer science programs",
    degrees: [
      {
        id: createDegreeId("Diploma in Information Technology MUT"),
        name: "Diploma in Information Technology",
        faculty: "Information and Communication Technology",
        duration: "3 years",
        apsRequirement: 24,
        description: "Computer systems and information technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 3, isRequired: false },
        ],
        careerProspects: [
          "IT Support Technician",
          "Network Administrator",
          "Systems Analyst",
        ],
      },
      {
        id: createDegreeId("Diploma in Software Development MUT"),
        name: "Diploma in Software Development",
        faculty: "Information and Communication Technology",
        duration: "3 years",
        apsRequirement: 24,
        description: "Software programming and application development",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 3, isRequired: false },
        ],
        careerProspects: ["Software Developer", "Programmer", "Web Developer"],
      },
      {
        id: createDegreeId("Diploma in Multimedia MUT"),
        name: "Diploma in Multimedia",
        faculty: "Information and Communication Technology",
        duration: "3 years",
        apsRequirement: 22,
        description: "Digital media and multimedia production",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: false },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Multimedia Designer",
          "Video Editor",
          "Digital Content Creator",
        ],
      },
      {
        id: createDegreeId("BTech Information Technology MUT"),
        name: "Bachelor of Technology in Information Technology",
        faculty: "Information and Communication Technology",
        duration: "4 years",
        apsRequirement: 26,
        description: "Advanced information technology and systems management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: false },
        ],
        careerProspects: [
          "IT Manager",
          "Systems Architect",
          "Technology Consultant",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Management Sciences MUT"),
    name: "Faculty of Management Sciences",
    description: "Business management and administration programs",
    degrees: [
      {
        id: createDegreeId("Diploma in Business Management MUT"),
        name: "Diploma in Business Management",
        faculty: "Management Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Business administration and management principles",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Supervisor",
          "Team Leader",
          "Operations Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma in Marketing MUT"),
        name: "Diploma in Marketing",
        faculty: "Management Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Marketing principles and consumer behavior",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Marketing Assistant",
          "Sales Representative",
          "Brand Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma in Public Management MUT"),
        name: "Diploma in Public Management",
        faculty: "Management Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Public administration and government management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Public Administrator",
          "Municipal Officer",
          "Government Official",
        ],
      },
      {
        id: createDegreeId("Diploma in Human Resources MUT"),
        name: "Diploma in Human Resources Management",
        faculty: "Management Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Human resource management and industrial relations",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "HR Assistant",
          "Recruitment Officer",
          "Training Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma in Entrepreneurship MUT"),
        name: "Diploma in Entrepreneurship",
        faculty: "Management Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Business development and entrepreneurial skills",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Entrepreneur",
          "Business Developer",
          "Small Business Owner",
        ],
      },
      {
        id: createDegreeId("BTech Business Administration MUT"),
        name: "Bachelor of Technology in Business Administration",
        faculty: "Management Sciences",
        duration: "4 years",
        apsRequirement: 24,
        description:
          "Advanced business administration and strategic management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Business Manager",
          "Operations Manager",
          "Strategic Planner",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Natural Sciences MUT"),
    name: "Faculty of Natural Sciences",
    description: "Science and mathematics programs",
    degrees: [
      {
        id: createDegreeId("Diploma in Analytical Chemistry MUT"),
        name: "Diploma in Analytical Chemistry",
        faculty: "Natural Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Chemical analysis and laboratory techniques",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Analytical Chemist",
          "Quality Control Analyst",
          "Laboratory Technician",
        ],
      },
      {
        id: createDegreeId("Diploma in Biotechnology MUT"),
        name: "Diploma in Biotechnology",
        faculty: "Natural Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Biotechnology and biological applications",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Biotechnologist",
          "Research Scientist",
          "Quality Control Specialist",
        ],
      },
      {
        id: createDegreeId("Diploma in Environmental Science MUT"),
        name: "Diploma in Environmental Science",
        faculty: "Natural Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Environmental studies and conservation management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Geography", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Environmental Scientist",
          "Conservation Officer",
          "Environmental Consultant",
        ],
      },
      {
        id: createDegreeId("BTech Chemistry MUT"),
        name: "Bachelor of Technology in Chemistry",
        faculty: "Natural Sciences",
        duration: "4 years",
        apsRequirement: 26,
        description: "Advanced chemistry and industrial applications",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Chemical Engineer",
          "Process Engineer",
          "Research Scientist",
        ],
      },
    ],
  },
];
