import { Faculty } from "@/types/university";
import { createDegreeId, createFacultyId } from "./base";

// North-West University (NWU) - Faculty Data
export const NWU_FACULTIES: Faculty[] = [
  {
    id: createFacultyId("Faculty of Economic Management Sciences NWU"),
    name: "Faculty of Economic and Management Sciences",
    description: "Business, economics, and management programs",
    degrees: [
      {
        id: createDegreeId("BCom Accounting NWU"),
        name: "Bachelor of Commerce in Accounting",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "General accounting and financial management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Accounting", level: 4, isRequired: true },
        ],
        careerProspects: ["Accountant", "Financial Analyst", "Bookkeeper"],
      },
      {
        id: createDegreeId("BCom Chartered Accountancy NWU"),
        name: "Bachelor of Commerce in Chartered Accountancy",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Professional chartered accounting qualification",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Accounting", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Chartered Accountant",
          "Financial Manager",
          "Auditor",
        ],
      },
      {
        id: createDegreeId("BCom Chartered Accountancy Extended NWU"),
        name: "Extended Bachelor of Commerce in Chartered Accountancy",
        faculty: "Economic and Management Sciences",
        duration: "4 years",
        apsRequirement: 28,
        description: "Extended chartered accounting program",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Accounting", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Chartered Accountant",
          "Financial Manager",
          "Auditor",
        ],
      },
      {
        id: createDegreeId("BCom Financial Accountancy NWU"),
        name: "Bachelor of Commerce in Financial Accountancy",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 28,
        description: "Financial accounting and reporting",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Accounting", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Financial Accountant",
          "Financial Analyst",
          "Bookkeeper",
        ],
      },
      {
        id: createDegreeId("BCom Financial Accountancy Extended NWU"),
        name: "Extended Bachelor of Commerce in Financial Accountancy",
        faculty: "Economic and Management Sciences",
        duration: "4 years",
        apsRequirement: 24,
        description: "Extended financial accounting program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Accounting", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Financial Accountant",
          "Financial Analyst",
          "Bookkeeper",
        ],
      },
      {
        id: createDegreeId("BCom Forensic Accountancy NWU"),
        name: "Bachelor of Commerce in Forensic Accountancy",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 36,
        description: "Forensic accounting and fraud investigation",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Accounting", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Forensic Accountant",
          "Fraud Investigator",
          "Risk Analyst",
        ],
      },
      {
        id: createDegreeId("BCom Management Accountancy NWU"),
        name: "Bachelor of Commerce in Management Accountancy",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "Management accounting and cost control",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Accounting", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Management Accountant",
          "Cost Analyst",
          "Financial Controller",
        ],
      },
      {
        id: createDegreeId("BCom Operations Research NWU"),
        name: "Bachelor of Commerce in Operations Research",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Operations research and optimization",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Operations Research Analyst",
          "Data Scientist",
          "Management Consultant",
        ],
      },
      {
        id: createDegreeId("BCom Statistics NWU"),
        name: "Bachelor of Commerce in Statistics",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Statistical analysis and data science",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: ["Statistician", "Data Analyst", "Market Researcher"],
      },
      {
        id: createDegreeId("BCom Statistics Extended NWU"),
        name: "Extended Bachelor of Commerce in Statistics",
        faculty: "Economic and Management Sciences",
        duration: "4 years",
        apsRequirement: 20,
        description: "Extended statistics program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: ["Statistician", "Data Analyst", "Market Researcher"],
      },
      {
        id: createDegreeId("BCom Business Operations Logistics NWU"),
        name: "Bachelor of Commerce in Business Operations (with Logistics Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Business operations with logistics specialization",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Logistics Manager",
          "Operations Manager",
          "Supply Chain Analyst",
        ],
      },
      {
        id: createDegreeId("BCom Business Operations Logistics Extended NWU"),
        name: "Extended Bachelor of Commerce in Business Operations (with Logistics Management)",
        faculty: "Economic and Management Sciences",
        duration: "4 years",
        apsRequirement: 20,
        description: "Extended business operations with logistics",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Logistics Manager",
          "Operations Manager",
          "Supply Chain Analyst",
        ],
      },
      {
        id: createDegreeId("BCom Business Operations Transport Economics NWU"),
        name: "Bachelor of Commerce in Business Operations (with Transport Economics)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Business operations with transport economics",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Transport Economist",
          "Operations Manager",
          "Logistics Coordinator",
        ],
      },
      {
        id: createDegreeId(
          "BCom Business Operations Transport Economics Extended NWU",
        ),
        name: "Extended Bachelor of Commerce in Business Operations (with Transport Economics)",
        faculty: "Economic and Management Sciences",
        duration: "4 years",
        apsRequirement: 20,
        description: "Extended business operations with transport economics",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Transport Economist",
          "Operations Manager",
          "Logistics Coordinator",
        ],
      },
      {
        id: createDegreeId(
          "BCom Economic Sciences Agricultural Economics Risk Management NWU",
        ),
        name: "Bachelor of Commerce in Economic Sciences (with Agricultural Economics and Risk Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Economics with agricultural and risk management focus",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Agricultural Economist",
          "Risk Analyst",
          "Policy Researcher",
        ],
      },
      {
        id: createDegreeId("BCom Economic Sciences Econometrics NWU"),
        name: "Bachelor of Commerce in Economic Sciences (with Econometrics)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Economics with econometric analysis",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Econometrician",
          "Economic Analyst",
          "Research Economist",
        ],
      },
      {
        id: createDegreeId("BCom Economic Sciences Econometrics Extended NWU"),
        name: "Extended Bachelor of Commerce in Economic Sciences (with Econometrics)",
        faculty: "Economic and Management Sciences",
        duration: "4 years",
        apsRequirement: 20,
        description: "Extended economics with econometrics",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Econometrician",
          "Economic Analyst",
          "Research Economist",
        ],
      },
      {
        id: createDegreeId("BCom Economic Sciences International Trade NWU"),
        name: "Bachelor of Commerce in Economic Sciences (with International Trade)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Economics with international trade focus",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "International Trade Specialist",
          "Economic Analyst",
          "Trade Consultant",
        ],
      },
      {
        id: createDegreeId(
          "BCom Economic Sciences International Trade Extended NWU",
        ),
        name: "Extended Bachelor of Commerce in Economic Sciences (with International Trade)",
        faculty: "Economic and Management Sciences",
        duration: "4 years",
        apsRequirement: 20,
        description: "Extended economics with international trade",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "International Trade Specialist",
          "Economic Analyst",
          "Trade Consultant",
        ],
      },
      {
        id: createDegreeId("BCom Economic Sciences Informatics NWU"),
        name: "Bachelor of Commerce in Economic Sciences (with Informatics)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Economics with informatics and data analysis",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Economic Informatics Specialist",
          "Data Economist",
          "Business Analyst",
        ],
      },
      {
        id: createDegreeId("BCom Economic Sciences Information Systems NWU"),
        name: "Bachelor of Commerce in Economic Sciences (with Information Systems)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Economics with information systems focus",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Economic Systems Analyst",
          "Information Economist",
          "Business Systems Specialist",
        ],
      },
      {
        id: createDegreeId(
          "BCom Economic Sciences Information Systems Extended NWU",
        ),
        name: "Extended Bachelor of Commerce in Economic Sciences (with Information Systems)",
        faculty: "Economic and Management Sciences",
        duration: "4 years",
        apsRequirement: 20,
        description: "Extended economics with information systems",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Economic Systems Analyst",
          "Information Economist",
          "Business Systems Specialist",
        ],
      },
      {
        id: createDegreeId("BCom Economic Sciences Risk Management NWU"),
        name: "Bachelor of Commerce in Economic Sciences (with Risk Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Economics with risk management specialization",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Risk Manager",
          "Economic Risk Analyst",
          "Financial Risk Specialist",
        ],
      },
      {
        id: createDegreeId(
          "BCom Economic Sciences Risk Management Extended NWU",
        ),
        name: "Extended Bachelor of Commerce in Economic Sciences (with Risk Management)",
        faculty: "Economic and Management Sciences",
        duration: "4 years",
        apsRequirement: 24,
        description: "Extended economics with risk management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Risk Manager",
          "Economic Risk Analyst",
          "Financial Risk Specialist",
        ],
      },
      {
        id: createDegreeId("BAdmin Human Resource Management NWU"),
        name: "Bachelor of Administration in Human Resource Management",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 23,
        description: "Human resource management and administration",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "HR Administrator",
          "HR Coordinator",
          "Personnel Officer",
        ],
      },
      {
        id: createDegreeId("BAdmin Human Resource Management Extended NWU"),
        name: "Extended Bachelor of Administration in Human Resource Management",
        faculty: "Economic and Management Sciences",
        duration: "4 years",
        apsRequirement: 21,
        description: "Extended HR management program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "HR Administrator",
          "HR Coordinator",
          "Personnel Officer",
        ],
      },
      {
        id: createDegreeId("BAdmin Industrial Organisational Psychology NWU"),
        name: "Bachelor of Administration in Industrial and Organisational Psychology",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 23,
        description: "Psychology in organizational settings",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Industrial Psychologist",
          "Organizational Consultant",
          "HR Specialist",
        ],
      },
      {
        id: createDegreeId(
          "BAdmin Industrial Organisational Psychology Extended NWU",
        ),
        name: "Extended Bachelor of Administration in Industrial and Organisational Psychology",
        faculty: "Economic and Management Sciences",
        duration: "4 years",
        apsRequirement: 21,
        description: "Extended industrial psychology program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Industrial Psychologist",
          "Organizational Consultant",
          "HR Specialist",
        ],
      },
      {
        id: createDegreeId(
          "BA Industrial Organisational Psychology Labour Relations NWU",
        ),
        name: "Bachelor of Arts (with Industrial and Organisational Psychology and Labour Relations Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Psychology and labour relations in organizations",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Labour Relations Manager",
          "Industrial Psychologist",
          "HR Manager",
        ],
      },
      {
        id: createDegreeId("BCom Human Resource Management Professional NWU"),
        name: "Bachelor of Commerce (Human Resource Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "Professional human resource management",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "HR Manager",
          "Recruitment Specialist",
          "Training Manager",
        ],
      },
      {
        id: createDegreeId(
          "BCom Industrial Organisational Psychology Professional NWU",
        ),
        name: "Bachelor of Commerce (in Industrial and Organisational Psychology)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "Professional industrial and organizational psychology",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Industrial Psychologist",
          "Organizational Consultant",
          "HR Specialist",
        ],
      },
      {
        id: createDegreeId("Bachelor Human Resource Development NWU"),
        name: "Bachelor of Human Resource Development",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 20,
        description: "Human resource development (20-22 APS range)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "HR Development Officer",
          "Training Coordinator",
          "Skills Development Facilitator",
        ],
      },
      {
        id: createDegreeId("BA Tourism Management NWU"),
        name: "Bachelor of Arts (with Tourism Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Tourism management and development",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Tourism Manager",
          "Travel Consultant",
          "Tourism Developer",
        ],
      },
      {
        id: createDegreeId("BCom Management Sciences Tourism Management NWU"),
        name: "Bachelor of Commerce in Management Sciences (with Tourism Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Management sciences with tourism focus",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Tourism Manager",
          "Hospitality Manager",
          "Tourism Consultant",
        ],
      },
      {
        id: createDegreeId(
          "BCom Management Sciences Tourism Recreation Skills NWU",
        ),
        name: "Bachelor of Commerce in Management Sciences (with Tourism and Recreation Skills)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Tourism and recreation management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Tourism Manager",
          "Recreation Officer",
          "Event Coordinator",
        ],
      },
      {
        id: createDegreeId("BCom Management Sciences Business Management NWU"),
        name: "Bachelor of Commerce in Management Sciences (with Business Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Business management and administration",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Business Manager",
          "Operations Manager",
          "Project Manager",
        ],
      },
      {
        id: createDegreeId(
          "BCom Management Sciences Business Management Extended NWU",
        ),
        name: "Extended Bachelor of Commerce in Management Sciences (with Business Management)",
        faculty: "Economic and Management Sciences",
        duration: "4 years",
        apsRequirement: 24,
        description: "Extended business management program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Business Manager",
          "Operations Manager",
          "Project Manager",
        ],
      },
      {
        id: createDegreeId(
          "BCom Management Sciences Communication Management NWU",
        ),
        name: "Bachelor of Commerce in Management Sciences (with Communication Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Communication and management integration",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Communications Manager",
          "Public Relations Manager",
          "Marketing Manager",
        ],
      },
      {
        id: createDegreeId("BCom Management Sciences Marketing Management NWU"),
        name: "Bachelor of Commerce in Management Sciences (with Marketing Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Marketing strategy and consumer behavior",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Marketing Manager",
          "Brand Manager",
          "Digital Marketing Specialist",
        ],
      },
      {
        id: createDegreeId(
          "BCom Management Sciences Marketing Management Extended NWU",
        ),
        name: "Extended Bachelor of Commerce in Management Sciences (with Marketing Management)",
        faculty: "Economic and Management Sciences",
        duration: "4 years",
        apsRequirement: 20,
        description: "Extended marketing management program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Marketing Manager",
          "Brand Manager",
          "Digital Marketing Specialist",
        ],
      },
      {
        id: createDegreeId(
          "BCom Management Sciences Sport Business Management NWU",
        ),
        name: "Bachelor of Commerce in Management Sciences (with Sport and Business Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Sports business and management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Sports Manager",
          "Sports Marketing Specialist",
          "Event Manager",
        ],
      },
      {
        id: createDegreeId("BCom Management Sciences Safety Management NWU"),
        name: "Bachelor of Commerce in Management Sciences (with Safety Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Safety and risk management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Safety Manager",
          "Risk Assessment Officer",
          "Occupational Health Specialist",
        ],
      },
      {
        id: createDegreeId(
          "BCom Management Sciences Marketing Tourism Management NWU",
        ),
        name: "Bachelor of Commerce in Management Sciences (with Marketing & Tourism Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Combined marketing and tourism management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Tourism Marketing Manager",
          "Destination Marketing Specialist",
          "Travel Marketing Coordinator",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Education NWU"),
    name: "Faculty of Education",
    description: "Teacher education and educational development programs",
    degrees: [
      {
        id: createDegreeId("BEd Early Childhood Care Education NWU"),
        name: "Bachelor of Education Early Childhood Care and Education",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description: "Early childhood development and education",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Early Childhood Educator",
          "Preschool Teacher",
          "Educational Specialist",
        ],
      },
      {
        id: createDegreeId("BEd Foundation Phase NWU"),
        name: "Bachelor of Education Foundation Phase",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description: "Foundation phase teaching (Grades R-3)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Foundation Phase Teacher",
          "Primary School Teacher",
          "Educational Specialist",
        ],
      },
      {
        id: createDegreeId("BEd Intermediate Phase NWU"),
        name: "Bachelor of Education Intermediate Phase",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description: "Intermediate phase teaching (Grades 4-6)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Intermediate Phase Teacher",
          "Primary School Teacher",
          "Subject Specialist",
        ],
      },
      {
        id: createDegreeId("BEd Senior Further Education NWU"),
        name: "Bachelor of Education Senior and Further Education",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description: "Senior phase and FET teaching (Grades 7-12)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "High School Teacher",
          "Subject Specialist",
          "Educational Consultant",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Engineering NWU"),
    name: "Faculty of Engineering",
    description: "Engineering and technology programs",
    degrees: [
      {
        id: createDegreeId("BEng Chemical NWU"),
        name: "Bachelor of Engineering (Chemical)",
        faculty: "Engineering",
        duration: "4 years",
        apsRequirement: 34,
        description: "Chemical process engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Chemical Engineer",
          "Process Engineer",
          "Plant Manager",
        ],
      },
      {
        id: createDegreeId("BEng Electrical NWU"),
        name: "Bachelor of Engineering (Electrical)",
        faculty: "Engineering",
        duration: "4 years",
        apsRequirement: 34,
        description: "Electrical power and systems engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Electrical Engineer",
          "Power Systems Engineer",
          "Control Engineer",
        ],
      },
      {
        id: createDegreeId("BEng Computer Electronic NWU"),
        name: "Bachelor of Engineering (Computer & Electronic)",
        faculty: "Engineering",
        duration: "4 years",
        apsRequirement: 34,
        description: "Computer and electronic systems engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Computer Engineer",
          "Electronic Engineer",
          "Systems Engineer",
        ],
      },
      {
        id: createDegreeId("BEng Electromechanical NWU"),
        name: "Bachelor of Engineering (Electromechanical)",
        faculty: "Engineering",
        duration: "4 years",
        apsRequirement: 34,
        description: "Electromechanical systems engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Electromechanical Engineer",
          "Automation Engineer",
          "Systems Engineer",
        ],
      },
      {
        id: createDegreeId("BEng Mechanical NWU"),
        name: "Bachelor of Engineering (Mechanical)",
        faculty: "Engineering",
        duration: "4 years",
        apsRequirement: 34,
        description: "Mechanical systems and design engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Mechanical Engineer",
          "Design Engineer",
          "Manufacturing Engineer",
        ],
      },
      {
        id: createDegreeId("BEng Industrial NWU"),
        name: "Bachelor of Engineering (Industrial)",
        faculty: "Engineering",
        duration: "4 years",
        apsRequirement: 34,
        description: "Manufacturing and operations engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Industrial Engineer",
          "Operations Manager",
          "Quality Engineer",
        ],
      },
      {
        id: createDegreeId("BEng Mechatronic NWU"),
        name: "Bachelor of Engineering (Mechatronic)",
        faculty: "Engineering",
        duration: "4 years",
        apsRequirement: 34,
        description: "Mechatronic and automation engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Mechatronic Engineer",
          "Automation Engineer",
          "Robotics Engineer",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Health Sciences NWU"),
    name: "Faculty of Health Sciences",
    description: "Health, medical, and wellness programs",
    degrees: [
      {
        id: createDegreeId("Diploma Coaching Science NWU"),
        name: "Diploma in Coaching Science",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 18,
        description: "Sports coaching and science",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Life Sciences", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Sports Coach",
          "Fitness Trainer",
          "Athletic Performance Specialist",
        ],
      },
      {
        id: createDegreeId("BHSc Physiology Biochemistry NWU"),
        name: "Bachelor of Health Sciences (with Physiology and Biochemistry)",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Health sciences with physiology and biochemistry",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: ["Health Scientist", "Physiologist", "Biochemist"],
      },
      {
        id: createDegreeId("BHSc Physiology Psychology NWU"),
        name: "Bachelor of Health Sciences (with Physiology and Psychology)",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Health sciences with physiology and psychology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Health Psychologist",
          "Physiologist",
          "Neuropsychologist",
        ],
      },
      {
        id: createDegreeId("BHSc Sport Coaching Human Movement Sciences NWU"),
        name: "Bachelor of Health Sciences (with Sport Coaching and Human Movement Sciences)",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Sports coaching and human movement sciences",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Sports Scientist",
          "Movement Specialist",
          "Sports Coach",
        ],
      },
      {
        id: createDegreeId("BHSc Recreation Sciences Psychology NWU"),
        name: "Bachelor of Health Sciences (with Recreation Sciences and Psychology)",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Recreation sciences with psychology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Recreation Therapist",
          "Sports Psychologist",
          "Recreation Manager",
        ],
      },
      {
        id: createDegreeId(
          "BHSc Recreation Science Tourism Management Sport Recreation Administration NWU",
        ),
        name: "Bachelor of Health Sciences (with Recreation Science and Tourism Management, with Sport and Recreation Administration)",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Recreation, tourism, and sports administration",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Recreation Manager",
          "Sports Administrator",
          "Tourism Officer",
        ],
      },
      {
        id: createDegreeId(
          "BA Behavioural Sciences Psychology Geography Environmental Tourism NWU",
        ),
        name: "Bachelor of Arts in Behavioural Sciences (with Psychology and Geography and Environmental Management, with Psychology and Tourism Management)",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Behavioral sciences with various specializations",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Behavioral Scientist",
          "Environmental Psychologist",
          "Tourism Psychologist",
        ],
      },
      {
        id: createDegreeId("BSocSc Psychology NWU"),
        name: "Bachelor of Social Sciences (with Psychology)",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Social sciences with psychology focus",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Social Psychologist",
          "Community Psychologist",
          "Researcher",
        ],
      },
      {
        id: createDegreeId("Bachelor Consumer Studies NWU"),
        name: "Bachelor of Consumer Studies",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Consumer behavior and studies",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Consumer Researcher",
          "Market Analyst",
          "Product Developer",
        ],
      },
      {
        id: createDegreeId(
          "Bachelor Consumer Studies Food Production Management NWU",
        ),
        name: "Bachelor of Consumer Studies (in Food Production Management)",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Consumer studies with food production focus",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Food Production Manager",
          "Quality Control Manager",
          "Food Safety Officer",
        ],
      },
      {
        id: createDegreeId(
          "Bachelor Consumer Studies Fashion Retail Management NWU",
        ),
        name: "Bachelor of Consumer Studies (in Fashion Retail Management)",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Consumer studies with fashion retail focus",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Fashion Retail Manager",
          "Merchandiser",
          "Fashion Buyer",
        ],
      },
      {
        id: createDegreeId("Bachelor Social Work NWU"),
        name: "Bachelor of Social Work",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 28,
        description: "Social work practice and community development",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Social Worker",
          "Community Developer",
          "Family Counselor",
        ],
      },
      {
        id: createDegreeId("Bachelor Pharmacy NWU"),
        name: "Bachelor of Pharmacy",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 32,
        description: "Pharmaceutical sciences and practice",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Pharmacist",
          "Clinical Pharmacist",
          "Pharmaceutical Researcher",
        ],
      },
      {
        id: createDegreeId("BSc Dietetics NWU"),
        name: "Bachelor of Science in Dietetics",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 30,
        description: "Nutrition and dietetic practice",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: ["Dietitian", "Nutritionist", "Food Service Manager"],
      },
      {
        id: createDegreeId("BHSc Occupational Hygiene NWU"),
        name: "Bachelor of Health Science in Occupational Hygiene",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 27,
        description: "Occupational health and safety",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Occupational Hygienist",
          "Safety Officer",
          "Industrial Hygienist",
        ],
      },
      {
        id: createDegreeId("BHSc Biokinetics NWU"),
        name: "Bachelor of Health Science in Biokinetics",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 32,
        description: "Biokinetics and exercise therapy",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Biokineticist",
          "Exercise Therapist",
          "Sports Scientist",
        ],
      },
      {
        id: createDegreeId("Bachelor Nursing NWU"),
        name: "Bachelor of Nursing",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 25,
        description: "Professional nursing practice",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Professional Nurse",
          "Nurse Manager",
          "Clinical Specialist",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Humanities NWU"),
    name: "Faculty of Humanities",
    description: "Arts, languages, and social science programs",
    degrees: [
      {
        id: createDegreeId("BA Public Governance Public Administration NWU"),
        name: "Bachelor of Arts (BA) in Public Governance (with Public Administration, Politics and Public Administration, Social Studies, Geography, Labour Relations Management)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 25,
        description: "Public governance with various specializations",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "History", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Public Administrator",
          "Government Official",
          "Policy Analyst",
        ],
      },
      {
        id: createDegreeId(
          "BA Public Governance Municipal Management Leadership NWU",
        ),
        name: "Bachelor of Arts (BA) in Public Governance (with Municipal Management and Leadership)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 25,
        description: "Public governance with municipal management focus",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Municipal Manager",
          "Local Government Official",
          "Public Administrator",
        ],
      },
      {
        id: createDegreeId("BA Public Governance Policing Practice NWU"),
        name: "Bachelor of Arts (BA) in Public Governance (with Policing Practice)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 25,
        description: "Public governance with policing practice",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Police Officer",
          "Law Enforcement Manager",
          "Security Consultant",
        ],
      },
      {
        id: createDegreeId(
          "BSocSc Political Studies International Relations NWU",
        ),
        name: "Bachelor of Social Sciences (BSocSc) (with Political Studies and International Relations)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 24,
        description: "Political studies and international relations",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "History", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Political Scientist",
          "Diplomat",
          "International Relations Officer",
        ],
      },
      {
        id: createDegreeId(
          "BAdmin Development Management Local Government NWU",
        ),
        name: "Bachelor of Administration in Development and Management (with Local Government Management)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 21,
        description: "Development and local government management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Development Manager",
          "Local Government Official",
          "Project Coordinator",
        ],
      },
      {
        id: createDegreeId(
          "BAdmin Development Management Local Government Extended NWU",
        ),
        name: "Extended Bachelor of Administration in Development and Management (with Local Government Management)",
        faculty: "Humanities",
        duration: "4 years",
        apsRequirement: 20,
        description: "Extended development and local government management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Development Manager",
          "Local Government Official",
          "Project Coordinator",
        ],
      },
      {
        id: createDegreeId("BA Communication NWU"),
        name: "Bachelor of Arts (BA) in Communication",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 24,
        description: "Communication theory and practice",
        subjects: [{ name: "English", level: 5, isRequired: true }],
        careerProspects: [
          "Communications Specialist",
          "Public Relations Officer",
          "Media Coordinator",
        ],
      },
      {
        id: createDegreeId("BA Graphic Design NWU"),
        name: "Bachelor of Arts (BA) in Graphic Design",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 24,
        description: "Graphic design and visual communication",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Visual Arts", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Graphic Designer",
          "Visual Designer",
          "Creative Director",
        ],
      },
      {
        id: createDegreeId("BA Graphic Design Communication NWU"),
        name: "Bachelor of Arts (BA) in Graphic Design (with Communication)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 24,
        description: "Graphic design with communication focus",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Visual Arts", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Graphic Designer",
          "Communications Designer",
          "Brand Designer",
        ],
      },
      {
        id: createDegreeId("BA Language Literary Studies NWU"),
        name: "Bachelor of Arts (BA) in Language and Literary Studies",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 24,
        description:
          "Language and literature studies with various specializations",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Home Language", level: 4, isRequired: true },
        ],
        careerProspects: ["Language Teacher", "Editor", "Translator"],
      },
      {
        id: createDegreeId("BA Language Technology NWU"),
        name: "Bachelor of Arts (BA) in Language Technology",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 24,
        description: "Language technology and computational linguistics",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Language Technologist",
          "Computational Linguist",
          "Software Developer",
        ],
      },
      {
        id: createDegreeId("Diploma Music DM NWU"),
        name: "Diploma in Music (DM)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 18,
        description: "Music performance and theory",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Music", level: 4, isRequired: true },
        ],
        careerProspects: ["Musician", "Music Teacher", "Performer"],
      },
      {
        id: createDegreeId("BA Music Society NWU"),
        name: "Bachelor of Arts (BA) in Music and Society",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 21,
        description: "Music in social context",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Music", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Music Educator",
          "Community Music Leader",
          "Cultural Officer",
        ],
      },
      {
        id: createDegreeId("BMus NWU"),
        name: "Baccalaureus Musicae (BMus)",
        faculty: "Humanities",
        duration: "4 years",
        apsRequirement: 24,
        description: "Professional music qualification",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Music", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Professional Musician",
          "Composer",
          "Music Director",
        ],
      },
      {
        id: createDegreeId("BPhil Philosophy Politics Economics NWU"),
        name: "Bachelor of Philosophy (BPhil) (with Philosophy, Politics and Economics)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 26,
        description: "Interdisciplinary philosophy, politics and economics",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Policy Analyst",
          "Political Researcher",
          "Economic Advisor",
        ],
      },
      {
        id: createDegreeId("BA Humanities Languages NWU"),
        name: "Bachelor of Arts (BA) Humanities (with various languages and subjects)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 24,
        description:
          "Humanities with various language and subject combinations",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Home Language", level: 4, isRequired: true },
        ],
        careerProspects: ["Teacher", "Translator", "Cultural Specialist"],
      },
      {
        id: createDegreeId("BSocSc Social Sciences NWU"),
        name: "Bachelor of Social Sciences (BSocSc) with various specializations",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 22,
        description: "Social sciences with various specializations",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Social Researcher",
          "Community Worker",
          "Social Services Officer",
        ],
      },
      {
        id: createDegreeId("BSocSc Economics NWU"),
        name: "Bachelor of Social Sciences (BSocSc) (with Economics)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 22,
        description: "Social sciences with economics focus",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Economic Researcher",
          "Policy Analyst",
          "Development Economist",
        ],
      },
      {
        id: createDegreeId("BA Sociology Geography Labour Relations NWU"),
        name: "Bachelor of Arts (BA) (with Sociology and Geography, with Sociology and Labour Relations Management)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 22,
        description: "Sociology with geography or labour relations",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Sociologist",
          "Labour Relations Officer",
          "Social Researcher",
        ],
      },
      {
        id: createDegreeId("BA Behavioural Sciences Sociology Psychology NWU"),
        name: "Bachelor of Arts (BA) in Behavioural Sciences (with Sociology and Psychology)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 22,
        description: "Behavioral sciences with sociology and psychology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Behavioral Scientist",
          "Social Psychologist",
          "Community Researcher",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Law NWU"),
    name: "Faculty of Law",
    description: "Legal studies and jurisprudence programs",
    degrees: [
      {
        id: createDegreeId(
          "BA Law Psychology Politics Industrial Psychology NWU",
        ),
        name: "Bachelor of Arts in Law (BA in Law) (with Psychology, Politics, Industrial Psychology)",
        faculty: "Law",
        duration: "3 years",
        apsRequirement: 28,
        description:
          "Liberal arts with legal foundation and various specializations",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: ["Legal Assistant", "Paralegal", "Legal Researcher"],
      },
      {
        id: createDegreeId("BCom Law NWU"),
        name: "Bachelor of Commerce in Law (BCom in Law)",
        faculty: "Law",
        duration: "3 years",
        apsRequirement: 30,
        description: "Commerce with legal foundation",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Corporate Legal Officer",
          "Legal Advisor",
          "Compliance Officer",
        ],
      },
      {
        id: createDegreeId("LLB NWU"),
        name: "Bachelor of Laws (LLB)",
        faculty: "Law",
        duration: "4 years",
        apsRequirement: 30,
        description: "Professional legal qualification",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: ["Lawyer", "Attorney", "Legal Consultant"],
      },
      {
        id: createDegreeId("LLB Extended NWU"),
        name: "Extended Bachelor of Laws (LLB)",
        faculty: "Law",
        duration: "5 years",
        apsRequirement: 28,
        description: "Extended legal qualification program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: ["Lawyer", "Attorney", "Legal Consultant"],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Natural Agricultural Sciences NWU"),
    name: "Faculty of Natural and Agricultural Sciences",
    description: "Natural sciences, agriculture, and technology programs",
    degrees: [
      {
        id: createDegreeId("Diploma Animal Health NWU"),
        name: "Diploma in Animal Health",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Animal health and veterinary support",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Animal Health Technician",
          "Veterinary Assistant",
          "Livestock Health Officer",
        ],
      },
      {
        id: createDegreeId("Diploma Animal Science NWU"),
        name: "Diploma in Animal Science",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Animal science and production",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Animal Scientist",
          "Livestock Manager",
          "Feed Specialist",
        ],
      },
      {
        id: createDegreeId("Diploma Plant Science Crop Production NWU"),
        name: "Diploma in Plant Science (Crop Production)",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Plant science and crop production",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Plant Scientist",
          "Crop Specialist",
          "Agricultural Technician",
        ],
      },
      {
        id: createDegreeId("BSc Various Combinations NWU"),
        name: "Bachelor of Science (with various subject combinations)",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Science with various subject combinations",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: ["Scientist", "Researcher", "Analyst"],
      },
      {
        id: createDegreeId("BSc Extended NWU"),
        name: "Extended Bachelor of Science",
        faculty: "Natural and Agricultural Sciences",
        duration: "4 years",
        apsRequirement: 24,
        description: "Extended science foundation program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: ["Scientist", "Researcher", "Laboratory Technician"],
      },
      {
        id: createDegreeId("BSc Information Technology NWU"),
        name: "Bachelor of Science in Information Technology",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Information technology and systems",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "IT Specialist",
          "Software Developer",
          "Systems Administrator",
        ],
      },
      {
        id: createDegreeId("BSc Information Technology Extended NWU"),
        name: "Extended Bachelor of Science in Information Technology",
        faculty: "Natural and Agricultural Sciences",
        duration: "4 years",
        apsRequirement: 24,
        description: "Extended information technology program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "IT Specialist",
          "Software Developer",
          "Systems Administrator",
        ],
      },
      {
        id: createDegreeId("BSc Mathematical Sciences NWU"),
        name: "Bachelor of Science in Mathematical Sciences",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Mathematical sciences with various specializations",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
        ],
        careerProspects: ["Mathematician", "Statistician", "Data Analyst"],
      },
      {
        id: createDegreeId("BSc Biological Sciences NWU"),
        name: "Bachelor of Science in Biological Sciences",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Biological sciences with various combinations",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Biologist",
          "Research Scientist",
          "Laboratory Scientist",
        ],
      },
      {
        id: createDegreeId("BSc Environmental Sciences NWU"),
        name: "Bachelor of Science in Environmental Sciences",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Environmental sciences with various combinations",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Geography", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Environmental Scientist",
          "Conservation Officer",
          "Environmental Consultant",
        ],
      },
      {
        id: createDegreeId(
          "BSc Environmental Sciences Chemistry Geography Special NWU",
        ),
        name: "Bachelor of Science in Environmental Sciences with Chemistry and Geography",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description:
          "Specialized environmental sciences with chemistry and geography",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
          { name: "Geography", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Environmental Chemist",
          "Geographer",
          "Environmental Analyst",
        ],
      },
      {
        id: createDegreeId("BSc Financial Mathematics Extended NWU"),
        name: "Extended Bachelor of Science in Financial Mathematics",
        faculty: "Natural and Agricultural Sciences",
        duration: "4 years",
        apsRequirement: 28,
        description: "Extended financial mathematics program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Financial Mathematician",
          "Quantitative Analyst",
          "Risk Analyst",
        ],
      },
      {
        id: createDegreeId("BSc Business Analytics NWU"),
        name: "Bachelor of Science in Business Analytics",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Business analytics and data science",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Business Analyst",
          "Data Scientist",
          "Analytics Consultant",
        ],
      },
      {
        id: createDegreeId("BSc Business Analytics Extended NWU"),
        name: "Extended Bachelor of Science in Business Analytics",
        faculty: "Natural and Agricultural Sciences",
        duration: "4 years",
        apsRequirement: 28,
        description: "Extended business analytics program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Business Analyst",
          "Data Scientist",
          "Analytics Consultant",
        ],
      },
      {
        id: createDegreeId("BSc Quantitative Risk Management NWU"),
        name: "Bachelor of Science in Quantitative Risk Management",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Quantitative risk assessment and management",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Risk Manager",
          "Quantitative Analyst",
          "Financial Risk Specialist",
        ],
      },
      {
        id: createDegreeId("BSc Quantitative Risk Management Extended NWU"),
        name: "Extended Bachelor of Science in Quantitative Risk Management",
        faculty: "Natural and Agricultural Sciences",
        duration: "4 years",
        apsRequirement: 28,
        description: "Extended quantitative risk management program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Risk Manager",
          "Quantitative Analyst",
          "Financial Risk Specialist",
        ],
      },
      {
        id: createDegreeId("BSc Actuarial Science NWU"),
        name: "Bachelor of Science in Actuarial Science",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Actuarial mathematics and risk assessment",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
        ],
        careerProspects: ["Actuary", "Risk Analyst", "Insurance Specialist"],
      },
      {
        id: createDegreeId("BSc Urban Regional Planning NWU"),
        name: "Bachelor of Science in Urban and Regional Planning",
        faculty: "Natural and Agricultural Sciences",
        duration: "4 years",
        apsRequirement: 28,
        description: "Urban and regional planning",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Geography", level: 4, isRequired: true },
        ],
        careerProspects: ["Town Planner", "Urban Designer", "Regional Planner"],
      },
      {
        id: createDegreeId("BSc Agricultural Sciences NWU"),
        name: "Bachelor of Science in Agricultural Sciences",
        faculty: "Natural and Agricultural Sciences",
        duration: "4 years",
        apsRequirement: 26,
        description: "Agricultural sciences with various specializations",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Agricultural Scientist",
          "Farm Manager",
          "Agricultural Consultant",
        ],
      },
      {
        id: createDegreeId("BSc Indigenous Knowledge Systems NWU"),
        name: "Bachelor of Science in Indigenous Knowledge Systems",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Indigenous knowledge systems and practices",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Home Language", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Indigenous Knowledge Specialist",
          "Cultural Researcher",
          "Community Developer",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Theology NWU"),
    name: "Faculty of Theology",
    description: "Theological and religious studies programs",
    degrees: [
      {
        id: createDegreeId("BA Ancient Languages NWU"),
        name: "BA in Ancient Languages",
        faculty: "Theology",
        duration: "3 years",
        apsRequirement: 24,
        description: "Ancient languages and biblical studies",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Home Language", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Biblical Scholar",
          "Translator",
          "Religious Educator",
        ],
      },
      {
        id: createDegreeId("Bachelor Divinity BDiv NWU"),
        name: "Bachelor of Divinity (BDiv)",
        faculty: "Theology",
        duration: "4 years",
        apsRequirement: 24,
        description: "Advanced theological and divinity studies",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: ["Minister", "Theologian", "Religious Scholar"],
      },
      {
        id: createDegreeId("BTh Bible Languages Translation NWU"),
        name: "BTh with Bible Languages & Bible Translation",
        faculty: "Theology",
        duration: "3 years",
        apsRequirement: 24,
        description: "Biblical languages and translation studies",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Home Language", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Bible Translator",
          "Biblical Scholar",
          "Religious Educator",
        ],
      },
      {
        id: createDegreeId("BA Pastoral Psychology NWU"),
        name: "BA in Pastoral Psychology",
        faculty: "Theology",
        duration: "3 years",
        apsRequirement: 24,
        description: "Pastoral care and psychology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Pastoral Counselor",
          "Chaplain",
          "Religious Counselor",
        ],
      },
      {
        id: createDegreeId("BTh Christian Ministry NWU"),
        name: "BTh in Christian Ministry",
        faculty: "Theology",
        duration: "3 years",
        apsRequirement: 24,
        description: "Christian ministry and pastoral studies",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: ["Minister", "Youth Pastor", "Missionary"],
      },
    ],
  },
];
