import { Faculty } from "@/types/university";
import { createDegreeId, createFacultyId } from "./base";

// North-West University (NWU) - Faculty Data
export const NWU_FACULTIES: Faculty[] = [
  {
    id: createFacultyId("Faculty of Economic and Management Sciences NWU"),
    name: "Faculty of Economic and Management Sciences",
    description:
      "Commerce, economics, accounting, and business management programs",
    degrees: [
      // Accounting Programs
      {
        id: createDegreeId("BCom Accounting NWU"),
        name: "Bachelor of Commerce in Accounting",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "General accounting program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: ["Accountant", "Financial Analyst", "Bookkeeper"],
      },
      {
        id: createDegreeId("BCom Chartered Accountancy NWU"),
        name: "Bachelor of Commerce in Chartered Accountancy",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Professional chartered accountancy pathway",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Chartered Accountant",
          "Financial Manager",
          "Auditor",
        ],
      },
      {
        id: createDegreeId("Extended BCom Chartered Accountancy NWU"),
        name: "Extended Bachelor of Commerce in Chartered Accountancy",
        faculty: "Economic and Management Sciences",
        duration: "4 years",
        apsRequirement: 28,
        description: "Extended chartered accountancy program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Chartered Accountant",
          "Financial Manager",
          "Auditor",
        ],
      },
      {
        id: createDegreeId("BCom Financial Accountancy NWU"),
        name: "Bachelor of Commerce in Financial Accountancy",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 28,
        description: "Financial accounting specialization",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Financial Accountant",
          "Financial Analyst",
          "Investment Advisor",
        ],
      },
      {
        id: createDegreeId("Extended BCom Financial Accountancy NWU"),
        name: "Extended Bachelor of Commerce in Financial Accountancy",
        faculty: "Economic and Management Sciences",
        duration: "4 years",
        apsRequirement: 24,
        description: "Extended financial accounting program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Financial Accountant",
          "Financial Analyst",
          "Investment Advisor",
        ],
      },
      {
        id: createDegreeId("BCom Forensic Accountancy NWU"),
        name: "Bachelor of Commerce in Forensic Accountancy",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 36,
        description: "Forensic accounting and fraud investigation",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Forensic Accountant",
          "Fraud Investigator",
          "Financial Crime Analyst",
        ],
      },
      {
        id: createDegreeId("BCom Management Accountancy NWU"),
        name: "Bachelor of Commerce in Management Accountancy",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "Management accounting and cost control",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Management Accountant",
          "Cost Analyst",
          "Financial Manager",
        ],
      },
      // Operations Research and Statistics
      {
        id: createDegreeId("BCom Operations Research NWU"),
        name: "Bachelor of Commerce in Operations Research",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Operations research and optimization",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Operations Research Analyst",
          "Business Analyst",
          "Optimization Specialist",
        ],
      },
      {
        id: createDegreeId("BCom Statistics NWU"),
        name: "Bachelor of Commerce in Statistics",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Statistical analysis and data science",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: ["Statistician", "Data Analyst", "Research Analyst"],
      },
      {
        id: createDegreeId("Extended BCom Statistics NWU"),
        name: "Extended Bachelor of Commerce in Statistics",
        faculty: "Economic and Management Sciences",
        duration: "4 years",
        apsRequirement: 20,
        description: "Extended statistics program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: ["Statistician", "Data Analyst", "Research Analyst"],
      },
      // Business Operations
      {
        id: createDegreeId("BCom Business Operations Logistics NWU"),
        name: "Bachelor of Commerce in Business Operations (with Logistics Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description:
          "Business operations with logistics management specialization",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Logistics Manager",
          "Supply Chain Analyst",
          "Operations Manager",
        ],
      },
      {
        id: createDegreeId("Extended BCom Business Operations Logistics NWU"),
        name: "Extended Bachelor of Commerce in Business Operations (with Logistics Management)",
        faculty: "Economic and Management Sciences",
        duration: "4 years",
        apsRequirement: 20,
        description: "Extended business operations with logistics management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Logistics Manager",
          "Supply Chain Analyst",
          "Operations Manager",
        ],
      },
      {
        id: createDegreeId("BCom Business Operations Transport Economics NWU"),
        name: "Bachelor of Commerce in Business Operations (with Transport Economics)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description:
          "Business operations with transport economics specialization",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Transport Economist",
          "Logistics Specialist",
          "Transportation Analyst",
        ],
      },
      {
        id: createDegreeId(
          "Extended BCom Business Operations Transport Economics NWU",
        ),
        name: "Extended Bachelor of Commerce in Business Operations (with Transport Economics)",
        faculty: "Economic and Management Sciences",
        duration: "4 years",
        apsRequirement: 20,
        description: "Extended business operations with transport economics",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Transport Economist",
          "Logistics Specialist",
          "Transportation Analyst",
        ],
      },
      // Economic Sciences
      {
        id: createDegreeId(
          "BCom Economic Sciences Agricultural Economics Risk Management NWU",
        ),
        name: "Bachelor of Commerce in Economic Sciences (with Agricultural Economics and Risk Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description:
          "Economic sciences with agricultural economics and risk management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Agricultural Economist",
          "Risk Analyst",
          "Economic Consultant",
        ],
      },
      {
        id: createDegreeId("BCom Economic Sciences Econometrics NWU"),
        name: "Bachelor of Commerce in Economic Sciences (with Econometrics)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Economic sciences with econometrics specialization",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Econometrician",
          "Economic Analyst",
          "Research Economist",
        ],
      },
      {
        id: createDegreeId("Extended BCom Economic Sciences Econometrics NWU"),
        name: "Extended Bachelor of Commerce in Economic Sciences (with Econometrics)",
        faculty: "Economic and Management Sciences",
        duration: "4 years",
        apsRequirement: 20,
        description: "Extended economic sciences with econometrics",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Econometrician",
          "Economic Analyst",
          "Research Economist",
        ],
      },
      {
        id: createDegreeId("BCom Economic Sciences International Trade NWU"),
        name: "Bachelor of Commerce in Economic Sciences (with International Trade)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Economic sciences with international trade focus",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "International Trade Specialist",
          "Export Manager",
          "Trade Analyst",
        ],
      },
      {
        id: createDegreeId(
          "Extended BCom Economic Sciences International Trade NWU",
        ),
        name: "Extended Bachelor of Commerce in Economic Sciences (with International Trade)",
        faculty: "Economic and Management Sciences",
        duration: "4 years",
        apsRequirement: 20,
        description: "Extended economic sciences with international trade",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "International Trade Specialist",
          "Export Manager",
          "Trade Analyst",
        ],
      },
      {
        id: createDegreeId("BCom Economic Sciences Informatics NWU"),
        name: "Bachelor of Commerce in Economic Sciences (with Informatics)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Economic sciences with informatics specialization",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Information Technology", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Economic Informatician",
          "Data Analyst",
          "Business Intelligence Analyst",
        ],
      },
      {
        id: createDegreeId("BCom Economic Sciences Information Systems NWU"),
        name: "Bachelor of Commerce in Economic Sciences (with Information Systems)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Economic sciences with information systems focus",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Information Technology", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Information Systems Analyst",
          "Business Analyst",
          "Systems Developer",
        ],
      },
      {
        id: createDegreeId(
          "Extended BCom Economic Sciences Information Systems NWU",
        ),
        name: "Extended Bachelor of Commerce in Economic Sciences (with Information Systems)",
        faculty: "Economic and Management Sciences",
        duration: "4 years",
        apsRequirement: 20,
        description: "Extended economic sciences with information systems",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Information Technology", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Information Systems Analyst",
          "Business Analyst",
          "Systems Developer",
        ],
      },
      {
        id: createDegreeId("BCom Economic Sciences Risk Management NWU"),
        name: "Bachelor of Commerce in Economic Sciences (with Risk Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Economic sciences with risk management specialization",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Risk Manager",
          "Risk Analyst",
          "Insurance Specialist",
        ],
      },
      {
        id: createDegreeId(
          "Extended BCom Economic Sciences Risk Management NWU",
        ),
        name: "Extended Bachelor of Commerce in Economic Sciences (with Risk Management)",
        faculty: "Economic and Management Sciences",
        duration: "4 years",
        apsRequirement: 24,
        description: "Extended economic sciences with risk management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Risk Manager",
          "Risk Analyst",
          "Insurance Specialist",
        ],
      },
      // Human Resource Management and Psychology
      {
        id: createDegreeId("BAdmin Human Resource Management NWU"),
        name: "Bachelor of Administration in Human Resource Management",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 23,
        description: "Human resource management administration",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "HR Manager",
          "Recruitment Specialist",
          "Training Coordinator",
        ],
      },
      {
        id: createDegreeId("Extended BAdmin Human Resource Management NWU"),
        name: "Extended Bachelor of Administration in Human Resource Management",
        faculty: "Economic and Management Sciences",
        duration: "4 years",
        apsRequirement: 21,
        description: "Extended human resource management administration",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "HR Manager",
          "Recruitment Specialist",
          "Training Coordinator",
        ],
      },
      {
        id: createDegreeId("BAdmin Industrial Organisational Psychology NWU"),
        name: "Bachelor of Administration in Industrial and Organisational Psychology",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 23,
        description: "Industrial and organisational psychology administration",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Industrial Psychologist",
          "Organisational Consultant",
          "HR Specialist",
        ],
      },
      {
        id: createDegreeId(
          "Extended BAdmin Industrial Organisational Psychology NWU",
        ),
        name: "Extended Bachelor of Administration in Industrial and Organisational Psychology",
        faculty: "Economic and Management Sciences",
        duration: "4 years",
        apsRequirement: 21,
        description:
          "Extended industrial and organisational psychology administration",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Industrial Psychologist",
          "Organisational Consultant",
          "HR Specialist",
        ],
      },
      {
        id: createDegreeId(
          "BA Industrial Organisational Psychology Labour Relations NWU",
        ),
        name: "Bachelor of Arts (with Industrial and Organisational Psychology and Labour Relations Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description:
          "Arts degree with industrial psychology and labour relations",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Labour Relations Officer",
          "Industrial Psychologist",
          "HR Manager",
        ],
      },
      {
        id: createDegreeId("BCom Human Resource Management NWU"),
        name: "Bachelor of Commerce (Human Resource Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "Commerce degree with human resource management focus",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "HR Manager",
          "Talent Acquisition Specialist",
          "Compensation Analyst",
        ],
      },
      {
        id: createDegreeId("BCom Industrial Organisational Psychology NWU"),
        name: "Bachelor of Commerce (in Industrial and Organisational Psychology)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description:
          "Commerce degree with industrial and organisational psychology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Industrial Psychologist",
          "Organisational Development Specialist",
          "HR Consultant",
        ],
      },
      {
        id: createDegreeId("Bachelor of Human Resource Development NWU"),
        name: "Bachelor of Human Resource Development",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description:
          "Human resource development specialization (20-22 APS range)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "HR Development Specialist",
          "Training Manager",
          "Organizational Development Consultant",
        ],
      },
      // Tourism Management
      {
        id: createDegreeId("BA Tourism Management NWU"),
        name: "Bachelor of Arts (with Tourism Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Arts degree with tourism management specialization",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Geography", level: 3, isRequired: false },
        ],
        careerProspects: ["Tourism Manager", "Tour Guide", "Travel Consultant"],
      },
      {
        id: createDegreeId("BCom Management Sciences Tourism Management NWU"),
        name: "Bachelor of Commerce in Management Sciences (with Tourism Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Management sciences with tourism management focus",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Tourism Manager",
          "Destination Marketer",
          "Hospitality Manager",
        ],
      },
      {
        id: createDegreeId(
          "BCom Management Sciences Tourism Recreation Skills NWU",
        ),
        name: "Bachelor of Commerce in Management Sciences (with Tourism and Recreation Skills)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Management sciences with tourism and recreation focus",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Recreation Manager",
          "Tourism Specialist",
          "Event Coordinator",
        ],
      },
      // Management Sciences
      {
        id: createDegreeId("BCom Management Sciences Business Management NWU"),
        name: "Bachelor of Commerce in Management Sciences (with Business Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Management sciences with business management focus",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Business Manager",
          "Operations Manager",
          "Strategic Planner",
        ],
      },
      {
        id: createDegreeId(
          "Extended BCom Management Sciences Business Management NWU",
        ),
        name: "Extended Bachelor of Commerce in Management Sciences (with Business Management)",
        faculty: "Economic and Management Sciences",
        duration: "4 years",
        apsRequirement: 24,
        description: "Extended management sciences with business management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Business Manager",
          "Operations Manager",
          "Strategic Planner",
        ],
      },
      {
        id: createDegreeId(
          "BCom Management Sciences Communication Management NWU",
        ),
        name: "Bachelor of Commerce in Management Sciences (with Communication Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Management sciences with communication management focus",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Communications Manager",
          "Public Relations Officer",
          "Marketing Manager",
        ],
      },
      {
        id: createDegreeId("BCom Management Sciences Marketing Management NWU"),
        name: "Bachelor of Commerce in Management Sciences (with Marketing Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Management sciences with marketing management focus",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Marketing Manager",
          "Brand Manager",
          "Digital Marketing Specialist",
        ],
      },
      {
        id: createDegreeId(
          "Extended BCom Management Sciences Marketing Management NWU",
        ),
        name: "Extended Bachelor of Commerce in Management Sciences (with Marketing Management)",
        faculty: "Economic and Management Sciences",
        duration: "4 years",
        apsRequirement: 20,
        description: "Extended management sciences with marketing management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Marketing Manager",
          "Brand Manager",
          "Digital Marketing Specialist",
        ],
      },
      {
        id: createDegreeId(
          "BCom Management Sciences Sport Business Management NWU",
        ),
        name: "Bachelor of Commerce in Management Sciences (with Sport and Business Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description:
          "Management sciences with sport and business management focus",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Sports Manager",
          "Athletic Administrator",
          "Sports Business Analyst",
        ],
      },
      {
        id: createDegreeId("BCom Management Sciences Safety Management NWU"),
        name: "Bachelor of Commerce in Management Sciences (with Safety Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Management sciences with safety management focus",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Safety Manager",
          "Risk Assessment Specialist",
          "Occupational Health Officer",
        ],
      },
      {
        id: createDegreeId(
          "BCom Management Sciences Marketing Tourism Management NWU",
        ),
        name: "Bachelor of Commerce in Management Sciences (with Marketing & Tourism Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description:
          "Management sciences with marketing and tourism management focus",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Tourism Marketing Manager",
          "Destination Marketer",
          "Travel Marketing Specialist",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Education NWU"),
    name: "Faculty of Education",
    description: "Teacher education and educational programs",
    degrees: [
      {
        id: createDegreeId("BEd Early Childhood Care Education NWU"),
        name: "Bachelor of Education in Early Childhood Care and Education",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description: "Early childhood development and education",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Early Childhood Educator",
          "Preschool Teacher",
          "Child Development Specialist",
        ],
      },
      {
        id: createDegreeId("BEd Foundation Phase NWU"),
        name: "Bachelor of Education Foundation Phase",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description: "Foundation phase teacher education (Grades R-3)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Foundation Phase Teacher",
          "Primary School Teacher",
          "Curriculum Specialist",
        ],
      },
      {
        id: createDegreeId("BEd Intermediate Phase NWU"),
        name: "Bachelor of Education Intermediate Phase",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description: "Intermediate phase teacher education (Grades 4-6)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Intermediate Phase Teacher",
          "Primary School Teacher",
          "Subject Specialist",
        ],
      },
      {
        id: createDegreeId("BEd Senior Further Education NWU"),
        name: "Bachelor of Education Senior and Further Education",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description: "Senior phase and FET teacher education (Grades 7-12)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: false },
        ],
        careerProspects: [
          "High School Teacher",
          "Subject Specialist",
          "Education Coordinator",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Engineering NWU"),
    name: "Faculty of Engineering",
    description: "Engineering programs across multiple disciplines",
    degrees: [
      {
        id: createDegreeId("BEng Chemical Engineering NWU"),
        name: "Bachelor of Engineering (Chemical Engineering)",
        faculty: "Engineering",
        duration: "4 years",
        apsRequirement: 34,
        description: "Chemical engineering program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Chemical Engineer",
          "Process Engineer",
          "Plant Manager",
        ],
      },
      {
        id: createDegreeId("BEng Electrical Engineering NWU"),
        name: "Bachelor of Engineering (Electrical Engineering)",
        faculty: "Engineering",
        duration: "4 years",
        apsRequirement: 34,
        description: "Electrical engineering program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Electrical Engineer",
          "Power Systems Engineer",
          "Electronics Engineer",
        ],
      },
      {
        id: createDegreeId("BEng Computer Electronic Engineering NWU"),
        name: "Bachelor of Engineering (Computer & Electronic Engineering)",
        faculty: "Engineering",
        duration: "4 years",
        apsRequirement: 34,
        description: "Computer and electronic engineering program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Computer Engineer",
          "Electronics Engineer",
          "Software Engineer",
        ],
      },
      {
        id: createDegreeId("BEng Electromechanical Engineering NWU"),
        name: "Bachelor of Engineering (Electromechanical Engineering)",
        faculty: "Engineering",
        duration: "4 years",
        apsRequirement: 34,
        description: "Electromechanical engineering program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Electromechanical Engineer",
          "Automation Engineer",
          "Systems Engineer",
        ],
      },
      {
        id: createDegreeId("BEng Mechanical Engineering NWU"),
        name: "Bachelor of Engineering (Mechanical Engineering)",
        faculty: "Engineering",
        duration: "4 years",
        apsRequirement: 34,
        description: "Mechanical engineering program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Mechanical Engineer",
          "Design Engineer",
          "Manufacturing Engineer",
        ],
      },
      {
        id: createDegreeId("BEng Industrial Engineering NWU"),
        name: "Bachelor of Engineering (Industrial Engineering)",
        faculty: "Engineering",
        duration: "4 years",
        apsRequirement: 34,
        description: "Industrial engineering program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Industrial Engineer",
          "Operations Manager",
          "Quality Engineer",
        ],
      },
      {
        id: createDegreeId("BEng Mechatronic Engineering NWU"),
        name: "Bachelor of Engineering (Mechatronic Engineering)",
        faculty: "Engineering",
        duration: "4 years",
        apsRequirement: 34,
        description: "Mechatronic engineering program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Mechatronics Engineer",
          "Robotics Engineer",
          "Automation Specialist",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Health Sciences NWU"),
    name: "Faculty of Health Sciences",
    description: "Health sciences, medical, and sports science programs",
    degrees: [
      {
        id: createDegreeId("Diploma Coaching Science NWU"),
        name: "Diploma in Coaching Science",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 18,
        description: "Sports coaching and exercise science",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
          { name: "Life Sciences", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Sports Coach",
          "Fitness Trainer",
          "Athletic Trainer",
        ],
      },
      {
        id: createDegreeId("BHealthSci Physiology Biochemistry NWU"),
        name: "Bachelor of Health Sciences (with Physiology and Biochemistry)",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Health sciences with physiology and biochemistry focus",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Medical Researcher",
          "Laboratory Scientist",
          "Health Consultant",
        ],
      },
      {
        id: createDegreeId("BHealthSci Physiology Psychology NWU"),
        name: "Bachelor of Health Sciences (with Physiology and Psychology)",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Health sciences with physiology and psychology focus",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Health Psychologist",
          "Sports Psychologist",
          "Research Scientist",
        ],
      },
      {
        id: createDegreeId("BHealthSci Sport Coaching Human Movement NWU"),
        name: "Bachelor of Health Sciences (with Sport Coaching and Human Movement Sciences)",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description:
          "Health sciences with sport coaching and human movement focus",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Sports Coach",
          "Exercise Physiologist",
          "Movement Specialist",
        ],
      },
      {
        id: createDegreeId("BHealthSci Recreation Sciences Psychology NWU"),
        name: "Bachelor of Health Sciences (with Recreation Sciences and Psychology)",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description:
          "Health sciences with recreation sciences and psychology focus",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Recreation Therapist",
          "Sports Psychologist",
          "Wellness Coordinator",
        ],
      },
      {
        id: createDegreeId(
          "BHealthSci Recreation Science Tourism Sport Recreation Admin NWU",
        ),
        name: "Bachelor of Health Sciences (with Recreation Science and Tourism Management, with Sport and Recreation Administration)",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description:
          "Health sciences with recreation, tourism and sport administration focus",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
          { name: "Geography", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Recreation Manager",
          "Sports Administrator",
          "Tourism Recreation Specialist",
        ],
      },
      {
        id: createDegreeId(
          "BA Behavioural Sciences Psychology Geography Environmental NWU",
        ),
        name: "Bachelor of Arts in Behavioural Sciences (with Psychology and Geography and Environmental Management, with Psychology and Tourism Management)",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description:
          "Behavioural sciences with psychology and environmental or tourism focus",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Geography", level: 4, isRequired: false },
          { name: "Life Orientation", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Environmental Psychologist",
          "Tourism Psychologist",
          "Behavioural Analyst",
        ],
      },
      {
        id: createDegreeId("BSocSci Psychology NWU"),
        name: "Bachelor of Social Sciences (with Psychology)",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Social sciences with psychology specialization",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: false },
          { name: "Life Orientation", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Social Psychologist",
          "Research Psychologist",
          "Community Psychologist",
        ],
      },
      {
        id: createDegreeId("Bachelor of Consumer Studies NWU"),
        name: "Bachelor of Consumer Studies",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Consumer behavior and market research",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Consumer Researcher",
          "Market Analyst",
          "Product Manager",
        ],
      },
      {
        id: createDegreeId(
          "Bachelor of Consumer Studies Food Production Management NWU",
        ),
        name: "Bachelor of Consumer Studies (in Food Production Management)",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Consumer studies with food production management focus",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Food Production Manager",
          "Quality Control Manager",
          "Food Safety Inspector",
        ],
      },
      {
        id: createDegreeId(
          "Bachelor of Consumer Studies Fashion Retail Management NWU",
        ),
        name: "Bachelor of Consumer Studies (in Fashion Retail Management)",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Consumer studies with fashion retail management focus",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Visual Arts", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Fashion Retail Manager",
          "Merchandising Manager",
          "Fashion Buyer",
        ],
      },
      {
        id: createDegreeId("Bachelor of Social Work NWU"),
        name: "Bachelor of Social Work",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 28,
        description: "Professional social work program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Social Worker",
          "Community Developer",
          "Case Manager",
        ],
      },
      {
        id: createDegreeId("Bachelor of Pharmacy NWU"),
        name: "Bachelor of Pharmacy",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 32,
        description: "Professional pharmacy program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Pharmacist",
          "Clinical Pharmacist",
          "Pharmaceutical Researcher",
        ],
      },
      {
        id: createDegreeId("BSc Dietetics NWU"),
        name: "Bachelor of Science in Dietetics",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 30,
        description: "Nutrition and dietetic science",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: ["Dietitian", "Nutritionist", "Health Consultant"],
      },
      {
        id: createDegreeId("BHealthSci Occupational Hygiene NWU"),
        name: "Bachelor of Health Science in Occupational Hygiene",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 27,
        description: "Occupational health and safety science",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Occupational Hygienist",
          "Safety Officer",
          "Health and Safety Consultant",
        ],
      },
      {
        id: createDegreeId("BHealthSci Biokinetics NWU"),
        name: "Bachelor of Health Science in Biokinetics",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 32,
        description: "Exercise science and rehabilitation",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Biokineticist",
          "Exercise Therapist",
          "Sports Scientist",
        ],
      },
      {
        id: createDegreeId("Bachelor of Nursing NWU"),
        name: "Bachelor of Nursing",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 25,
        description: "Professional nursing program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: ["Nurse", "Healthcare Manager", "Clinical Specialist"],
      },
    ],
  },
];
