import { Faculty } from "@/types/university";
import { createDegreeId, createFacultyId } from "./base";

// Rhodes University (RU) - Faculty Data - Based on 2024/2025 Academic Programs
export const RHODES_FACULTIES: Faculty[] = [
  {
    id: createFacultyId("Faculty of Commerce Rhodes"),
    name: "Faculty of Commerce",
    description: "Business, economics, and financial studies programs",
    degrees: [
      {
        id: createDegreeId("BBusSc Rhodes"),
        name: "Bachelor of Business Science",
        faculty: "Commerce",
        duration: "3 years",
        apsRequirement: 36,
        description:
          "Comprehensive business science education with various specializations",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          {
            name: "Economics or Business Studies",
            level: 5,
            isRequired: false,
          },
        ],
        careerProspects: [
          "Business Analyst",
          "Financial Consultant",
          "Management Consultant",
          "Investment Advisor",
          "Business Development Manager",
        ],
      },
      {
        id: createDegreeId("BCom Rhodes"),
        name: "Bachelor of Commerce",
        faculty: "Commerce",
        duration: "3 years",
        apsRequirement: 34,
        description: "Commercial and business management education",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Accounting", level: 5, isRequired: false },
        ],
        careerProspects: [
          "Accountant",
          "Financial Manager",
          "Business Manager",
          "Marketing Manager",
          "Human Resources Manager",
        ],
      },
      {
        id: createDegreeId("BEcon Rhodes"),
        name: "Bachelor of Economics",
        faculty: "Commerce",
        duration: "3 years",
        apsRequirement: 34,
        description: "Economic theory and policy analysis",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Economics", level: 5, isRequired: false },
        ],
        careerProspects: [
          "Economist",
          "Economic Analyst",
          "Policy Researcher",
          "Development Economist",
          "Financial Analyst",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Education Rhodes"),
    name: "Faculty of Education",
    description: "Teacher training and educational development programs",
    degrees: [
      {
        id: createDegreeId("BEd Foundation Phase Rhodes"),
        name: "Bachelor of Education (Foundation Phase Teaching)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 30,
        description: "Foundation phase teacher training (Grades R-3)",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Foundation Phase Teacher",
          "Early Childhood Educator",
          "Curriculum Developer",
          "Educational Coordinator",
          "Learning Support Specialist",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Humanities Rhodes"),
    name: "Faculty of Humanities",
    description: "Liberal arts, social sciences, and creative disciplines",
    degrees: [
      {
        id: createDegreeId("BA Rhodes"),
        name: "Bachelor of Arts",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 32,
        description:
          "Liberal arts education with diverse majors including languages, literature, history, philosophy, and social sciences",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          {
            name: "Mathematics or Mathematical Literacy",
            level: 4,
            isRequired: true,
          },
          { name: "Two additional subjects", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Teacher",
          "Journalist",
          "Social Worker",
          "Museum Curator",
          "Government Official",
          "Writer",
        ],
      },
      {
        id: createDegreeId("BFA Rhodes"),
        name: "Bachelor of Fine Arts",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 30,
        description: "Visual arts practice and creative expression",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Visual Arts", level: 6, isRequired: true },
          { name: "Art History", level: 5, isRequired: false },
        ],
        careerProspects: [
          "Visual Artist",
          "Art Teacher",
          "Gallery Curator",
          "Art Director",
          "Freelance Artist",
          "Art Therapist",
        ],
      },
      {
        id: createDegreeId("BJourn Rhodes"),
        name: "Bachelor of Journalism and Media Studies",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 32,
        description: "Journalism, media production, and communication studies",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          {
            name: "Mathematics or Mathematical Literacy",
            level: 4,
            isRequired: true,
          },
          { name: "History or Geography", level: 5, isRequired: false },
        ],
        careerProspects: [
          "Journalist",
          "Media Producer",
          "Public Relations Officer",
          "Content Creator",
          "News Editor",
          "Communications Manager",
        ],
      },
      {
        id: createDegreeId("BMus Rhodes"),
        name: "Bachelor of Music",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 28,
        description: "Musical performance, composition, and music theory",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Music", level: 6, isRequired: true },
          {
            name: "Mathematics or Mathematical Literacy",
            level: 4,
            isRequired: true,
          },
        ],
        careerProspects: [
          "Professional Musician",
          "Music Teacher",
          "Composer",
          "Sound Engineer",
          "Music Therapist",
          "Music Producer",
        ],
      },
      {
        id: createDegreeId("BSocSci Rhodes"),
        name: "Bachelor of Social Science",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 32,
        description:
          "Social sciences including psychology, sociology, anthropology, and politics",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Social Worker",
          "Psychologist",
          "Community Development Officer",
          "Policy Analyst",
          "Research Officer",
          "Human Rights Advocate",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Law Rhodes"),
    name: "Faculty of Law",
    description: "Legal education and jurisprudence",
    degrees: [
      {
        id: createDegreeId("LLB Rhodes"),
        name: "Bachelor of Laws",
        faculty: "Law",
        duration: "4 years",
        apsRequirement: 36,
        description: "Professional legal qualification",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "History or Geography", level: 5, isRequired: false },
        ],
        careerProspects: [
          "Attorney",
          "Advocate",
          "Legal Advisor",
          "Magistrate",
          "Legal Researcher",
          "Corporate Lawyer",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Pharmacy Rhodes"),
    name: "Faculty of Pharmacy",
    description: "Pharmaceutical sciences and practice",
    degrees: [
      {
        id: createDegreeId("BPharm Rhodes"),
        name: "Bachelor of Pharmacy",
        faculty: "Pharmacy",
        duration: "4 years",
        apsRequirement: 36,
        description: "Pharmaceutical sciences and clinical pharmacy practice",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
          { name: "Life Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Pharmacist",
          "Clinical Pharmacist",
          "Hospital Pharmacist",
          "Industrial Pharmacist",
          "Pharmaceutical Researcher",
          "Regulatory Affairs Specialist",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Science Rhodes"),
    name: "Faculty of Science",
    description: "Natural sciences, mathematics, and computer science",
    degrees: [
      {
        id: createDegreeId("BSc Rhodes"),
        name: "Bachelor of Science",
        faculty: "Science",
        duration: "3 years",
        apsRequirement: 32,
        description:
          "General science education with various specialization options",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: false },
        ],
        careerProspects: [
          "Research Scientist",
          "Laboratory Technician",
          "Environmental Consultant",
          "Science Teacher",
          "Quality Control Analyst",
        ],
      },
      {
        id: createDegreeId("BSc Computer Science Rhodes"),
        name: "Bachelor of Science in Computer Science",
        faculty: "Science",
        duration: "3 years",
        apsRequirement: 36,
        description:
          "Computer programming, software development, and information technology",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 7, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Software Developer",
          "Systems Analyst",
          "IT Consultant",
          "Database Administrator",
          "Cybersecurity Specialist",
        ],
      },
      {
        id: createDegreeId("BSc Environmental Science Rhodes"),
        name: "Bachelor of Science in Environmental Science",
        faculty: "Science",
        duration: "3 years",
        apsRequirement: 32,
        description: "Environmental systems, conservation, and sustainability",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 6, isRequired: true },
          { name: "Geography", level: 5, isRequired: false },
        ],
        careerProspects: [
          "Environmental Consultant",
          "Conservation Officer",
          "Environmental Impact Assessor",
          "Sustainability Coordinator",
          "Environmental Researcher",
        ],
      },
      {
        id: createDegreeId("BSc Mathematics Rhodes"),
        name: "Bachelor of Science in Mathematics",
        faculty: "Science",
        duration: "3 years",
        apsRequirement: 36,
        description: "Pure and applied mathematics",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 7, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Mathematician",
          "Statistician",
          "Data Analyst",
          "Actuary",
          "Research Scientist",
        ],
      },
      {
        id: createDegreeId("BSc Psychology Rhodes"),
        name: "Bachelor of Science in Psychology",
        faculty: "Science",
        duration: "3 years",
        apsRequirement: 32,
        description: "Scientific study of human behavior and mental processes",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: false },
        ],
        careerProspects: [
          "Psychologist",
          "Counselor",
          "Human Resources Specialist",
          "Market Research Analyst",
          "Clinical Researcher",
        ],
      },
      {
        id: createDegreeId("BSc Information Systems Rhodes"),
        name: "Bachelor of Science in Information Systems",
        faculty: "Science",
        duration: "3 years",
        apsRequirement: 34,
        description: "Business information systems and technology management",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Information Technology", level: 5, isRequired: false },
        ],
        careerProspects: [
          "Business Analyst",
          "IT Project Manager",
          "Systems Administrator",
          "Database Designer",
          "IT Consultant",
        ],
      },
    ],
  },
];
