import { Faculty } from "@/types/university";
import { createDegreeId, createFacultyId } from "./base";

// Sol Plaatje University (SPU) - Faculty Data
export const SPU_FACULTIES: Faculty[] = [
  {
    id: createFacultyId("Faculty of Natural and Applied Sciences SPU"),
    name: "Faculty of Natural and Applied Sciences",
    description: "Science, technology, and applied sciences programs",
    degrees: [
      {
        id: createDegreeId("BSc Computing SPU"),
        name: "Bachelor of Science in Computing",
        faculty: "Natural and Applied Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Computer science and information technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Software Developer",
          "Systems Analyst",
          "IT Consultant",
        ],
      },
      {
        id: createDegreeId("BSc Mathematics SPU"),
        name: "Bachelor of Science in Mathematical Sciences",
        faculty: "Natural and Applied Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Mathematics and statistical sciences",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: ["Mathematician", "Statistician", "Data Analyst"],
      },
      {
        id: createDegreeId("BSc Natural Sciences SPU"),
        name: "Bachelor of Science in Natural Sciences",
        faculty: "Natural and Applied Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Physical and life sciences foundation",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Research Scientist",
          "Laboratory Technician",
          "Science Teacher",
        ],
      },
      {
        id: createDegreeId("BSc Environmental Management SPU"),
        name: "Bachelor of Science in Environmental Management",
        faculty: "Natural and Applied Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Environmental science and sustainability",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Geography", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Environmental Manager",
          "Conservation Officer",
          "Sustainability Consultant",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Humanities SPU"),
    name: "Faculty of Humanities",
    description: "Liberal arts, languages, and social sciences programs",
    degrees: [
      {
        id: createDegreeId("BA General SPU"),
        name: "Bachelor of Arts (General)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 23,
        description: "Liberal arts foundation program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: ["Social Worker", "Researcher", "Community Developer"],
      },
      {
        id: createDegreeId("BA English SPU"),
        name: "Bachelor of Arts in English",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 24,
        description: "English language and literature studies",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: ["Teacher", "Editor", "Writer"],
      },
      {
        id: createDegreeId("BA Psychology SPU"),
        name: "Bachelor of Arts in Psychology",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 25,
        description: "Psychological studies and human behavior",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: false },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Psychologist",
          "Counselor",
          "Human Resources Officer",
        ],
      },
      {
        id: createDegreeId("BA Social Work SPU"),
        name: "Bachelor of Social Work",
        faculty: "Humanities",
        duration: "4 years",
        apsRequirement: 23,
        description: "Professional social work practice",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Social Worker",
          "Community Organizer",
          "Case Manager",
        ],
      },
      {
        id: createDegreeId("BA Languages SPU"),
        name: "Bachelor of Arts in Languages",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 23,
        description: "African languages and linguistics",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: ["Translator", "Language Teacher", "Cultural Officer"],
      },
      {
        id: createDegreeId("BA Heritage Studies SPU"),
        name: "Bachelor of Arts in Heritage Studies",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 23,
        description: "Cultural heritage and museum studies",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Museum Curator",
          "Heritage Officer",
          "Cultural Consultant",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Management and Law SPU"),
    name: "Faculty of Management and Law",
    description: "Business, law, and public administration programs",
    degrees: [
      {
        id: createDegreeId("BCom Accounting SPU"),
        name: "Bachelor of Commerce in Accounting",
        faculty: "Management and Law",
        duration: "3 years",
        apsRequirement: 26,
        description: "Accounting and financial management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: ["Accountant", "Financial Analyst", "Auditor"],
      },
      {
        id: createDegreeId("BCom Business Management SPU"),
        name: "Bachelor of Commerce in Business Management",
        faculty: "Management and Law",
        duration: "3 years",
        apsRequirement: 24,
        description: "Business administration and management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Business Manager",
          "Operations Manager",
          "Consultant",
        ],
      },
      {
        id: createDegreeId("BCom Economics SPU"),
        name: "Bachelor of Commerce in Economics",
        faculty: "Management and Law",
        duration: "3 years",
        apsRequirement: 24,
        description: "Economic theory and analysis",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: ["Economist", "Policy Analyst", "Research Officer"],
      },
      {
        id: createDegreeId("LLB SPU"),
        name: "Bachelor of Laws (LLB)",
        faculty: "Management and Law",
        duration: "4 years",
        apsRequirement: 30,
        description: "Professional law degree",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: false },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: ["Lawyer", "Advocate", "Legal Advisor"],
      },
      {
        id: createDegreeId("BAdmin SPU"),
        name: "Bachelor of Administration",
        faculty: "Management and Law",
        duration: "3 years",
        apsRequirement: 24,
        description: "Public administration and governance",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: false },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Public Administrator",
          "Municipal Officer",
          "Government Official",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Education SPU"),
    name: "Faculty of Education",
    description: "Teacher education and educational programs",
    degrees: [
      {
        id: createDegreeId("BEd Foundation Phase SPU"),
        name: "BEd Foundation Phase",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 24,
        description: "Teacher education for foundation phase (Grades R-3)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Foundation Phase Teacher",
          "Early Childhood Educator",
        ],
      },
      {
        id: createDegreeId("BEd Intermediate Phase SPU"),
        name: "BEd Intermediate Phase",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 24,
        description: "Teacher education for intermediate phase (Grades 4-6)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Intermediate Phase Teacher",
          "Primary School Teacher",
        ],
      },
      {
        id: createDegreeId("BEd Senior Phase FET SPU"),
        name: "BEd Senior Phase and FET",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 24,
        description:
          "Teacher education for senior phase (Grades 7-9) and FET (Grades 10-12)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "High School Teacher",
          "Subject Specialist",
          "Education Coordinator",
        ],
      },
    ],
  },
];
