import { Faculty } from "@/types/university";
import { createDegreeId, createFacultyId } from "./base";

// Tshwane University of Technology (TUT) - Faculty Data
export const TUT_FACULTIES: Faculty[] = [
  {
    id: createFacultyId("Faculty of Engineering and the Built Environment TUT"),
    name: "Faculty of Engineering and the Built Environment",
    description: "Engineering, architecture, and construction programs",
    degrees: [
      {
        id: createDegreeId("Diploma in Civil Engineering TUT"),
        name: "Diploma in Civil Engineering",
        faculty: "Engineering and the Built Environment",
        duration: "3 years",
        apsRequirement: 26,
        description: "Civil engineering and construction technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Civil Technician",
          "Construction Manager",
          "Project Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma in Electrical Engineering TUT"),
        name: "Diploma in Electrical Engineering",
        faculty: "Engineering and the Built Environment",
        duration: "3 years",
        apsRequirement: 26,
        description: "Electrical engineering and power systems",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Electrical Technician",
          "Power Systems Engineer",
          "Maintenance Engineer",
        ],
      },
      {
        id: createDegreeId("Diploma in Mechanical Engineering TUT"),
        name: "Diploma in Mechanical Engineering",
        faculty: "Engineering and the Built Environment",
        duration: "3 years",
        apsRequirement: 26,
        description: "Mechanical engineering and manufacturing technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Mechanical Technician",
          "Manufacturing Engineer",
          "Design Engineer",
        ],
      },
      {
        id: createDegreeId("Diploma in Chemical Engineering TUT"),
        name: "Diploma in Chemical Engineering",
        faculty: "Engineering and the Built Environment",
        duration: "3 years",
        apsRequirement: 26,
        description: "Chemical engineering and process technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Chemical Technician",
          "Process Engineer",
          "Plant Operator",
        ],
      },
      {
        id: createDegreeId("Diploma in Industrial Engineering TUT"),
        name: "Diploma in Industrial Engineering",
        faculty: "Engineering and the Built Environment",
        duration: "3 years",
        apsRequirement: 26,
        description: "Industrial engineering and systems optimization",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Industrial Engineer",
          "Systems Analyst",
          "Operations Manager",
        ],
      },
      {
        id: createDegreeId("Diploma in Architecture TUT"),
        name: "Diploma in Architectural Technology",
        faculty: "Engineering and the Built Environment",
        duration: "3 years",
        apsRequirement: 24,
        description: "Architectural design and building technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Architectural Technician",
          "Draughtsperson",
          "Building Inspector",
        ],
      },
      {
        id: createDegreeId("BTech Civil Engineering TUT"),
        name: "Bachelor of Technology in Civil Engineering",
        faculty: "Engineering and the Built Environment",
        duration: "4 years",
        apsRequirement: 28,
        description: "Advanced civil engineering and project management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Civil Engineer",
          "Structural Engineer",
          "Project Manager",
        ],
      },
      {
        id: createDegreeId("BTech Electrical Engineering TUT"),
        name: "Bachelor of Technology in Electrical Engineering",
        faculty: "Engineering and the Built Environment",
        duration: "4 years",
        apsRequirement: 28,
        description: "Advanced electrical engineering and automation",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Electrical Engineer",
          "Control Systems Engineer",
          "Power Engineer",
        ],
      },
    ],
  },
  {
    id: createFacultyId(
      "Faculty of Information and Communication Technology TUT",
    ),
    name: "Faculty of Information and Communication Technology",
    description:
      "Information technology, computer science, and digital media programs",
    degrees: [
      {
        id: createDegreeId("Diploma in Information Technology TUT"),
        name: "Diploma in Information Technology",
        faculty: "Information and Communication Technology",
        duration: "3 years",
        apsRequirement: 24,
        description: "Computer systems and information technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 3, isRequired: false },
        ],
        careerProspects: [
          "IT Support Technician",
          "Network Administrator",
          "Systems Analyst",
        ],
      },
      {
        id: createDegreeId("Diploma in Software Development TUT"),
        name: "Diploma in Software Development",
        faculty: "Information and Communication Technology",
        duration: "3 years",
        apsRequirement: 24,
        description: "Software programming and application development",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 3, isRequired: false },
        ],
        careerProspects: ["Software Developer", "Programmer", "Web Developer"],
      },
      {
        id: createDegreeId("Diploma in Computer Systems Engineering TUT"),
        name: "Diploma in Computer Systems Engineering",
        faculty: "Information and Communication Technology",
        duration: "3 years",
        apsRequirement: 26,
        description: "Computer hardware and systems engineering",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Computer Systems Engineer",
          "Hardware Technician",
          "Network Engineer",
        ],
      },
      {
        id: createDegreeId("Diploma in Multimedia TUT"),
        name: "Diploma in Multimedia",
        faculty: "Information and Communication Technology",
        duration: "3 years",
        apsRequirement: 22,
        description: "Digital media and multimedia production",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: false },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Multimedia Designer",
          "Video Editor",
          "Digital Content Creator",
        ],
      },
      {
        id: createDegreeId("BTech Information Technology TUT"),
        name: "Bachelor of Technology in Information Technology",
        faculty: "Information and Communication Technology",
        duration: "4 years",
        apsRequirement: 26,
        description: "Advanced information technology and systems management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: false },
        ],
        careerProspects: [
          "IT Manager",
          "Systems Architect",
          "Technology Consultant",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Economic and Financial Sciences TUT"),
    name: "Faculty of Economic and Financial Sciences",
    description: "Business, accounting, and financial management programs",
    degrees: [
      {
        id: createDegreeId("Diploma in Accounting TUT"),
        name: "Diploma in Accounting",
        faculty: "Economic and Financial Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Accounting principles and financial management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Bookkeeper",
          "Accounting Clerk",
          "Financial Assistant",
        ],
      },
      {
        id: createDegreeId("Diploma in Business Management TUT"),
        name: "Diploma in Business Management",
        faculty: "Economic and Financial Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Business administration and management principles",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Supervisor",
          "Team Leader",
          "Operations Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma in Marketing TUT"),
        name: "Diploma in Marketing",
        faculty: "Economic and Financial Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Marketing principles and consumer behavior",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Marketing Assistant",
          "Sales Representative",
          "Brand Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma in Human Resources TUT"),
        name: "Diploma in Human Resources Management",
        faculty: "Economic and Financial Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Human resource management and industrial relations",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "HR Assistant",
          "Recruitment Officer",
          "Training Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma in Economics TUT"),
        name: "Diploma in Economics",
        faculty: "Economic and Financial Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Economic theory and financial analysis",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Economic Analyst",
          "Research Assistant",
          "Financial Consultant",
        ],
      },
      {
        id: createDegreeId("BTech Business Administration TUT"),
        name: "Bachelor of Technology in Business Administration",
        faculty: "Economic and Financial Sciences",
        duration: "4 years",
        apsRequirement: 24,
        description:
          "Advanced business administration and strategic management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Business Manager",
          "Operations Manager",
          "Strategic Planner",
        ],
      },
      {
        id: createDegreeId("BTech Financial Management TUT"),
        name: "Bachelor of Technology in Financial Management",
        faculty: "Economic and Financial Sciences",
        duration: "4 years",
        apsRequirement: 26,
        description: "Financial management and investment analysis",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Financial Manager",
          "Investment Analyst",
          "Treasury Officer",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Science TUT"),
    name: "Faculty of Science",
    description: "Natural sciences, mathematics, and applied sciences programs",
    degrees: [
      {
        id: createDegreeId("Diploma in Analytical Chemistry TUT"),
        name: "Diploma in Analytical Chemistry",
        faculty: "Science",
        duration: "3 years",
        apsRequirement: 24,
        description: "Chemical analysis and laboratory techniques",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Analytical Chemist",
          "Quality Control Analyst",
          "Laboratory Technician",
        ],
      },
      {
        id: createDegreeId("Diploma in Biotechnology TUT"),
        name: "Diploma in Biotechnology",
        faculty: "Science",
        duration: "3 years",
        apsRequirement: 24,
        description: "Biotechnology and biological applications",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Biotechnologist",
          "Research Scientist",
          "Quality Control Specialist",
        ],
      },
      {
        id: createDegreeId("Diploma in Environmental Science TUT"),
        name: "Diploma in Environmental Science",
        faculty: "Science",
        duration: "3 years",
        apsRequirement: 24,
        description: "Environmental studies and conservation management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Geography", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Environmental Scientist",
          "Conservation Officer",
          "Environmental Consultant",
        ],
      },
      {
        id: createDegreeId("Diploma in Food Technology TUT"),
        name: "Diploma in Food Technology",
        faculty: "Science",
        duration: "3 years",
        apsRequirement: 24,
        description: "Food science and processing technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Food Technologist",
          "Quality Assurance Manager",
          "Product Developer",
        ],
      },
      {
        id: createDegreeId("BTech Chemistry TUT"),
        name: "Bachelor of Technology in Chemistry",
        faculty: "Science",
        duration: "4 years",
        apsRequirement: 26,
        description: "Advanced chemistry and industrial applications",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Chemical Engineer",
          "Process Engineer",
          "Research Scientist",
        ],
      },
      {
        id: createDegreeId("BTech Biotechnology TUT"),
        name: "Bachelor of Technology in Biotechnology",
        faculty: "Science",
        duration: "4 years",
        apsRequirement: 26,
        description: "Advanced biotechnology and bioprocessing",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Senior Biotechnologist",
          "Research Manager",
          "Product Development Manager",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Humanities TUT"),
    name: "Faculty of Humanities",
    description: "Liberal arts, education, and social sciences programs",
    degrees: [
      {
        id: createDegreeId("Diploma in Language Practice TUT"),
        name: "Diploma in Language Practice",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 23,
        description: "Language editing, translation, and communication",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: ["Language Practitioner", "Editor", "Translator"],
      },
      {
        id: createDegreeId("Diploma in Journalism TUT"),
        name: "Diploma in Journalism",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 24,
        description: "Print and digital journalism",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: ["Journalist", "Reporter", "News Editor"],
      },
      {
        id: createDegreeId("Diploma in Communication TUT"),
        name: "Diploma in Communication",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 23,
        description: "Communication theory and media studies",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Communications Officer",
          "Media Coordinator",
          "Public Relations Assistant",
        ],
      },
      {
        id: createDegreeId("BTech Education TUT"),
        name: "Bachelor of Technology in Education",
        faculty: "Humanities",
        duration: "4 years",
        apsRequirement: 24,
        description: "Technical and vocational education",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Vocational Teacher",
          "Technical Trainer",
          "Education Coordinator",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of The Arts TUT"),
    name: "Faculty of The Arts",
    description: "Creative arts, design, and visual communication programs",
    degrees: [
      {
        id: createDegreeId("Diploma in Graphic Design TUT"),
        name: "Diploma in Graphic Design",
        faculty: "The Arts",
        duration: "3 years",
        apsRequirement: 22,
        description: "Visual communication and graphic design",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: false },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Graphic Designer",
          "Visual Designer",
          "Creative Director",
        ],
      },
      {
        id: createDegreeId("Diploma in Fashion Design TUT"),
        name: "Diploma in Fashion Design",
        faculty: "The Arts",
        duration: "3 years",
        apsRequirement: 22,
        description: "Fashion design and clothing technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: false },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Fashion Designer",
          "Pattern Maker",
          "Fashion Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma in Interior Design TUT"),
        name: "Diploma in Interior Design",
        faculty: "The Arts",
        duration: "3 years",
        apsRequirement: 22,
        description: "Interior design and space planning",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: false },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Interior Designer",
          "Space Planner",
          "Design Consultant",
        ],
      },
      {
        id: createDegreeId("Diploma in Photography TUT"),
        name: "Diploma in Photography",
        faculty: "The Arts",
        duration: "3 years",
        apsRequirement: 22,
        description: "Photography and visual media",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: false },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Photographer",
          "Visual Media Specialist",
          "Photo Editor",
        ],
      },
      {
        id: createDegreeId("BTech Design TUT"),
        name: "Bachelor of Technology in Design",
        faculty: "The Arts",
        duration: "4 years",
        apsRequirement: 24,
        description: "Advanced design and creative direction",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: false },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Senior Designer",
          "Creative Director",
          "Design Manager",
        ],
      },
    ],
  },
];
