import { Faculty } from "@/types/university";
import { createDegreeId, createFacultyId } from "./base";

// University of Cape Town (UCT) - Faculty Data - Based on 2024/2025 Academic Programs
export const UCT_FACULTIES: Faculty[] = [
  {
    id: createFacultyId("Faculty of Commerce UCT"),
    name: "Faculty of Commerce",
    description:
      "Business, economics, finance, and information systems programs",
    degrees: [
      {
        id: createDegreeId("BBusSc Actuarial Science UCT"),
        name: "Bachelor of Business Science in Actuarial Science",
        faculty: "Commerce",
        duration: "3 years",
        apsRequirement: 42,
        description:
          "Mathematical and statistical analysis of risk in insurance and finance",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 7, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Actuary",
          "Risk Analyst",
          "Investment Analyst",
          "Insurance Specialist",
          "Financial Modeller",
        ],
      },
      {
        id: createDegreeId("BBusSc Statistics Data Sciences UCT"),
        name: "Bachelor of Business Science in Statistics and Data Sciences",
        faculty: "Commerce",
        duration: "3 years",
        apsRequirement: 40,
        description:
          "Statistical analysis and data science applications in business",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 7, isRequired: true },
          { name: "Information Technology", level: 5, isRequired: false },
        ],
        careerProspects: [
          "Data Scientist",
          "Statistician",
          "Business Analyst",
          "Market Research Analyst",
          "Operations Research Analyst",
        ],
      },
      {
        id: createDegreeId("BBusSc Finance Investment Banking UCT"),
        name: "Bachelor of Business Science in Finance, Investment, and Banking",
        faculty: "Commerce",
        duration: "3 years",
        apsRequirement: 40,
        description: "Advanced finance and investment management",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Economics", level: 5, isRequired: false },
        ],
        careerProspects: [
          "Investment Banker",
          "Financial Analyst",
          "Portfolio Manager",
          "Corporate Finance Specialist",
          "Financial Advisor",
        ],
      },
      {
        id: createDegreeId("BCom Financial Accounting CA UCT"),
        name: "Bachelor of Commerce in Financial Accounting (Chartered Accountant)",
        faculty: "Commerce",
        duration: "3 years",
        apsRequirement: 38,
        description: "Professional accounting qualification leading to CA(SA)",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Accounting", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Chartered Accountant (CA)",
          "Financial Manager",
          "External Auditor",
          "Management Consultant",
          "CFO",
        ],
      },
      {
        id: createDegreeId("BCom Economics Finance UCT"),
        name: "Bachelor of Commerce in Economics and Finance",
        faculty: "Commerce",
        duration: "3 years",
        apsRequirement: 36,
        description: "Economic theory and financial markets analysis",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Economics", level: 5, isRequired: false },
        ],
        careerProspects: [
          "Economist",
          "Financial Analyst",
          "Policy Analyst",
          "Investment Consultant",
          "Economic Researcher",
        ],
      },
      {
        id: createDegreeId("BCom Information Systems UCT"),
        name: "Bachelor of Commerce in Information Systems",
        faculty: "Commerce",
        duration: "3 years",
        apsRequirement: 36,
        description: "Business information systems and technology management",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Information Technology", level: 5, isRequired: false },
        ],
        careerProspects: [
          "Business Analyst",
          "IT Consultant",
          "Systems Manager",
          "Project Manager",
          "Database Administrator",
        ],
      },
      {
        id: createDegreeId("BCom Management Studies UCT"),
        name: "Bachelor of Commerce in Management Studies",
        faculty: "Commerce",
        duration: "3 years",
        apsRequirement: 34,
        description: "Business management and organizational leadership",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Business Studies", level: 5, isRequired: false },
        ],
        careerProspects: [
          "Management Consultant",
          "Business Manager",
          "Operations Manager",
          "HR Manager",
          "Entrepreneur",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Engineering Built Environment UCT"),
    name: "Faculty of Engineering & the Built Environment",
    description: "Engineering disciplines and built environment programs",
    degrees: [
      {
        id: createDegreeId("BEng Chemical Engineering UCT"),
        name: "Bachelor of Engineering in Chemical Engineering",
        faculty: "Engineering & the Built Environment",
        duration: "4 years",
        apsRequirement: 42,
        description: "Chemical processes and industrial engineering",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 7, isRequired: true },
          { name: "Physical Sciences", level: 7, isRequired: true },
        ],
        careerProspects: [
          "Chemical Engineer",
          "Process Engineer",
          "Production Manager",
          "Environmental Engineer",
          "Research Engineer",
        ],
      },
      {
        id: createDegreeId("BEng Civil Engineering UCT"),
        name: "Bachelor of Engineering in Civil Engineering",
        faculty: "Engineering & the Built Environment",
        duration: "4 years",
        apsRequirement: 42,
        description: "Infrastructure design and construction engineering",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 7, isRequired: true },
          { name: "Physical Sciences", level: 7, isRequired: true },
        ],
        careerProspects: [
          "Civil Engineer",
          "Structural Engineer",
          "Construction Manager",
          "Project Engineer",
          "Infrastructure Consultant",
        ],
      },
      {
        id: createDegreeId("BEng Electrical Engineering UCT"),
        name: "Bachelor of Engineering in Electrical Engineering",
        faculty: "Engineering & the Built Environment",
        duration: "4 years",
        apsRequirement: 42,
        description: "Electrical systems and power engineering",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 7, isRequired: true },
          { name: "Physical Sciences", level: 7, isRequired: true },
        ],
        careerProspects: [
          "Electrical Engineer",
          "Power Systems Engineer",
          "Control Systems Engineer",
          "Electronics Engineer",
          "Telecommunications Engineer",
        ],
      },
      {
        id: createDegreeId("BEng Mechanical Engineering UCT"),
        name: "Bachelor of Engineering in Mechanical Engineering",
        faculty: "Engineering & the Built Environment",
        duration: "4 years",
        apsRequirement: 42,
        description: "Mechanical systems and manufacturing engineering",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 7, isRequired: true },
          { name: "Physical Sciences", level: 7, isRequired: true },
        ],
        careerProspects: [
          "Mechanical Engineer",
          "Design Engineer",
          "Manufacturing Engineer",
          "Automotive Engineer",
          "Aerospace Engineer",
        ],
      },
      {
        id: createDegreeId("BEng Mechatronics UCT"),
        name: "Bachelor of Engineering in Mechatronics",
        faculty: "Engineering & the Built Environment",
        duration: "4 years",
        apsRequirement: 42,
        description:
          "Integration of mechanical, electrical, and computer engineering",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 7, isRequired: true },
          { name: "Physical Sciences", level: 7, isRequired: true },
        ],
        careerProspects: [
          "Mechatronics Engineer",
          "Robotics Engineer",
          "Automation Engineer",
          "Control Systems Engineer",
          "Product Development Engineer",
        ],
      },
      {
        id: createDegreeId("BAS Architecture UCT"),
        name: "Bachelor of Architectural Studies",
        faculty: "Engineering & the Built Environment",
        duration: "3 years",
        apsRequirement: 36,
        description: "Foundation in architectural design and theory",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          {
            name: "Visual Arts or Technical Drawing",
            level: 5,
            isRequired: false,
          },
        ],
        careerProspects: [
          "Architect",
          "Urban Planner",
          "Architectural Draughtsperson",
          "Building Designer",
          "Heritage Consultant",
        ],
      },
      {
        id: createDegreeId("BSc Geomatics UCT"),
        name: "Bachelor of Science in Geomatics",
        faculty: "Engineering & the Built Environment",
        duration: "3 years",
        apsRequirement: 34,
        description: "Geographic information systems and surveying",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Geography", level: 5, isRequired: false },
        ],
        careerProspects: [
          "Land Surveyor",
          "GIS Specialist",
          "Cartographer",
          "Remote Sensing Analyst",
          "Spatial Data Analyst",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Health Sciences UCT"),
    name: "Faculty of Health Sciences",
    description: "Medical and health professional programs",
    degrees: [
      {
        id: createDegreeId("MBChB Medicine Surgery UCT"),
        name: "Bachelor of Medicine and Bachelor of Surgery",
        faculty: "Health Sciences",
        duration: "6 years",
        apsRequirement: 42,
        description: "Professional medical degree leading to medical practice",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
          { name: "Life Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Medical Doctor",
          "Specialist Physician",
          "Surgeon",
          "General Practitioner",
          "Medical Researcher",
        ],
      },
      {
        id: createDegreeId("BSc Audiology UCT"),
        name: "Bachelor of Science in Audiology",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 36,
        description: "Hearing and balance disorders diagnosis and treatment",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Audiologist",
          "Hearing Aid Specialist",
          "Clinical Audiologist",
          "Research Audiologist",
          "Educational Audiologist",
        ],
      },
      {
        id: createDegreeId("BSc Occupational Therapy UCT"),
        name: "Bachelor of Science in Occupational Therapy",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 36,
        description:
          "Rehabilitation through meaningful activities and occupations",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Occupational Therapist",
          "Rehabilitation Specialist",
          "Community Health Worker",
          "Assistive Technology Specialist",
          "Hand Therapist",
        ],
      },
      {
        id: createDegreeId("BSc Physiotherapy UCT"),
        name: "Bachelor of Science in Physiotherapy",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 36,
        description: "Physical rehabilitation and movement therapy",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Physiotherapist",
          "Sports Physiotherapist",
          "Rehabilitation Specialist",
          "Private Practice Owner",
          "Clinical Researcher",
        ],
      },
      {
        id: createDegreeId("BSc Speech Language Pathology UCT"),
        name: "Bachelor of Science in Speech-Language Pathology",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 36,
        description: "Communication disorders diagnosis and treatment",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Speech-Language Pathologist",
          "Communication Specialist",
          "Voice Therapist",
          "Swallowing Specialist",
          "Pediatric Speech Therapist",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Humanities UCT"),
    name: "Faculty of Humanities",
    description: "Liberal arts, social sciences, and creative disciplines",
    degrees: [
      {
        id: createDegreeId("BA UCT"),
        name: "Bachelor of Arts",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 32,
        description:
          "Liberal arts education with diverse specialization options",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          {
            name: "Mathematics or Mathematical Literacy",
            level: 4,
            isRequired: true,
          },
          { name: "Two additional subjects", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Journalist",
          "Social Worker",
          "Teacher",
          "Museum Curator",
          "Government Official",
          "Non-profit Manager",
        ],
      },
      {
        id: createDegreeId("BA Film Media Production UCT"),
        name: "Bachelor of Arts in Film & Media Production",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 34,
        description: "Practical film and media production skills",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Visual Arts", level: 5, isRequired: false },
          { name: "Drama", level: 5, isRequired: false },
        ],
        careerProspects: [
          "Film Director",
          "Video Producer",
          "Cinematographer",
          "Film Editor",
          "Media Content Creator",
        ],
      },
      {
        id: createDegreeId("BA Fine Art UCT"),
        name: "Bachelor of Arts in Fine Art",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 32,
        description: "Visual arts practice and theory",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Visual Arts", level: 6, isRequired: true },
          { name: "Art History", level: 5, isRequired: false },
        ],
        careerProspects: [
          "Visual Artist",
          "Art Teacher",
          "Gallery Curator",
          "Art Therapist",
          "Freelance Artist",
        ],
      },
      {
        id: createDegreeId("BSocSci Psychology UCT"),
        name: "Bachelor of Social Science in Psychology",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 34,
        description: "Scientific study of human behavior and mental processes",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: false },
        ],
        careerProspects: [
          "Psychologist",
          "Counselor",
          "Human Resources Specialist",
          "Market Researcher",
          "Clinical Researcher",
        ],
      },
      {
        id: createDegreeId("BSocSci Politics International Relations UCT"),
        name: "Bachelor of Social Science in Politics & International Relations",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 32,
        description: "Political systems and international affairs",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "History", level: 5, isRequired: false },
          { name: "Geography", level: 5, isRequired: false },
        ],
        careerProspects: [
          "Diplomat",
          "Political Analyst",
          "Government Official",
          "International Relations Specialist",
          "Policy Researcher",
        ],
      },
      {
        id: createDegreeId("BMus UCT"),
        name: "Bachelor of Music",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 30,
        description: "Musical performance, composition, and theory",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Music", level: 6, isRequired: true },
          {
            name: "Mathematics or Mathematical Literacy",
            level: 4,
            isRequired: true,
          },
        ],
        careerProspects: [
          "Professional Musician",
          "Music Teacher",
          "Composer",
          "Music Therapist",
          "Sound Engineer",
        ],
      },
      {
        id: createDegreeId("BSW Social Work UCT"),
        name: "Bachelor of Social Work",
        faculty: "Humanities",
        duration: "4 years",
        apsRequirement: 32,
        description:
          "Professional social work practice and community development",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          {
            name: "Mathematics or Mathematical Literacy",
            level: 4,
            isRequired: true,
          },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Social Worker",
          "Community Development Officer",
          "Family Therapist",
          "Child Protection Officer",
          "NGO Manager",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Law UCT"),
    name: "Faculty of Law",
    description: "Legal education and jurisprudence",
    degrees: [
      {
        id: createDegreeId("LLB UCT"),
        name: "Bachelor of Laws",
        faculty: "Law",
        duration: "4 years",
        apsRequirement: 38,
        description: "Professional legal qualification",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "History or Geography", level: 5, isRequired: false },
        ],
        careerProspects: [
          "Attorney",
          "Advocate",
          "Legal Advisor",
          "Corporate Lawyer",
          "Magistrate",
          "Legal Researcher",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Science UCT"),
    name: "Faculty of Science",
    description: "Natural sciences, mathematics, and computer science",
    degrees: [
      {
        id: createDegreeId("BSc Computer Science UCT"),
        name: "Bachelor of Science in Computer Science",
        faculty: "Science",
        duration: "3 years",
        apsRequirement: 38,
        description:
          "Computer programming, algorithms, and software development",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 7, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Software Developer",
          "Computer Scientist",
          "Systems Analyst",
          "AI Specialist",
          "Cybersecurity Expert",
        ],
      },
      {
        id: createDegreeId("BSc Mathematics UCT"),
        name: "Bachelor of Science in Mathematics",
        faculty: "Science",
        duration: "3 years",
        apsRequirement: 38,
        description: "Pure and applied mathematics",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 7, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Mathematician",
          "Data Scientist",
          "Actuary",
          "Statistician",
          "Research Scientist",
        ],
      },
      {
        id: createDegreeId("BSc Physics UCT"),
        name: "Bachelor of Science in Physics",
        faculty: "Science",
        duration: "3 years",
        apsRequirement: 38,
        description: "Fundamental physics principles and applications",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 7, isRequired: true },
          { name: "Physical Sciences", level: 7, isRequired: true },
        ],
        careerProspects: [
          "Physicist",
          "Research Scientist",
          "Engineering Physicist",
          "Medical Physicist",
          "Astronomer",
        ],
      },
      {
        id: createDegreeId("BSc Chemistry UCT"),
        name: "Bachelor of Science in Chemistry",
        faculty: "Science",
        duration: "3 years",
        apsRequirement: 36,
        description: "Chemical principles and laboratory research",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 7, isRequired: true },
        ],
        careerProspects: [
          "Chemist",
          "Research Scientist",
          "Quality Control Analyst",
          "Pharmaceutical Scientist",
          "Environmental Consultant",
        ],
      },
      {
        id: createDegreeId("BSc Marine Biology UCT"),
        name: "Bachelor of Science in Marine Biology",
        faculty: "Science",
        duration: "3 years",
        apsRequirement: 36,
        description: "Study of marine organisms and ecosystems",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Life Sciences", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Marine Biologist",
          "Oceanographer",
          "Aquarium Curator",
          "Environmental Consultant",
          "Fisheries Scientist",
        ],
      },
      {
        id: createDegreeId("BSc Environmental Geographical Science UCT"),
        name: "Bachelor of Science in Environmental & Geographical Science",
        faculty: "Science",
        duration: "3 years",
        apsRequirement: 34,
        description: "Environmental systems and geographical analysis",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Geography", level: 5, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: false },
        ],
        careerProspects: [
          "Environmental Consultant",
          "Geographer",
          "GIS Specialist",
          "Climate Researcher",
          "Urban Planner",
        ],
      },
    ],
  },
];
