import { Faculty } from "@/types/university";
import { createDegreeId, createFacultyId } from "./base";

// University of Free State (UFS) - Faculty Data
export const UFS_FACULTIES: Faculty[] = [
  {
    id: createFacultyId("Faculty of Economic and Management Sciences UFS"),
    name: "Faculty of Economic and Management Sciences",
    description: "Business, economics, and management programs",
    degrees: [
      {
        id: createDegreeId("Bachelor Commerce BCom UFS"),
        name: "Bachelor of Commerce (BCom)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 28,
        description: "General commerce and business studies",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Business Analyst",
          "Financial Officer",
          "Management Trainee",
        ],
      },
      {
        id: createDegreeId("Bachelor Commerce specialisation Economics UFS"),
        name: "Bachelor of Commerce (specialisation in Economics)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 28,
        description: "Economics and economic analysis",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: ["Economist", "Policy Analyst", "Market Researcher"],
      },
      {
        id: createDegreeId("Bachelor Commerce specialisation Finance UFS"),
        name: "Bachelor of Commerce (specialisation in Finance)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 28,
        description: "Finance and financial management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Financial Analyst",
          "Investment Advisor",
          "Financial Manager",
        ],
      },
      {
        id: createDegreeId(
          "Bachelor Commerce specialisation Business Financial Analytics UFS",
        ),
        name: "Bachelor of Commerce (specialisation in Business and Financial Analytics)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 34,
        description: "Business analytics and financial analysis",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Business Analyst",
          "Data Analyst",
          "Financial Analyst",
        ],
      },
      {
        id: createDegreeId("Bachelor Commerce specialisation Marketing UFS"),
        name: "Bachelor of Commerce (specialisation in Marketing)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 28,
        description: "Marketing and brand management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Marketing Manager",
          "Brand Manager",
          "Digital Marketing Specialist",
        ],
      },
      {
        id: createDegreeId(
          "Bachelor Commerce specialisation Business Management UFS",
        ),
        name: "Bachelor of Commerce (specialisation in Business Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 28,
        description: "Business management and administration",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Business Manager",
          "Operations Manager",
          "Management Consultant",
        ],
      },
      {
        id: createDegreeId(
          "Bachelor Commerce specialisation Human Resource Management UFS",
        ),
        name: "Bachelor of Commerce (specialisation in Human Resource Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 28,
        description: "Human resources and people management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "HR Manager",
          "Recruitment Specialist",
          "Training Officer",
        ],
      },
      {
        id: createDegreeId("Bachelor Commerce Law UFS"),
        name: "Bachelor of Commerce (Law)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 33,
        description: "Commerce with legal foundation",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Corporate Legal Officer",
          "Legal Advisor",
          "Compliance Officer",
        ],
      },
      {
        id: createDegreeId("Bachelor Administration BAdmin UFS"),
        name: "Bachelor of Administration (BAdmin)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 28,
        description: "Public administration and governance",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Public Administrator",
          "Government Official",
          "Policy Officer",
        ],
      },
      {
        id: createDegreeId("Bachelor Accounting BAcc UFS"),
        name: "Bachelor of Accounting (BAcc)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 34,
        description: "Professional accounting qualification",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Accounting", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Chartered Accountant",
          "Auditor",
          "Financial Manager",
        ],
      },
      {
        id: createDegreeId("Bachelor Commerce Accounting UFS"),
        name: "Bachelor of Commerce (Accounting)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 28,
        description: "Commerce with accounting specialization",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Accounting", level: 4, isRequired: true },
        ],
        careerProspects: ["Accountant", "Financial Officer", "Bookkeeper"],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Education UFS"),
    name: "Faculty of Education",
    description: "Teacher education and training programs",
    degrees: [
      {
        id: createDegreeId("Bachelor Education Foundation Phase UFS"),
        name: "Bachelor of Education (Foundation Phase)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 30,
        description: "Foundation phase teaching (Grades R-3)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Foundation Phase Teacher",
          "Primary School Teacher",
          "Educational Specialist",
        ],
      },
      {
        id: createDegreeId("Bachelor Education Intermediate Phase UFS"),
        name: "Bachelor of Education (Intermediate Phase)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 30,
        description: "Intermediate phase teaching (Grades 4-6)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Intermediate Phase Teacher",
          "Primary School Teacher",
          "Subject Specialist",
        ],
      },
      {
        id: createDegreeId("Bachelor Education Senior FET Phase UFS"),
        name: "Bachelor of Education (Senior and FET Phase)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 30,
        description: "Senior phase and FET teaching (Grades 7-12)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "High School Teacher",
          "Subject Specialist",
          "Educational Consultant",
        ],
      },
      {
        id: createDegreeId("Diploma Grade R Teaching 3 year online UFS"),
        name: "Diploma in Grade R Teaching (3-year online)",
        faculty: "Education",
        duration: "3 years",
        apsRequirement: 20, // N/A - distance learning
        description: "Grade R teaching qualification (online)",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Grade R Teacher",
          "Early Childhood Educator",
          "Preschool Teacher",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Health Sciences UFS"),
    name: "Faculty of Health Sciences",
    description: "Medical and health-related programs",
    degrees: [
      {
        id: createDegreeId("Bachelor Medical Science Radiation Science UFS"),
        name: "Bachelor of Medical Science (Radiation Science)",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "Medical radiation and imaging sciences",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Radiographer",
          "Medical Imaging Technologist",
          "Radiation Therapist",
        ],
      },
      {
        id: createDegreeId("Bachelor Medicine Bachelor Surgery MB ChB UFS"),
        name: "Bachelor of Medicine and Bachelor of Surgery (MB ChB)",
        faculty: "Health Sciences",
        duration: "6 years",
        apsRequirement: 36,
        description: "Medical practice and surgery",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: ["Medical Doctor", "Surgeon", "Medical Specialist"],
      },
      {
        id: createDegreeId("Bachelor Optometry UFS"),
        name: "Bachelor of Optometry",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 33,
        description: "Eye care and vision therapy",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Optometrist",
          "Vision Therapist",
          "Eye Care Specialist",
        ],
      },
      {
        id: createDegreeId("Bachelor Science Physiotherapy UFS"),
        name: "Bachelor of Science in Physiotherapy",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 33,
        description: "Physical therapy and rehabilitation",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Physiotherapist",
          "Sports Therapist",
          "Rehabilitation Specialist",
        ],
      },
      {
        id: createDegreeId("Bachelor Science Dietetics UFS"),
        name: "Bachelor of Science in Dietetics",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 33,
        description: "Nutrition and dietetic practice",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: ["Dietitian", "Nutritionist", "Food Service Manager"],
      },
      {
        id: createDegreeId("Bachelor Occupational Therapy UFS"),
        name: "Bachelor of Occupational Therapy",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 33,
        description: "Occupational therapy practice",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Occupational Therapist",
          "Rehabilitation Specialist",
          "Community Health Worker",
        ],
      },
      {
        id: createDegreeId("Bachelor Biokinetics UFS"),
        name: "Bachelor of Biokinetics",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 33,
        description: "Biokinetics and exercise science",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Biokineticist",
          "Exercise Physiologist",
          "Rehabilitation Specialist",
        ],
      },
      {
        id: createDegreeId("Bachelor Sport Coaching UFS"),
        name: "Bachelor of Sport Coaching",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "Sports coaching and development",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Sports Coach",
          "Sports Development Officer",
          "Athletic Trainer",
        ],
      },
      {
        id: createDegreeId("Bachelor Nursing UFS"),
        name: "Bachelor of Nursing",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 30,
        description: "Professional nursing practice",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Professional Nurse",
          "Nurse Manager",
          "Clinical Specialist",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Law UFS"),
    name: "Faculty of Law",
    description: "Legal education and jurisprudence programs",
    degrees: [
      {
        id: createDegreeId("Bachelor Laws LLB UFS"),
        name: "Bachelor of Laws (LLB)",
        faculty: "Law",
        duration: "4 years",
        apsRequirement: 33,
        description: "Professional legal qualification",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: ["Lawyer", "Attorney", "Legal Advisor"],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Natural and Agricultural Sciences UFS"),
    name: "Faculty of Natural and Agricultural Sciences",
    description:
      "Natural sciences, agriculture, and building sciences programs",
    degrees: [
      // Natural Sciences
      {
        id: createDegreeId("Bachelor Science Biological Sciences UFS"),
        name: "Bachelor of Science (Biological Sciences)",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Biological and life sciences",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Biologist",
          "Research Scientist",
          "Environmental Consultant",
        ],
      },
      {
        id: createDegreeId("Bachelor Science Forensic Sciences UFS"),
        name: "Bachelor of Science (Forensic Sciences)",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 34,
        description: "Forensic science and criminal investigation",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Forensic Scientist",
          "Crime Scene Investigator",
          "Laboratory Analyst",
        ],
      },
      {
        id: createDegreeId("Bachelor Science Mathematical Sciences UFS"),
        name: "Bachelor of Science (Mathematical Sciences)",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Pure and applied mathematics",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Mathematician",
          "Data Analyst",
          "Mathematics Teacher",
        ],
      },
      {
        id: createDegreeId("Bachelor Science Actuarial Science UFS"),
        name: "Bachelor of Science (Actuarial Science)",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 34,
        description: "Actuarial science and risk management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
        ],
        careerProspects: ["Actuary", "Risk Analyst", "Financial Analyst"],
      },
      {
        id: createDegreeId("Bachelor Science Chemical Sciences UFS"),
        name: "Bachelor of Science (Chemical Sciences)",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Chemical analysis and research",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Chemist",
          "Laboratory Analyst",
          "Research Scientist",
        ],
      },
      {
        id: createDegreeId("Bachelor Science Physical Sciences UFS"),
        name: "Bachelor of Science (Physical Sciences)",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Physical sciences and physics",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: ["Physicist", "Research Scientist", "Science Teacher"],
      },
      {
        id: createDegreeId("Bachelor Science Geography UFS"),
        name: "Bachelor of Science (Geography)",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Physical and human geography",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Geography", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Geographer",
          "GIS Specialist",
          "Environmental Consultant",
        ],
      },
      {
        id: createDegreeId("Bachelor Science Geology UFS"),
        name: "Bachelor of Science (Geology)",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "Earth sciences and geological processes",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: ["Geologist", "Mining Specialist", "Earth Scientist"],
      },
      {
        id: createDegreeId("Bachelor Science Computer Science Informatics UFS"),
        name: "Bachelor of Science (Computer Science and Informatics)",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Computer science and information systems",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Software Developer",
          "Computer Scientist",
          "Systems Analyst",
        ],
      },
      {
        id: createDegreeId("Bachelor Computer Information Systems UFS"),
        name: "Bachelor of Computer Information Systems",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "Computer information systems and IT",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "IT Specialist",
          "Systems Administrator",
          "Information Manager",
        ],
      },
      {
        id: createDegreeId("Bachelor Sustainable Food Systems UFS"),
        name: "Bachelor of Sustainable Food Systems",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "Sustainable food production and systems",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Food Systems Specialist",
          "Sustainability Officer",
          "Agricultural Advisor",
        ],
      },
      // Agricultural Sciences
      {
        id: createDegreeId("Bachelor Agriculture UFS"),
        name: "Bachelor of Agriculture",
        faculty: "Natural and Agricultural Sciences",
        duration: "4 years",
        apsRequirement: 30,
        description: "General agriculture and farming systems",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: ["Farmer", "Agricultural Advisor", "Farm Manager"],
      },
      {
        id: createDegreeId("Bachelor Science Agriculture UFS"),
        name: "Bachelor of Science in Agriculture",
        faculty: "Natural and Agricultural Sciences",
        duration: "4 years",
        apsRequirement: 32,
        description: "Agricultural science and technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Agricultural Scientist",
          "Crop Specialist",
          "Agricultural Researcher",
        ],
      },
      {
        id: createDegreeId("Bachelor Science Agricultural Economics UFS"),
        name: "Bachelor of Science in Agricultural Economics",
        faculty: "Natural and Agricultural Sciences",
        duration: "4 years",
        apsRequirement: 32,
        description: "Agricultural economics and agribusiness",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Agricultural Economist",
          "Farm Manager",
          "Agribusiness Analyst",
        ],
      },
      // Building Sciences
      {
        id: createDegreeId("Bachelor Architecture UFS"),
        name: "Bachelor of Architecture",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "Architectural design and planning",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: ["Architect", "Design Consultant", "Urban Planner"],
      },
      {
        id: createDegreeId(
          "Bachelor Science Construction Economics Management UFS",
        ),
        name: "Bachelor of Science (Construction Economics and Management)",
        faculty: "Natural and Agricultural Sciences",
        duration: "4 years",
        apsRequirement: 30,
        description: "Construction management and economics",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Construction Manager",
          "Project Manager",
          "Quantity Surveyor",
        ],
      },
      {
        id: createDegreeId("Bachelor Science Quantity Surveying UFS"),
        name: "Bachelor of Science (Quantity Surveying)",
        faculty: "Natural and Agricultural Sciences",
        duration: "4 years",
        apsRequirement: 30,
        description: "Construction cost estimation and management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Quantity Surveyor",
          "Cost Estimator",
          "Project Coordinator",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of The Humanities UFS"),
    name: "Faculty of The Humanities",
    description: "Arts, humanities, and creative programs",
    degrees: [
      {
        id: createDegreeId("Bachelor Arts BA UFS"),
        name: "Bachelor of Arts (BA)",
        faculty: "The Humanities",
        duration: "3 years",
        apsRequirement: 30,
        description: "General arts and humanities",
        subjects: [{ name: "English", level: 4, isRequired: true }],
        careerProspects: [
          "Administrative Officer",
          "Communications Officer",
          "Research Assistant",
        ],
      },
      {
        id: createDegreeId("Bachelor Arts Language Practice UFS"),
        name: "Bachelor of Arts (Language Practice)",
        faculty: "The Humanities",
        duration: "3 years",
        apsRequirement: 30,
        description: "Language practice and linguistics",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Additional Language", level: 4, isRequired: true },
        ],
        careerProspects: ["Translator", "Language Teacher", "Interpreter"],
      },
      {
        id: createDegreeId(
          "Bachelor Arts Integrated Organisational Communication UFS",
        ),
        name: "Bachelor of Arts (Integrated Organisational Communication)",
        faculty: "The Humanities",
        duration: "3 years",
        apsRequirement: 30,
        description: "Organizational communication and public relations",
        subjects: [{ name: "English", level: 4, isRequired: true }],
        careerProspects: [
          "Communications Manager",
          "Public Relations Officer",
          "Corporate Communications Specialist",
        ],
      },
      {
        id: createDegreeId("Bachelor Arts Journalism UFS"),
        name: "Bachelor of Arts (Journalism)",
        faculty: "The Humanities",
        duration: "3 years",
        apsRequirement: 30,
        description: "Journalism and media studies",
        subjects: [{ name: "English", level: 4, isRequired: true }],
        careerProspects: ["Journalist", "News Reporter", "Media Producer"],
      },
      {
        id: createDegreeId("Bachelor Arts Fine Arts UFS"),
        name: "Bachelor of Arts (Fine Arts)",
        faculty: "The Humanities",
        duration: "3 years",
        apsRequirement: 30,
        description: "Visual and creative arts",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Visual Arts", level: 4, isRequired: true },
        ],
        careerProspects: ["Artist", "Art Teacher", "Gallery Curator"],
      },
      {
        id: createDegreeId("Bachelor Arts Drama Theatre Arts UFS"),
        name: "Bachelor of Arts (Drama and Theatre Arts)",
        faculty: "The Humanities",
        duration: "3 years",
        apsRequirement: 30,
        description: "Theatre and dramatic arts",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Dramatic Arts", level: 4, isRequired: true },
        ],
        careerProspects: ["Actor", "Theatre Director", "Drama Teacher"],
      },
      {
        id: createDegreeId("Bachelor Music UFS"),
        name: "Bachelor of Music",
        faculty: "The Humanities",
        duration: "3 years",
        apsRequirement: 30,
        description: "Music performance and theory",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Music", level: 5, isRequired: true },
        ],
        careerProspects: ["Musician", "Music Teacher", "Composer"],
      },
      {
        id: createDegreeId("Bachelor Social Sciences BSocSci UFS"),
        name: "Bachelor of Social Sciences (BSocSci)",
        faculty: "The Humanities",
        duration: "3 years",
        apsRequirement: 30,
        description: "Social sciences and community studies",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Social Researcher",
          "Community Worker",
          "Policy Analyst",
        ],
      },
      {
        id: createDegreeId("Bachelor Social Work UFS"),
        name: "Bachelor of Social Work",
        faculty: "The Humanities",
        duration: "4 years",
        apsRequirement: 30,
        description: "Social work practice and community development",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Social Worker",
          "Community Developer",
          "Family Counselor",
        ],
      },
      {
        id: createDegreeId("Higher Certificate Music Performance UFS"),
        name: "Higher Certificate in Music Performance",
        faculty: "The Humanities",
        duration: "1 year",
        apsRequirement: 20,
        description: "Music performance foundation",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Music", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Music Performer",
          "Music Assistant",
          "Performance Artist",
        ],
      },
      {
        id: createDegreeId("Diploma Music UFS"),
        name: "Diploma in Music",
        faculty: "The Humanities",
        duration: "3 years",
        apsRequirement: 25,
        description: "Music diploma qualification",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Music", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Music Teacher",
          "Music Performer",
          "Arts Coordinator",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Theology and Religion UFS"),
    name: "Faculty of Theology and Religion",
    description: "Theological and religious studies programs",
    degrees: [
      {
        id: createDegreeId("Bachelor Divinity BDiv UFS"),
        name: "Bachelor of Divinity (BDiv)",
        faculty: "Theology and Religion",
        duration: "4 years",
        apsRequirement: 28,
        description: "Advanced theological studies and divinity",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: true },
        ],
        careerProspects: ["Minister", "Theologian", "Religious Scholar"],
      },
    ],
  },
];
