import { Faculty } from "@/types/university";
import { createDegreeId, createFacultyId } from "./base";

// University of KwaZulu-Natal (UKZN) - Faculty Data
export const UKZN_FACULTIES: Faculty[] = [
  {
    id: createFacultyId("College of Agriculture Engineering and Science UKZN"),
    name: "College of Agriculture, Engineering and Science",
    description: "Engineering, agricultural, and science programs",
    degrees: [
      {
        id: createDegreeId("BSc Eng Agricultural UKZN"),
        name: "B Sc Eng: Agricultural",
        faculty: "Agriculture, Engineering and Science",
        duration: "4 years",
        apsRequirement: 33,
        description: "Agricultural engineering and technology",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Agricultural Engineer",
          "Irrigation Engineer",
          "Farm Systems Engineer",
        ],
      },
      {
        id: createDegreeId("BSc Eng Chemical UKZN"),
        name: "B Sc Eng: Chemical",
        faculty: "Agriculture, Engineering and Science",
        duration: "4 years",
        apsRequirement: 33,
        description: "Chemical process engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Chemical Engineer",
          "Process Engineer",
          "Plant Manager",
        ],
      },
      {
        id: createDegreeId("BSc Eng Civil UKZN"),
        name: "B Sc Eng: Civil",
        faculty: "Agriculture, Engineering and Science",
        duration: "4 years",
        apsRequirement: 33,
        description: "Infrastructure and construction engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Civil Engineer",
          "Structural Engineer",
          "Project Manager",
        ],
      },
      {
        id: createDegreeId("BSc Eng Computer UKZN"),
        name: "B Sc Eng: Computer",
        faculty: "Agriculture, Engineering and Science",
        duration: "4 years",
        apsRequirement: 33,
        description: "Computer hardware and software engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Computer Engineer",
          "Software Engineer",
          "Systems Engineer",
        ],
      },
      {
        id: createDegreeId("BSc Eng Electrical UKZN"),
        name: "B Sc Eng: Electrical",
        faculty: "Agriculture, Engineering and Science",
        duration: "4 years",
        apsRequirement: 33,
        description: "Electrical power and systems engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Electrical Engineer",
          "Power Systems Engineer",
          "Control Engineer",
        ],
      },
      {
        id: createDegreeId("BSc Eng Electronic UKZN"),
        name: "B Sc Eng: Electronic",
        faculty: "Agriculture, Engineering and Science",
        duration: "4 years",
        apsRequirement: 33,
        description: "Electronic systems and communications engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Electronic Engineer",
          "Communications Engineer",
          "Design Engineer",
        ],
      },
      {
        id: createDegreeId("BSc Eng Mechanical UKZN"),
        name: "B Sc Eng: Mechanical",
        faculty: "Agriculture, Engineering and Science",
        duration: "4 years",
        apsRequirement: 33,
        description: "Mechanical systems and design engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Mechanical Engineer",
          "Design Engineer",
          "Manufacturing Engineer",
        ],
      },
      {
        id: createDegreeId("BSc Land Surveying UKZN"),
        name: "B Sc Land Surveying",
        faculty: "Agriculture, Engineering and Science",
        duration: "3 years",
        apsRequirement: 33,
        description: "Land surveying and geomatics",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Geography", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Land Surveyor",
          "Geomatics Specialist",
          "Cadastral Surveyor",
        ],
      },
      {
        id: createDegreeId("BSc Agric Agricultural Economics UKZN"),
        name: "B Sc Agric: Agricultural Economics",
        faculty: "Agriculture, Engineering and Science",
        duration: "4 years",
        apsRequirement: 28,
        description: "Agricultural economics and agribusiness",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Agricultural Economist",
          "Farm Manager",
          "Agribusiness Analyst",
        ],
      },
      {
        id: createDegreeId("B Agricultural Management UKZN"),
        name: "B Agricultural Management",
        faculty: "Agriculture, Engineering and Science",
        duration: "3 years",
        apsRequirement: 28,
        description: "Agricultural management and farming systems",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Farm Manager",
          "Agricultural Consultant",
          "Production Manager",
        ],
      },
      {
        id: createDegreeId("BSc Agric Agricultural Plant Sciences UKZN"),
        name: "B Sc Agric: Agricultural Plant Sciences",
        faculty: "Agriculture, Engineering and Science",
        duration: "4 years",
        apsRequirement: 28,
        description: "Plant science and crop production",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Plant Scientist",
          "Crop Specialist",
          "Agricultural Researcher",
        ],
      },
      {
        id: createDegreeId("BSc Agric Agribusiness Pathology UKZN"),
        name: "B Sc Agric: Agribusiness Pathology",
        faculty: "Agriculture, Engineering and Science",
        duration: "4 years",
        apsRequirement: 28,
        description: "Plant pathology and disease management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Plant Pathologist",
          "Disease Specialist",
          "Agricultural Advisor",
        ],
      },
      {
        id: createDegreeId("BSc Agric Plant Pathology UKZN"),
        name: "B Sc Agric: Plant Pathology",
        faculty: "Agriculture, Engineering and Science",
        duration: "4 years",
        apsRequirement: 28,
        description: "Plant diseases and pathology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Plant Pathologist",
          "Crop Protection Specialist",
          "Agricultural Researcher",
        ],
      },
      {
        id: createDegreeId("BSc Agric Soil Science UKZN"),
        name: "B Sc Agric: Soil Science",
        faculty: "Agriculture, Engineering and Science",
        duration: "4 years",
        apsRequirement: 28,
        description: "Soil science and fertility management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Soil Scientist",
          "Fertility Specialist",
          "Environmental Consultant",
        ],
      },
      {
        id: createDegreeId("BSc Agric Animal Poultry Science UKZN"),
        name: "B Sc Agric: Animal & Poultry Science",
        faculty: "Agriculture, Engineering and Science",
        duration: "4 years",
        apsRequirement: 28,
        description: "Animal production and poultry science",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Animal Scientist",
          "Poultry Specialist",
          "Livestock Manager",
        ],
      },
      {
        id: createDegreeId("BSc Stream LES Life Earth Sciences UKZN"),
        name: "B Sc Stream (LES) Life and Earth Sciences",
        faculty: "Agriculture, Engineering and Science",
        duration: "3 years",
        apsRequirement: 30,
        description: "Life and earth sciences foundation",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Life Scientist",
          "Earth Scientist",
          "Research Assistant",
        ],
      },
      {
        id: createDegreeId("BSc Stream M Mathematics UKZN"),
        name: "B Sc Stream M (Mathematics)",
        faculty: "Agriculture, Engineering and Science",
        duration: "3 years",
        apsRequirement: 30,
        description: "Mathematics and quantitative sciences",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Mathematician",
          "Data Analyst",
          "Mathematics Teacher",
        ],
      },
      {
        id: createDegreeId(
          "BSc Geographic Information Systems Earth Observation UKZN",
        ),
        name: "B Sc Geographic Information Systems and Earth Observation",
        faculty: "Agriculture, Engineering and Science",
        duration: "3 years",
        apsRequirement: 30,
        description: "GIS and remote sensing technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Geography", level: 4, isRequired: true },
        ],
        careerProspects: [
          "GIS Specialist",
          "Remote Sensing Analyst",
          "Spatial Data Scientist",
        ],
      },
      {
        id: createDegreeId("BSc Applied Chemistry UKZN"),
        name: "B Sc Applied Chemistry",
        faculty: "Agriculture, Engineering and Science",
        duration: "3 years",
        apsRequirement: 28,
        description: "Applied chemistry and chemical analysis",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Analytical Chemist",
          "Laboratory Analyst",
          "Quality Control Officer",
        ],
      },
      {
        id: createDegreeId("BSc Chemistry Chemical Technology UKZN"),
        name: "B Sc Chemistry and Chemical Technology",
        faculty: "Agriculture, Engineering and Science",
        duration: "3 years",
        apsRequirement: 28,
        description: "Chemistry and chemical technology applications",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Chemical Technologist",
          "Process Chemist",
          "Research Scientist",
        ],
      },
      {
        id: createDegreeId("BSc Computer Science Information Technology UKZN"),
        name: "B Sc Computer Science and Information Technology",
        faculty: "Agriculture, Engineering and Science",
        duration: "3 years",
        apsRequirement: 30,
        description: "Computer science and IT applications",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Software Developer",
          "IT Specialist",
          "Systems Analyst",
        ],
      },
      {
        id: createDegreeId("BSc Crop Horticultural Science UKZN"),
        name: "B Sc Crop and Horticultural Science",
        faculty: "Agriculture, Engineering and Science",
        duration: "3 years",
        apsRequirement: 28,
        description: "Crop production and horticulture",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Horticulturist",
          "Crop Specialist",
          "Garden Manager",
        ],
      },
      {
        id: createDegreeId("BSc Environmental Science UKZN"),
        name: "B Sc Environmental Science",
        faculty: "Agriculture, Engineering and Science",
        duration: "3 years",
        apsRequirement: 28,
        description: "Environmental science and management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Environmental Scientist",
          "Conservation Officer",
          "Environmental Consultant",
        ],
      },
      {
        id: createDegreeId("BSc Environmental Earth Science UKZN"),
        name: "B Sc Environmental and Earth Science",
        faculty: "Agriculture, Engineering and Science",
        duration: "3 years",
        apsRequirement: 28,
        description: "Environmental and earth sciences",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Environmental Scientist",
          "Earth Scientist",
          "Geological Consultant",
        ],
      },
      {
        id: createDegreeId("BSc Geological Science UKZN"),
        name: "B Sc Geological Science",
        faculty: "Agriculture, Engineering and Science",
        duration: "3 years",
        apsRequirement: 28,
        description: "Geological sciences and earth processes",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: ["Geologist", "Mining Geologist", "Earth Scientist"],
      },
      {
        id: createDegreeId("BSc Marine Biology UKZN"),
        name: "B Sc Marine Biology",
        faculty: "Agriculture, Engineering and Science",
        duration: "3 years",
        apsRequirement: 28,
        description: "Marine biology and ocean sciences",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Marine Biologist",
          "Ocean Scientist",
          "Aquatic Researcher",
        ],
      },
      {
        id: createDegreeId("BSc Augmented Programme UKZN"),
        name: "B Sc Augmented Programme",
        faculty: "Agriculture, Engineering and Science",
        duration: "4 years",
        apsRequirement: 26,
        description: "Extended science programme",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Physical Sciences", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Science Officer",
          "Laboratory Technician",
          "Research Assistant",
        ],
      },
      {
        id: createDegreeId("BSc Engineering Access UKZN"),
        name: "B Sc Engineering Access",
        faculty: "Agriculture, Engineering and Science",
        duration: "4 years",
        apsRequirement: 28,
        description: "Engineering foundation and access programme",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Engineering Technician",
          "Technical Officer",
          "Engineering Assistant",
        ],
      },
    ],
  },
  {
    id: createFacultyId("College of Health Sciences UKZN"),
    name: "College of Health Sciences",
    description: "Medical and health-related programs",
    degrees: [
      {
        id: createDegreeId("Bachelor Audiology UKZN"),
        name: "Bachelor of Audiology",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 30,
        description: "Hearing and auditory rehabilitation",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Audiologist",
          "Hearing Aid Specialist",
          "Auditory Therapist",
        ],
      },
      {
        id: createDegreeId("Bachelor Speech Language Therapy UKZN"),
        name: "Bachelor of Speech-Language Therapy",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 30,
        description: "Speech and language therapy",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Speech Therapist",
          "Language Therapist",
          "Communication Specialist",
        ],
      },
      {
        id: createDegreeId("B Dental Therapy UKZN"),
        name: "B Dental Therapy",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "Dental therapy and oral health care",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Dental Therapist",
          "Oral Health Practitioner",
          "Community Dental Worker",
        ],
      },
      {
        id: createDegreeId("B Medical Science Anatomy UKZN"),
        name: "B Medical Science Anatomy",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "Human anatomy and medical sciences",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Anatomist",
          "Medical Researcher",
          "Science Educator",
        ],
      },
      {
        id: createDegreeId("B Medical Science Physiology UKZN"),
        name: "B Medical Science Physiology",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "Human physiology and medical sciences",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Physiologist",
          "Medical Researcher",
          "Health Specialist",
        ],
      },
      {
        id: createDegreeId("B Occupational Therapy UKZN"),
        name: "B Occupational Therapy",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 30,
        description: "Occupational therapy practice",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Occupational Therapist",
          "Rehabilitation Specialist",
          "Community Health Worker",
        ],
      },
      {
        id: createDegreeId("B Optometry UKZN"),
        name: "B Optometry",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 33,
        description: "Eye care and vision therapy",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Optometrist",
          "Vision Therapist",
          "Eye Care Specialist",
        ],
      },
      {
        id: createDegreeId("B Oral Hygiene UKZN"),
        name: "B Oral Hygiene",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "Oral health and hygiene care",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Oral Hygienist",
          "Dental Therapist",
          "Oral Health Educator",
        ],
      },
      {
        id: createDegreeId("B Pharmacy UKZN"),
        name: "B Pharmacy",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 33,
        description: "Pharmaceutical sciences and practice",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Pharmacist",
          "Clinical Pharmacist",
          "Pharmaceutical Researcher",
        ],
      },
      {
        id: createDegreeId("B Physiotherapy UKZN"),
        name: "B Physiotherapy",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 30,
        description: "Physical therapy and rehabilitation",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Physiotherapist",
          "Sports Therapist",
          "Rehabilitation Specialist",
        ],
      },
      {
        id: createDegreeId("B Sport Science UKZN"),
        name: "B Sport Science",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "Sports science and exercise physiology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Sports Scientist",
          "Exercise Physiologist",
          "Sports Coach",
        ],
      },
      {
        id: createDegreeId("B Nursing UKZN"),
        name: "B Nursing",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 30,
        description: "Professional nursing practice",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Professional Nurse",
          "Nurse Manager",
          "Clinical Specialist",
        ],
      },
      {
        id: createDegreeId("B Medicine B Surgery UKZN"),
        name: "B Medicine & B Surgery",
        faculty: "Health Sciences",
        duration: "6 years",
        apsRequirement: 40, // N/A - extremely competitive
        description: "Medical practice and surgery (highly competitive)",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Life Sciences", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: ["Medical Doctor", "Surgeon", "Medical Specialist"],
      },
    ],
  },
  {
    id: createFacultyId("College of Humanities UKZN"),
    name: "College of Humanities",
    description: "Arts, education, and social sciences programs",
    degrees: [
      {
        id: createDegreeId("BEd Foundation Phase UKZN"),
        name: "BEd (Foundation Phase)",
        faculty: "Humanities",
        duration: "4 years",
        apsRequirement: 28,
        description: "Foundation phase teaching (Grades R-3)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Foundation Phase Teacher",
          "Primary School Teacher",
          "Educational Specialist",
        ],
      },
      {
        id: createDegreeId("BEd Intermediate Phase UKZN"),
        name: "BEd (Intermediate Phase)",
        faculty: "Humanities",
        duration: "4 years",
        apsRequirement: 28,
        description: "Intermediate phase teaching (Grades 4-6)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Intermediate Phase Teacher",
          "Primary School Teacher",
          "Subject Specialist",
        ],
      },
      {
        id: createDegreeId("BEd Senior Phase Further Education Training UKZN"),
        name: "BEd (Senior Phase / Further Education & Training)",
        faculty: "Humanities",
        duration: "4 years",
        apsRequirement: 28,
        description: "Senior phase and FET teaching (Grades 7-12)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "High School Teacher",
          "Subject Specialist",
          "Educational Consultant",
        ],
      },
      {
        id: createDegreeId("BA General Studies UKZN"),
        name: "BA (General Studies)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 28,
        description: "General arts and humanities",
        subjects: [{ name: "English", level: 4, isRequired: true }],
        careerProspects: [
          "Administrative Officer",
          "Communications Officer",
          "Research Assistant",
        ],
      },
      {
        id: createDegreeId("BA Music Foundation UKZN"),
        name: "BA in Music Foundation",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 28,
        description: "Music foundation and theory",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Music", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Music Teacher",
          "Music Therapist",
          "Arts Administrator",
        ],
      },
      {
        id: createDegreeId("B Soc Sc General Studies UKZN"),
        name: "B Soc Sc (General Studies)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 28,
        description: "General social sciences",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Social Researcher",
          "Community Worker",
          "Administrative Officer",
        ],
      },
      {
        id: createDegreeId("B SocSc Housing UKZN"),
        name: "B SocSc (Housing)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 28,
        description: "Housing and urban development",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Housing Officer",
          "Urban Planner",
          "Development Coordinator",
        ],
      },
      {
        id: createDegreeId("B Architectural Studies UKZN"),
        name: "B Architectural Studies",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 30,
        description: "Architectural design and planning",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: ["Architect", "Design Consultant", "Urban Planner"],
      },
      {
        id: createDegreeId("B Social Work UKZN"),
        name: "B Social Work",
        faculty: "Humanities",
        duration: "4 years",
        apsRequirement: 28,
        description: "Social work practice and community development",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Social Worker",
          "Community Developer",
          "Family Counselor",
        ],
      },
      {
        id: createDegreeId("BA Philosophy Politics Law UKZN"),
        name: "BA Philosophy, Politics & Law",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 30,
        description: "Interdisciplinary philosophy, politics, and law",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Policy Analyst",
          "Legal Assistant",
          "Political Researcher",
        ],
      },
      {
        id: createDegreeId("BA International Studies UKZN"),
        name: "BA International Studies",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 30,
        description: "International relations and global studies",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "History", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Diplomat",
          "International Relations Officer",
          "Policy Analyst",
        ],
      },
      {
        id: createDegreeId("BA Visual Art UKZN"),
        name: "BA Visual Art",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 30,
        description: "Visual arts and creative expression",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Visual Arts", level: 4, isRequired: true },
        ],
        careerProspects: ["Artist", "Art Teacher", "Gallery Curator"],
      },
      {
        id: createDegreeId("B Soc Sc Government Business Ethics UKZN"),
        name: "B Soc Sc Government, Business & Ethics",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 30,
        description: "Government, business, and ethical studies",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Government Officer",
          "Ethics Consultant",
          "Policy Analyst",
        ],
      },
      {
        id: createDegreeId("B Theology UKZN"),
        name: "B Theology",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 28,
        description: "Theological studies and ministry",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: true },
        ],
        careerProspects: ["Minister", "Chaplain", "Religious Counselor"],
      },
      {
        id: createDegreeId("Humanities Extended Curriculum UKZN"),
        name: "Humanities Extended Curriculum",
        faculty: "Humanities",
        duration: "4 years",
        apsRequirement: 20,
        description: "Extended humanities foundation programme",
        subjects: [{ name: "English", level: 3, isRequired: true }],
        careerProspects: [
          "Administrative Assistant",
          "Community Worker",
          "Research Assistant",
        ],
      },
    ],
  },
  {
    id: createFacultyId("College of Law and Management Studies UKZN"),
    name: "College of Law and Management Studies",
    description: "Law, business, and management programs",
    degrees: [
      {
        id: createDegreeId("Bachelor Laws UKZN"),
        name: "Bachelor of Laws",
        faculty: "Law and Management Studies",
        duration: "4 years",
        apsRequirement: 32,
        description: "Professional legal qualification",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: ["Lawyer", "Attorney", "Legal Advisor"],
      },
      {
        id: createDegreeId("Bachelor Laws part time UKZN"),
        name: "Bachelor of Laws (p/t)",
        faculty: "Law and Management Studies",
        duration: "5 years",
        apsRequirement: 32,
        description: "Part-time legal qualification",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: ["Lawyer", "Attorney", "Legal Advisor"],
      },
      {
        id: createDegreeId("Bachelor Administration UKZN"),
        name: "Bachelor of Administration",
        faculty: "Law and Management Studies",
        duration: "3 years",
        apsRequirement: 28,
        description: "Public administration and governance",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Public Administrator",
          "Government Official",
          "Policy Officer",
        ],
      },
      {
        id: createDegreeId("Bachelor Business Administration UKZN"),
        name: "Bachelor of Business Administration",
        faculty: "Law and Management Studies",
        duration: "3 years",
        apsRequirement: 26,
        description: "Business administration and management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Business Administrator",
          "Operations Manager",
          "Management Trainee",
        ],
      },
      {
        id: createDegreeId("Bachelor Business Science Finance Behavior UKZN"),
        name: "Bachelor of Business Science in Finance & Behavior",
        faculty: "Law and Management Studies",
        duration: "3 years",
        apsRequirement: 33,
        description: "Finance and behavioral economics",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Financial Analyst",
          "Behavioral Economist",
          "Investment Advisor",
        ],
      },
      {
        id: createDegreeId("Business Science Investment Science UKZN"),
        name: "Business Science in Investment Science",
        faculty: "Law and Management Studies",
        duration: "3 years",
        apsRequirement: 33,
        description: "Investment analysis and portfolio management",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Investment Analyst",
          "Portfolio Manager",
          "Financial Advisor",
        ],
      },
      {
        id: createDegreeId("B Com General UKZN"),
        name: "B Com (General)",
        faculty: "Law and Management Studies",
        duration: "3 years",
        apsRequirement: 30,
        description: "General commerce and business",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Business Analyst",
          "Financial Officer",
          "Management Trainee",
        ],
      },
      {
        id: createDegreeId("B Com Accounting UKZN"),
        name: "B Com (Accounting)",
        faculty: "Law and Management Studies",
        duration: "3 years",
        apsRequirement: 32,
        description: "Accounting and financial management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Accounting", level: 4, isRequired: true },
        ],
        careerProspects: ["Accountant", "Financial Manager", "Auditor"],
      },
      {
        id: createDegreeId("B Com General Extended Curriculum UKZN"),
        name: "B Com General (Extended Curriculum)",
        faculty: "Law and Management Studies",
        duration: "4 years",
        apsRequirement: 26,
        description: "Extended commerce programme",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Business Analyst",
          "Financial Officer",
          "Management Trainee",
        ],
      },
      {
        id: createDegreeId("B Com Accounting Extended Curriculum UKZN"),
        name: "B Com Accounting (Extended Curriculum)",
        faculty: "Law and Management Studies",
        duration: "4 years",
        apsRequirement: 28,
        description: "Extended accounting programme",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Accounting", level: 3, isRequired: true },
        ],
        careerProspects: ["Accountant", "Financial Manager", "Auditor"],
      },
    ],
  },
];
