import { Faculty } from "@/types/university";
import { createDegreeId, createFacultyId } from "./base";

// University of Limpopo (UL) - Faculty Data
export const UL_FACULTIES: Faculty[] = [
  {
    id: createFacultyId("Faculty of Humanities UL"),
    name: "Faculty of Humanities",
    description:
      "Humanities programs focusing on education, social sciences, communication studies, and languages",
    degrees: [
      {
        id: createDegreeId("Bachelor of Education BEd UL"),
        name: "Bachelor of Education (BEd)",
        faculty: "Humanities",
        duration: "4 years",
        apsRequirement: 24,
        description: "Professional teacher education program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Teacher",
          "Education Specialist",
          "Curriculum Developer",
        ],
      },
      {
        id: createDegreeId("Bachelor of Arts Criminology Psychology UL"),
        name: "Bachelor of Arts (Criminology & Psychology stream)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 25,
        description: "Liberal arts with criminology and psychology focus",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: false },
        ],
        careerProspects: ["Criminologist", "Psychologist", "Social Worker"],
      },
      {
        id: createDegreeId("Bachelor of Arts Sociology Anthropology UL"),
        name: "Bachelor of Arts (Sociology & Anthropology stream)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 25,
        description: "Liberal arts with sociology and anthropology focus",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "History", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Sociologist",
          "Anthropologist",
          "Community Developer",
        ],
      },
      {
        id: createDegreeId("Bachelor of Arts Political Studies UL"),
        name: "Bachelor of Arts (Political Studies stream)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 25,
        description: "Liberal arts with political studies focus",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "History", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Political Analyst",
          "Government Official",
          "Journalist",
        ],
      },
      {
        id: createDegreeId("Bachelor of Psychology UL"),
        name: "Bachelor of Psychology",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 25,
        description: "Comprehensive psychology program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: ["Psychologist", "Counselor", "Research Analyst"],
      },
      {
        id: createDegreeId(
          "Bachelor of Arts Criminology Psychology Extended UL",
        ),
        name: "Bachelor of Arts (Criminology & Psychology stream) Extended Curricular Programme",
        faculty: "Humanities",
        duration: "4 years",
        apsRequirement: 24,
        description: "Extended program for criminology and psychology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: ["Criminologist", "Psychologist", "Social Worker"],
      },
      {
        id: createDegreeId("Bachelor of Social Work UL"),
        name: "Bachelor of Social Work",
        faculty: "Humanities",
        duration: "4 years",
        apsRequirement: 25,
        description: "Professional social work program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Social Worker",
          "Community Developer",
          "Case Manager",
        ],
      },
      {
        id: createDegreeId("Bachelor of Arts Languages UL"),
        name: "Bachelor of Arts (Languages stream)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 25,
        description: "Language studies and linguistics",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Additional Language", level: 4, isRequired: true },
        ],
        careerProspects: ["Translator", "Language Teacher", "Interpreter"],
      },
      {
        id: createDegreeId("Bachelor of Arts Translation Linguistics UL"),
        name: "Bachelor of Arts (Translation and Linguistics)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 25,
        description: "Translation and linguistics specialization",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Additional Language", level: 4, isRequired: true },
        ],
        careerProspects: ["Translator", "Linguist", "Language Specialist"],
      },
      {
        id: createDegreeId("Bachelor of Information Studies UL"),
        name: "Bachelor of Information Studies",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 25,
        description: "Information science and management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: ["Information Manager", "Librarian", "Data Analyst"],
      },
      {
        id: createDegreeId("Bachelor of Arts Contemporary English UL"),
        name: "Bachelor of Arts in Contemporary English and Multilingual Studies",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 25,
        description: "Contemporary English and multilingual studies",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Additional Language", level: 4, isRequired: false },
        ],
        careerProspects: [
          "English Teacher",
          "Writer",
          "Communications Specialist",
        ],
      },
      {
        id: createDegreeId("Bachelor of Arts Communication Studies UL"),
        name: "Bachelor of Arts in Communication Studies",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 25,
        description: "Communication and media studies",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Communications Specialist",
          "Public Relations Officer",
          "Journalist",
        ],
      },
      {
        id: createDegreeId("Bachelor of Arts Media Studies UL"),
        name: "Bachelor of Arts in Media Studies",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 25,
        description: "Media production and analysis",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Visual Arts", level: 3, isRequired: false },
        ],
        careerProspects: ["Media Producer", "Journalist", "Content Creator"],
      },
      {
        id: createDegreeId("Bachelor of Arts Media Studies Extended UL"),
        name: "Bachelor of Arts in Media Studies Extended Curricular Programme",
        faculty: "Humanities",
        duration: "4 years",
        apsRequirement: 23,
        description: "Extended media studies program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Visual Arts", level: 3, isRequired: false },
        ],
        careerProspects: ["Media Producer", "Journalist", "Content Creator"],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Management and Law UL"),
    name: "Faculty of Management and Law",
    description: "Business management, economics, and law programs",
    degrees: [
      {
        id: createDegreeId("Bachelor of Accountancy UL"),
        name: "Bachelor of Accountancy",
        faculty: "Management and Law",
        duration: "3 years",
        apsRequirement: 30,
        description: "Professional accounting program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Chartered Accountant",
          "Financial Manager",
          "Auditor",
        ],
      },
      {
        id: createDegreeId("Bachelor of Commerce Accountancy UL"),
        name: "Bachelor of Commerce in Accountancy",
        faculty: "Management and Law",
        duration: "3 years",
        apsRequirement: 28,
        description: "Commerce with accounting specialization",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: ["Accountant", "Financial Analyst", "Bookkeeper"],
      },
      {
        id: createDegreeId("Bachelor of Commerce Accountancy Extended UL"),
        name: "Bachelor of Commerce in Accountancy Extended Curricular Programme",
        faculty: "Management and Law",
        duration: "4 years",
        apsRequirement: 26,
        description: "Extended commerce with accounting program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: ["Accountant", "Financial Analyst", "Bookkeeper"],
      },
      {
        id: createDegreeId("Bachelor of Commerce Human Resources UL"),
        name: "Bachelor of Commerce in Human Resources Management",
        faculty: "Management and Law",
        duration: "3 years",
        apsRequirement: 26,
        description: "Human resources management specialization",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "HR Manager",
          "Recruitment Specialist",
          "Training Coordinator",
        ],
      },
      {
        id: createDegreeId("Bachelor of Commerce Human Resources Extended UL"),
        name: "Bachelor of Commerce in Human Resources Management Extended Curricular Programme",
        faculty: "Management and Law",
        duration: "4 years",
        apsRequirement: 22,
        description: "Extended human resources management program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "HR Manager",
          "Recruitment Specialist",
          "Training Coordinator",
        ],
      },
      {
        id: createDegreeId("Bachelor of Commerce Business Management UL"),
        name: "Bachelor of Commerce in Business Management",
        faculty: "Management and Law",
        duration: "3 years",
        apsRequirement: 26,
        description: "General business management program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Business Manager",
          "Entrepreneur",
          "Operations Manager",
        ],
      },
      {
        id: createDegreeId(
          "Bachelor of Commerce Business Management Extended UL",
        ),
        name: "Bachelor of Commerce in Business Management Extended Curricular Programme",
        faculty: "Management and Law",
        duration: "4 years",
        apsRequirement: 22,
        description: "Extended business management program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Business Manager",
          "Entrepreneur",
          "Operations Manager",
        ],
      },
      {
        id: createDegreeId("Bachelor of Commerce Economics UL"),
        name: "Bachelor of Commerce in Economics",
        faculty: "Management and Law",
        duration: "3 years",
        apsRequirement: 26,
        description: "Economic theory and policy analysis",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Economist",
          "Policy Analyst",
          "Financial Consultant",
        ],
      },
      {
        id: createDegreeId("Bachelor of Commerce Economics Extended UL"),
        name: "Bachelor of Commerce in Economics Extended Curricular Programme",
        faculty: "Management and Law",
        duration: "4 years",
        apsRequirement: 22,
        description: "Extended economics program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Economist",
          "Policy Analyst",
          "Financial Consultant",
        ],
      },
      {
        id: createDegreeId("Bachelor of Administration UL"),
        name: "Bachelor of Administration",
        faculty: "Management and Law",
        duration: "3 years",
        apsRequirement: 26,
        description: "Public and private sector administration",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: ["Administrator", "Government Official", "Manager"],
      },
      {
        id: createDegreeId("Bachelor of Administration Local Government UL"),
        name: "Bachelor of Administration (Local Government)",
        faculty: "Management and Law",
        duration: "3 years",
        apsRequirement: 26,
        description: "Local government administration specialization",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Municipal Manager",
          "Local Government Official",
          "Administrator",
        ],
      },
      {
        id: createDegreeId("Bachelor of Development Planning Management UL"),
        name: "Bachelor of Development in Planning and Management",
        faculty: "Management and Law",
        duration: "3 years",
        apsRequirement: 26,
        description: "Development planning and management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Development Planner",
          "Project Manager",
          "Policy Analyst",
        ],
      },
      {
        id: createDegreeId("Bachelor of Laws LLB UL"),
        name: "Bachelor of Laws (LLB)",
        faculty: "Management and Law",
        duration: "4 years",
        apsRequirement: 30,
        description: "Professional law degree",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: ["Lawyer", "Legal Advisor", "Magistrate"],
      },
      {
        id: createDegreeId("Bachelor of Laws LLB Extended UL"),
        name: "Bachelor of Laws (LLB) Extended Curricular Programme",
        faculty: "Management and Law",
        duration: "5 years",
        apsRequirement: 26,
        description: "Extended law degree program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: ["Lawyer", "Legal Advisor", "Magistrate"],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Science and Agriculture UL"),
    name: "Faculty of Science and Agriculture",
    description: "Natural sciences, agriculture, and environmental programs",
    degrees: [
      {
        id: createDegreeId("Bachelor of Agricultural Management UL"),
        name: "Bachelor of Agricultural Management",
        faculty: "Science and Agriculture",
        duration: "4 years",
        apsRequirement: 24,
        description: "Agricultural management and business",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Agricultural Manager",
          "Farm Consultant",
          "Agricultural Economist",
        ],
      },
      {
        id: createDegreeId("Bachelor of Science Agriculture Economics UL"),
        name: "Bachelor of Science in Agriculture (Agricultural Economics)",
        faculty: "Science and Agriculture",
        duration: "4 years",
        apsRequirement: 24,
        description: "Agricultural economics specialization",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Agricultural Economist",
          "Market Analyst",
          "Policy Advisor",
        ],
      },
      {
        id: createDegreeId(
          "Bachelor of Science Agriculture Plant Production UL",
        ),
        name: "Bachelor of Science in Agriculture (Plant Production)",
        faculty: "Science and Agriculture",
        duration: "4 years",
        apsRequirement: 24,
        description: "Plant production and crop science",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Crop Scientist",
          "Farm Manager",
          "Agricultural Consultant",
        ],
      },
      {
        id: createDegreeId(
          "Bachelor of Science Agriculture Animal Production UL",
        ),
        name: "Bachelor of Science in Agriculture (Animal Production)",
        faculty: "Science and Agriculture",
        duration: "4 years",
        apsRequirement: 24,
        description: "Animal production and livestock management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Animal Scientist",
          "Livestock Manager",
          "Veterinary Assistant",
        ],
      },
      {
        id: createDegreeId("Bachelor of Science Agriculture Soil Science UL"),
        name: "Bachelor of Science in Agriculture (Soil Science)",
        faculty: "Science and Agriculture",
        duration: "4 years",
        apsRequirement: 25,
        description: "Soil science and management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Soil Scientist",
          "Environmental Consultant",
          "Agricultural Advisor",
        ],
      },
      {
        id: createDegreeId(
          "Bachelor of Science Environmental Resource Studies UL",
        ),
        name: "Bachelor of Science in Environmental & Resource Studies",
        faculty: "Science and Agriculture",
        duration: "3 years",
        apsRequirement: 24,
        description: "Environmental science and resource management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Environmental Scientist",
          "Conservation Officer",
          "Resource Manager",
        ],
      },
      {
        id: createDegreeId("Bachelor of Science Water Sanitation Sciences UL"),
        name: "Bachelor of Science in Water & Sanitation Sciences",
        faculty: "Science and Agriculture",
        duration: "3 years",
        apsRequirement: 24,
        description: "Water and sanitation management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Water Engineer",
          "Sanitation Specialist",
          "Environmental Health Officer",
        ],
      },
      {
        id: createDegreeId("Bachelor of Science Mathematical Sciences UL"),
        name: "Bachelor of Science (Mathematical Sciences stream)",
        faculty: "Science and Agriculture",
        duration: "3 years",
        apsRequirement: 24,
        description: "Mathematics and applied mathematics",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: ["Mathematician", "Statistician", "Data Analyst"],
      },
      {
        id: createDegreeId(
          "Bachelor of Science Mathematical Sciences Extended UL",
        ),
        name: "Bachelor of Science (Mathematical Sciences stream) Extended Curricular Programme",
        faculty: "Science and Agriculture",
        duration: "4 years",
        apsRequirement: 22,
        description: "Extended mathematics program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 3, isRequired: true },
        ],
        careerProspects: ["Mathematician", "Statistician", "Data Analyst"],
      },
      {
        id: createDegreeId("Bachelor of Science Life Sciences UL"),
        name: "Bachelor of Science (Life Sciences stream)",
        faculty: "Science and Agriculture",
        duration: "3 years",
        apsRequirement: 24,
        description: "Biological and life sciences",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Biologist",
          "Research Scientist",
          "Laboratory Technician",
        ],
      },
      {
        id: createDegreeId("Bachelor of Science Life Sciences Extended UL"),
        name: "Bachelor of Science (Life Sciences stream) Extended Curricular Programme",
        faculty: "Science and Agriculture",
        duration: "4 years",
        apsRequirement: 22,
        description: "Extended life sciences program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Biologist",
          "Research Scientist",
          "Laboratory Technician",
        ],
      },
      {
        id: createDegreeId("Bachelor of Science Physical Sciences UL"),
        name: "Bachelor of Science (Physical Sciences stream)",
        faculty: "Science and Agriculture",
        duration: "3 years",
        apsRequirement: 26,
        description: "Chemistry and physics studies",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: ["Chemist", "Physicist", "Research Scientist"],
      },
      {
        id: createDegreeId("Bachelor of Science Physical Sciences Extended UL"),
        name: "Bachelor of Science (Physical Sciences stream) Extended Curricular Programme",
        faculty: "Science and Agriculture",
        duration: "4 years",
        apsRequirement: 22,
        description: "Extended physical sciences program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: ["Chemist", "Physicist", "Research Scientist"],
      },
      {
        id: createDegreeId("Bachelor of Science Geology UL"),
        name: "Bachelor of Science in Geology",
        faculty: "Science and Agriculture",
        duration: "3 years",
        apsRequirement: 26,
        description: "Earth sciences and geology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Geologist",
          "Mining Engineer",
          "Environmental Consultant",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Health Sciences UL"),
    name: "Faculty of Health Sciences",
    description: "Medical and health-related programs",
    degrees: [
      {
        id: createDegreeId("Bachelor of Medicine Surgery UL"),
        name: "Bachelor of Medicine & Bachelor of Surgery",
        faculty: "Health Sciences",
        duration: "6 years",
        apsRequirement: 27,
        description: "Medical degree program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Medical Doctor",
          "Specialist Physician",
          "Medical Researcher",
        ],
      },
      {
        id: createDegreeId("Bachelor of Science Medical Studies UL"),
        name: "Bachelor of Science in Medical Studies",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Pre-medical and medical studies",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Medical Technologist",
          "Research Assistant",
          "Laboratory Analyst",
        ],
      },
      {
        id: createDegreeId("Bachelor of Science Dietetics UL"),
        name: "Bachelor of Science in Dietetics",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 26,
        description: "Nutrition and dietetic science",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: ["Dietitian", "Nutritionist", "Health Consultant"],
      },
      {
        id: createDegreeId("Bachelor of Optometry UL"),
        name: "Bachelor of Optometry",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 27,
        description: "Optometry and eye care",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Optometrist",
          "Eye Care Specialist",
          "Vision Therapist",
        ],
      },
      {
        id: createDegreeId("Bachelor of Nursing UL"),
        name: "Bachelor of Nursing",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 26,
        description: "Professional nursing program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: ["Nurse", "Healthcare Manager", "Clinical Specialist"],
      },
      {
        id: createDegreeId("Bachelor of Pharmacy UL"),
        name: "Bachelor of Pharmacy",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 27,
        description: "Pharmaceutical sciences program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Pharmacist",
          "Pharmaceutical Researcher",
          "Clinical Pharmacist",
        ],
      },
    ],
  },
];
