import { Faculty } from "@/types/university";
import { createDegreeId, createFacultyId } from "./base";

// University of Mpumalanga (UMP) - Faculty Data
export const UMP_FACULTIES: Faculty[] = [
  {
    id: createFacultyId("Faculty of Agriculture and Natural Sciences UMP"),
    name: "Faculty of Agriculture and Natural Sciences",
    description:
      "Agricultural sciences, natural sciences, and environmental programs",
    degrees: [
      {
        id: createDegreeId("BSc Agriculture UMP"),
        name: "Bachelor of Science in Agriculture",
        faculty: "Agriculture and Natural Sciences",
        duration: "4 years",
        apsRequirement: 24,
        description: "Agricultural sciences and farming technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Agricultural Officer",
          "Farm Manager",
          "Agricultural Consultant",
        ],
      },
      {
        id: createDegreeId("BSc Environmental Management UMP"),
        name: "Bachelor of Science in Environmental Management",
        faculty: "Agriculture and Natural Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Environmental science and conservation management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Geography", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Environmental Manager",
          "Conservation Officer",
          "Sustainability Consultant",
        ],
      },
      {
        id: createDegreeId("BSc Forestry UMP"),
        name: "Bachelor of Science in Forestry",
        faculty: "Agriculture and Natural Sciences",
        duration: "4 years",
        apsRequirement: 24,
        description: "Forest management and conservation",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Forester",
          "Conservation Officer",
          "Environmental Consultant",
        ],
      },
      {
        id: createDegreeId("BSc Biological Sciences UMP"),
        name: "Bachelor of Science in Biological Sciences",
        faculty: "Agriculture and Natural Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Biology and life sciences",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Biologist",
          "Research Scientist",
          "Laboratory Technician",
        ],
      },
      {
        id: createDegreeId("BSc Chemistry UMP"),
        name: "Bachelor of Science in Chemistry",
        faculty: "Agriculture and Natural Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Chemical sciences and analysis",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Chemist",
          "Quality Control Analyst",
          "Research Scientist",
        ],
      },
      {
        id: createDegreeId("BSc Physics UMP"),
        name: "Bachelor of Science in Physics",
        faculty: "Agriculture and Natural Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Physical sciences and applied physics",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Physicist",
          "Research Scientist",
          "Technical Consultant",
        ],
      },
      {
        id: createDegreeId("BSc Mathematics UMP"),
        name: "Bachelor of Science in Mathematics",
        faculty: "Agriculture and Natural Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Pure and applied mathematics",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: ["Mathematician", "Statistician", "Data Analyst"],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Education UMP"),
    name: "Faculty of Education",
    description: "Teacher education and educational programs",
    degrees: [
      {
        id: createDegreeId("BEd Foundation Phase UMP"),
        name: "BEd Foundation Phase",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 24,
        description: "Teacher education for foundation phase (Grades R-3)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Foundation Phase Teacher",
          "Early Childhood Educator",
        ],
      },
      {
        id: createDegreeId("BEd Intermediate Phase UMP"),
        name: "BEd Intermediate Phase",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 24,
        description: "Teacher education for intermediate phase (Grades 4-6)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Intermediate Phase Teacher",
          "Primary School Teacher",
        ],
      },
      {
        id: createDegreeId("BEd Senior Phase FET UMP"),
        name: "BEd Senior Phase and FET",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 24,
        description:
          "Teacher education for senior phase (Grades 7-9) and FET (Grades 10-12)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "High School Teacher",
          "Subject Specialist",
          "Education Coordinator",
        ],
      },
      {
        id: createDegreeId("PGCE UMP"),
        name: "Postgraduate Certificate in Education (PGCE)",
        faculty: "Education",
        duration: "1 year",
        apsRequirement: 24,
        description: "Professional teaching qualification for graduates",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: ["Teacher", "Education Coordinator", "Subject Head"],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Humanities and Social Sciences UMP"),
    name: "Faculty of Humanities and Social Sciences",
    description: "Liberal arts, languages, and social sciences programs",
    degrees: [
      {
        id: createDegreeId("BA General UMP"),
        name: "Bachelor of Arts (General)",
        faculty: "Humanities and Social Sciences",
        duration: "3 years",
        apsRequirement: 23,
        description: "Liberal arts foundation program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: ["Social Worker", "Researcher", "Community Developer"],
      },
      {
        id: createDegreeId("BA Psychology UMP"),
        name: "Bachelor of Arts in Psychology",
        faculty: "Humanities and Social Sciences",
        duration: "3 years",
        apsRequirement: 25,
        description: "Psychological studies and human behavior",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: false },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Psychologist",
          "Counselor",
          "Human Resources Officer",
        ],
      },
      {
        id: createDegreeId("BA Social Work UMP"),
        name: "Bachelor of Social Work",
        faculty: "Humanities and Social Sciences",
        duration: "4 years",
        apsRequirement: 23,
        description: "Professional social work practice",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Social Worker",
          "Community Organizer",
          "Case Manager",
        ],
      },
      {
        id: createDegreeId("BA Languages UMP"),
        name: "Bachelor of Arts in Languages",
        faculty: "Humanities and Social Sciences",
        duration: "3 years",
        apsRequirement: 23,
        description: "Language studies and linguistics",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: ["Translator", "Language Teacher", "Editor"],
      },
      {
        id: createDegreeId("BA Communication UMP"),
        name: "Bachelor of Arts in Communication",
        faculty: "Humanities and Social Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Communication studies and media",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Journalist",
          "Communications Officer",
          "Media Specialist",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Economic and Management Sciences UMP"),
    name: "Faculty of Economic and Management Sciences",
    description: "Business, economics, and management programs",
    degrees: [
      {
        id: createDegreeId("BCom Accounting UMP"),
        name: "Bachelor of Commerce in Accounting",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Accounting and financial management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: ["Accountant", "Financial Analyst", "Auditor"],
      },
      {
        id: createDegreeId("BCom Business Management UMP"),
        name: "Bachelor of Commerce in Business Management",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Business administration and management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Business Manager",
          "Operations Manager",
          "Consultant",
        ],
      },
      {
        id: createDegreeId("BCom Economics UMP"),
        name: "Bachelor of Commerce in Economics",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Economic theory and analysis",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: ["Economist", "Policy Analyst", "Research Officer"],
      },
      {
        id: createDegreeId("BCom Human Resources UMP"),
        name: "Bachelor of Commerce in Human Resources",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Human resource management and industrial relations",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "HR Manager",
          "Training Coordinator",
          "Labour Relations Officer",
        ],
      },
      {
        id: createDegreeId("BCom Marketing UMP"),
        name: "Bachelor of Commerce in Marketing",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Marketing and sales management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Marketing Manager",
          "Sales Representative",
          "Brand Manager",
        ],
      },
    ],
  },
];
