import { Faculty } from "@/types/university";
import { createDegreeId, createFacultyId } from "./base";

// University of VENDA (UNIVEN) - Faculty Data
export const UNIVEN_FACULTIES: Faculty[] = [
  {
    id: createFacultyId(
      "Faculty of Humanities Social Sciences and Education UNIVEN",
    ),
    name: "Faculty of Humanities, Social Sciences and Education",
    description: "Humanities, social sciences, and education programs",
    degrees: [
      {
        id: createDegreeId("Bachelor Arts Media Studies UNIVEN"),
        name: "Bachelor of Arts (Media Studies)",
        faculty: "Humanities, Social Sciences and Education",
        duration: "3 years",
        apsRequirement: 30,
        description: "Media studies and communication",
        subjects: [{ name: "English", level: 4, isRequired: true }],
        careerProspects: [
          "Media Producer",
          "Journalist",
          "Communications Officer",
        ],
      },
      {
        id: createDegreeId("Bachelor Arts Development Studies UNIVEN"),
        name: "Bachelor of Arts (Development Studies)",
        faculty: "Humanities, Social Sciences and Education",
        duration: "3 years",
        apsRequirement: 30,
        description: "Development studies and community development",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Geography", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Development Worker",
          "Project Coordinator",
          "Community Organizer",
        ],
      },
      {
        id: createDegreeId("Bachelor Arts General UNIVEN"),
        name: "Bachelor of Arts",
        faculty: "Humanities, Social Sciences and Education",
        duration: "3 years",
        apsRequirement: 30,
        description: "General arts and humanities",
        subjects: [{ name: "English", level: 4, isRequired: true }],
        careerProspects: [
          "Administrative Officer",
          "Communications Officer",
          "Research Assistant",
        ],
      },
      {
        id: createDegreeId("Bachelor Indigenous Knowledge Systems UNIVEN"),
        name: "Bachelor of Indigenous Knowledge Systems",
        faculty: "Humanities, Social Sciences and Education",
        duration: "3 years",
        apsRequirement: 30,
        description: "Indigenous knowledge and cultural studies",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Additional African Language", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Cultural Consultant",
          "Heritage Officer",
          "Research Specialist",
        ],
      },
      {
        id: createDegreeId("Bachelor Arts Language Practice UNIVEN"),
        name: "Bachelor of Arts in Language Practice",
        faculty: "Humanities, Social Sciences and Education",
        duration: "3 years",
        apsRequirement: 30,
        description: "Language practice and linguistics",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Additional Language", level: 4, isRequired: true },
        ],
        careerProspects: ["Translator", "Language Teacher", "Interpreter"],
      },
      {
        id: createDegreeId("Bachelor Arts International Relations UNIVEN"),
        name: "Bachelor of Arts in International Relations",
        faculty: "Humanities, Social Sciences and Education",
        duration: "3 years",
        apsRequirement: 30,
        description: "International relations and global studies",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "History", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Diplomat",
          "International Relations Officer",
          "Policy Analyst",
        ],
      },
      {
        id: createDegreeId("Bachelor Arts Youth Development UNIVEN"),
        name: "Bachelor of Arts, Youth in Development",
        faculty: "Humanities, Social Sciences and Education",
        duration: "3 years",
        apsRequirement: 30,
        description: "Youth development and community work",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Youth Worker",
          "Development Coordinator",
          "Community Facilitator",
        ],
      },
      {
        id: createDegreeId("Bachelor Theology UNIVEN"),
        name: "Bachelor of Theology",
        faculty: "Humanities, Social Sciences and Education",
        duration: "3 years",
        apsRequirement: 30,
        description: "Theological studies and ministry",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: true },
        ],
        careerProspects: ["Minister", "Chaplain", "Religious Counselor"],
      },
      {
        id: createDegreeId("Bachelor Religious Studies UNIVEN"),
        name: "Bachelor of Religious Studies",
        faculty: "Humanities, Social Sciences and Education",
        duration: "3 years",
        apsRequirement: 30,
        description: "Religious studies and comparative religion",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Religious Scholar",
          "Community Leader",
          "Cultural Advisor",
        ],
      },
      {
        id: createDegreeId("Higher Certificate Music UNIVEN"),
        name: "Higher Certificate in Music",
        faculty: "Humanities, Social Sciences and Education",
        duration: "1 year",
        apsRequirement: 20, // NSC required
        description: "Music foundation qualification",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Music", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Music Assistant",
          "Junior Music Teacher",
          "Music Coordinator",
        ],
      },
      {
        id: createDegreeId("Bachelor Social Work UNIVEN"),
        name: "Bachelor of Social Work",
        faculty: "Humanities, Social Sciences and Education",
        duration: "4 years",
        apsRequirement: 30,
        description: "Social work practice (English Level 4 required)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Social Worker",
          "Community Developer",
          "Family Counselor",
        ],
      },
      {
        id: createDegreeId("Bachelor Education Senior Phase FET UNIVEN"),
        name: "Bachelor of Education (Senior Phase & FET)",
        faculty: "Humanities, Social Sciences and Education",
        duration: "4 years",
        apsRequirement: 36,
        description:
          "Senior phase and FET teaching (50% in English + two subjects)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "High School Teacher",
          "Subject Specialist",
          "Educational Consultant",
        ],
      },
      {
        id: createDegreeId("Bachelor Education Foundation Phase UNIVEN"),
        name: "Bachelor of Education (Foundation Phase)",
        faculty: "Humanities, Social Sciences and Education",
        duration: "4 years",
        apsRequirement: 36,
        description: "Foundation phase teaching (50% in English)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Foundation Phase Teacher",
          "Primary School Teacher",
          "Educational Specialist",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Health Sciences UNIVEN"),
    name: "Faculty of Health Sciences",
    description: "Health and medical programs",
    degrees: [
      {
        id: createDegreeId("Bachelor Nursing UNIVEN"),
        name: "Bachelor of Nursing",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 36,
        description:
          "Professional nursing (Life Sciences, Maths, English, Physical Sciences)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Professional Nurse",
          "Nurse Manager",
          "Clinical Specialist",
        ],
      },
      {
        id: createDegreeId("BSc Nutrition UNIVEN"),
        name: "BSc in Nutrition",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 34,
        description:
          "Nutrition science (Life Sciences, English, Maths, Physical/Agricultural Sciences)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Nutritionist",
          "Food Scientist",
          "Dietary Consultant",
        ],
      },
      {
        id: createDegreeId("BSc Biokinetics UNIVEN"),
        name: "BSc in Biokinetics",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 34,
        description:
          "Biokinetics and exercise science (Life Sciences, English, Maths, Physical Sciences)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Biokineticist",
          "Exercise Physiologist",
          "Rehabilitation Specialist",
        ],
      },
      {
        id: createDegreeId("BSc Sports Exercise Science UNIVEN"),
        name: "BSc in Sports and Exercise Science",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 34,
        description:
          "Sports science (Life Sciences, English, Physical Sciences)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Sports Scientist",
          "Exercise Physiologist",
          "Sports Coach",
        ],
      },
      {
        id: createDegreeId("BSc Recreation Leisure Studies UNIVEN"),
        name: "BSc in Recreation and Leisure Studies",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 34,
        description: "Recreation and leisure management (English)",
        subjects: [{ name: "English", level: 4, isRequired: true }],
        careerProspects: [
          "Recreation Officer",
          "Leisure Coordinator",
          "Tourism Officer",
        ],
      },
      {
        id: createDegreeId("Bachelor Psychology UNIVEN"),
        name: "Bachelor of Psychology",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 36,
        description: "Psychology (English + selection test)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: ["Psychologist", "Counselor", "Social Researcher"],
      },
      {
        id: createDegreeId("Diploma Nursing UNIVEN"),
        name: "Diploma in Nursing",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 28,
        description:
          "Nursing diploma (Life Sciences Level 4, English Level 4, Maths Level 3)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Registered Nurse",
          "Community Health Worker",
          "Clinical Assistant",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Management Commerce and Law UNIVEN"),
    name: "Faculty of Management, Commerce and Law",
    description: "Business, management, and law programs",
    degrees: [
      {
        id: createDegreeId("Bachelor Administration UNIVEN"),
        name: "Bachelor of Administration",
        faculty: "Management, Commerce and Law",
        duration: "3 years",
        apsRequirement: 32,
        description: "Public administration and governance",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Public Administrator",
          "Government Official",
          "Policy Officer",
        ],
      },
      {
        id: createDegreeId("Bachelor Commerce Accounting Sciences UNIVEN"),
        name: "Bachelor of Commerce (Accounting Sciences)",
        faculty: "Management, Commerce and Law",
        duration: "3 years",
        apsRequirement: 35,
        description:
          "Accounting sciences (55% Maths or 50% Maths + 60% Accounting)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Accounting", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Chartered Accountant",
          "Auditor",
          "Financial Manager",
        ],
      },
      {
        id: createDegreeId("Bachelor Commerce Accounting UNIVEN"),
        name: "Bachelor of Commerce in Accounting",
        faculty: "Management, Commerce and Law",
        duration: "3 years",
        apsRequirement: 32,
        description: "Commerce accounting specialization",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Accounting", level: 4, isRequired: true },
        ],
        careerProspects: ["Accountant", "Financial Officer", "Bookkeeper"],
      },
      {
        id: createDegreeId(
          "Bachelor Commerce Business Information Systems UNIVEN",
        ),
        name: "Bachelor of Commerce in Business Information Systems",
        faculty: "Management, Commerce and Law",
        duration: "3 years",
        apsRequirement: 32,
        description: "Business information systems",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Systems Analyst",
          "IT Business Analyst",
          "Information Systems Manager",
        ],
      },
      {
        id: createDegreeId("Bachelor Commerce Business Management UNIVEN"),
        name: "Bachelor of Commerce in Business Management",
        faculty: "Management, Commerce and Law",
        duration: "3 years",
        apsRequirement: 32,
        description: "Business management and administration",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Business Manager",
          "Operations Manager",
          "Management Consultant",
        ],
      },
      {
        id: createDegreeId(
          "Bachelor Commerce Cost Management Accounting UNIVEN",
        ),
        name: "Bachelor of Commerce in Cost and Management Accounting",
        faculty: "Management, Commerce and Law",
        duration: "3 years",
        apsRequirement: 32,
        description: "Cost and management accounting",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Accounting", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Management Accountant",
          "Cost Accountant",
          "Financial Analyst",
        ],
      },
      {
        id: createDegreeId("Bachelor Commerce Economics UNIVEN"),
        name: "Bachelor of Commerce in Economics",
        faculty: "Management, Commerce and Law",
        duration: "3 years",
        apsRequirement: 32,
        description: "Economics and economic analysis",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: ["Economist", "Policy Analyst", "Market Researcher"],
      },
      {
        id: createDegreeId(
          "Bachelor Commerce Human Resource Management UNIVEN",
        ),
        name: "Bachelor of Commerce in Human Resource Management",
        faculty: "Management, Commerce and Law",
        duration: "3 years",
        apsRequirement: 32,
        description: "Human resources and people management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "HR Manager",
          "Recruitment Specialist",
          "Training Officer",
        ],
      },
      {
        id: createDegreeId("Bachelor Commerce Industrial Psychology UNIVEN"),
        name: "Bachelor of Commerce in Industrial Psychology",
        faculty: "Management, Commerce and Law",
        duration: "3 years",
        apsRequirement: 32,
        description: "Industrial psychology and organizational behavior",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Industrial Psychologist",
          "HR Specialist",
          "Organizational Consultant",
        ],
      },
      {
        id: createDegreeId("Bachelor Commerce Tourism Management UNIVEN"),
        name: "Bachelor of Commerce in Tourism Management",
        faculty: "Management, Commerce and Law",
        duration: "3 years",
        apsRequirement: 32,
        description: "Tourism and hospitality management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Tourism Manager",
          "Travel Consultant",
          "Hospitality Manager",
        ],
      },
      {
        id: createDegreeId("Baccalaureus Legum LLB UNIVEN"),
        name: "Baccalaureus Legum (LLB)",
        faculty: "Management, Commerce and Law",
        duration: "4 years",
        apsRequirement: 38,
        description: "Professional legal qualification (60% English)",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: ["Lawyer", "Attorney", "Legal Advisor"],
      },
      {
        id: createDegreeId("Bachelor Arts Criminal Justice UNIVEN"),
        name: "Bachelor of Arts in Criminal Justice",
        faculty: "Management, Commerce and Law",
        duration: "3 years",
        apsRequirement: 34,
        description: "Criminal justice studies (50% English)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Criminal Justice Officer",
          "Police Officer",
          "Correctional Officer",
        ],
      },
      // Extended Programmes (APS 28-31)
      {
        id: createDegreeId("Extended Bachelor Administration UNIVEN"),
        name: "Extended Bachelor of Administration",
        faculty: "Management, Commerce and Law",
        duration: "4 years",
        apsRequirement: 28,
        description: "Extended public administration programme",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Public Administrator",
          "Government Official",
          "Policy Officer",
        ],
      },
      {
        id: createDegreeId("Extended Bachelor Commerce Accounting UNIVEN"),
        name: "Extended Bachelor of Commerce in Accounting",
        faculty: "Management, Commerce and Law",
        duration: "4 years",
        apsRequirement: 28,
        description: "Extended commerce accounting programme",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Accounting", level: 3, isRequired: true },
        ],
        careerProspects: ["Accountant", "Financial Officer", "Bookkeeper"],
      },
      {
        id: createDegreeId(
          "Extended Bachelor Commerce Business Information Systems UNIVEN",
        ),
        name: "Extended Bachelor of Commerce in Business Information Systems",
        faculty: "Management, Commerce and Law",
        duration: "4 years",
        apsRequirement: 28,
        description: "Extended business information systems programme",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Systems Analyst",
          "IT Business Analyst",
          "Information Systems Manager",
        ],
      },
      {
        id: createDegreeId(
          "Extended Bachelor Commerce Business Management UNIVEN",
        ),
        name: "Extended Bachelor of Commerce in Business Management",
        faculty: "Management, Commerce and Law",
        duration: "4 years",
        apsRequirement: 28,
        description: "Extended business management programme",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Business Manager",
          "Operations Manager",
          "Management Consultant",
        ],
      },
      {
        id: createDegreeId(
          "Extended Bachelor Commerce Cost Management Accounting UNIVEN",
        ),
        name: "Extended Bachelor of Commerce in Cost and Management Accounting",
        faculty: "Management, Commerce and Law",
        duration: "4 years",
        apsRequirement: 28,
        description: "Extended cost and management accounting programme",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Accounting", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Management Accountant",
          "Cost Accountant",
          "Financial Analyst",
        ],
      },
      {
        id: createDegreeId("Extended Bachelor Commerce Economics UNIVEN"),
        name: "Extended Bachelor of Commerce in Economics",
        faculty: "Management, Commerce and Law",
        duration: "4 years",
        apsRequirement: 28,
        description: "Extended economics programme",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: ["Economist", "Policy Analyst", "Market Researcher"],
      },
      {
        id: createDegreeId(
          "Extended Bachelor Commerce Human Resources Management UNIVEN",
        ),
        name: "Extended Bachelor of Commerce in Human Resources Management",
        faculty: "Management, Commerce and Law",
        duration: "4 years",
        apsRequirement: 28,
        description: "Extended human resources management programme",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "HR Manager",
          "Recruitment Specialist",
          "Training Officer",
        ],
      },
      {
        id: createDegreeId(
          "Extended Bachelor Commerce Tourism Management UNIVEN",
        ),
        name: "Extended Bachelor of Commerce in Tourism Management",
        faculty: "Management, Commerce and Law",
        duration: "4 years",
        apsRequirement: 28,
        description: "Extended tourism management programme",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Tourism Manager",
          "Travel Consultant",
          "Hospitality Manager",
        ],
      },
    ],
  },
  {
    id: createFacultyId(
      "Faculty of Science Engineering and Agriculture UNIVEN",
    ),
    name: "Faculty of Science, Engineering and Agriculture",
    description: "Science, engineering, and agricultural programs",
    degrees: [
      // Science Stream
      {
        id: createDegreeId("BSc Biochemistry Microbiology UNIVEN"),
        name: "BSc in Biochemistry and Microbiology",
        faculty: "Science, Engineering and Agriculture",
        duration: "3 years",
        apsRequirement: 26,
        description: "Biochemistry and microbiology studies",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: ["Biochemist", "Microbiologist", "Laboratory Analyst"],
      },
      {
        id: createDegreeId("BSc Biochemistry Biology UNIVEN"),
        name: "BSc in Biochemistry and Biology",
        faculty: "Science, Engineering and Agriculture",
        duration: "3 years",
        apsRequirement: 26,
        description: "Biochemistry and biological sciences",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: ["Biochemist", "Biologist", "Research Scientist"],
      },
      {
        id: createDegreeId("BSc Microbiology Botany UNIVEN"),
        name: "BSc in Microbiology and Botany",
        faculty: "Science, Engineering and Agriculture",
        duration: "3 years",
        apsRequirement: 26,
        description: "Microbiology and plant sciences",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: ["Microbiologist", "Botanist", "Plant Scientist"],
      },
      {
        id: createDegreeId("BSc Mathematics Applied Mathematics UNIVEN"),
        name: "BSc in Mathematics and Applied Mathematics",
        faculty: "Science, Engineering and Agriculture",
        duration: "3 years",
        apsRequirement: 26,
        description: "Pure and applied mathematics",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Mathematician",
          "Data Analyst",
          "Mathematics Teacher",
        ],
      },
      {
        id: createDegreeId(
          "BSc Financial Mathematics Applied Mathematics UNIVEN",
        ),
        name: "BSc in Financial Mathematics and Applied Mathematics",
        faculty: "Science, Engineering and Agriculture",
        duration: "3 years",
        apsRequirement: 26,
        description: "Financial and applied mathematics",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Financial Analyst",
          "Quantitative Analyst",
          "Actuary",
        ],
      },
      {
        id: createDegreeId("BSc Mathematics Physics UNIVEN"),
        name: "BSc in Mathematics and Physics",
        faculty: "Science, Engineering and Agriculture",
        duration: "3 years",
        apsRequirement: 26,
        description: "Mathematics and physics combination",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: ["Physicist", "Mathematician", "Research Scientist"],
      },
      {
        id: createDegreeId("BSc Mathematics Statistics UNIVEN"),
        name: "BSc in Mathematics and Statistics",
        faculty: "Science, Engineering and Agriculture",
        duration: "3 years",
        apsRequirement: 26,
        description: "Mathematics and statistical analysis",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Statistician",
          "Data Scientist",
          "Market Researcher",
        ],
      },
      {
        id: createDegreeId("BSc Physics Chemistry UNIVEN"),
        name: "BSc in Physics and Chemistry",
        faculty: "Science, Engineering and Agriculture",
        duration: "3 years",
        apsRequirement: 26,
        description: "Physics and chemistry combination",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: ["Physicist", "Chemist", "Research Scientist"],
      },
      {
        id: createDegreeId("BSc Chemistry Mathematics UNIVEN"),
        name: "BSc in Chemistry and Mathematics",
        faculty: "Science, Engineering and Agriculture",
        duration: "3 years",
        apsRequirement: 26,
        description: "Chemistry and mathematics combination",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: ["Chemist", "Mathematician", "Research Scientist"],
      },
      {
        id: createDegreeId("BSc Chemistry Biochemistry UNIVEN"),
        name: "BSc in Chemistry and Biochemistry",
        faculty: "Science, Engineering and Agriculture",
        duration: "3 years",
        apsRequirement: 26,
        description: "Chemistry and biochemistry combination",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: ["Chemist", "Biochemist", "Laboratory Analyst"],
      },
      {
        id: createDegreeId("BSc Chemistry UNIVEN"),
        name: "BSc in Chemistry",
        faculty: "Science, Engineering and Agriculture",
        duration: "3 years",
        apsRequirement: 26,
        description: "Chemical analysis and research",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Chemist",
          "Laboratory Analyst",
          "Research Scientist",
        ],
      },
      {
        id: createDegreeId("BSc Botany Zoology UNIVEN"),
        name: "BSc in Botany and Zoology",
        faculty: "Science, Engineering and Agriculture",
        duration: "3 years",
        apsRequirement: 26,
        description: "Plant and animal sciences",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: ["Botanist", "Zoologist", "Conservation Scientist"],
      },
      {
        id: createDegreeId("BSc Computer Science UNIVEN"),
        name: "BSc in Computer Science",
        faculty: "Science, Engineering and Agriculture",
        duration: "3 years",
        apsRequirement: 26,
        description: "Computer science and programming",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Software Developer",
          "Computer Scientist",
          "Systems Analyst",
        ],
      },
      {
        id: createDegreeId("BSc Computer Science Mathematics UNIVEN"),
        name: "BSc in Computer Science and Mathematics",
        faculty: "Science, Engineering and Agriculture",
        duration: "3 years",
        apsRequirement: 26,
        description: "Computer science and mathematics combination",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Software Developer",
          "Data Scientist",
          "Systems Analyst",
        ],
      },
      // Extended BSc Programmes (APS 26)
      {
        id: createDegreeId("Extended BSc Biochemistry Microbiology UNIVEN"),
        name: "Extended BSc in Biochemistry and Microbiology",
        faculty: "Science, Engineering and Agriculture",
        duration: "4 years",
        apsRequirement: 26,
        description: "Extended biochemistry and microbiology programme",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Sciences", level: 3, isRequired: true },
          { name: "Physical Sciences", level: 3, isRequired: true },
        ],
        careerProspects: ["Biochemist", "Microbiologist", "Laboratory Analyst"],
      },
      {
        id: createDegreeId("Extended BSc Biochemistry Biology UNIVEN"),
        name: "Extended BSc in Biochemistry and Biology",
        faculty: "Science, Engineering and Agriculture",
        duration: "4 years",
        apsRequirement: 26,
        description: "Extended biochemistry and biology programme",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Sciences", level: 3, isRequired: true },
          { name: "Physical Sciences", level: 3, isRequired: true },
        ],
        careerProspects: ["Biochemist", "Biologist", "Research Scientist"],
      },
      {
        id: createDegreeId("Extended BSc Computer Science UNIVEN"),
        name: "Extended BSc in Computer Science",
        faculty: "Science, Engineering and Agriculture",
        duration: "4 years",
        apsRequirement: 26,
        description: "Extended computer science programme",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Software Developer",
          "Computer Scientist",
          "Systems Analyst",
        ],
      },
      // Environmental Sciences Stream
      {
        id: createDegreeId("Bachelor Environmental Sciences UNIVEN"),
        name: "Bachelor of Environmental Sciences",
        faculty: "Science, Engineering and Agriculture",
        duration: "3 years",
        apsRequirement: 32,
        description: "Environmental science and management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Environmental Scientist",
          "Conservation Officer",
          "Environmental Consultant",
        ],
      },
      {
        id: createDegreeId(
          "Bachelor Earth Sciences Mining Environmental Geology UNIVEN",
        ),
        name: "Bachelor of Earth Sciences (Mining & Environmental Geology)",
        faculty: "Science, Engineering and Agriculture",
        duration: "3 years",
        apsRequirement: 35,
        description: "Mining and environmental geology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Geologist",
          "Mining Geologist",
          "Environmental Consultant",
        ],
      },
      {
        id: createDegreeId(
          "Bachelor Earth Sciences Hydrology Water Resources UNIVEN",
        ),
        name: "Bachelor of Earth Sciences (Hydrology & Water Resources)",
        faculty: "Science, Engineering and Agriculture",
        duration: "3 years",
        apsRequirement: 35,
        description: "Hydrology and water resource management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Hydrologist",
          "Water Resource Manager",
          "Environmental Engineer",
        ],
      },
      {
        id: createDegreeId("Bachelor Urban Regional Planning UNIVEN"),
        name: "Bachelor of Urban and Regional Planning",
        faculty: "Science, Engineering and Agriculture",
        duration: "4 years",
        apsRequirement: 35,
        description: "Urban and regional planning",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Town Planner",
          "Urban Designer",
          "Planning Consultant",
        ],
      },
      {
        id: createDegreeId(
          "Bachelor Environmental Sciences Disaster Risk Reduction UNIVEN",
        ),
        name: "Bachelor of Environmental Sciences (Disaster Risk Reduction)",
        faculty: "Science, Engineering and Agriculture",
        duration: "3 years",
        apsRequirement: 35,
        description: "Environmental sciences with disaster risk focus",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Disaster Risk Manager",
          "Emergency Coordinator",
          "Environmental Specialist",
        ],
      },
      // Agriculture Stream
      {
        id: createDegreeId("BSc Agriculture Agricultural Economics UNIVEN"),
        name: "BSc in Agriculture (Agricultural Economics)",
        faculty: "Science, Engineering and Agriculture",
        duration: "4 years",
        apsRequirement: 26,
        description: "Agricultural economics and agribusiness",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Agricultural Economist",
          "Farm Manager",
          "Agribusiness Analyst",
        ],
      },
      {
        id: createDegreeId("BSc Agriculture Agribusiness Management UNIVEN"),
        name: "BSc in Agriculture (Agribusiness Management)",
        faculty: "Science, Engineering and Agriculture",
        duration: "3 years",
        apsRequirement: 26,
        description: "Agricultural business management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Agribusiness Manager",
          "Farm Manager",
          "Agricultural Advisor",
        ],
      },
      {
        id: createDegreeId("BSc Agriculture Animal Science UNIVEN"),
        name: "BSc in Agriculture (Animal Science)",
        faculty: "Science, Engineering and Agriculture",
        duration: "4 years",
        apsRequirement: 26,
        description: "Animal production and management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Animal Scientist",
          "Livestock Manager",
          "Veterinary Technician",
        ],
      },
      {
        id: createDegreeId("BSc Agriculture Horticultural Sciences UNIVEN"),
        name: "BSc in Agriculture (Horticultural Sciences)",
        faculty: "Science, Engineering and Agriculture",
        duration: "4 years",
        apsRequirement: 26,
        description: "Horticultural production and management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Horticulturist",
          "Garden Manager",
          "Crop Specialist",
        ],
      },
      {
        id: createDegreeId("BSc Agriculture Plant Production UNIVEN"),
        name: "BSc in Agriculture (Plant Production)",
        faculty: "Science, Engineering and Agriculture",
        duration: "4 years",
        apsRequirement: 26,
        description: "Plant production and crop management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Plant Scientist",
          "Crop Specialist",
          "Agricultural Advisor",
        ],
      },
      {
        id: createDegreeId("BSc Soil Science UNIVEN"),
        name: "BSc in Soil Science",
        faculty: "Science, Engineering and Agriculture",
        duration: "3 years",
        apsRequirement: 26,
        description: "Soil science and fertility management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Soil Scientist",
          "Fertility Specialist",
          "Environmental Consultant",
        ],
      },
      {
        id: createDegreeId("BSc Forestry UNIVEN"),
        name: "BSc in Forestry",
        faculty: "Science, Engineering and Agriculture",
        duration: "4 years",
        apsRequirement: 26,
        description: "Forest management and conservation",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: ["Forester", "Conservation Officer", "Forest Manager"],
      },
      {
        id: createDegreeId("BSc Food Science Technology UNIVEN"),
        name: "BSc in Food Science and Technology",
        faculty: "Science, Engineering and Agriculture",
        duration: "4 years",
        apsRequirement: 26,
        description: "Food science and technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Food Scientist",
          "Food Technologist",
          "Quality Control Manager",
        ],
      },
      {
        id: createDegreeId("BSc Agricultural Biosystems Engineering UNIVEN"),
        name: "BSc in Agricultural and Biosystems Engineering",
        faculty: "Science, Engineering and Agriculture",
        duration: "4 years",
        apsRequirement: 26,
        description: "Agricultural engineering and biosystems",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Agricultural Engineer",
          "Biosystems Engineer",
          "Technical Specialist",
        ],
      },
      // Other
      {
        id: createDegreeId("Diploma Freshwater Technology UNIVEN"),
        name: "Diploma in Freshwater Technology",
        faculty: "Science, Engineering and Agriculture",
        duration: "3 years",
        apsRequirement: 24,
        description: "Freshwater management and technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Sciences", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Water Technologist",
          "Aquaculture Specialist",
          "Water Quality Officer",
        ],
      },
    ],
  },
];
