import { Faculty } from "@/types/university";
import { createDegreeId, createFacultyId } from "./base";

// University of Zululand (UNIZULU) - Faculty Data
export const UNIZULU_FACULTIES: Faculty[] = [
  {
    id: createFacultyId("Faculty of Arts UNIZULU"),
    name: "Faculty of Arts",
    description: "Humanities, languages, and social sciences programs",
    degrees: [
      {
        id: createDegreeId("BA General UNIZULU"),
        name: "Bachelor of Arts (General)",
        faculty: "Arts",
        duration: "3 years",
        apsRequirement: 23,
        description: "Liberal arts foundation program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: ["Social Worker", "Researcher", "Community Developer"],
      },
      {
        id: createDegreeId("BA Psychology UNIZULU"),
        name: "Bachelor of Arts in Psychology",
        faculty: "Arts",
        duration: "3 years",
        apsRequirement: 25,
        description: "Psychological studies and human behavior",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: false },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Psychologist",
          "Counselor",
          "Human Resources Officer",
        ],
      },
      {
        id: createDegreeId("BA Social Work UNIZULU"),
        name: "Bachelor of Social Work",
        faculty: "Arts",
        duration: "4 years",
        apsRequirement: 23,
        description: "Professional social work practice",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Social Worker",
          "Community Organizer",
          "Case Manager",
        ],
      },
      {
        id: createDegreeId("BA Communication Science UNIZULU"),
        name: "Bachelor of Arts in Communication Science",
        faculty: "Arts",
        duration: "3 years",
        apsRequirement: 24,
        description: "Communication theory and media studies",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Journalist",
          "Communications Officer",
          "Media Specialist",
        ],
      },
      {
        id: createDegreeId("BA Criminology UNIZULU"),
        name: "Bachelor of Arts in Criminology",
        faculty: "Arts",
        duration: "3 years",
        apsRequirement: 24,
        description: "Criminal justice and law enforcement studies",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Police Officer",
          "Security Manager",
          "Crime Analyst",
        ],
      },
      {
        id: createDegreeId("BA Languages UNIZULU"),
        name: "Bachelor of Arts in Languages",
        faculty: "Arts",
        duration: "3 years",
        apsRequirement: 23,
        description: "Language studies and linguistics",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: ["Translator", "Language Teacher", "Editor"],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Commerce Administration and Law UNIZULU"),
    name: "Faculty of Commerce, Administration and Law",
    description: "Business, law, and public administration programs",
    degrees: [
      {
        id: createDegreeId("BCom Accounting UNIZULU"),
        name: "Bachelor of Commerce in Accounting",
        faculty: "Commerce, Administration and Law",
        duration: "3 years",
        apsRequirement: 26,
        description: "Accounting and financial management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: ["Accountant", "Financial Analyst", "Auditor"],
      },
      {
        id: createDegreeId("BCom Business Management UNIZULU"),
        name: "Bachelor of Commerce in Business Management",
        faculty: "Commerce, Administration and Law",
        duration: "3 years",
        apsRequirement: 24,
        description: "Business administration and management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Business Manager",
          "Operations Manager",
          "Consultant",
        ],
      },
      {
        id: createDegreeId("BCom Economics UNIZULU"),
        name: "Bachelor of Commerce in Economics",
        faculty: "Commerce, Administration and Law",
        duration: "3 years",
        apsRequirement: 24,
        description: "Economic theory and analysis",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: ["Economist", "Policy Analyst", "Research Officer"],
      },
      {
        id: createDegreeId("BCom Industrial Psychology UNIZULU"),
        name: "Bachelor of Commerce in Industrial Psychology",
        faculty: "Commerce, Administration and Law",
        duration: "3 years",
        apsRequirement: 26,
        description: "Workplace psychology and human resources",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "HR Manager",
          "Industrial Psychologist",
          "Training Coordinator",
        ],
      },
      {
        id: createDegreeId("BCom Information Systems UNIZULU"),
        name: "Bachelor of Commerce in Information Systems",
        faculty: "Commerce, Administration and Law",
        duration: "3 years",
        apsRequirement: 26,
        description: "Business information systems and technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Systems Analyst",
          "IT Consultant",
          "Database Administrator",
        ],
      },
      {
        id: createDegreeId("LLB UNIZULU"),
        name: "Bachelor of Laws (LLB)",
        faculty: "Commerce, Administration and Law",
        duration: "4 years",
        apsRequirement: 30,
        description: "Professional law degree",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: false },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: ["Lawyer", "Advocate", "Legal Advisor"],
      },
      {
        id: createDegreeId("BAdmin UNIZULU"),
        name: "Bachelor of Administration",
        faculty: "Commerce, Administration and Law",
        duration: "3 years",
        apsRequirement: 24,
        description: "Public administration and management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: false },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Public Administrator",
          "Municipal Officer",
          "Government Official",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Science and Agriculture UNIZULU"),
    name: "Faculty of Science and Agriculture",
    description: "Natural sciences and agricultural programs",
    degrees: [
      {
        id: createDegreeId("BSc General UNIZULU"),
        name: "Bachelor of Science (General)",
        faculty: "Science and Agriculture",
        duration: "3 years",
        apsRequirement: 24,
        description: "General science foundation program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Research Assistant",
          "Laboratory Technician",
          "Science Teacher",
        ],
      },
      {
        id: createDegreeId("BSc Computer Science UNIZULU"),
        name: "Bachelor of Science in Computer Science",
        faculty: "Science and Agriculture",
        duration: "3 years",
        apsRequirement: 26,
        description: "Computer science and software development",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Software Developer",
          "Systems Analyst",
          "IT Consultant",
        ],
      },
      {
        id: createDegreeId("BSc Mathematics UNIZULU"),
        name: "Bachelor of Science in Mathematics",
        faculty: "Science and Agriculture",
        duration: "3 years",
        apsRequirement: 26,
        description: "Pure and applied mathematics",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: ["Mathematician", "Statistician", "Actuary"],
      },
      {
        id: createDegreeId("BSc Chemistry UNIZULU"),
        name: "Bachelor of Science in Chemistry",
        faculty: "Science and Agriculture",
        duration: "3 years",
        apsRequirement: 26,
        description: "Chemical sciences and analysis",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Chemist",
          "Quality Control Analyst",
          "Research Scientist",
        ],
      },
      {
        id: createDegreeId("BSc Physics UNIZULU"),
        name: "Bachelor of Science in Physics",
        faculty: "Science and Agriculture",
        duration: "3 years",
        apsRequirement: 26,
        description: "Physical sciences and theoretical physics",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Physicist",
          "Research Scientist",
          "Technical Consultant",
        ],
      },
      {
        id: createDegreeId("BSc Biology UNIZULU"),
        name: "Bachelor of Science in Biology",
        faculty: "Science and Agriculture",
        duration: "3 years",
        apsRequirement: 24,
        description: "Biological sciences and life sciences",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Biologist",
          "Research Scientist",
          "Environmental Consultant",
        ],
      },
      {
        id: createDegreeId("BSc Agriculture UNIZULU"),
        name: "Bachelor of Science in Agriculture",
        faculty: "Science and Agriculture",
        duration: "4 years",
        apsRequirement: 24,
        description: "Agricultural sciences and farming technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Agricultural Officer",
          "Farm Manager",
          "Agricultural Consultant",
        ],
      },
      {
        id: createDegreeId("BSc Environmental Science UNIZULU"),
        name: "Bachelor of Science in Environmental Science",
        faculty: "Science and Agriculture",
        duration: "3 years",
        apsRequirement: 24,
        description: "Environmental studies and conservation",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Geography", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Environmental Scientist",
          "Conservation Officer",
          "Environmental Consultant",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Education UNIZULU"),
    name: "Faculty of Education",
    description: "Teacher education and educational programs",
    degrees: [
      {
        id: createDegreeId("BEd Foundation Phase UNIZULU"),
        name: "BEd Foundation Phase",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 24,
        description: "Teacher education for foundation phase (Grades R-3)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Foundation Phase Teacher",
          "Early Childhood Educator",
        ],
      },
      {
        id: createDegreeId("BEd Intermediate Phase UNIZULU"),
        name: "BEd Intermediate Phase",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 24,
        description: "Teacher education for intermediate phase (Grades 4-6)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Intermediate Phase Teacher",
          "Primary School Teacher",
        ],
      },
      {
        id: createDegreeId("BEd Senior Phase FET UNIZULU"),
        name: "BEd Senior Phase and FET",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 24,
        description:
          "Teacher education for senior phase (Grades 7-9) and FET (Grades 10-12)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "High School Teacher",
          "Subject Specialist",
          "Education Coordinator",
        ],
      },
      {
        id: createDegreeId("PGCE UNIZULU"),
        name: "Postgraduate Certificate in Education (PGCE)",
        faculty: "Education",
        duration: "1 year",
        apsRequirement: 24,
        description: "Professional teaching qualification for graduates",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: ["Teacher", "Education Coordinator", "Subject Head"],
      },
    ],
  },
];
