import { Faculty } from "@/types/university";
import { createDegreeId, createFacultyId } from "./base";

// University of Zululand (UNIZULU) - Faculty Data
export const UNIZULU_FACULTIES: Faculty[] = [
  {
    id: createFacultyId("Faculty of Commerce Administration and Law UNIZULU"),
    name: "Faculty of Commerce, Administration & Law (FCAL)",
    description: "Business, commerce, administration, and law programs",
    degrees: [
      {
        id: createDegreeId("BCom Accounting UNIZULU"),
        name: "Bachelor of Commerce in Accounting",
        faculty: "Commerce, Administration & Law",
        duration: "3 years",
        apsRequirement: 28,
        description: "Accounting and financial management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: ["Accountant", "Financial Analyst", "Auditor"],
      },
      {
        id: createDegreeId("BCom Accounting Science CTA UNIZULU"),
        name: "Bachelor of Commerce in Accounting Science (CTA stream)",
        faculty: "Commerce, Administration & Law",
        duration: "3 years",
        apsRequirement: 28,
        description: "Professional accounting pathway to CTA",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Chartered Accountant",
          "Financial Manager",
          "Tax Consultant",
        ],
      },
      {
        id: createDegreeId("Extended BCom UNIZULU"),
        name: "Extended Bachelor of Commerce (Extended Programme)",
        faculty: "Commerce, Administration & Law",
        duration: "4 years",
        apsRequirement: 26,
        description: "Extended commerce program with foundation support",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: ["Business Manager", "Accountant", "Administrator"],
      },
      {
        id: createDegreeId("BCom Management Information Systems UNIZULU"),
        name: "Bachelor of Commerce in Management Information Systems",
        faculty: "Commerce, Administration & Law",
        duration: "3 years",
        apsRequirement: 28,
        description: "Business information systems and technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Information Technology", level: 4, isRequired: false },
        ],
        careerProspects: ["Systems Analyst", "IT Manager", "Business Analyst"],
      },
      {
        id: createDegreeId("Bachelor of Administration UNIZULU"),
        name: "Bachelor of Administration",
        faculty: "Commerce, Administration & Law",
        duration: "3 years",
        apsRequirement: 28,
        description: "Public and private sector administration",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: ["Administrator", "Government Official", "Manager"],
      },
      {
        id: createDegreeId("Bachelor of Laws LLB UNIZULU"),
        name: "Bachelor of Laws (LLB)",
        faculty: "Commerce, Administration & Law",
        duration: "4 years",
        apsRequirement: 30,
        description: "Professional law degree",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: false },
        ],
        careerProspects: ["Lawyer", "Legal Advisor", "Magistrate"],
      },
      {
        id: createDegreeId("Higher Certificate Accountancy UNIZULU"),
        name: "Higher Certificate in Accountancy",
        faculty: "Commerce, Administration & Law",
        duration: "1 year",
        apsRequirement: 22,
        description: "Basic accounting certificate program",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Accounting Clerk",
          "Bookkeeper",
          "Financial Assistant",
        ],
      },
    ],
  },
  {
    id: createFacultyId(
      "Faculty of Science Agriculture and Engineering UNIZULU",
    ),
    name: "Faculty of Science, Agriculture & Engineering",
    description: "Science, agriculture, engineering, and health programs",
    degrees: [
      {
        id: createDegreeId("BEng Mechanical Engineering UNIZULU"),
        name: "Bachelor of Engineering (Mechanical Engineering)",
        faculty: "Science, Agriculture & Engineering",
        duration: "4 years",
        apsRequirement: 30,
        description: "Mechanical engineering program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Mechanical Engineer",
          "Design Engineer",
          "Manufacturing Engineer",
        ],
      },
      {
        id: createDegreeId("BEng Electrical Engineering UNIZULU"),
        name: "Bachelor of Engineering (Electrical Engineering)",
        faculty: "Science, Agriculture & Engineering",
        duration: "4 years",
        apsRequirement: 30,
        description: "Electrical engineering program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Electrical Engineer",
          "Power Systems Engineer",
          "Electronics Engineer",
        ],
      },
      {
        id: createDegreeId("BSc Mainstream UNIZULU"),
        name: "Bachelor of Science (Mainstream BSc)",
        faculty: "Science, Agriculture & Engineering",
        duration: "3 years",
        apsRequirement: 28,
        description: "General science degree with multiple specializations",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Research Scientist",
          "Laboratory Technician",
          "Science Teacher",
        ],
      },
      {
        id: createDegreeId("BSc Agriculture UNIZULU"),
        name: "Bachelor of Science in Agriculture (Agronomy / Animal Science)",
        faculty: "Science, Agriculture & Engineering",
        duration: "4 years",
        apsRequirement: 28,
        description: "Agricultural science specializations",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Agricultural Scientist",
          "Farm Manager",
          "Agricultural Consultant",
        ],
      },
      {
        id: createDegreeId("BSc Foundational Augmented UNIZULU"),
        name: "Bachelor of Science Foundational/Augmented Stream",
        faculty: "Science, Agriculture & Engineering",
        duration: "4 years",
        apsRequirement: 28,
        description: "Extended science program with foundation support",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Physical Sciences", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Research Scientist",
          "Laboratory Technician",
          "Science Teacher",
        ],
      },
      {
        id: createDegreeId("BEd BSc Stream UNIZULU"),
        name: "Bachelor of Education stream BSc",
        faculty: "Science, Agriculture & Engineering",
        duration: "4 years",
        apsRequirement: 26,
        description: "Science education for foundation phase",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Science Teacher",
          "Education Specialist",
          "Curriculum Developer",
        ],
      },
      {
        id: createDegreeId("Bachelor of Nursing Science UNIZULU"),
        name: "Bachelor of Nursing Science",
        faculty: "Science, Agriculture & Engineering",
        duration: "4 years",
        apsRequirement: 30,
        description: "Professional nursing program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: ["Nurse", "Healthcare Manager", "Clinical Specialist"],
      },
      {
        id: createDegreeId("BConsumerSci Extension Rural Development UNIZULU"),
        name: "Bachelor of Consumer Science: Extension & Rural Development",
        faculty: "Science, Agriculture & Engineering",
        duration: "4 years",
        apsRequirement: 28,
        description: "Consumer science with rural development focus",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Extension Officer",
          "Rural Development Specialist",
          "Community Organizer",
        ],
      },
      {
        id: createDegreeId("BConsumerSci Hospitality Tourism UNIZULU"),
        name: "Bachelor of Consumer Science: Hospitality & Tourism",
        faculty: "Science, Agriculture & Engineering",
        duration: "4 years",
        apsRequirement: 28,
        description: "Consumer science with hospitality and tourism focus",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Geography", level: 3, isRequired: false },
          { name: "Life Orientation", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Tourism Manager",
          "Hotel Manager",
          "Event Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma Sport Exercise UNIZULU"),
        name: "Diploma in Sport & Exercise",
        faculty: "Science, Agriculture & Engineering",
        duration: "3 years",
        apsRequirement: 26,
        description: "Sports science and exercise physiology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Sports Scientist",
          "Exercise Physiologist",
          "Fitness Trainer",
        ],
      },
      {
        id: createDegreeId("Diploma Hospitality Management UNIZULU"),
        name: "Diploma in Hospitality Management",
        faculty: "Science, Agriculture & Engineering",
        duration: "3 years",
        apsRequirement: 26,
        description: "Hospitality industry management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Hotel Manager",
          "Restaurant Manager",
          "Event Coordinator",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Education UNIZULU"),
    name: "Faculty of Education",
    description: "Teacher education and educational programs",
    degrees: [
      {
        id: createDegreeId("BEd Foundation Phase Teaching UNIZULU"),
        name: "Bachelor of Education (Foundation Phase Teaching)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description: "Teacher education for foundation phase (Grades R-3)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Foundation Phase Teacher",
          "Early Childhood Educator",
        ],
      },
      {
        id: createDegreeId("BEd Intermediate Phase Languages UNIZULU"),
        name: "Bachelor of Education (Intermediate Phase Teaching: Languages)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description:
          "Teacher education for intermediate phase language teaching",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Additional Language", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Language Teacher",
          "Intermediate Phase Teacher",
          "Curriculum Specialist",
        ],
      },
      {
        id: createDegreeId("BEd Intermediate Phase Maths Science UNIZULU"),
        name: "Bachelor of Education (Intermediate Phase: Languages, Maths, Natural Science & Tech)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description: "Teacher education for intermediate phase core subjects",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Mathematics Teacher",
          "Science Teacher",
          "Technology Teacher",
        ],
      },
      {
        id: createDegreeId("BEd Senior Social Science Education UNIZULU"),
        name: "Bachelor of Education (Senior & Social Science Education)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description: "Teacher education for senior phase social sciences",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "History", level: 4, isRequired: true },
          { name: "Geography", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Social Sciences Teacher",
          "History Teacher",
          "Geography Teacher",
        ],
      },
      {
        id: createDegreeId("BEd Senior Science Technology Education UNIZULU"),
        name: "Bachelor of Education (Senior Science & Technology Education)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description:
          "Teacher education for senior phase science and technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Science Teacher",
          "Technology Teacher",
          "Mathematics Teacher",
        ],
      },
      {
        id: createDegreeId("BEd Senior Management Sciences EMS UNIZULU"),
        name: "Bachelor of Education (Senior Management Sciences – EMS)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description: "Teacher education for EMS subjects",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Economics", level: 4, isRequired: false },
        ],
        careerProspects: [
          "EMS Teacher",
          "Business Studies Teacher",
          "Economics Teacher",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Humanities and Social Sciences UNIZULU"),
    name: "Faculty of Humanities & Social Sciences",
    description: "Liberal arts, social sciences, and communication programs",
    degrees: [
      {
        id: createDegreeId("Diploma Public Relations Management UNIZULU"),
        name: "Diploma in Public Relations Management",
        faculty: "Humanities & Social Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Public relations and communications management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Public Relations Officer",
          "Communications Manager",
          "Marketing Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma Media Studies UNIZULU"),
        name: "Diploma in Media Studies",
        faculty: "Humanities & Social Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Media production and analysis",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Visual Arts", level: 3, isRequired: false },
        ],
        careerProspects: ["Media Producer", "Journalist", "Content Creator"],
      },
      {
        id: createDegreeId("Diploma Tourism Management UNIZULU"),
        name: "Diploma in Tourism Management",
        faculty: "Humanities & Social Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Tourism industry management and operations",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Geography", level: 3, isRequired: false },
        ],
        careerProspects: ["Tourism Manager", "Tour Guide", "Travel Consultant"],
      },
      {
        id: createDegreeId("BA Anthropology History UNIZULU"),
        name: "Bachelor of Arts (Anthropology & History)",
        faculty: "Humanities & Social Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Anthropology and history studies",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "History", level: 4, isRequired: true },
        ],
        careerProspects: ["Anthropologist", "Historian", "Cultural Researcher"],
      },
      {
        id: createDegreeId("BA Linguistics English UNIZULU"),
        name: "Bachelor of Arts (Linguistics & English)",
        faculty: "Humanities & Social Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Linguistics and English language studies",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Additional Language", level: 4, isRequired: false },
        ],
        careerProspects: ["Linguist", "English Teacher", "Language Specialist"],
      },
      {
        id: createDegreeId("BA Geography History UNIZULU"),
        name: "Bachelor of Arts (Geography & History)",
        faculty: "Humanities & Social Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Geography and history studies",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Geography", level: 4, isRequired: true },
          { name: "History", level: 4, isRequired: true },
        ],
        careerProspects: ["Geographer", "Historian", "Urban Planner"],
      },
      {
        id: createDegreeId("BA Geography Tourism UNIZULU"),
        name: "Bachelor of Arts (Geography & Tourism)",
        faculty: "Humanities & Social Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Geography with tourism specialization",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Geography", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Tourism Specialist",
          "Geographer",
          "Travel Consultant",
        ],
      },
      {
        id: createDegreeId("BA History IsiZulu UNIZULU"),
        name: "Bachelor of Arts (History & IsiZulu)",
        faculty: "Humanities & Social Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "History and IsiZulu language studies",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "IsiZulu", level: 4, isRequired: true },
          { name: "History", level: 4, isRequired: true },
        ],
        careerProspects: [
          "History Teacher",
          "IsiZulu Teacher",
          "Cultural Officer",
        ],
      },
      {
        id: createDegreeId("BA Philosophy Psychology UNIZULU"),
        name: "Bachelor of Arts (Philosophy & Psychology)",
        faculty: "Humanities & Social Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Philosophy and psychology studies",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: false },
        ],
        careerProspects: ["Philosopher", "Psychologist", "Counselor"],
      },
      {
        id: createDegreeId("BA Correctional Studies UNIZULU"),
        name: "Bachelor of Arts in Correctional Studies",
        faculty: "Humanities & Social Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Correctional services and rehabilitation studies",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Correctional Officer",
          "Rehabilitation Specialist",
          "Social Worker",
        ],
      },
      {
        id: createDegreeId("BA Development Studies UNIZULU"),
        name: "Bachelor of Arts in Development Studies",
        faculty: "Humanities & Social Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Development studies and community development",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Development Specialist",
          "Community Organizer",
          "Project Manager",
        ],
      },
      {
        id: createDegreeId("Bachelor of Social Work UNIZULU"),
        name: "Bachelor of Social Work",
        faculty: "Humanities & Social Sciences",
        duration: "4 years",
        apsRequirement: 28,
        description: "Professional social work program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Social Worker",
          "Community Developer",
          "Case Manager",
        ],
      },
      {
        id: createDegreeId("BA Environmental Planning Development UNIZULU"),
        name: "Bachelor of Arts in Environmental Planning & Development",
        faculty: "Humanities & Social Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Environmental planning and sustainable development",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Geography", level: 4, isRequired: true },
          { name: "Life Sciences", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Environmental Planner",
          "Sustainability Consultant",
          "Urban Planner",
        ],
      },
      {
        id: createDegreeId("BA Industrial Sociology UNIZULU"),
        name: "Bachelor of Arts in Industrial Sociology",
        faculty: "Humanities & Social Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Industrial relations and workplace sociology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Industrial Sociologist",
          "Labour Relations Officer",
          "HR Specialist",
        ],
      },
      {
        id: createDegreeId("BA Intercultural Communication UNIZULU"),
        name: "Bachelor of Arts in Intercultural Communication",
        faculty: "Humanities & Social Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Cross-cultural communication and language studies",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Additional Language", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Communications Specialist",
          "Cultural Liaison Officer",
          "International Relations Officer",
        ],
      },
      {
        id: createDegreeId("Bachelor of Library Information Science UNIZULU"),
        name: "Bachelor of Library & Information Science",
        faculty: "Humanities & Social Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Library science and information management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Information Technology", level: 3, isRequired: false },
        ],
        careerProspects: ["Librarian", "Information Manager", "Archivist"],
      },
      {
        id: createDegreeId("Bachelor of Psychology UNIZULU"),
        name: "Bachelor of Psychology",
        faculty: "Humanities & Social Sciences",
        duration: "3 years",
        apsRequirement: 28,
        description: "Comprehensive psychology program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: ["Psychologist", "Counselor", "Research Analyst"],
      },
      {
        id: createDegreeId("BSocSci Political International Studies UNIZULU"),
        name: "Bachelor of Social Science in Political & International Studies",
        faculty: "Humanities & Social Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "Political science and international relations",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "History", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Political Analyst",
          "International Relations Officer",
          "Diplomat",
        ],
      },
      {
        id: createDegreeId("Bachelor of Tourism Studies UNIZULU"),
        name: "Bachelor of Tourism Studies",
        faculty: "Humanities & Social Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Tourism industry and destination management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Geography", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Tourism Manager",
          "Destination Marketer",
          "Travel Consultant",
        ],
      },
    ],
  },
];
