import { Faculty } from "@/types/university";
import { createDegreeId, createFacultyId } from "./base";

// University of Zululand (UNIZULU) - Faculty Data - Comprehensive Update
export const UNIZULU_FACULTIES: Faculty[] = [
  {
    id: createFacultyId("Faculty of Commerce Administration Law UNIZULU"),
    name: "Faculty of Commerce, Administration & Law",
    description: "Business, administration, and legal programs",
    degrees: [
      {
        id: createDegreeId("BCom Accounting UNIZULU"),
        name: "Bachelor of Commerce in Accounting",
        faculty: "Commerce, Administration & Law",
        duration: "3 years",
        apsRequirement: 28,
        description: "General accounting and financial management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Accounting", level: 4, isRequired: true },
        ],
        careerProspects: ["Accountant", "Financial Analyst", "Bookkeeper"],
      },
      {
        id: createDegreeId("BCom Accounting Science CTA UNIZULU"),
        name: "Bachelor of Commerce in Accounting Science (CTA stream)",
        faculty: "Commerce, Administration & Law",
        duration: "3 years",
        apsRequirement: 28,
        description: "Accounting science with CTA preparation",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Accounting", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Chartered Accountant",
          "Financial Manager",
          "Auditor",
        ],
      },
      {
        id: createDegreeId("BCom Extended Programme UNIZULU"),
        name: "Extended Bachelor of Commerce (Extended Programme)",
        faculty: "Commerce, Administration & Law",
        duration: "4 years",
        apsRequirement: 26,
        description: "Extended commerce program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Business Manager",
          "Commercial Officer",
          "Financial Assistant",
        ],
      },
      {
        id: createDegreeId("BCom Management Information Systems UNIZULU"),
        name: "Bachelor of Commerce in Management Information Systems",
        faculty: "Commerce, Administration & Law",
        duration: "3 years",
        apsRequirement: 28,
        description: "Management information systems and technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Information Technology", level: 4, isRequired: true },
        ],
        careerProspects: ["Systems Analyst", "IT Manager", "Business Analyst"],
      },
      {
        id: createDegreeId("Bachelor Administration UNIZULU"),
        name: "Bachelor of Administration",
        faculty: "Commerce, Administration & Law",
        duration: "3 years",
        apsRequirement: 28,
        description: "Public and business administration",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Administrator",
          "Public Service Officer",
          "Management Trainee",
        ],
      },
      {
        id: createDegreeId("LLB UNIZULU"),
        name: "Bachelor of Laws (LLB)",
        faculty: "Commerce, Administration & Law",
        duration: "4 years",
        apsRequirement: 30,
        description: "Professional legal qualification",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: ["Lawyer", "Attorney", "Legal Consultant"],
      },
      {
        id: createDegreeId("Higher Certificate Accountancy UNIZULU"),
        name: "Higher Certificate in Accountancy",
        faculty: "Commerce, Administration & Law",
        duration: "1 year",
        apsRequirement: 22,
        description: "Basic accounting qualification",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Accounting", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Bookkeeper",
          "Accounting Assistant",
          "Finance Clerk",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Science Agriculture Engineering UNIZULU"),
    name: "Faculty of Science, Agriculture & Engineering",
    description: "Science, engineering, and agricultural programs",
    degrees: [
      {
        id: createDegreeId("BEng Mechanical Engineering UNIZULU"),
        name: "Bachelor of Engineering (Mechanical Engineering)",
        faculty: "Science, Agriculture & Engineering",
        duration: "4 years",
        apsRequirement: 30,
        description: "Mechanical engineering and design",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Mechanical Engineer",
          "Design Engineer",
          "Manufacturing Engineer",
        ],
      },
      {
        id: createDegreeId("BEng Electrical Engineering UNIZULU"),
        name: "Bachelor of Engineering (Electrical Engineering)",
        faculty: "Science, Agriculture & Engineering",
        duration: "4 years",
        apsRequirement: 30,
        description: "Electrical engineering and power systems",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Electrical Engineer",
          "Power Systems Engineer",
          "Control Systems Engineer",
        ],
      },
      {
        id: createDegreeId("BSc Mainstream UNIZULU"),
        name: "Bachelor of Science (Mainstream BSc)",
        faculty: "Science, Agriculture & Engineering",
        duration: "3 years",
        apsRequirement: 28,
        description: "General science qualification",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Scientist",
          "Research Assistant",
          "Laboratory Technician",
        ],
      },
      {
        id: createDegreeId("BSc Agriculture Agronomy UNIZULU"),
        name: "Bachelor of Science in Agriculture (Agronomy)",
        faculty: "Science, Agriculture & Engineering",
        duration: "4 years",
        apsRequirement: 28,
        description: "Agricultural science with agronomy specialization",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: ["Agronomist", "Crop Specialist", "Farm Manager"],
      },
      {
        id: createDegreeId("BSc Agriculture Animal Science UNIZULU"),
        name: "Bachelor of Science in Agriculture (Animal Science)",
        faculty: "Science, Agriculture & Engineering",
        duration: "4 years",
        apsRequirement: 28,
        description: "Agricultural science with animal science specialization",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Animal Scientist",
          "Livestock Manager",
          "Veterinary Technician",
        ],
      },
      {
        id: createDegreeId("BSc Foundational Augmented Stream UNIZULU"),
        name: "Bachelor of Science Foundational/Augmented Stream",
        faculty: "Science, Agriculture & Engineering",
        duration: "4 years",
        apsRequirement: 28,
        description: "Foundational science program with additional support",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Scientist",
          "Research Assistant",
          "Laboratory Technician",
        ],
      },
      {
        id: createDegreeId("BEd Stream BSc UNIZULU"),
        name: "Bachelor of Education stream BSc",
        faculty: "Science, Agriculture & Engineering",
        duration: "4 years",
        apsRequirement: 26,
        description: "Education with science foundation",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Science Teacher",
          "Mathematics Teacher",
          "Educational Coordinator",
        ],
      },
      {
        id: createDegreeId("Bachelor Nursing Science UNIZULU"),
        name: "Bachelor of Nursing Science",
        faculty: "Science, Agriculture & Engineering",
        duration: "4 years",
        apsRequirement: 30,
        description: "Professional nursing science",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Professional Nurse",
          "Nurse Manager",
          "Clinical Specialist",
        ],
      },
      {
        id: createDegreeId(
          "Bachelor Consumer Science Extension Rural Development UNIZULU",
        ),
        name: "Bachelor of Consumer Science: Extension & Rural Development",
        faculty: "Science, Agriculture & Engineering",
        duration: "3 years",
        apsRequirement: 28,
        description: "Consumer science with extension and rural development",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Extension Officer",
          "Rural Development Specialist",
          "Community Development Worker",
        ],
      },
      {
        id: createDegreeId(
          "Bachelor Consumer Science Hospitality Tourism UNIZULU",
        ),
        name: "Bachelor of Consumer Science: Hospitality & Tourism",
        faculty: "Science, Agriculture & Engineering",
        duration: "3 years",
        apsRequirement: 28,
        description: "Consumer science with hospitality and tourism",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Geography", level: 4, isRequired: true },
          { name: "Consumer Studies", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Hospitality Manager",
          "Tourism Coordinator",
          "Event Manager",
        ],
      },
      {
        id: createDegreeId("Diploma Sport Exercise UNIZULU"),
        name: "Diploma in Sport & Exercise",
        faculty: "Science, Agriculture & Engineering",
        duration: "3 years",
        apsRequirement: 26,
        description: "Sport and exercise science",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Sports Coach",
          "Exercise Specialist",
          "Fitness Trainer",
        ],
      },
      {
        id: createDegreeId("Diploma Hospitality Management UNIZULU"),
        name: "Diploma in Hospitality Management",
        faculty: "Science, Agriculture & Engineering",
        duration: "3 years",
        apsRequirement: 26,
        description: "Hospitality and hotel management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Consumer Studies", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Hotel Manager",
          "Restaurant Manager",
          "Event Coordinator",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Education UNIZULU"),
    name: "Faculty of Education",
    description: "Teacher education and educational programs",
    degrees: [
      {
        id: createDegreeId("BEd Foundation Phase Teaching UNIZULU"),
        name: "Bachelor of Education (Foundation Phase Teaching)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description: "Foundation phase teaching (Grades R-3)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Foundation Phase Teacher",
          "Primary School Teacher",
          "Educational Coordinator",
        ],
      },
      {
        id: createDegreeId("BEd Intermediate Phase Teaching Languages UNIZULU"),
        name: "Bachelor of Education (Intermediate Phase Teaching: Languages)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description: "Intermediate phase language teaching (Grades 4-6)",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Home Language", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Language Teacher",
          "Intermediate Phase Teacher",
          "Literacy Coordinator",
        ],
      },
      {
        id: createDegreeId(
          "BEd Intermediate Phase Languages Maths Science Tech UNIZULU",
        ),
        name: "Bachelor of Education (Intermediate Phase: Languages, Maths, Natural Science & Tech)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description: "Intermediate phase teaching in multiple subjects",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Intermediate Phase Teacher",
          "Mathematics Teacher",
          "Science Teacher",
        ],
      },
      {
        id: createDegreeId("BEd Senior Social Science Education UNIZULU"),
        name: "Bachelor of Education (Senior & Social Science Education)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description: "Senior phase social science education",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "History", level: 4, isRequired: true },
          { name: "Geography", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Social Science Teacher",
          "History Teacher",
          "Geography Teacher",
        ],
      },
      {
        id: createDegreeId("BEd Senior Science Technology Education UNIZULU"),
        name: "Bachelor of Education (Senior Science & Technology Education)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description: "Senior phase science and technology education",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Science Teacher",
          "Technology Teacher",
          "Mathematics Teacher",
        ],
      },
      {
        id: createDegreeId("BEd Senior Management Sciences EMS UNIZULU"),
        name: "Bachelor of Education (Senior Management Sciences – EMS)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description: "Senior phase economic and management sciences education",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Accounting", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Business Studies Teacher",
          "Economics Teacher",
          "Accounting Teacher",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Humanities Social Sciences UNIZULU"),
    name: "Faculty of Humanities & Social Sciences",
    description: "Humanities, arts, and social science programs",
    degrees: [
      {
        id: createDegreeId("Diploma Public Relations Management UNIZULU"),
        name: "Diploma in Public Relations Management",
        faculty: "Humanities & Social Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Public relations and communications management",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Public Relations Manager",
          "Communications Specialist",
          "Media Liaison",
        ],
      },
      {
        id: createDegreeId("Diploma Media Studies UNIZULU"),
        name: "Diploma in Media Studies",
        faculty: "Humanities & Social Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Media and communication studies",
        subjects: [{ name: "English", level: 5, isRequired: true }],
        careerProspects: ["Media Analyst", "Journalist", "Content Creator"],
      },
      {
        id: createDegreeId("Diploma Tourism Management UNIZULU"),
        name: "Diploma in Tourism Management",
        faculty: "Humanities & Social Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Tourism management and hospitality",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Geography", level: 4, isRequired: true },
        ],
        careerProspects: ["Tourism Manager", "Travel Consultant", "Tour Guide"],
      },
      {
        id: createDegreeId("BA Anthropology History UNIZULU"),
        name: "Bachelor of Arts (Anthropology & History)",
        faculty: "Humanities & Social Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Arts with anthropology and history specialization",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "History", level: 4, isRequired: true },
        ],
        careerProspects: ["Anthropologist", "Historian", "Cultural Researcher"],
      },
      {
        id: createDegreeId("BA Linguistics English UNIZULU"),
        name: "Bachelor of Arts (Linguistics & English)",
        faculty: "Humanities & Social Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Arts with linguistics and English specialization",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Home Language", level: 4, isRequired: true },
        ],
        careerProspects: ["Linguist", "English Teacher", "Language Specialist"],
      },
      {
        id: createDegreeId("BA Geography History UNIZULU"),
        name: "Bachelor of Arts (Geography & History)",
        faculty: "Humanities & Social Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Arts with geography and history specialization",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Geography", level: 4, isRequired: true },
          { name: "History", level: 4, isRequired: true },
        ],
        careerProspects: ["Geographer", "Historian", "Social Researcher"],
      },
      {
        id: createDegreeId("BA Geography Tourism UNIZULU"),
        name: "Bachelor of Arts (Geography & Tourism)",
        faculty: "Humanities & Social Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Arts with geography and tourism specialization",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Geography", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Tourism Geographer",
          "Destination Planner",
          "Tourism Consultant",
        ],
      },
      {
        id: createDegreeId("BA History IsiZulu UNIZULU"),
        name: "Bachelor of Arts (History & IsiZulu)",
        faculty: "Humanities & Social Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Arts with history and IsiZulu specialization",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "IsiZulu", level: 5, isRequired: true },
          { name: "History", level: 4, isRequired: true },
        ],
        careerProspects: [
          "IsiZulu Teacher",
          "Cultural Historian",
          "Language Specialist",
        ],
      },
      {
        id: createDegreeId("BA Philosophy Psychology UNIZULU"),
        name: "Bachelor of Arts (Philosophy & Psychology)",
        faculty: "Humanities & Social Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Arts with philosophy and psychology specialization",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: ["Philosopher", "Psychologist", "Counselor"],
      },
      {
        id: createDegreeId("BA Correctional Studies UNIZULU"),
        name: "Bachelor of Arts in Correctional Studies",
        faculty: "Humanities & Social Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Correctional services and criminal justice",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Correctional Officer",
          "Probation Officer",
          "Criminal Justice Worker",
        ],
      },
      {
        id: createDegreeId("BA Development Studies UNIZULU"),
        name: "Bachelor of Arts in Development Studies",
        faculty: "Humanities & Social Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Development theory and practice",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Geography", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Development Worker",
          "Project Manager",
          "Social Development Officer",
        ],
      },
      {
        id: createDegreeId("Bachelor Social Work UNIZULU"),
        name: "Bachelor of Social Work",
        faculty: "Humanities & Social Sciences",
        duration: "4 years",
        apsRequirement: 28,
        description: "Professional social work practice",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Social Worker",
          "Community Developer",
          "Family Counselor",
        ],
      },
      {
        id: createDegreeId("BA Environmental Planning Development UNIZULU"),
        name: "Bachelor of Arts in Environmental Planning & Development",
        faculty: "Humanities & Social Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Environmental planning and sustainable development",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Geography", level: 5, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Environmental Planner",
          "Development Consultant",
          "Sustainability Officer",
        ],
      },
      {
        id: createDegreeId("BA Industrial Sociology UNIZULU"),
        name: "Bachelor of Arts in Industrial Sociology",
        faculty: "Humanities & Social Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Industrial sociology and workplace relations",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Industrial Sociologist",
          "Labour Relations Specialist",
          "Workplace Analyst",
        ],
      },
      {
        id: createDegreeId("BA Intercultural Communication UNIZULU"),
        name: "Bachelor of Arts in Intercultural Communication",
        faculty: "Humanities & Social Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Cross-cultural communication and diversity",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Home Language", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Intercultural Consultant",
          "Communications Specialist",
          "Diversity Officer",
        ],
      },
      {
        id: createDegreeId("Bachelor Library Information Science UNIZULU"),
        name: "Bachelor of Library & Information Science",
        faculty: "Humanities & Social Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Library and information management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: ["Librarian", "Information Manager", "Archivist"],
      },
      {
        id: createDegreeId("Bachelor Psychology UNIZULU"),
        name: "Bachelor of Psychology",
        faculty: "Humanities & Social Sciences",
        duration: "3 years",
        apsRequirement: 28,
        description: "Psychology theory and practice",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: ["Psychologist", "Counselor", "Researcher"],
      },
      {
        id: createDegreeId("BSocSc Political International Studies UNIZULU"),
        name: "Bachelor of Social Science in Political & International Studies",
        faculty: "Humanities & Social Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "Political science and international relations",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "History", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Political Analyst",
          "International Relations Officer",
          "Diplomat",
        ],
      },
      {
        id: createDegreeId("Bachelor Tourism Studies UNIZULU"),
        name: "Bachelor of Tourism Studies",
        faculty: "Humanities & Social Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "Tourism studies and destination management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Geography", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Tourism Specialist",
          "Destination Manager",
          "Tourism Planner",
        ],
      },
    ],
  },
];
