import { Faculty } from "@/types/university";
import { createDegreeId, createFacultyId } from "./base";

// University of Pretoria (UP) - Faculty Data
export const UP_FACULTIES: Faculty[] = [
  {
    id: createFacultyId("Faculty of Economic Management Sciences UP"),
    name: "Faculty of Economic and Management Sciences",
    description: "Economics, business, and management programs",
    degrees: [
      {
        id: createDegreeId("Bachelor Administration Public Administration UP"),
        name: "Bachelor of Administration (Public Administration)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 28,
        description: "Public administration and governance",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Public Administrator",
          "Government Official",
          "Policy Analyst",
        ],
      },
      {
        id: createDegreeId("Bachelor Commerce Accounting Sciences UP"),
        name: "Bachelor of Commerce in Accounting Sciences",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 34,
        description: "Professional accounting sciences",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Accounting", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Chartered Accountant",
          "Financial Manager",
          "Auditor",
        ],
      },
      {
        id: createDegreeId("Bachelor Commerce Investment Management UP"),
        name: "Bachelor of Commerce (Investment Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 34,
        description: "Investment and portfolio management",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Investment Manager",
          "Portfolio Manager",
          "Financial Advisor",
        ],
      },
      {
        id: createDegreeId(
          "Bachelor Commerce Financial Management Sciences UP",
        ),
        name: "Bachelor of Commerce (Financial Management Sciences)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Financial management and corporate finance",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Financial Manager",
          "Corporate Finance Specialist",
          "Treasury Manager",
        ],
      },
      {
        id: createDegreeId("Bachelor Commerce Econometrics UP"),
        name: "Bachelor of Commerce (Econometrics)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Economics with statistical and mathematical modeling",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Econometrician",
          "Economic Analyst",
          "Research Economist",
        ],
      },
      {
        id: createDegreeId("Bachelor Commerce Economics UP"),
        name: "Bachelor of Commerce (Economics)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Economic theory and analysis",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: ["Economist", "Economic Analyst", "Policy Researcher"],
      },
      {
        id: createDegreeId("Bachelor Commerce Law UP"),
        name: "Bachelor of Commerce (Law)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Commerce with legal foundation",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Corporate Legal Officer",
          "Compliance Manager",
          "Legal Advisor",
        ],
      },
      {
        id: createDegreeId("Bachelor Commerce Statistics Data Science UP"),
        name: "Bachelor of Commerce (Statistics and Data Science)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Statistics and data science applications",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: ["Data Scientist", "Statistician", "Business Analyst"],
      },
      {
        id: createDegreeId("Bachelor Commerce Information Systems UP"),
        name: "Bachelor of Commerce (Information Systems)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "Business information systems and technology",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Systems Analyst",
          "IT Business Analyst",
          "Information Systems Manager",
        ],
      },
      {
        id: createDegreeId("Bachelor Commerce Agribusiness Management UP"),
        name: "Bachelor of Commerce (Agribusiness Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "Agricultural business management",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Agribusiness Manager",
          "Agricultural Economist",
          "Farm Manager",
        ],
      },
      {
        id: createDegreeId("Bachelor Commerce Business Management UP"),
        name: "Bachelor of Commerce (Business Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "General business management",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Business Manager",
          "Operations Manager",
          "Project Manager",
        ],
      },
      {
        id: createDegreeId("Bachelor Commerce Supply Chain Management UP"),
        name: "Bachelor of Commerce (Supply Chain Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "Supply chain and logistics management",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Supply Chain Manager",
          "Logistics Manager",
          "Operations Analyst",
        ],
      },
      {
        id: createDegreeId("Bachelor Commerce Marketing Management UP"),
        name: "Bachelor of Commerce (Marketing Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "Marketing strategy and consumer behavior",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Marketing Manager",
          "Brand Manager",
          "Digital Marketing Specialist",
        ],
      },
      {
        id: createDegreeId("Bachelor Commerce Human Resource Management UP"),
        name: "Bachelor of Commerce (Human Resource Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "Human resource management and organizational behavior",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "HR Manager",
          "Recruitment Specialist",
          "Training Coordinator",
        ],
      },
      {
        id: createDegreeId("Bachelor Commerce General UP"),
        name: "Bachelor of Commerce",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "General commerce and business studies",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Business Analyst",
          "Financial Officer",
          "Management Trainee",
        ],
      },
      {
        id: createDegreeId("Bachelor Commerce 4 year programme UP"),
        name: "Bachelor of Commerce (4-year programme)",
        faculty: "Economic and Management Sciences",
        duration: "4 years",
        apsRequirement: 26,
        description: "Extended commerce degree program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Business Analyst",
          "Financial Officer",
          "Management Trainee",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Education UP"),
    name: "Faculty of Education",
    description: "Teacher education and educational development programs",
    degrees: [
      {
        id: createDegreeId(
          "Bachelor Education Early Childhood Care Education UP",
        ),
        name: "Bachelor of Education (Early Childhood Care and Education)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 28,
        description: "Early childhood development and education",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Early Childhood Educator",
          "Preschool Teacher",
          "Educational Specialist",
        ],
      },
      {
        id: createDegreeId("Bachelor Education Foundation Phase Teaching UP"),
        name: "Bachelor of Education (Foundation Phase Teaching)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 28,
        description: "Foundation phase teaching (Grades R-3)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Foundation Phase Teacher",
          "Primary School Teacher",
          "Educational Specialist",
        ],
      },
      {
        id: createDegreeId("Bachelor Education Intermediate Phase Teaching UP"),
        name: "Bachelor of Education (Intermediate Phase Teaching)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 28,
        description: "Intermediate phase teaching (Grades 4-6)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Intermediate Phase Teacher",
          "Primary School Teacher",
          "Subject Specialist",
        ],
      },
      {
        id: createDegreeId("Bachelor Education Senior Phase FET Teaching UP"),
        name: "Bachelor of Education (Senior Phase and Further Education and Training Teaching)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 28,
        description: "Senior phase and FET teaching (Grades 7-12)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "High School Teacher",
          "Subject Specialist",
          "Educational Consultant",
        ],
      },
      {
        id: createDegreeId("Higher Certificate Sports Sciences 1 year UP"),
        name: "Higher Certificate in Sports Sciences (1 year)",
        faculty: "Education",
        duration: "1 year",
        apsRequirement: 20,
        description: "Sports sciences certificate program",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Life Sciences", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Sports Coach",
          "Fitness Instructor",
          "Sports Administrator",
        ],
      },
      {
        id: createDegreeId(
          "Higher Certificate Sports Sciences 2 years online UP",
        ),
        name: "Higher Certificate in Sports Sciences (2 years, online)",
        faculty: "Education",
        duration: "2 years",
        apsRequirement: 20,
        description: "Online sports sciences certificate program",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Life Sciences", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Sports Coach",
          "Fitness Instructor",
          "Sports Administrator",
        ],
      },
    ],
  },
  {
    id: createFacultyId(
      "Faculty of Engineering Built Environment Information Technology UP",
    ),
    name: "Faculty of Engineering, Built Environment and Information Technology",
    description:
      "Engineering, architecture, and information technology programs",
    degrees: [
      // School of Engineering
      {
        id: createDegreeId("Bachelor Engineering Chemical Engineering UP"),
        name: "Bachelor of Engineering (Chemical Engineering)",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "4 years",
        apsRequirement: 35,
        description: "Chemical process engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Chemical Engineer",
          "Process Engineer",
          "Plant Manager",
        ],
      },
      {
        id: createDegreeId("Bachelor Engineering Civil Engineering UP"),
        name: "Bachelor of Engineering (Civil Engineering)",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "4 years",
        apsRequirement: 35,
        description: "Civil and structural engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Civil Engineer",
          "Structural Engineer",
          "Project Manager",
        ],
      },
      {
        id: createDegreeId("Bachelor Engineering Computer Engineering UP"),
        name: "Bachelor of Engineering (Computer Engineering)",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "4 years",
        apsRequirement: 35,
        description: "Computer hardware and software engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Computer Engineer",
          "Software Engineer",
          "Systems Engineer",
        ],
      },
      {
        id: createDegreeId("Bachelor Engineering Electrical Engineering UP"),
        name: "Bachelor of Engineering (Electrical Engineering)",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "4 years",
        apsRequirement: 35,
        description: "Electrical power and systems engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Electrical Engineer",
          "Power Systems Engineer",
          "Control Engineer",
        ],
      },
      {
        id: createDegreeId("Bachelor Engineering Electronic Engineering UP"),
        name: "Bachelor of Engineering (Electronic Engineering)",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "4 years",
        apsRequirement: 35,
        description: "Electronic systems and communications engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Electronic Engineer",
          "Communications Engineer",
          "Telecommunications Specialist",
        ],
      },
      {
        id: createDegreeId("Bachelor Engineering Industrial Engineering UP"),
        name: "Bachelor of Engineering (Industrial Engineering)",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "4 years",
        apsRequirement: 35,
        description: "Manufacturing and operations engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Industrial Engineer",
          "Operations Manager",
          "Quality Engineer",
        ],
      },
      {
        id: createDegreeId("Bachelor Engineering Mechanical Engineering UP"),
        name: "Bachelor of Engineering (Mechanical Engineering)",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "4 years",
        apsRequirement: 35,
        description: "Mechanical systems and design engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Mechanical Engineer",
          "Design Engineer",
          "Manufacturing Engineer",
        ],
      },
      {
        id: createDegreeId("Bachelor Engineering Metallurgical Engineering UP"),
        name: "Bachelor of Engineering (Metallurgical Engineering)",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "4 years",
        apsRequirement: 35,
        description: "Metallurgy and materials engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Metallurgical Engineer",
          "Materials Engineer",
          "Mining Engineer",
        ],
      },
      {
        id: createDegreeId("Bachelor Engineering Mining Engineering UP"),
        name: "Bachelor of Engineering (Mining Engineering)",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "4 years",
        apsRequirement: 35,
        description: "Mining and mineral extraction engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Mining Engineer",
          "Mine Manager",
          "Extraction Engineer",
        ],
      },
      {
        id: createDegreeId("Bachelor Engineering 5 year programme UP"),
        name: "Bachelor of Engineering (5-year programme)",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "5 years",
        apsRequirement: 33,
        description: "Extended engineering degree program",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Professional Engineer",
          "Engineering Consultant",
          "Project Manager",
        ],
      },
      // School for the Built Environment
      {
        id: createDegreeId("Bachelor Science Architecture UP"),
        name: "Bachelor of Science in Architecture",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "3 years",
        apsRequirement: 30,
        description: "Architectural design and planning",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: ["Architect", "Design Consultant", "Urban Planner"],
      },
      {
        id: createDegreeId("Bachelor Science Construction Management UP"),
        name: "Bachelor of Science in Construction Management",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "4 years",
        apsRequirement: 30,
        description: "Construction management and technology",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Construction Manager",
          "Project Manager",
          "Site Manager",
        ],
      },
      {
        id: createDegreeId("Bachelor Science Real Estate UP"),
        name: "Bachelor of Science in Real Estate",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "3 years",
        apsRequirement: 30,
        description: "Real estate development and management",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Real Estate Developer",
          "Property Manager",
          "Property Valuer",
        ],
      },
      {
        id: createDegreeId("Bachelor Science Quantity Surveying UP"),
        name: "Bachelor of Science in Quantity Surveying",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "4 years",
        apsRequirement: 30,
        description: "Quantity surveying and cost management",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Quantity Surveyor",
          "Cost Estimator",
          "Construction Economist",
        ],
      },
      {
        id: createDegreeId("Bachelor Town Regional Planning UP"),
        name: "Bachelor of Town and Regional Planning",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "4 years",
        apsRequirement: 27,
        description: "Urban and regional planning",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: ["Town Planner", "Urban Designer", "Regional Planner"],
      },
      // School of Information Technology
      {
        id: createDegreeId("Bachelor Information Science UP"),
        name: "Bachelor of Information Science",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "3 years",
        apsRequirement: 28,
        description: "Information science and management",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Information Scientist",
          "Data Manager",
          "Information Analyst",
        ],
      },
      {
        id: createDegreeId("Bachelor Information Science Publishing UP"),
        name: "Bachelor of Information Science (Publishing)",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "3 years",
        apsRequirement: 28,
        description: "Information science with publishing specialization",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: ["Publisher", "Editor", "Content Manager"],
      },
      {
        id: createDegreeId("Bachelor Information Science Multimedia UP"),
        name: "Bachelor of Information Science (Multimedia)",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "3 years",
        apsRequirement: 30,
        description: "Information science with multimedia applications",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Multimedia Designer",
          "Digital Content Creator",
          "Media Producer",
        ],
      },
      {
        id: createDegreeId(
          "Bachelor Information Technology Information Systems UP",
        ),
        name: "Bachelor of Information Technology (Information Systems)",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "3 years",
        apsRequirement: 30,
        description: "Information technology and systems",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "IT Specialist",
          "Systems Administrator",
          "Database Administrator",
        ],
      },
      {
        id: createDegreeId("Bachelor Science Computer Science UP"),
        name: "Bachelor of Science in Computer Science",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "3 years",
        apsRequirement: 30,
        description: "Computer science and programming",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Software Developer",
          "Computer Scientist",
          "Systems Analyst",
        ],
      },
      {
        id: createDegreeId(
          "Bachelor Science Information Technology Information Knowledge Systems UP",
        ),
        name: "Bachelor of Science in Information Technology (Information and Knowledge Systems)",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "3 years",
        apsRequirement: 30,
        description: "Information technology and knowledge management",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Knowledge Manager",
          "Information Systems Analyst",
          "Data Architect",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Health Sciences UP"),
    name: "Faculty of Health Sciences",
    description: "Medical, health, and sports science programs",
    degrees: [
      {
        id: createDegreeId("Bachelor Dental Surgery UP"),
        name: "Bachelor of Dental Surgery",
        faculty: "Health Sciences",
        duration: "5 years",
        apsRequirement: 35,
        description: "Dental medicine and oral health",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Life Sciences", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: ["Dentist", "Oral Surgeon", "Dental Specialist"],
      },
      {
        id: createDegreeId("Bachelor Oral Hygiene UP"),
        name: "Bachelor of Oral Hygiene",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 25,
        description: "Oral hygiene and dental therapy",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Oral Hygienist",
          "Dental Therapist",
          "Oral Health Educator",
        ],
      },
      {
        id: createDegreeId("Bachelor Dietetics UP"),
        name: "Bachelor of Dietetics",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 28,
        description: "Nutrition and dietetic practice",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: ["Dietitian", "Nutritionist", "Food Service Manager"],
      },
      {
        id: createDegreeId("Bachelor Nursing Science UP"),
        name: "Bachelor of Nursing Science",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 28,
        description: "Professional nursing practice",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Professional Nurse",
          "Nurse Manager",
          "Clinical Specialist",
        ],
      },
      {
        id: createDegreeId("Bachelor Occupational Therapy UP"),
        name: "Bachelor of Occupational Therapy",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 30,
        description: "Occupational therapy and rehabilitation",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Occupational Therapist",
          "Rehabilitation Specialist",
          "Community Health Worker",
        ],
      },
      {
        id: createDegreeId("Bachelor Physiotherapy UP"),
        name: "Bachelor of Physiotherapy",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 30,
        description: "Physical therapy and rehabilitation",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Physiotherapist",
          "Sports Therapist",
          "Rehabilitation Specialist",
        ],
      },
      {
        id: createDegreeId("Bachelor Radiography Diagnostics UP"),
        name: "Bachelor of Radiography in Diagnostics",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 30,
        description: "Medical imaging and diagnostic radiography",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Diagnostic Radiographer",
          "Medical Imaging Technologist",
          "Radiology Technician",
        ],
      },
      {
        id: createDegreeId("Bachelor Clinical Medical Practice UP"),
        name: "Bachelor of Clinical Medical Practice",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 28,
        description: "Clinical medical practice and primary healthcare",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Clinical Associate",
          "Medical Practitioner",
          "Primary Healthcare Provider",
        ],
      },
      {
        id: createDegreeId("Bachelor Medicine Surgery MBChB UP"),
        name: "Bachelor of Medicine and Surgery (MBChB)",
        faculty: "Health Sciences",
        duration: "6 years",
        apsRequirement: 35,
        description: "Medical practice and surgery",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Life Sciences", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: ["Medical Doctor", "Surgeon", "Medical Specialist"],
      },
      {
        id: createDegreeId("Bachelor Sports Science UP"),
        name: "Bachelor of Sports Science",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "Sports science and exercise physiology",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Sports Scientist",
          "Exercise Physiologist",
          "Sports Coach",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Humanities UP"),
    name: "Faculty of Humanities",
    description: "Arts, languages, and social sciences programs",
    degrees: [
      {
        id: createDegreeId("Bachelor Arts Speech Language Pathology UP"),
        name: "Bachelor of Arts (Speech-Language Pathology)",
        faculty: "Humanities",
        duration: "4 years",
        apsRequirement: 32,
        description: "Speech and language therapy",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Speech Therapist",
          "Language Therapist",
          "Communication Specialist",
        ],
      },
      {
        id: createDegreeId("Bachelor Arts Audiology UP"),
        name: "Bachelor of Arts (Audiology)",
        faculty: "Humanities",
        duration: "4 years",
        apsRequirement: 32,
        description: "Hearing and auditory rehabilitation",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Audiologist",
          "Hearing Aid Specialist",
          "Auditory Therapist",
        ],
      },
      {
        id: createDegreeId("Bachelor Arts Information Design UP"),
        name: "Bachelor of Arts (Information Design)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 30,
        description: "Information design and visual communication",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Visual Arts", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Information Designer",
          "Visual Designer",
          "UX/UI Designer",
        ],
      },
      {
        id: createDegreeId("Bachelor Arts General UP"),
        name: "Bachelor of Arts",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 30,
        description: "General arts and humanities",
        subjects: [{ name: "English", level: 5, isRequired: true }],
        careerProspects: [
          "Administrative Officer",
          "Communications Officer",
          "Research Assistant",
        ],
      },
      {
        id: createDegreeId("Bachelor Social Work UP"),
        name: "Bachelor of Social Work",
        faculty: "Humanities",
        duration: "4 years",
        apsRequirement: 30,
        description: "Social work practice and community development",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Social Worker",
          "Community Developer",
          "Family Counselor",
        ],
      },
      {
        id: createDegreeId("Bachelor Arts Law UP"),
        name: "Bachelor of Arts (Law)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 34,
        description: "Liberal arts with legal foundation",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: ["Legal Assistant", "Paralegal", "Legal Researcher"],
      },
      {
        id: createDegreeId("Bachelor Arts Languages UP"),
        name: "Bachelor of Arts (Languages)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 30,
        description: "Language studies and linguistics",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Home Language", level: 5, isRequired: true },
        ],
        careerProspects: ["Translator", "Language Teacher", "Linguist"],
      },
      {
        id: createDegreeId(
          "Bachelor Social Science Industrial Sociology Labour Studies UP",
        ),
        name: "Bachelor of Social Science (Industrial Sociology and Labour Studies)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 30,
        description: "Industrial sociology and labor relations",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Labor Relations Officer",
          "Industrial Sociologist",
          "HR Specialist",
        ],
      },
      {
        id: createDegreeId(
          "Bachelor Social Science Heritage Cultural Sciences UP",
        ),
        name: "Bachelor of Social Science (Heritage and Cultural Sciences)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 30,
        description: "Heritage and cultural studies",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "History", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Museum Curator",
          "Heritage Officer",
          "Cultural Analyst",
        ],
      },
      {
        id: createDegreeId("Bachelor Arts Philosophy Politics Economics UP"),
        name: "Bachelor of Arts (Philosophy, Politics and Economics)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 32,
        description: "Interdisciplinary philosophy, politics and economics",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Policy Analyst",
          "Political Researcher",
          "Economic Advisor",
        ],
      },
      {
        id: createDegreeId(
          "Bachelor Political Science International Studies UP",
        ),
        name: "Bachelor of Political Science (International Studies)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 30,
        description: "International relations and global politics",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "History", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Diplomat",
          "International Relations Officer",
          "Political Analyst",
        ],
      },
      {
        id: createDegreeId("Bachelor Political Science Political Studies UP"),
        name: "Bachelor of Political Science (Political Studies)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 30,
        description: "Political science and governance",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "History", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Political Scientist",
          "Government Official",
          "Policy Researcher",
        ],
      },
      {
        id: createDegreeId("Bachelor Arts Fine Arts UP"),
        name: "Bachelor of Arts (Fine Arts)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 30,
        description: "Visual and creative arts",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Visual Arts", level: 5, isRequired: true },
        ],
        careerProspects: ["Artist", "Art Teacher", "Gallery Curator"],
      },
      {
        id: createDegreeId("Bachelor Arts Fine Arts 5 year programme UP"),
        name: "Bachelor of Arts (Fine Arts, 5-year programme)",
        faculty: "Humanities",
        duration: "5 years",
        apsRequirement: 26,
        description: "Extended fine arts program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Visual Arts", level: 4, isRequired: true },
        ],
        careerProspects: ["Artist", "Art Teacher", "Gallery Curator"],
      },
      {
        id: createDegreeId("Bachelor Arts Visual Studies UP"),
        name: "Bachelor of Arts (Visual Studies)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 30,
        description: "Visual culture and media studies",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Visual Arts", level: 4, isRequired: true },
        ],
        careerProspects: ["Visual Researcher", "Media Analyst", "Curator"],
      },
      {
        id: createDegreeId("Bachelor Music UP"),
        name: "Bachelor of Music",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 30,
        description: "Music performance and theory",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Music", level: 5, isRequired: true },
        ],
        careerProspects: ["Musician", "Music Teacher", "Composer"],
      },
      {
        id: createDegreeId("Bachelor Music 5 year programme UP"),
        name: "Bachelor of Music (5-year programme)",
        faculty: "Humanities",
        duration: "5 years",
        apsRequirement: 26,
        description: "Extended music program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Music", level: 4, isRequired: true },
        ],
        careerProspects: ["Musician", "Music Teacher", "Composer"],
      },
      {
        id: createDegreeId("Bachelor Drama UP"),
        name: "Bachelor of Drama",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 30,
        description: "Theatre and performance arts",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Dramatic Arts", level: 5, isRequired: true },
        ],
        careerProspects: ["Actor", "Theatre Director", "Drama Teacher"],
      },
      {
        id: createDegreeId("Bachelor Drama 5 year programme UP"),
        name: "Bachelor of Drama (5-year programme)",
        faculty: "Humanities",
        duration: "5 years",
        apsRequirement: 26,
        description: "Extended drama program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Dramatic Arts", level: 4, isRequired: true },
        ],
        careerProspects: ["Actor", "Theatre Director", "Drama Teacher"],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Law UP"),
    name: "Faculty of Law",
    description: "Legal studies and jurisprudence programs",
    degrees: [
      {
        id: createDegreeId("Bachelor Laws LLB UP"),
        name: "Bachelor of Laws (LLB)",
        faculty: "Law",
        duration: "4 years",
        apsRequirement: 35,
        description: "Professional legal qualification",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: ["Lawyer", "Attorney", "Legal Consultant"],
      },
      {
        id: createDegreeId("Bachelor Arts Law Faculty UP"),
        name: "Bachelor of Arts (Law)",
        faculty: "Law",
        duration: "3 years",
        apsRequirement: 34,
        description: "Liberal arts with legal foundation",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: ["Legal Assistant", "Paralegal", "Legal Researcher"],
      },
      {
        id: createDegreeId("Bachelor Commerce Law Faculty UP"),
        name: "Bachelor of Commerce (Law)",
        faculty: "Law",
        duration: "3 years",
        apsRequirement: 32,
        description: "Commerce with legal foundation",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Corporate Legal Officer",
          "Compliance Manager",
          "Legal Advisor",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Theology Religion UP"),
    name: "Faculty of Theology and Religion",
    description: "Theological and religious studies programs",
    degrees: [
      {
        id: createDegreeId("Bachelor Theology UP"),
        name: "Bachelor of Theology",
        faculty: "Theology and Religion",
        duration: "3 years",
        apsRequirement: 23,
        description: "Theological studies and ministry preparation",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: true },
        ],
        careerProspects: ["Minister", "Chaplain", "Religious Educator"],
      },
      {
        id: createDegreeId("Diploma Theology UP"),
        name: "Diploma in Theology",
        faculty: "Theology and Religion",
        duration: "3 years",
        apsRequirement: 23,
        description: "Theological diploma program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: true },
        ],
        careerProspects: ["Religious Leader", "Youth Pastor", "Missionary"],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Natural Agricultural Sciences UP"),
    name: "Faculty of Natural and Agricultural Sciences",
    description: "Natural sciences, agriculture, and food science programs",
    degrees: [
      // Agricultural and Food Sciences
      {
        id: createDegreeId(
          "Bachelor Science Agriculture Agricultural Economics UP",
        ),
        name: "Bachelor of Science in Agriculture (Agricultural Economics)",
        faculty: "Natural and Agricultural Sciences",
        duration: "4 years",
        apsRequirement: 32,
        description: "Agricultural economics and farm management",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Agricultural Economist",
          "Farm Manager",
          "Agricultural Consultant",
        ],
      },
      {
        id: createDegreeId("Bachelor Science Agriculture Animal Science UP"),
        name: "Bachelor of Science in Agriculture (Animal Science)",
        faculty: "Natural and Agricultural Sciences",
        duration: "4 years",
        apsRequirement: 32,
        description: "Animal husbandry and production",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Animal Scientist",
          "Livestock Manager",
          "Veterinary Technician",
        ],
      },
      {
        id: createDegreeId(
          "Bachelor Science Agriculture Applied Plant Soil Sciences 4year UP",
        ),
        name: "Bachelor of Science in Agriculture (Applied Plant and Soil Sciences)",
        faculty: "Natural and Agricultural Sciences",
        duration: "4 years",
        apsRequirement: 32,
        description: "Plant science and soil management",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: ["Plant Scientist", "Soil Scientist", "Agronomist"],
      },
      {
        id: createDegreeId("Bachelor Science Agriculture Plant Pathology UP"),
        name: "Bachelor of Science in Agriculture (Plant Pathology)",
        faculty: "Natural and Agricultural Sciences",
        duration: "4 years",
        apsRequirement: 32,
        description: "Plant diseases and pest management",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Plant Pathologist",
          "Pest Control Specialist",
          "Agricultural Researcher",
        ],
      },
      {
        id: createDegreeId(
          "Bachelor Science Food Management Culinary Science UP",
        ),
        name: "Bachelor of Science in Food Management (Culinary Science)",
        faculty: "Natural and Agricultural Sciences",
        duration: "4 years",
        apsRequirement: 32,
        description: "Culinary science and food management",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Food Scientist",
          "Culinary Manager",
          "Food Product Developer",
        ],
      },
      {
        id: createDegreeId(
          "Bachelor Science Food Management Nutritional Science UP",
        ),
        name: "Bachelor of Science in Food Management (Nutritional Science)",
        faculty: "Natural and Agricultural Sciences",
        duration: "4 years",
        apsRequirement: 32,
        description: "Nutritional science and food management",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Food Scientist",
          "Nutritionist",
          "Food Quality Manager",
        ],
      },
      {
        id: createDegreeId("Bachelor Science Food Science UP"),
        name: "Bachelor of Science in Food Science",
        faculty: "Natural and Agricultural Sciences",
        duration: "4 years",
        apsRequirement: 32,
        description: "Food science and technology",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Food Scientist",
          "Food Technologist",
          "Quality Assurance Manager",
        ],
      },
      // Biological Sciences
      {
        id: createDegreeId("Bachelor Science Biochemistry UP"),
        name: "Bachelor of Science in Biochemistry",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Biochemical processes and molecular biology",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Biochemist",
          "Research Scientist",
          "Laboratory Manager",
        ],
      },
      {
        id: createDegreeId("Bachelor Science Biotechnology UP"),
        name: "Bachelor of Science in Biotechnology",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Biotechnology and genetic engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Biotechnologist",
          "Genetic Engineer",
          "Biomedical Researcher",
        ],
      },
      {
        id: createDegreeId("Bachelor Science Ecology UP"),
        name: "Bachelor of Science in Ecology",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Ecological systems and environmental biology",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Ecologist",
          "Environmental Scientist",
          "Conservation Biologist",
        ],
      },
      {
        id: createDegreeId("Bachelor Science Entomology UP"),
        name: "Bachelor of Science in Entomology",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Insect biology and pest management",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Entomologist",
          "Pest Control Specialist",
          "Agricultural Researcher",
        ],
      },
      {
        id: createDegreeId("Bachelor Science Genetics UP"),
        name: "Bachelor of Science in Genetics",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Genetic principles and molecular genetics",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Geneticist",
          "Genetic Counselor",
          "Research Scientist",
        ],
      },
      {
        id: createDegreeId("Bachelor Science Human Genetics UP"),
        name: "Bachelor of Science in Human Genetics",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Human genetics and medical genetics",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Human Geneticist",
          "Genetic Counselor",
          "Medical Researcher",
        ],
      },
      {
        id: createDegreeId("Bachelor Science Human Physiology UP"),
        name: "Bachelor of Science in Human Physiology",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Human physiological systems",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Physiologist",
          "Medical Researcher",
          "Clinical Scientist",
        ],
      },
      {
        id: createDegreeId(
          "Bachelor Science Human Physiology Genetics Psychology UP",
        ),
        name: "Bachelor of Science in Human Physiology, Genetics and Psychology",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Interdisciplinary human sciences",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Research Scientist",
          "Medical Researcher",
          "Neuropsychologist",
        ],
      },
      {
        id: createDegreeId("Bachelor Science Medical Sciences UP"),
        name: "Bachelor of Science in Medical Sciences",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Medical and biomedical sciences",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Medical Scientist",
          "Biomedical Researcher",
          "Laboratory Manager",
        ],
      },
      {
        id: createDegreeId("Bachelor Science Microbiology UP"),
        name: "Bachelor of Science in Microbiology",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Microbiology and infectious diseases",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Microbiologist",
          "Medical Laboratory Scientist",
          "Quality Control Specialist",
        ],
      },
      {
        id: createDegreeId("Bachelor Science Plant Science UP"),
        name: "Bachelor of Science in Plant Science",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Plant biology and botany",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Plant Scientist",
          "Botanist",
          "Agricultural Researcher",
        ],
      },
      {
        id: createDegreeId("Bachelor Science Zoology UP"),
        name: "Bachelor of Science in Zoology",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Animal biology and zoology",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Zoologist",
          "Wildlife Biologist",
          "Conservation Specialist",
        ],
      },
      // Consumer Science
      {
        id: createDegreeId(
          "Bachelor Consumer Science Clothing Retail Management UP",
        ),
        name: "Bachelor of Consumer Science (Clothing Retail Management)",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 28,
        description: "Clothing and retail management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Retail Manager",
          "Fashion Buyer",
          "Merchandise Manager",
        ],
      },
      {
        id: createDegreeId("Bachelor Consumer Science Food Management UP"),
        name: "Bachelor of Consumer Science (Food Management)",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 28,
        description: "Food service and hospitality management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Food Service Manager",
          "Catering Manager",
          "Restaurant Manager",
        ],
      },
      // Mathematical Sciences
      {
        id: createDegreeId(
          "Bachelor Science Actuarial Financial Mathematics UP",
        ),
        name: "Bachelor of Science in Actuarial and Financial Mathematics",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 36,
        description: "Actuarial science and financial mathematics",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
        ],
        careerProspects: ["Actuary", "Risk Analyst", "Investment Analyst"],
      },
      {
        id: createDegreeId("Bachelor Science Mathematics 3year UP"),
        name: "Bachelor of Science in Mathematics",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 34,
        description: "Pure and applied mathematics",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
        ],
        careerProspects: ["Mathematician", "Statistician", "Data Analyst"],
      },
      {
        id: createDegreeId("Bachelor Science Applied Mathematics UP"),
        name: "Bachelor of Science in Applied Mathematics",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 34,
        description: "Applied mathematical methods",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Applied Mathematician",
          "Data Scientist",
          "Research Analyst",
        ],
      },
      {
        id: createDegreeId("Bachelor Science Mathematical Statistics UP"),
        name: "Bachelor of Science in Mathematical Statistics",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 34,
        description: "Statistical analysis and data science",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Statistician",
          "Data Scientist",
          "Market Researcher",
        ],
      },
      // Physical Sciences
      {
        id: createDegreeId("Bachelor Science Chemistry 3year UP"),
        name: "Bachelor of Science in Chemistry",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 34,
        description: "Chemical sciences and analysis",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Chemist",
          "Research Scientist",
          "Quality Control Analyst",
        ],
      },
      {
        id: createDegreeId(
          "Bachelor Science Environmental Engineering Geology UP",
        ),
        name: "Bachelor of Science in Environmental and Engineering Geology",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 34,
        description: "Environmental and engineering geology",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Geologist",
          "Environmental Consultant",
          "Mining Engineer",
        ],
      },
      {
        id: createDegreeId(
          "Bachelor Science Geography Geography Environmental Science UP",
        ),
        name: "Bachelor of Science in Geography (Geography and Environmental Science)",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 34,
        description: "Geography and environmental science",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Geography", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Geographer",
          "Environmental Scientist",
          "GIS Specialist",
        ],
      },
      {
        id: createDegreeId("Bachelor Science Geoinformatics 3year UP"),
        name: "Bachelor of Science in Geoinformatics",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 34,
        description: "Geographic information systems",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Geography", level: 5, isRequired: true },
        ],
        careerProspects: [
          "GIS Specialist",
          "Geospatial Analyst",
          "Cartographer",
        ],
      },
      {
        id: createDegreeId("Bachelor Science Geology 3year UP"),
        name: "Bachelor of Science in Geology",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 34,
        description: "Earth sciences and geological processes",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: ["Geologist", "Mining Specialist", "Earth Scientist"],
      },
      {
        id: createDegreeId("Bachelor Science Meteorology 3year UP"),
        name: "Bachelor of Science in Meteorology",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 34,
        description: "Atmospheric science and weather forecasting",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Meteorologist",
          "Weather Forecaster",
          "Climate Scientist",
        ],
      },
      {
        id: createDegreeId("Bachelor Science Physics 3year UP"),
        name: "Bachelor of Science in Physics",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 34,
        description: "Physical sciences and theoretical physics",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Physicist",
          "Research Scientist",
          "Engineering Physicist",
        ],
      },
      // Extended Programmes
      {
        id: createDegreeId("Bachelor Science Mathematics 4 year UP"),
        name: "Bachelor of Science in Mathematics (4-year)",
        faculty: "Natural and Agricultural Sciences",
        duration: "4 years",
        apsRequirement: 32,
        description: "Extended mathematics degree",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: ["Mathematician", "Statistician", "Data Analyst"],
      },
      {
        id: createDegreeId("Bachelor Science Chemistry 4 year UP"),
        name: "Bachelor of Science in Chemistry (4-year)",
        faculty: "Natural and Agricultural Sciences",
        duration: "4 years",
        apsRequirement: 32,
        description: "Extended chemistry degree",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Chemist",
          "Research Scientist",
          "Quality Control Analyst",
        ],
      },
      {
        id: createDegreeId("Bachelor Science Geoinformatics 4 year UP"),
        name: "Bachelor of Science in Geoinformatics (4-year)",
        faculty: "Natural and Agricultural Sciences",
        duration: "4 years",
        apsRequirement: 32,
        description: "Extended geoinformatics degree",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Geography", level: 4, isRequired: true },
        ],
        careerProspects: [
          "GIS Specialist",
          "Geospatial Analyst",
          "Cartographer",
        ],
      },
      {
        id: createDegreeId("Bachelor Science Geology 4 year UP"),
        name: "Bachelor of Science in Geology (4-year)",
        faculty: "Natural and Agricultural Sciences",
        duration: "4 years",
        apsRequirement: 32,
        description: "Extended geology degree",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: ["Geologist", "Mining Specialist", "Earth Scientist"],
      },
      {
        id: createDegreeId("Bachelor Science Meteorology 4 year UP"),
        name: "Bachelor of Science in Meteorology (4-year)",
        faculty: "Natural and Agricultural Sciences",
        duration: "4 years",
        apsRequirement: 32,
        description: "Extended meteorology degree",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Meteorologist",
          "Weather Forecaster",
          "Climate Scientist",
        ],
      },
      {
        id: createDegreeId("Bachelor Science Physics 4 year UP"),
        name: "Bachelor of Science in Physics (4-year)",
        faculty: "Natural and Agricultural Sciences",
        duration: "4 years",
        apsRequirement: 32,
        description: "Extended physics degree",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Physicist",
          "Research Scientist",
          "Engineering Physicist",
        ],
      },
      {
        id: createDegreeId(
          "Bachelor Science Agriculture Applied Plant Soil Sciences 5 year UP",
        ),
        name: "Bachelor of Science in Agriculture (Applied Plant and Soil Sciences, 5-year)",
        faculty: "Natural and Agricultural Sciences",
        duration: "5 years",
        apsRequirement: 32,
        description: "Extended plant and soil sciences degree",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
        ],
        careerProspects: ["Plant Scientist", "Soil Scientist", "Agronomist"],
      },
      {
        id: createDegreeId(
          "Bachelor Science Agriculture Plant Pathology 5 year UP",
        ),
        name: "Bachelor of Science in Agriculture (Plant Pathology, 5-year)",
        faculty: "Natural and Agricultural Sciences",
        duration: "5 years",
        apsRequirement: 32,
        description: "Extended plant pathology degree",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Plant Pathologist",
          "Pest Control Specialist",
          "Agricultural Researcher",
        ],
      },
      {
        id: createDegreeId("Bachelor Science Ecology 5 year UP"),
        name: "Bachelor of Science in Ecology (5-year)",
        faculty: "Natural and Agricultural Sciences",
        duration: "5 years",
        apsRequirement: 32,
        description: "Extended ecology degree",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Ecologist",
          "Environmental Scientist",
          "Conservation Biologist",
        ],
      },
      {
        id: createDegreeId("Bachelor Science Human Physiology 5 year UP"),
        name: "Bachelor of Science in Human Physiology (5-year)",
        faculty: "Natural and Agricultural Sciences",
        duration: "5 years",
        apsRequirement: 32,
        description: "Extended human physiology degree",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Physiologist",
          "Medical Researcher",
          "Clinical Scientist",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Veterinary Science UP"),
    name: "Faculty of Veterinary Science",
    description: "Veterinary medicine and animal health programs",
    degrees: [
      {
        id: createDegreeId("Bachelor Veterinary Science UP"),
        name: "Bachelor of Veterinary Science",
        faculty: "Veterinary Science",
        duration: "6 years",
        apsRequirement: 34,
        description: "Veterinary medicine and animal health",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Life Sciences", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Veterinarian",
          "Animal Health Specialist",
          "Veterinary Researcher",
        ],
      },
      {
        id: createDegreeId("Bachelor Veterinary Nursing UP"),
        name: "Bachelor of Veterinary Nursing",
        faculty: "Veterinary Science",
        duration: "3 years",
        apsRequirement: 24,
        description: "Veterinary nursing and animal care",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Veterinary Nurse",
          "Animal Care Specialist",
          "Veterinary Technician",
        ],
      },
    ],
  },
];
