import { Faculty } from "@/types/university";
import { createDegreeId, createFacultyId } from "./base";

// University of Pretoria (UP) - Faculty Data
export const UP_FACULTIES: Faculty[] = [
  {
    id: createFacultyId("Faculty of Economic and Management Sciences UP"),
    name: "Faculty of Economic and Management Sciences",
    description: "Business, economics, and management programs",
    degrees: [
      {
        id: createDegreeId("Bachelor of Administration UP"),
        name: "Bachelor of Administration (Public Administration)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 28,
        description: "Public administration and governance",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Public Administrator",
          "Government Official",
          "Policy Analyst",
        ],
      },
      {
        id: createDegreeId("BCom Accounting Sciences UP"),
        name: "Bachelor of Commerce in Accounting Sciences",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 34,
        description: "Chartered accountancy qualification pathway",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Accounting", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Chartered Accountant",
          "Auditor",
          "Financial Analyst",
        ],
      },
      {
        id: createDegreeId("BCom Investment Management UP"),
        name: "Bachelor of Commerce (Investment Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 34,
        description: "Investment and portfolio management",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Investment Analyst",
          "Portfolio Manager",
          "Financial Advisor",
        ],
      },
      {
        id: createDegreeId("BCom Financial Management Sciences UP"),
        name: "Bachelor of Commerce (Financial Management Sciences)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Financial management and analysis",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Financial Manager",
          "Corporate Finance Analyst",
          "Financial Consultant",
        ],
      },
      {
        id: createDegreeId("BCom Econometrics UP"),
        name: "Bachelor of Commerce (Econometrics)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Statistical analysis of economic data",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Econometrician",
          "Data Analyst",
          "Research Economist",
        ],
      },
      {
        id: createDegreeId("BCom Economics UP"),
        name: "Bachelor of Commerce (Economics)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Economic theory and analysis",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: ["Economist", "Policy Analyst", "Market Researcher"],
      },
      {
        id: createDegreeId("BCom Law UP"),
        name: "Bachelor of Commerce (Law)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Commerce with legal foundations",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Legal Advisor",
          "Corporate Legal Officer",
          "Compliance Officer",
        ],
      },
      {
        id: createDegreeId("BCom Statistics and Data Science UP"),
        name: "Bachelor of Commerce (Statistics and Data Science)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Statistical analysis and data science",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: ["Data Scientist", "Statistician", "Business Analyst"],
      },
      {
        id: createDegreeId("BCom Information Systems UP"),
        name: "Bachelor of Commerce (Information Systems)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "Business information systems",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Systems Analyst",
          "IT Business Analyst",
          "Information Systems Manager",
        ],
      },
      {
        id: createDegreeId("BCom Agribusiness Management UP"),
        name: "Bachelor of Commerce (Agribusiness Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "Agricultural business management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Agribusiness Manager",
          "Agricultural Economist",
          "Farm Manager",
        ],
      },
      {
        id: createDegreeId("BCom Business Management UP"),
        name: "Bachelor of Commerce (Business Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "General business management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Business Manager",
          "Operations Manager",
          "Management Consultant",
        ],
      },
      {
        id: createDegreeId("BCom Supply Chain Management UP"),
        name: "Bachelor of Commerce (Supply Chain Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "Supply chain and logistics management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Supply Chain Manager",
          "Logistics Coordinator",
          "Operations Analyst",
        ],
      },
      {
        id: createDegreeId("BCom Marketing Management UP"),
        name: "Bachelor of Commerce (Marketing Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "Marketing and brand management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Marketing Manager",
          "Brand Manager",
          "Digital Marketing Specialist",
        ],
      },
      {
        id: createDegreeId("BCom Human Resource Management UP"),
        name: "Bachelor of Commerce (Human Resource Management)",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "Human resources and people management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "HR Manager",
          "Recruitment Specialist",
          "Training and Development Officer",
        ],
      },
      {
        id: createDegreeId("BCom General UP"),
        name: "Bachelor of Commerce",
        faculty: "Economic and Management Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "General commerce qualification",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Business Analyst",
          "Administrative Officer",
          "Financial Officer",
        ],
      },
      {
        id: createDegreeId("BCom 4 year programme UP"),
        name: "Bachelor of Commerce (4-year programme)",
        faculty: "Economic and Management Sciences",
        duration: "4 years",
        apsRequirement: 26,
        description: "Extended commerce programme",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Business Analyst",
          "Administrative Officer",
          "Financial Officer",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Education UP"),
    name: "Faculty of Education",
    description: "Teacher education and training programs",
    degrees: [
      {
        id: createDegreeId("BEd Early Childhood Care UP"),
        name: "Bachelor of Education (Early Childhood Care and Education)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 28,
        description: "Early childhood development and education",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Early Childhood Educator",
          "Preschool Teacher",
          "Child Development Specialist",
        ],
      },
      {
        id: createDegreeId("BEd Foundation Phase UP"),
        name: "Bachelor of Education (Foundation Phase Teaching)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 28,
        description: "Foundation phase teaching (Grades R-3)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Foundation Phase Teacher",
          "Primary School Teacher",
          "Educational Specialist",
        ],
      },
      {
        id: createDegreeId("BEd Intermediate Phase UP"),
        name: "Bachelor of Education (Intermediate Phase Teaching)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 28,
        description: "Intermediate phase teaching (Grades 4-6)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Intermediate Phase Teacher",
          "Primary School Teacher",
          "Subject Specialist",
        ],
      },
      {
        id: createDegreeId("BEd Senior Phase FET UP"),
        name: "Bachelor of Education (Senior Phase and Further Education and Training Teaching)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 28,
        description: "Senior phase and FET teaching (Grades 7-12)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "High School Teacher",
          "Subject Specialist",
          "Educational Consultant",
        ],
      },
      {
        id: createDegreeId("Higher Certificate Sports Sciences 1 year UP"),
        name: "Higher Certificate in Sports Sciences (1 year)",
        faculty: "Education",
        duration: "1 year",
        apsRequirement: 20,
        description: "Sports science foundation qualification",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Life Sciences", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Sports Assistant",
          "Fitness Instructor",
          "Sports Coordinator",
        ],
      },
      {
        id: createDegreeId(
          "Higher Certificate Sports Sciences 2 year online UP",
        ),
        name: "Higher Certificate in Sports Sciences (2 years, online)",
        faculty: "Education",
        duration: "2 years",
        apsRequirement: 20,
        description: "Online sports science qualification",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Life Sciences", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Sports Assistant",
          "Fitness Instructor",
          "Sports Coordinator",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Engineering Built Environment and IT UP"),
    name: "Faculty of Engineering, Built Environment and Information Technology",
    description: "Engineering, construction, and IT programs",
    degrees: [
      {
        id: createDegreeId("BEng Chemical Engineering UP"),
        name: "Bachelor of Engineering (Chemical Engineering)",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "4 years",
        apsRequirement: 35,
        description: "Chemical process engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Chemical Engineer",
          "Process Engineer",
          "Plant Manager",
        ],
      },
      {
        id: createDegreeId("BEng Civil Engineering UP"),
        name: "Bachelor of Engineering (Civil Engineering)",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "4 years",
        apsRequirement: 35,
        description: "Infrastructure and construction engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Civil Engineer",
          "Structural Engineer",
          "Project Manager",
        ],
      },
      {
        id: createDegreeId("BEng Computer Engineering UP"),
        name: "Bachelor of Engineering (Computer Engineering)",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "4 years",
        apsRequirement: 35,
        description: "Computer hardware and software engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Computer Engineer",
          "Software Engineer",
          "Systems Engineer",
        ],
      },
      {
        id: createDegreeId("BEng Electrical Engineering UP"),
        name: "Bachelor of Engineering (Electrical Engineering)",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "4 years",
        apsRequirement: 35,
        description: "Electrical power and systems engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Electrical Engineer",
          "Power Systems Engineer",
          "Control Engineer",
        ],
      },
      {
        id: createDegreeId("BEng Electronic Engineering UP"),
        name: "Bachelor of Engineering (Electronic Engineering)",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "4 years",
        apsRequirement: 35,
        description: "Electronic systems and communications engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Electronic Engineer",
          "Communications Engineer",
          "Design Engineer",
        ],
      },
      {
        id: createDegreeId("BEng Industrial Engineering UP"),
        name: "Bachelor of Engineering (Industrial Engineering)",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "4 years",
        apsRequirement: 35,
        description: "Manufacturing and operations engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Industrial Engineer",
          "Operations Manager",
          "Quality Engineer",
        ],
      },
      {
        id: createDegreeId("BEng Mechanical Engineering UP"),
        name: "Bachelor of Engineering (Mechanical Engineering)",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "4 years",
        apsRequirement: 35,
        description: "Mechanical systems and design engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Mechanical Engineer",
          "Design Engineer",
          "Manufacturing Engineer",
        ],
      },
      {
        id: createDegreeId("BEng Metallurgical Engineering UP"),
        name: "Bachelor of Engineering (Metallurgical Engineering)",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "4 years",
        apsRequirement: 35,
        description: "Materials and metallurgical engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Metallurgical Engineer",
          "Materials Engineer",
          "Process Engineer",
        ],
      },
      {
        id: createDegreeId("BEng Mining Engineering UP"),
        name: "Bachelor of Engineering (Mining Engineering)",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "4 years",
        apsRequirement: 35,
        description: "Mining and mineral extraction engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Mining Engineer",
          "Mine Manager",
          "Extraction Engineer",
        ],
      },
      {
        id: createDegreeId("BEng 5 year programme UP"),
        name: "Bachelor of Engineering (5-year programme)",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "5 years",
        apsRequirement: 33,
        description: "Extended engineering programme",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Professional Engineer",
          "Design Engineer",
          "Project Engineer",
        ],
      },
      {
        id: createDegreeId("BSc Architecture UP"),
        name: "Bachelor of Science in Architecture",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "3 years",
        apsRequirement: 30,
        description: "Architectural design and planning",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: ["Architect", "Design Consultant", "Urban Planner"],
      },
      {
        id: createDegreeId("BSc Construction Management UP"),
        name: "Bachelor of Science in Construction Management",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "3 years",
        apsRequirement: 30,
        description: "Construction project management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Construction Manager",
          "Project Manager",
          "Site Manager",
        ],
      },
      {
        id: createDegreeId("BSc Real Estate UP"),
        name: "Bachelor of Science in Real Estate",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "3 years",
        apsRequirement: 30,
        description: "Property and real estate management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Real Estate Agent",
          "Property Manager",
          "Property Valuer",
        ],
      },
      {
        id: createDegreeId("BSc Quantity Surveying UP"),
        name: "Bachelor of Science in Quantity Surveying",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "3 years",
        apsRequirement: 30,
        description: "Construction cost estimation and management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Quantity Surveyor",
          "Cost Estimator",
          "Project Coordinator",
        ],
      },
      {
        id: createDegreeId("Bachelor Town Regional Planning UP"),
        name: "Bachelor of Town and Regional Planning",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "4 years",
        apsRequirement: 27,
        description: "Urban and regional planning",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Town Planner",
          "Urban Designer",
          "Planning Consultant",
        ],
      },
      {
        id: createDegreeId("Bachelor Information Science UP"),
        name: "Bachelor of Information Science",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "3 years",
        apsRequirement: 28,
        description: "Information management and systems",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Information Manager",
          "Systems Analyst",
          "Data Manager",
        ],
      },
      {
        id: createDegreeId("Bachelor Information Science Publishing UP"),
        name: "Bachelor of Information Science (Publishing)",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "3 years",
        apsRequirement: 28,
        description: "Publishing and information management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: ["Publisher", "Editor", "Content Manager"],
      },
      {
        id: createDegreeId("Bachelor Information Science Multimedia UP"),
        name: "Bachelor of Information Science (Multimedia)",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "3 years",
        apsRequirement: 30,
        description: "Multimedia and digital information systems",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Multimedia Developer",
          "Digital Content Creator",
          "Web Designer",
        ],
      },
      {
        id: createDegreeId("Bachelor IT Information Systems UP"),
        name: "Bachelor of Information Technology (Information Systems)",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "3 years",
        apsRequirement: 30,
        description: "Information technology and systems",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "IT Specialist",
          "Systems Administrator",
          "Network Manager",
        ],
      },
      {
        id: createDegreeId("BSc Computer Science UP"),
        name: "Bachelor of Science in Computer Science",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "3 years",
        apsRequirement: 30,
        description: "Computer science and programming",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Software Developer",
          "Computer Scientist",
          "Systems Analyst",
        ],
      },
      {
        id: createDegreeId("BSc IT Information Knowledge Systems UP"),
        name: "Bachelor of Science in Information Technology (Information and Knowledge Systems)",
        faculty: "Engineering, Built Environment and Information Technology",
        duration: "3 years",
        apsRequirement: 30,
        description: "Information technology and knowledge systems",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Knowledge Manager",
          "Information Architect",
          "Data Analyst",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Health Sciences UP"),
    name: "Faculty of Health Sciences",
    description: "Medical and health-related programs",
    degrees: [
      {
        id: createDegreeId("Bachelor Dental Surgery UP"),
        name: "Bachelor of Dental Surgery",
        faculty: "Health Sciences",
        duration: "5 years",
        apsRequirement: 35,
        description: "Dental medicine and surgery",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: ["Dentist", "Oral Surgeon", "Dental Specialist"],
      },
      {
        id: createDegreeId("Bachelor Oral Hygiene UP"),
        name: "Bachelor of Oral Hygiene",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 25,
        description: "Oral health and hygiene care",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Oral Hygienist",
          "Dental Therapist",
          "Oral Health Educator",
        ],
      },
      {
        id: createDegreeId("Bachelor Dietetics UP"),
        name: "Bachelor of Dietetics",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 28,
        description: "Nutrition and dietetic practice",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: ["Dietitian", "Nutritionist", "Food Service Manager"],
      },
      {
        id: createDegreeId("Bachelor Nursing Science UP"),
        name: "Bachelor of Nursing Science",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 28,
        description: "Professional nursing practice",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Professional Nurse",
          "Nurse Manager",
          "Clinical Specialist",
        ],
      },
      {
        id: createDegreeId("Bachelor Occupational Therapy UP"),
        name: "Bachelor of Occupational Therapy",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 30,
        description: "Occupational therapy practice",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Occupational Therapist",
          "Rehabilitation Specialist",
          "Community Health Worker",
        ],
      },
      {
        id: createDegreeId("Bachelor Physiotherapy UP"),
        name: "Bachelor of Physiotherapy",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 30,
        description: "Physical therapy and rehabilitation",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Physiotherapist",
          "Sports Therapist",
          "Rehabilitation Specialist",
        ],
      },
      {
        id: createDegreeId("Bachelor Radiography Diagnostics UP"),
        name: "Bachelor of Radiography in Diagnostics",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "Medical imaging and radiography",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Radiographer",
          "Medical Imaging Technologist",
          "Diagnostic Specialist",
        ],
      },
      {
        id: createDegreeId("Bachelor Clinical Medical Practice UP"),
        name: "Bachelor of Clinical Medical Practice",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 28,
        description: "Clinical medical practice",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Clinical Associate",
          "Medical Practitioner",
          "Healthcare Provider",
        ],
      },
      {
        id: createDegreeId("Bachelor Medicine Surgery UP"),
        name: "Bachelor of Medicine and Surgery (MBChB)",
        faculty: "Health Sciences",
        duration: "6 years",
        apsRequirement: 35,
        description: "Medical practice and surgery",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: ["Medical Doctor", "Surgeon", "Medical Specialist"],
      },
      {
        id: createDegreeId("Bachelor Sports Science UP"),
        name: "Bachelor of Sports Science",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "Sports science and exercise physiology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Sports Scientist",
          "Exercise Physiologist",
          "Sports Coach",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Humanities UP"),
    name: "Faculty of Humanities",
    description: "Humanities, arts, and social sciences programs",
    degrees: [
      {
        id: createDegreeId("BA Speech Language Pathology UP"),
        name: "Bachelor of Arts (Speech-Language Pathology)",
        faculty: "Humanities",
        duration: "4 years",
        apsRequirement: 32,
        description: "Speech and language therapy",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Speech Therapist",
          "Language Therapist",
          "Communication Specialist",
        ],
      },
      {
        id: createDegreeId("BA Audiology UP"),
        name: "Bachelor of Arts (Audiology)",
        faculty: "Humanities",
        duration: "4 years",
        apsRequirement: 32,
        description: "Hearing and auditory rehabilitation",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Audiologist",
          "Hearing Aid Specialist",
          "Auditory Therapist",
        ],
      },
      {
        id: createDegreeId("BA Information Design UP"),
        name: "Bachelor of Arts (Information Design)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 30,
        description: "Visual communication and information design",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Visual Arts", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Information Designer",
          "Graphic Designer",
          "UX Designer",
        ],
      },
      {
        id: createDegreeId("BA General UP"),
        name: "Bachelor of Arts",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 30,
        description: "General humanities and liberal arts",
        subjects: [{ name: "English", level: 4, isRequired: true }],
        careerProspects: [
          "Administrative Officer",
          "Communications Officer",
          "Research Assistant",
        ],
      },
      {
        id: createDegreeId("Bachelor Social Work UP"),
        name: "Bachelor of Social Work",
        faculty: "Humanities",
        duration: "4 years",
        apsRequirement: 30,
        description: "Social work practice and community development",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Social Worker",
          "Community Developer",
          "Family Counselor",
        ],
      },
      {
        id: createDegreeId("BA Law UP"),
        name: "Bachelor of Arts (Law)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 34,
        description: "Liberal arts with legal foundation",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: ["Legal Assistant", "Paralegal", "Legal Researcher"],
      },
      {
        id: createDegreeId("BA Languages UP"),
        name: "Bachelor of Arts (Languages)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 30,
        description: "Language studies and linguistics",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Additional Language", level: 4, isRequired: true },
        ],
        careerProspects: ["Translator", "Language Teacher", "Interpreter"],
      },
      {
        id: createDegreeId("BSocSc Industrial Sociology Labour Studies UP"),
        name: "Bachelor of Social Science (Industrial Sociology and Labour Studies)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 30,
        description: "Industrial relations and labour studies",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Labour Relations Officer",
          "Industrial Psychologist",
          "HR Specialist",
        ],
      },
      {
        id: createDegreeId("BSocSc Heritage Cultural Sciences UP"),
        name: "Bachelor of Social Science (Heritage and Cultural Sciences)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 30,
        description: "Heritage preservation and cultural studies",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "History", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Heritage Officer",
          "Museum Curator",
          "Cultural Consultant",
        ],
      },
      {
        id: createDegreeId("BA Philosophy Politics Economics UP"),
        name: "Bachelor of Arts (Philosophy, Politics and Economics)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 32,
        description: "Interdisciplinary PPE studies",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Policy Analyst",
          "Political Researcher",
          "Economic Analyst",
        ],
      },
      {
        id: createDegreeId(
          "Bachelor Political Science International Studies UP",
        ),
        name: "Bachelor of Political Science (International Studies)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 30,
        description: "International relations and politics",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "History", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Diplomat",
          "International Relations Officer",
          "Political Analyst",
        ],
      },
      {
        id: createDegreeId("Bachelor Political Science Political Studies UP"),
        name: "Bachelor of Political Science (Political Studies)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 30,
        description: "Political science and governance",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "History", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Political Scientist",
          "Government Official",
          "Policy Researcher",
        ],
      },
      {
        id: createDegreeId("BA Fine Arts UP"),
        name: "Bachelor of Arts (Fine Arts)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 30,
        description: "Visual and creative arts",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Visual Arts", level: 4, isRequired: true },
        ],
        careerProspects: ["Artist", "Art Teacher", "Gallery Curator"],
      },
      {
        id: createDegreeId("BA Fine Arts 5 year UP"),
        name: "Bachelor of Arts (Fine Arts, 5-year programme)",
        faculty: "Humanities",
        duration: "5 years",
        apsRequirement: 26,
        description: "Extended fine arts programme",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Visual Arts", level: 3, isRequired: true },
        ],
        careerProspects: ["Artist", "Art Teacher", "Gallery Curator"],
      },
      {
        id: createDegreeId("BA Visual Studies UP"),
        name: "Bachelor of Arts (Visual Studies)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 30,
        description: "Visual culture and media studies",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Visual Arts", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Visual Artist",
          "Media Producer",
          "Cultural Analyst",
        ],
      },
      {
        id: createDegreeId("Bachelor Music UP"),
        name: "Bachelor of Music",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 30,
        description: "Music performance and theory",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Music", level: 5, isRequired: true },
        ],
        careerProspects: ["Musician", "Music Teacher", "Composer"],
      },
      {
        id: createDegreeId("Bachelor Music 5 year UP"),
        name: "Bachelor of Music (5-year programme)",
        faculty: "Humanities",
        duration: "5 years",
        apsRequirement: 26,
        description: "Extended music programme",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Music", level: 4, isRequired: true },
        ],
        careerProspects: ["Musician", "Music Teacher", "Composer"],
      },
      {
        id: createDegreeId("Bachelor Drama UP"),
        name: "Bachelor of Drama",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 30,
        description: "Theatre and dramatic arts",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Dramatic Arts", level: 4, isRequired: true },
        ],
        careerProspects: ["Actor", "Theatre Director", "Drama Teacher"],
      },
      {
        id: createDegreeId("Bachelor Drama 5 year UP"),
        name: "Bachelor of Drama (5-year programme)",
        faculty: "Humanities",
        duration: "5 years",
        apsRequirement: 26,
        description: "Extended drama programme",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Dramatic Arts", level: 3, isRequired: true },
        ],
        careerProspects: ["Actor", "Theatre Director", "Drama Teacher"],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Law UP"),
    name: "Faculty of Law",
    description: "Legal education and jurisprudence programs",
    degrees: [
      {
        id: createDegreeId("LLB UP"),
        name: "Bachelor of Laws (LLB)",
        faculty: "Law",
        duration: "4 years",
        apsRequirement: 35,
        description: "Professional legal qualification",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: ["Lawyer", "Attorney", "Legal Advisor"],
      },
      {
        id: createDegreeId("BA Law Humanities UP"),
        name: "Bachelor of Arts (Law)",
        faculty: "Law",
        duration: "3 years",
        apsRequirement: 34,
        description: "Liberal arts with legal foundation",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: ["Legal Assistant", "Paralegal", "Legal Researcher"],
      },
      {
        id: createDegreeId("BCom Law Economics UP"),
        name: "Bachelor of Commerce (Law)",
        faculty: "Law",
        duration: "3 years",
        apsRequirement: 32,
        description: "Commerce with legal foundation",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Corporate Legal Officer",
          "Legal Advisor",
          "Compliance Officer",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Theology and Religion UP"),
    name: "Faculty of Theology and Religion",
    description: "Theological and religious studies programs",
    degrees: [
      {
        id: createDegreeId("Bachelor Theology UP"),
        name: "Bachelor of Theology",
        faculty: "Theology and Religion",
        duration: "3 years",
        apsRequirement: 23,
        description: "Theological studies and ministry",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: true },
        ],
        careerProspects: ["Minister", "Chaplain", "Religious Counselor"],
      },
      {
        id: createDegreeId("Diploma Theology UP"),
        name: "Diploma in Theology",
        faculty: "Theology and Religion",
        duration: "3 years",
        apsRequirement: 23,
        description: "Practical theological training",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: true },
        ],
        careerProspects: ["Pastor", "Youth Minister", "Community Leader"],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Natural and Agricultural Sciences UP"),
    name: "Faculty of Natural and Agricultural Sciences",
    description: "Sciences, agriculture, and veterinary programs",
    degrees: [
      {
        id: createDegreeId("BSc Agriculture Agricultural Economics UP"),
        name: "Bachelor of Science in Agriculture (Agricultural Economics)",
        faculty: "Natural and Agricultural Sciences",
        duration: "4 years",
        apsRequirement: 32,
        description: "Agricultural economics and agribusiness",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Agricultural Economist",
          "Farm Manager",
          "Agribusiness Analyst",
        ],
      },
      {
        id: createDegreeId("BSc Agriculture Animal Science UP"),
        name: "Bachelor of Science in Agriculture (Animal Science)",
        faculty: "Natural and Agricultural Sciences",
        duration: "4 years",
        apsRequirement: 32,
        description: "Animal production and management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Animal Scientist",
          "Livestock Manager",
          "Veterinary Technician",
        ],
      },
      {
        id: createDegreeId("BSc Agriculture Applied Plant Soil Sciences UP"),
        name: "Bachelor of Science in Agriculture (Applied Plant and Soil Sciences)",
        faculty: "Natural and Agricultural Sciences",
        duration: "4 years",
        apsRequirement: 32,
        description: "Plant production and soil management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: ["Plant Scientist", "Soil Specialist", "Crop Advisor"],
      },
      {
        id: createDegreeId("BSc Agriculture Plant Pathology UP"),
        name: "Bachelor of Science in Agriculture (Plant Pathology)",
        faculty: "Natural and Agricultural Sciences",
        duration: "4 years",
        apsRequirement: 32,
        description: "Plant diseases and pathology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Plant Pathologist",
          "Crop Protection Specialist",
          "Agricultural Researcher",
        ],
      },
      {
        id: createDegreeId("BSc Food Management Culinary Science UP"),
        name: "Bachelor of Science in Food Management (Culinary Science)",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Culinary arts and food science",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Food Scientist",
          "Culinary Expert",
          "Food Product Developer",
        ],
      },
      {
        id: createDegreeId("BSc Food Management Nutritional Science UP"),
        name: "Bachelor of Science in Food Management (Nutritional Science)",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Nutrition and food science",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Nutritional Scientist",
          "Food Technologist",
          "Nutrition Consultant",
        ],
      },
      {
        id: createDegreeId("BSc Food Science UP"),
        name: "Bachelor of Science in Food Science",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Food technology and processing",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Food Scientist",
          "Quality Control Manager",
          "Food Safety Officer",
        ],
      },
      {
        id: createDegreeId("BSc Biochemistry UP"),
        name: "Bachelor of Science in Biochemistry",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Biochemical processes and analysis",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Biochemist",
          "Research Scientist",
          "Laboratory Analyst",
        ],
      },
      {
        id: createDegreeId("BSc Biotechnology UP"),
        name: "Bachelor of Science in Biotechnology",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Biological technology applications",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Biotechnologist",
          "Research Scientist",
          "Product Developer",
        ],
      },
      {
        id: createDegreeId("BSc Ecology UP"),
        name: "Bachelor of Science in Ecology",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Environmental and ecological systems",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Ecologist",
          "Environmental Consultant",
          "Conservation Officer",
        ],
      },
      {
        id: createDegreeId("BSc Entomology UP"),
        name: "Bachelor of Science in Entomology",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Insect science and pest management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Entomologist",
          "Pest Control Specialist",
          "Agricultural Advisor",
        ],
      },
      {
        id: createDegreeId("BSc Genetics UP"),
        name: "Bachelor of Science in Genetics",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Genetic analysis and biotechnology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Geneticist",
          "Research Scientist",
          "Genetic Counselor",
        ],
      },
      {
        id: createDegreeId("BSc Human Genetics UP"),
        name: "Bachelor of Science in Human Genetics",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Human genetic disorders and therapy",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Genetic Counselor",
          "Medical Researcher",
          "Clinical Geneticist",
        ],
      },
      {
        id: createDegreeId("BSc Human Physiology UP"),
        name: "Bachelor of Science in Human Physiology",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Human body systems and function",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Physiologist",
          "Medical Researcher",
          "Health Specialist",
        ],
      },
      {
        id: createDegreeId("BSc Human Physiology Genetics Psychology UP"),
        name: "Bachelor of Science in Human Physiology, Genetics and Psychology",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Interdisciplinary human sciences",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Research Scientist",
          "Health Specialist",
          "Medical Consultant",
        ],
      },
      {
        id: createDegreeId("BSc Medical Sciences UP"),
        name: "Bachelor of Science in Medical Sciences",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Medical and health sciences foundation",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Medical Researcher",
          "Laboratory Scientist",
          "Health Analyst",
        ],
      },
      {
        id: createDegreeId("BSc Microbiology UP"),
        name: "Bachelor of Science in Microbiology",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Microbial systems and applications",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Microbiologist",
          "Laboratory Analyst",
          "Quality Control Officer",
        ],
      },
      {
        id: createDegreeId("BSc Plant Science UP"),
        name: "Bachelor of Science in Plant Science",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Plant biology and production",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Plant Scientist",
          "Agricultural Researcher",
          "Crop Specialist",
        ],
      },
      {
        id: createDegreeId("BSc Zoology UP"),
        name: "Bachelor of Science in Zoology",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 32,
        description: "Animal biology and behavior",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Zoologist",
          "Wildlife Researcher",
          "Conservation Scientist",
        ],
      },
      {
        id: createDegreeId("BConsumerSc Clothing Retail Management UP"),
        name: "Bachelor of Consumer Science (Clothing Retail Management)",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 28,
        description: "Fashion and retail management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Retail Manager",
          "Fashion Buyer",
          "Merchandising Manager",
        ],
      },
      {
        id: createDegreeId("BConsumerSc Food Management UP"),
        name: "Bachelor of Consumer Science (Food Management)",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 28,
        description: "Food service and hospitality management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Food Service Manager",
          "Restaurant Manager",
          "Hospitality Manager",
        ],
      },
      {
        id: createDegreeId("BSc Actuarial Financial Mathematics UP"),
        name: "Bachelor of Science in Actuarial and Financial Mathematics",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 36,
        description: "Actuarial science and risk management",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
        ],
        careerProspects: ["Actuary", "Risk Analyst", "Financial Analyst"],
      },
      {
        id: createDegreeId("BSc Mathematics UP"),
        name: "Bachelor of Science in Mathematics",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 34,
        description: "Pure and applied mathematics",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Mathematician",
          "Data Analyst",
          "Mathematics Teacher",
        ],
      },
      {
        id: createDegreeId("BSc Applied Mathematics UP"),
        name: "Bachelor of Science in Applied Mathematics",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 34,
        description: "Mathematical applications in science and industry",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Applied Mathematician",
          "Systems Analyst",
          "Research Scientist",
        ],
      },
      {
        id: createDegreeId("BSc Mathematical Statistics UP"),
        name: "Bachelor of Science in Mathematical Statistics",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 34,
        description: "Statistical theory and applications",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Statistician",
          "Data Scientist",
          "Market Researcher",
        ],
      },
      {
        id: createDegreeId("BSc Chemistry UP"),
        name: "Bachelor of Science in Chemistry",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 34,
        description: "Chemical analysis and research",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Chemist",
          "Laboratory Analyst",
          "Research Scientist",
        ],
      },
      {
        id: createDegreeId("BSc Environmental Engineering Geology UP"),
        name: "Bachelor of Science in Environmental and Engineering Geology",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 34,
        description: "Geological engineering and environmental studies",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Geologist",
          "Environmental Consultant",
          "Mining Geologist",
        ],
      },
      {
        id: createDegreeId("BSc Geography Geography Environmental Science UP"),
        name: "Bachelor of Science in Geography (Geography and Environmental Science)",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 34,
        description: "Physical geography and environmental systems",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Geography", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Geographer",
          "Environmental Scientist",
          "GIS Specialist",
        ],
      },
      {
        id: createDegreeId("BSc Geoinformatics UP"),
        name: "Bachelor of Science in Geoinformatics",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 34,
        description: "Geographic information systems and spatial analysis",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Geography", level: 4, isRequired: true },
        ],
        careerProspects: ["GIS Specialist", "Spatial Analyst", "Cartographer"],
      },
      {
        id: createDegreeId("BSc Geology UP"),
        name: "Bachelor of Science in Geology",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 34,
        description: "Earth sciences and geological processes",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: ["Geologist", "Mining Specialist", "Earth Scientist"],
      },
      {
        id: createDegreeId("BSc Meteorology UP"),
        name: "Bachelor of Science in Meteorology",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 34,
        description: "Weather and atmospheric sciences",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Meteorologist",
          "Weather Forecaster",
          "Climate Scientist",
        ],
      },
      {
        id: createDegreeId("BSc Physics UP"),
        name: "Bachelor of Science in Physics",
        faculty: "Natural and Agricultural Sciences",
        duration: "3 years",
        apsRequirement: 34,
        description: "Physical sciences and theoretical physics",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: ["Physicist", "Research Scientist", "Science Teacher"],
      },
      // Extended Programmes
      {
        id: createDegreeId("BSc Mathematics 4 year UP"),
        name: "Bachelor of Science in Mathematics (4-year)",
        faculty: "Natural and Agricultural Sciences",
        duration: "4 years",
        apsRequirement: 32,
        description: "Extended mathematics programme",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Mathematician",
          "Data Analyst",
          "Mathematics Teacher",
        ],
      },
      {
        id: createDegreeId("BSc Chemistry 4 year UP"),
        name: "Bachelor of Science in Chemistry (4-year)",
        faculty: "Natural and Agricultural Sciences",
        duration: "4 years",
        apsRequirement: 32,
        description: "Extended chemistry programme",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Chemist",
          "Laboratory Analyst",
          "Research Scientist",
        ],
      },
      {
        id: createDegreeId("BSc Geoinformatics 4 year UP"),
        name: "Bachelor of Science in Geoinformatics (4-year)",
        faculty: "Natural and Agricultural Sciences",
        duration: "4 years",
        apsRequirement: 32,
        description: "Extended geoinformatics programme",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Geography", level: 4, isRequired: true },
        ],
        careerProspects: ["GIS Specialist", "Spatial Analyst", "Cartographer"],
      },
      {
        id: createDegreeId("BSc Geology 4 year UP"),
        name: "Bachelor of Science in Geology (4-year)",
        faculty: "Natural and Agricultural Sciences",
        duration: "4 years",
        apsRequirement: 32,
        description: "Extended geology programme",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: ["Geologist", "Mining Specialist", "Earth Scientist"],
      },
      {
        id: createDegreeId("BSc Meteorology 4 year UP"),
        name: "Bachelor of Science in Meteorology (4-year)",
        faculty: "Natural and Agricultural Sciences",
        duration: "4 years",
        apsRequirement: 32,
        description: "Extended meteorology programme",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Meteorologist",
          "Weather Forecaster",
          "Climate Scientist",
        ],
      },
      {
        id: createDegreeId("BSc Physics 4 year UP"),
        name: "Bachelor of Science in Physics (4-year)",
        faculty: "Natural and Agricultural Sciences",
        duration: "4 years",
        apsRequirement: 32,
        description: "Extended physics programme",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: ["Physicist", "Research Scientist", "Science Teacher"],
      },
      {
        id: createDegreeId(
          "BSc Agriculture Applied Plant Soil Sciences 5 year UP",
        ),
        name: "Bachelor of Science in Agriculture (Applied Plant and Soil Sciences, 5-year)",
        faculty: "Natural and Agricultural Sciences",
        duration: "5 years",
        apsRequirement: 32,
        description: "Extended agricultural sciences programme",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: ["Plant Scientist", "Soil Specialist", "Crop Advisor"],
      },
      {
        id: createDegreeId("BSc Agriculture Plant Pathology 5 year UP"),
        name: "Bachelor of Science in Agriculture (Plant Pathology, 5-year)",
        faculty: "Natural and Agricultural Sciences",
        duration: "5 years",
        apsRequirement: 32,
        description: "Extended plant pathology programme",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Plant Pathologist",
          "Crop Protection Specialist",
          "Agricultural Researcher",
        ],
      },
      {
        id: createDegreeId("BSc Ecology 5 year UP"),
        name: "Bachelor of Science in Ecology (5-year)",
        faculty: "Natural and Agricultural Sciences",
        duration: "5 years",
        apsRequirement: 32,
        description: "Extended ecology programme",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Ecologist",
          "Environmental Consultant",
          "Conservation Officer",
        ],
      },
      {
        id: createDegreeId("BSc Human Physiology 5 year UP"),
        name: "Bachelor of Science in Human Physiology (5-year)",
        faculty: "Natural and Agricultural Sciences",
        duration: "5 years",
        apsRequirement: 32,
        description: "Extended human physiology programme",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Physiologist",
          "Medical Researcher",
          "Health Specialist",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Veterinary Science UP"),
    name: "Faculty of Veterinary Science",
    description: "Veterinary medicine and animal health programs",
    degrees: [
      {
        id: createDegreeId("Bachelor Veterinary Science UP"),
        name: "Bachelor of Veterinary Science",
        faculty: "Veterinary Science",
        duration: "6 years",
        apsRequirement: 34,
        description: "Veterinary medicine and animal care",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Veterinarian",
          "Animal Health Specialist",
          "Veterinary Researcher",
        ],
      },
      {
        id: createDegreeId("Bachelor Veterinary Nursing UP"),
        name: "Bachelor of Veterinary Nursing",
        faculty: "Veterinary Science",
        duration: "3 years",
        apsRequirement: 24,
        description: "Veterinary nursing and animal care",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Veterinary Nurse",
          "Animal Care Specialist",
          "Veterinary Assistant",
        ],
      },
    ],
  },
];
