import { Faculty } from "@/types/university";
import { createDegreeId, createFacultyId } from "./base";

// Vaal University of Technology (VUT) - Faculty Data - Complete Update
export const VUT_FACULTIES: Faculty[] = [
  {
    id: createFacultyId("Faculty of Applied and Computer Sciences VUT"),
    name: "Faculty of Applied & Computer Sciences",
    description: "Applied sciences, computing, and technology programs",
    degrees: [
      {
        id: createDegreeId("Diploma Analytical Chemistry VUT"),
        name: "Diploma in Analytical Chemistry",
        faculty: "Applied & Computer Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Analytical chemistry diploma with Maths",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Analytical Chemist",
          "Laboratory Technician",
          "Quality Control Analyst",
        ],
      },
      {
        id: createDegreeId("Diploma Agricultural Management VUT"),
        name: "Diploma in Agricultural Management",
        faculty: "Applied & Computer Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Agricultural management with Maths",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Agricultural Manager",
          "Farm Supervisor",
          "Agricultural Consultant",
        ],
      },
      {
        id: createDegreeId("Diploma Agricultural Management Math Lit VUT"),
        name: "Diploma in Agricultural Management - Math Lit",
        faculty: "Applied & Computer Sciences",
        duration: "3 years",
        apsRequirement: 25,
        description: "Agricultural management with Mathematical Literacy",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematical Literacy", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Agricultural Manager",
          "Farm Supervisor",
          "Agricultural Consultant",
        ],
      },
      {
        id: createDegreeId("Diploma Biotechnology VUT"),
        name: "Diploma in Biotechnology",
        faculty: "Applied & Computer Sciences",
        duration: "3 years",
        apsRequirement: 23,
        description: "Biotechnology program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Biotechnologist",
          "Research Technician",
          "Quality Control Specialist",
        ],
      },
      {
        id: createDegreeId("Diploma Information Technology VUT"),
        name: "Diploma in Information Technology",
        faculty: "Applied & Computer Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "IT diploma with Maths or Tech Maths",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Technical Mathematics", level: 4, isRequired: false },
          { name: "Information Technology", level: 3, isRequired: false },
        ],
        careerProspects: [
          "IT Technician",
          "Software Developer",
          "Network Administrator",
        ],
      },
      {
        id: createDegreeId("Diploma Information Technology Math Lit VUT"),
        name: "Diploma in Information Technology - Math Lit",
        faculty: "Applied & Computer Sciences",
        duration: "3 years",
        apsRequirement: 26,
        description: "IT diploma with Mathematical Literacy",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematical Literacy", level: 4, isRequired: true },
          { name: "Information Technology", level: 3, isRequired: false },
        ],
        careerProspects: [
          "IT Technician",
          "Software Developer",
          "Network Administrator",
        ],
      },
      {
        id: createDegreeId("Diploma Environmental Science VUT"),
        name: "Diploma in Environmental Science",
        faculty: "Applied & Computer Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Environmental science with Maths",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Geography", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Environmental Scientist",
          "Conservation Officer",
          "Environmental Consultant",
        ],
      },
      {
        id: createDegreeId("Diploma NonDestructive Testing VUT"),
        name: "Diploma in Non-Destructive Testing",
        faculty: "Applied & Computer Sciences",
        duration: "3 years",
        apsRequirement: 19,
        description: "Non-destructive testing technology",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Physical Sciences", level: 3, isRequired: true },
        ],
        careerProspects: [
          "NDT Technician",
          "Quality Inspector",
          "Materials Tester",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Engineering and Technology VUT"),
    name: "Faculty of Engineering & Technology",
    description: "Engineering technology programs across multiple disciplines",
    degrees: [
      {
        id: createDegreeId("Diploma Chemical Engineering VUT"),
        name: "Diploma in Chemical Engineering",
        faculty: "Engineering & Technology",
        duration: "3 years",
        apsRequirement: 24,
        description: "Chemical engineering diploma requiring 24 APS with Maths",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Chemical Engineering Technician",
          "Process Technician",
          "Quality Control Engineer",
        ],
      },
      {
        id: createDegreeId("Diploma Civil Engineering VUT"),
        name: "Diploma in Civil Engineering",
        faculty: "Engineering & Technology",
        duration: "3 years",
        apsRequirement: 24,
        description: "Civil engineering diploma requiring 24 APS with Maths",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Civil Engineering Technician",
          "Construction Supervisor",
          "Infrastructure Technician",
        ],
      },
      {
        id: createDegreeId("Diploma Electronic Engineering VUT"),
        name: "Diploma in Electronic Engineering",
        faculty: "Engineering & Technology",
        duration: "3 years",
        apsRequirement: 24,
        description:
          "Electronic engineering diploma requiring 24 APS with Maths",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Electronic Engineering Technician",
          "Electronics Technician",
          "Telecommunications Technician",
        ],
      },
      {
        id: createDegreeId("Diploma Power Engineering VUT"),
        name: "Diploma in Power Engineering",
        faculty: "Engineering & Technology",
        duration: "3 years",
        apsRequirement: 24,
        description: "Power engineering diploma requiring 24 APS with Maths",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Power Systems Technician",
          "Electrical Technician",
          "Energy Engineer",
        ],
      },
      {
        id: createDegreeId("Diploma Process Control Engineering VUT"),
        name: "Diploma in Process Control Engineering",
        faculty: "Engineering & Technology",
        duration: "3 years",
        apsRequirement: 24,
        description:
          "Process control engineering diploma requiring 24 APS with Maths",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Process Control Technician",
          "Automation Technician",
          "Instrumentation Engineer",
        ],
      },
      {
        id: createDegreeId("Diploma Computer Systems Engineering VUT"),
        name: "Diploma in Computer Systems Engineering",
        faculty: "Engineering & Technology",
        duration: "3 years",
        apsRequirement: 24,
        description:
          "Computer systems engineering diploma requiring 24 APS with Maths",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
          { name: "Information Technology", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Computer Systems Engineer",
          "Network Engineer",
          "IT Systems Specialist",
        ],
      },
      {
        id: createDegreeId("Diploma Industrial Engineering VUT"),
        name: "Diploma in Industrial Engineering",
        faculty: "Engineering & Technology",
        duration: "3 years",
        apsRequirement: 24,
        description:
          "Industrial engineering diploma requiring 24 APS with Maths",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Industrial Engineering Technician",
          "Operations Supervisor",
          "Quality Engineer",
        ],
      },
      {
        id: createDegreeId("Diploma Mechanical Engineering VUT"),
        name: "Diploma in Mechanical Engineering",
        faculty: "Engineering & Technology",
        duration: "3 years",
        apsRequirement: 24,
        description:
          "Mechanical engineering diploma requiring 24 APS with Maths",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Mechanical Engineering Technician",
          "Manufacturing Technologist",
          "Maintenance Engineer",
        ],
      },
      {
        id: createDegreeId("Diploma Metallurgical Engineering VUT"),
        name: "Diploma in Metallurgical Engineering",
        faculty: "Engineering & Technology",
        duration: "3 years",
        apsRequirement: 24,
        description:
          "Metallurgical engineering diploma requiring 24 APS with Maths",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Metallurgical Technician",
          "Materials Engineer",
          "Mining Technologist",
        ],
      },
      {
        id: createDegreeId("Extended Engineering Courses VUT"),
        name: "Extended Engineering Courses",
        faculty: "Engineering & Technology",
        duration: "4 years",
        apsRequirement: 22,
        description: "Extended engineering programs requiring 22 APS",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Physical Sciences", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Engineering Technician",
          "Technical Supervisor",
          "Project Coordinator",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Human Sciences VUT"),
    name: "Faculty of Human Sciences",
    description: "Creative arts, design, tourism, and social science programs",
    degrees: [
      {
        id: createDegreeId("Diploma Fashion VUT"),
        name: "Diploma in Fashion",
        faculty: "Human Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Fashion design with Maths",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Visual Arts", level: 3, isRequired: false },
        ],
        careerProspects: ["Fashion Designer", "Pattern Maker", "Stylist"],
      },
      {
        id: createDegreeId("Diploma Fashion Math Lit VUT"),
        name: "Diploma in Fashion - Math Lit/Tech Maths",
        faculty: "Human Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Fashion design with Math Lit/Tech Maths",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematical Literacy", level: 4, isRequired: true },
          { name: "Technical Mathematics", level: 4, isRequired: false },
          { name: "Visual Arts", level: 3, isRequired: false },
        ],
        careerProspects: ["Fashion Designer", "Pattern Maker", "Stylist"],
      },
      {
        id: createDegreeId("Diploma Photography VUT"),
        name: "Diploma in Photography",
        faculty: "Human Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Photography",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Visual Arts", level: 4, isRequired: true },
        ],
        careerProspects: ["Photographer", "Photo Editor", "Visual Artist"],
      },
      {
        id: createDegreeId("Diploma Photography Math Lit VUT"),
        name: "Diploma in Photography - Math Lit/Tech Maths",
        faculty: "Human Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Photography with Math Lit/Tech Maths",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematical Literacy", level: 4, isRequired: true },
          { name: "Technical Mathematics", level: 4, isRequired: false },
          { name: "Visual Arts", level: 4, isRequired: true },
        ],
        careerProspects: ["Photographer", "Photo Editor", "Visual Artist"],
      },
      {
        id: createDegreeId("Diploma Graphic Design VUT"),
        name: "Diploma in Graphic Design",
        faculty: "Human Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Graphic design",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Visual Arts", level: 4, isRequired: true },
          { name: "Information Technology", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Graphic Designer",
          "Web Designer",
          "Creative Director",
        ],
      },
      {
        id: createDegreeId("Diploma Graphic Design Math Lit VUT"),
        name: "Diploma in Graphic Design - Math Lit/Tech Maths",
        faculty: "Human Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Graphic design with Math Lit/Tech Maths",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematical Literacy", level: 4, isRequired: true },
          { name: "Technical Mathematics", level: 4, isRequired: false },
          { name: "Visual Arts", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Graphic Designer",
          "Web Designer",
          "Creative Director",
        ],
      },
      {
        id: createDegreeId("Diploma Fine Art VUT"),
        name: "Diploma in Fine Art",
        faculty: "Human Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Fine art",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Visual Arts", level: 4, isRequired: true },
        ],
        careerProspects: ["Artist", "Art Teacher", "Gallery Curator"],
      },
      {
        id: createDegreeId("Diploma Fine Art Math Lit VUT"),
        name: "Diploma in Fine Art - Math Lit/Tech Maths",
        faculty: "Human Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Fine art with Math Lit/Tech Maths",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematical Literacy", level: 4, isRequired: true },
          { name: "Technical Mathematics", level: 4, isRequired: false },
          { name: "Visual Arts", level: 4, isRequired: true },
        ],
        careerProspects: ["Artist", "Art Teacher", "Gallery Curator"],
      },
      {
        id: createDegreeId("Diploma Food Service Management VUT"),
        name: "Diploma in Food Service Management",
        faculty: "Human Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Food service management with Maths",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Sciences", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Food Service Manager",
          "Restaurant Manager",
          "Catering Manager",
        ],
      },
      {
        id: createDegreeId("Diploma Food Service Management Math Lit VUT"),
        name: "Diploma in Food Service Management - Math Lit/Tech Maths",
        faculty: "Human Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Food service management with Math Lit/Tech Maths",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematical Literacy", level: 4, isRequired: true },
          { name: "Technical Mathematics", level: 4, isRequired: false },
          { name: "Life Sciences", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Food Service Manager",
          "Restaurant Manager",
          "Catering Manager",
        ],
      },
      {
        id: createDegreeId("Diploma Tourism Management VUT"),
        name: "Diploma in Tourism Management",
        faculty: "Human Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Tourism management with Maths",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Geography", level: 3, isRequired: false },
        ],
        careerProspects: ["Tourism Manager", "Tour Guide", "Travel Consultant"],
      },
      {
        id: createDegreeId("Diploma Tourism Management Math Lit VUT"),
        name: "Diploma in Tourism Management - Math Lit/Tech Maths",
        faculty: "Human Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Tourism management with Math Lit/Tech Maths",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematical Literacy", level: 4, isRequired: true },
          { name: "Technical Mathematics", level: 4, isRequired: false },
          { name: "Geography", level: 3, isRequired: false },
        ],
        careerProspects: ["Tourism Manager", "Tour Guide", "Travel Consultant"],
      },
      {
        id: createDegreeId("Diploma Ecotourism Management VUT"),
        name: "Diploma in Ecotourism Management",
        faculty: "Human Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Ecotourism management with Maths",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Geography", level: 3, isRequired: false },
          { name: "Life Sciences", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Ecotourism Manager",
          "Conservation Guide",
          "Environmental Educator",
        ],
      },
      {
        id: createDegreeId("Diploma Ecotourism Management Math Lit VUT"),
        name: "Diploma in Ecotourism Management - Math Lit/Tech Maths",
        faculty: "Human Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Ecotourism management with Math Lit/Tech Maths",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematical Literacy", level: 4, isRequired: true },
          { name: "Technical Mathematics", level: 4, isRequired: false },
          { name: "Geography", level: 3, isRequired: false },
          { name: "Life Sciences", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Ecotourism Manager",
          "Conservation Guide",
          "Environmental Educator",
        ],
      },
      {
        id: createDegreeId("Diploma Public Relations VUT"),
        name: "Diploma in Public Relations",
        faculty: "Human Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Public relations with Maths",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Public Relations Officer",
          "Communications Specialist",
          "Marketing Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma Public Relations Math Lit VUT"),
        name: "Diploma in Public Relations - Math Lit/Tech Maths",
        faculty: "Human Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Public relations with Math Lit/Tech Maths",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematical Literacy", level: 4, isRequired: true },
          { name: "Technical Mathematics", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Public Relations Officer",
          "Communications Specialist",
          "Marketing Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma Legal Assistance VUT"),
        name: "Diploma in Legal Assistance",
        faculty: "Human Sciences",
        duration: "3 years",
        apsRequirement: 23,
        description: "Legal assistance with Maths",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: ["Legal Assistant", "Paralegal", "Court Officer"],
      },
      {
        id: createDegreeId("Diploma Legal Assistance Math Lit VUT"),
        name: "Diploma in Legal Assistance - Math Lit/Tech Maths",
        faculty: "Human Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Legal assistance with Math Lit/Tech Maths",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematical Literacy", level: 4, isRequired: true },
          { name: "Technical Mathematics", level: 4, isRequired: false },
        ],
        careerProspects: ["Legal Assistant", "Paralegal", "Court Officer"],
      },
      {
        id: createDegreeId("Diploma Labour Law VUT"),
        name: "Diploma in Labour Law",
        faculty: "Human Sciences",
        duration: "3 years",
        apsRequirement: 23,
        description: "Labour law with Maths",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Labour Law Specialist",
          "HR Legal Advisor",
          "Labour Relations Officer",
        ],
      },
      {
        id: createDegreeId("Diploma Labour Law Math Lit VUT"),
        name: "Diploma in Labour Law - Math Lit/Tech Maths",
        faculty: "Human Sciences",
        duration: "3 years",
        apsRequirement: 24,
        description: "Labour law with Math Lit/Tech Maths",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematical Literacy", level: 4, isRequired: true },
          { name: "Technical Mathematics", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Labour Law Specialist",
          "HR Legal Advisor",
          "Labour Relations Officer",
        ],
      },
      {
        id: createDegreeId("Diploma Policing VUT"),
        name: "Diploma in Policing",
        faculty: "Human Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Policing with Maths",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: ["Police Officer", "Detective", "Security Manager"],
      },
      {
        id: createDegreeId("Diploma Policing Math Lit VUT"),
        name: "Diploma in Policing - Math Lit/Tech Maths",
        faculty: "Human Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Policing with Math Lit/Tech Maths",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematical Literacy", level: 4, isRequired: true },
          { name: "Technical Mathematics", level: 4, isRequired: false },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: ["Police Officer", "Detective", "Security Manager"],
      },
      {
        id: createDegreeId("Diploma Safety Management VUT"),
        name: "Diploma in Safety Management",
        faculty: "Human Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Safety management with Maths",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Safety Manager",
          "Risk Assessment Specialist",
          "Occupational Health Officer",
        ],
      },
      {
        id: createDegreeId("Diploma Safety Management Math Lit VUT"),
        name: "Diploma in Safety Management - Math Lit/Tech Maths",
        faculty: "Human Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Safety management with Math Lit/Tech Maths",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematical Literacy", level: 4, isRequired: true },
          { name: "Technical Mathematics", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Safety Manager",
          "Risk Assessment Specialist",
          "Occupational Health Officer",
        ],
      },
      {
        id: createDegreeId("BEd Senior Phase FET Teaching VUT"),
        name: "BEd (Senior Phase & FET teaching)",
        faculty: "Human Sciences",
        duration: "4 years",
        apsRequirement: 22,
        description: "Teacher education with Maths",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: false },
        ],
        careerProspects: [
          "High School Teacher",
          "Subject Specialist",
          "Education Coordinator",
        ],
      },
      {
        id: createDegreeId("BEd Senior Phase FET Teaching Math Lit VUT"),
        name: "BEd (Senior Phase & FET teaching) - Math Lit",
        faculty: "Human Sciences",
        duration: "4 years",
        apsRequirement: 24,
        description: "Teacher education with Math Lit",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematical Literacy", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: false },
        ],
        careerProspects: [
          "High School Teacher",
          "Subject Specialist",
          "Education Coordinator",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Management Sciences VUT"),
    name: "Faculty of Management Sciences",
    description: "Business management, finance, and commerce programs",
    degrees: [
      {
        id: createDegreeId("Diploma Financial Info Systems VUT"),
        name: "Diploma in Financial Info Systems",
        faculty: "Management Sciences",
        duration: "3 years",
        apsRequirement: 20,
        description: "Financial information systems with Maths",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Information Technology", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Financial Systems Analyst",
          "Data Processor",
          "Information Manager",
        ],
      },
      {
        id: createDegreeId("Diploma Financial Info Systems Math Lit VUT"),
        name: "Diploma in Financial Info Systems - Math Lit/Tech Maths",
        faculty: "Management Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Financial information systems with Math Lit/Tech Maths",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematical Literacy", level: 4, isRequired: true },
          { name: "Technical Mathematics", level: 4, isRequired: false },
          { name: "Information Technology", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Financial Systems Analyst",
          "Data Processor",
          "Information Manager",
        ],
      },
      {
        id: createDegreeId("Diploma Cost Management Accounting VUT"),
        name: "Diploma in Cost & Management Accounting",
        faculty: "Management Sciences",
        duration: "3 years",
        apsRequirement: 20,
        description: "Cost and management accounting with Maths",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Cost Accountant",
          "Management Accountant",
          "Financial Analyst",
        ],
      },
      {
        id: createDegreeId("Diploma Cost Management Accounting Math Lit VUT"),
        name: "Diploma in Cost & Management Accounting - Math Lit/Tech Maths",
        faculty: "Management Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Cost and management accounting with Math Lit/Tech Maths",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematical Literacy", level: 4, isRequired: true },
          { name: "Technical Mathematics", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Cost Accountant",
          "Management Accountant",
          "Financial Analyst",
        ],
      },
      {
        id: createDegreeId("Diploma Internal Auditing VUT"),
        name: "Diploma in Internal Auditing",
        faculty: "Management Sciences",
        duration: "3 years",
        apsRequirement: 20,
        description: "Internal auditing with Maths",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Internal Auditor",
          "Risk Analyst",
          "Compliance Officer",
        ],
      },
      {
        id: createDegreeId("Diploma Internal Auditing Math Lit VUT"),
        name: "Diploma in Internal Auditing - Math Lit/Tech Maths",
        faculty: "Management Sciences",
        duration: "3 years",
        apsRequirement: 23,
        description: "Internal auditing with Math Lit/Tech Maths",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematical Literacy", level: 4, isRequired: true },
          { name: "Technical Mathematics", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Internal Auditor",
          "Risk Analyst",
          "Compliance Officer",
        ],
      },
      {
        id: createDegreeId("Diploma Human Resources Management VUT"),
        name: "Diploma in Human Resources Management",
        faculty: "Management Sciences",
        duration: "3 years",
        apsRequirement: 20,
        description: "Human resources management with Maths",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "HR Assistant",
          "Recruitment Coordinator",
          "Training Officer",
        ],
      },
      {
        id: createDegreeId("Diploma Human Resources Management Math Lit VUT"),
        name: "Diploma in Human Resources Management - Math Lit/Tech Maths",
        faculty: "Management Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Human resources management with Math Lit/Tech Maths",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematical Literacy", level: 4, isRequired: true },
          { name: "Technical Mathematics", level: 4, isRequired: false },
        ],
        careerProspects: [
          "HR Assistant",
          "Recruitment Coordinator",
          "Training Officer",
        ],
      },
      {
        id: createDegreeId("Diploma Logistics Supply Chain Management VUT"),
        name: "Diploma in Logistics & Supply Chain Management",
        faculty: "Management Sciences",
        duration: "3 years",
        apsRequirement: 20,
        description: "Logistics and supply chain management with Maths",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Logistics Coordinator",
          "Supply Chain Analyst",
          "Warehouse Manager",
        ],
      },
      {
        id: createDegreeId(
          "Diploma Logistics Supply Chain Management Math Lit VUT",
        ),
        name: "Diploma in Logistics & Supply Chain Management - Math Lit/Tech Maths",
        faculty: "Management Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description:
          "Logistics and supply chain management with Math Lit/Tech Maths",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematical Literacy", level: 4, isRequired: true },
          { name: "Technical Mathematics", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Logistics Coordinator",
          "Supply Chain Analyst",
          "Warehouse Manager",
        ],
      },
      {
        id: createDegreeId("Diploma Marketing VUT"),
        name: "Diploma in Marketing",
        faculty: "Management Sciences",
        duration: "3 years",
        apsRequirement: 20,
        description: "Marketing with Maths",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Marketing Coordinator",
          "Sales Representative",
          "Brand Assistant",
        ],
      },
      {
        id: createDegreeId("Diploma Marketing Math Lit VUT"),
        name: "Diploma in Marketing - Math Lit/Tech Maths",
        faculty: "Management Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Marketing with Math Lit/Tech Maths",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematical Literacy", level: 4, isRequired: true },
          { name: "Technical Mathematics", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Marketing Coordinator",
          "Sales Representative",
          "Brand Assistant",
        ],
      },
      {
        id: createDegreeId("Diploma Retail Business Management VUT"),
        name: "Diploma in Retail Business Management",
        faculty: "Management Sciences",
        duration: "3 years",
        apsRequirement: 20,
        description: "Retail business management with Maths",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Retail Manager",
          "Store Manager",
          "Merchandising Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma Retail Business Management Math Lit VUT"),
        name: "Diploma in Retail Business Management - Math Lit/Tech Maths",
        faculty: "Management Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Retail business management with Math Lit/Tech Maths",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematical Literacy", level: 4, isRequired: true },
          { name: "Technical Mathematics", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Retail Manager",
          "Store Manager",
          "Merchandising Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma Sport Management VUT"),
        name: "Diploma in Sport Management",
        faculty: "Management Sciences",
        duration: "3 years",
        apsRequirement: 20,
        description: "Sport management with Maths",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Sports Manager",
          "Sports Administrator",
          "Event Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma Sport Management Math Lit VUT"),
        name: "Diploma in Sport Management - Math Lit/Tech Maths",
        faculty: "Management Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Sport management with Math Lit/Tech Maths",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematical Literacy", level: 4, isRequired: true },
          { name: "Technical Mathematics", level: 4, isRequired: false },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Sports Manager",
          "Sports Administrator",
          "Event Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma Operations Management VUT"),
        name: "Diploma in Operations Management",
        faculty: "Management Sciences",
        duration: "3 years",
        apsRequirement: 23,
        description: "Operations management with Maths",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Operations Manager",
          "Production Supervisor",
          "Quality Manager",
        ],
      },
    ],
  },
];
