import { Faculty } from "@/types/university";
import { createDegreeId, createFacultyId } from "./base";

// University of the Witwatersrand (Wits) - Faculty Data
export const WITS_FACULTIES: Faculty[] = [
  {
    id: createFacultyId("Faculty of Commerce Law Management WITS"),
    name: "Faculty of Commerce, Law & Management",
    description: "Business, law, and management programs",
    degrees: [
      {
        id: createDegreeId("BCom General WITS"),
        name: "Bachelor of Commerce (General)",
        faculty: "Commerce, Law & Management",
        duration: "3 years",
        apsRequirement: 38,
        description: "General commerce and business studies",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Business Analyst",
          "Financial Officer",
          "Management Trainee",
        ],
      },
      {
        id: createDegreeId("BCom Information Systems WITS"),
        name: "Bachelor of Commerce (Information Systems)",
        faculty: "Commerce, Law & Management",
        duration: "3 years",
        apsRequirement: 38,
        description: "Business information systems and technology",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Systems Analyst",
          "IT Business Analyst",
          "Information Systems Manager",
        ],
      },
      {
        id: createDegreeId("BCom Politics Philosophy Economics WITS"),
        name: "Bachelor of Commerce (Politics, Philosophy and Economics)",
        faculty: "Commerce, Law & Management",
        duration: "3 years",
        apsRequirement: 38,
        description: "Interdisciplinary PPE with commerce focus",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Policy Analyst",
          "Political Economic Researcher",
          "Government Advisor",
        ],
      },
      {
        id: createDegreeId("Bachelor Accounting Science WITS"),
        name: "Bachelor of Accounting Science",
        faculty: "Commerce, Law & Management",
        duration: "3 years",
        apsRequirement: 44,
        description: "Professional accounting qualification",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Accounting", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Chartered Accountant",
          "Auditor",
          "Financial Manager",
        ],
      },
      {
        id: createDegreeId("BCom Accounting WITS"),
        name: "Bachelor of Commerce (Accounting)",
        faculty: "Commerce, Law & Management",
        duration: "3 years",
        apsRequirement: 38,
        description: "Commerce with accounting specialization",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Accounting", level: 4, isRequired: true },
        ],
        careerProspects: ["Accountant", "Financial Analyst", "Bookkeeper"],
      },
      {
        id: createDegreeId("Bachelor Economic Science WITS"),
        name: "Bachelor of Economic Science",
        faculty: "Commerce, Law & Management",
        duration: "3 years",
        apsRequirement: 42,
        description: "Economics and economic analysis",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
        ],
        careerProspects: ["Economist", "Economic Analyst", "Policy Researcher"],
      },
      {
        id: createDegreeId("BCom with Law WITS"),
        name: "Bachelor of Commerce with Law",
        faculty: "Commerce, Law & Management",
        duration: "3 years",
        apsRequirement: 43,
        description: "Commerce with legal foundation",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Corporate Legal Officer",
          "Legal Advisor",
          "Compliance Officer",
        ],
      },
      {
        id: createDegreeId("LLB 4 year stream WITS"),
        name: "Bachelor of Laws (LLB, 4-year stream)",
        faculty: "Commerce, Law & Management",
        duration: "4 years",
        apsRequirement: 46,
        description: "Professional legal qualification",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: ["Lawyer", "Attorney", "Legal Consultant"],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Engineering Built Environment WITS"),
    name: "Faculty of Engineering and the Built Environment",
    description: "Engineering, architecture, and construction programs",
    degrees: [
      {
        id: createDegreeId("BEng Chemical Engineering WITS"),
        name: "Bachelor of Engineering (Chemical Engineering)",
        faculty: "Engineering and the Built Environment",
        duration: "4 years",
        apsRequirement: 42,
        description: "Chemical process engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Chemical Engineer",
          "Process Engineer",
          "Plant Manager",
        ],
      },
      {
        id: createDegreeId("BEng Metallurgy Materials Engineering WITS"),
        name: "Bachelor of Engineering (Metallurgy and Materials Engineering)",
        faculty: "Engineering and the Built Environment",
        duration: "4 years",
        apsRequirement: 42,
        description: "Materials and metallurgical engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Metallurgical Engineer",
          "Materials Engineer",
          "Research Engineer",
        ],
      },
      {
        id: createDegreeId("BEng Civil Engineering WITS"),
        name: "Bachelor of Engineering (Civil Engineering)",
        faculty: "Engineering and the Built Environment",
        duration: "4 years",
        apsRequirement: 42,
        description: "Infrastructure and construction engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Civil Engineer",
          "Structural Engineer",
          "Project Manager",
        ],
      },
      {
        id: createDegreeId("BEng Electrical Engineering WITS"),
        name: "Bachelor of Engineering (Electrical Engineering)",
        faculty: "Engineering and the Built Environment",
        duration: "4 years",
        apsRequirement: 42,
        description: "Electrical power and systems engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Electrical Engineer",
          "Power Systems Engineer",
          "Control Engineer",
        ],
      },
      {
        id: createDegreeId("BEng Biomedical Engineering WITS"),
        name: "Bachelor of Engineering (Biomedical Engineering)",
        faculty: "Engineering and the Built Environment",
        duration: "4 years",
        apsRequirement: 42,
        description: "Medical device and biomedical engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Biomedical Engineer",
          "Medical Device Engineer",
          "Clinical Engineer",
        ],
      },
      {
        id: createDegreeId("Bachelor Digital Arts WITS"),
        name: "Bachelor of Digital Arts",
        faculty: "Engineering and the Built Environment",
        duration: "3 years",
        apsRequirement: 42,
        description: "Digital media and interactive arts",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Digital Artist",
          "Multimedia Designer",
          "Game Developer",
        ],
      },
      {
        id: createDegreeId("BEng Aeronautical Engineering WITS"),
        name: "Bachelor of Engineering (Aeronautical Engineering)",
        faculty: "Engineering and the Built Environment",
        duration: "4 years",
        apsRequirement: 42,
        description: "Aircraft and aerospace engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Aeronautical Engineer",
          "Aerospace Engineer",
          "Aircraft Designer",
        ],
      },
      {
        id: createDegreeId("BEng Industrial Engineering WITS"),
        name: "Bachelor of Engineering (Industrial Engineering)",
        faculty: "Engineering and the Built Environment",
        duration: "4 years",
        apsRequirement: 42,
        description: "Manufacturing and operations engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Industrial Engineer",
          "Operations Manager",
          "Quality Engineer",
        ],
      },
      {
        id: createDegreeId("BEng Mechanical Engineering WITS"),
        name: "Bachelor of Engineering (Mechanical Engineering)",
        faculty: "Engineering and the Built Environment",
        duration: "4 years",
        apsRequirement: 42,
        description: "Mechanical systems and design engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Mechanical Engineer",
          "Design Engineer",
          "Manufacturing Engineer",
        ],
      },
      {
        id: createDegreeId("BEng Mining Engineering WITS"),
        name: "Bachelor of Engineering (Mining Engineering)",
        faculty: "Engineering and the Built Environment",
        duration: "4 years",
        apsRequirement: 42,
        description: "Mining and mineral extraction engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Mining Engineer",
          "Mine Manager",
          "Extraction Engineer",
        ],
      },
      {
        id: createDegreeId("Bachelor Architectural Studies WITS"),
        name: "Bachelor of Architectural Studies",
        faculty: "Engineering and the Built Environment",
        duration: "3 years",
        apsRequirement: 34,
        description:
          "Architectural design and planning (written/graphic exercise required)",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: ["Architect", "Design Consultant", "Urban Planner"],
      },
      {
        id: createDegreeId("Bachelor Urban Regional Planning WITS"),
        name: "Bachelor of Urban and Regional Planning",
        faculty: "Engineering and the Built Environment",
        duration: "4 years",
        apsRequirement: 36,
        description: "Urban and regional planning",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Town Planner",
          "Urban Designer",
          "Planning Consultant",
        ],
      },
      {
        id: createDegreeId("Bachelor Construction Studies WITS"),
        name: "Bachelor of Construction Studies",
        faculty: "Engineering and the Built Environment",
        duration: "4 years",
        apsRequirement: 36,
        description: "Construction management and economics",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Construction Manager",
          "Project Manager",
          "Quantity Surveyor",
        ],
      },
      {
        id: createDegreeId("Bachelor Property Studies WITS"),
        name: "Bachelor of Property Studies",
        faculty: "Engineering and the Built Environment",
        duration: "3 years",
        apsRequirement: 36,
        description: "Property management and development",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Property Manager",
          "Real Estate Developer",
          "Property Valuer",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Health Sciences WITS"),
    name: "Faculty of Health Sciences",
    description: "Medical and health-related programs",
    degrees: [
      {
        id: createDegreeId("Bachelor Health Sciences WITS"),
        name: "Bachelor of Health Sciences (Biomedical Sciences/Biokinetics/Health Systems Sciences)",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 38,
        description: "Health sciences foundation (NBT required)",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Health Scientist",
          "Biokinetecist",
          "Health Systems Analyst",
        ],
      },
      {
        id: createDegreeId("Bachelor Clinical Medical Practice WITS"),
        name: "Bachelor of Clinical Medical Practice",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 34,
        description: "Clinical medical practice (NBT required)",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Clinical Associate",
          "Medical Practitioner",
          "Healthcare Provider",
        ],
      },
      {
        id: createDegreeId("Bachelor Medicine Surgery WITS"),
        name: "Bachelor of Medicine and Surgery (MBChB)",
        faculty: "Health Sciences",
        duration: "6 years",
        apsRequirement: 42,
        description:
          "Medical practice and surgery (NBT and job shadowing required)",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Life Sciences", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: ["Medical Doctor", "Surgeon", "Medical Specialist"],
      },
      {
        id: createDegreeId("Bachelor Dental Science WITS"),
        name: "Bachelor of Dental Science",
        faculty: "Health Sciences",
        duration: "5 years",
        apsRequirement: 42,
        description: "Dental medicine (Life + Physical Sciences required)",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: ["Dentist", "Oral Surgeon", "Dental Specialist"],
      },
      {
        id: createDegreeId("Bachelor Oral Health Sciences WITS"),
        name: "Bachelor of Oral Health Sciences",
        faculty: "Health Sciences",
        duration: "3 years",
        apsRequirement: 34,
        description: "Oral health and dental therapy (NBT required)",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Oral Hygienist",
          "Dental Therapist",
          "Oral Health Educator",
        ],
      },
      {
        id: createDegreeId("Bachelor Nursing WITS"),
        name: "Bachelor of Nursing",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 34,
        description: "Professional nursing practice",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Professional Nurse",
          "Nurse Manager",
          "Clinical Specialist",
        ],
      },
      {
        id: createDegreeId("Bachelor Pharmacy WITS"),
        name: "Bachelor of Pharmacy",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 42,
        description: "Pharmaceutical sciences and practice",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Life Sciences", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Pharmacist",
          "Clinical Pharmacist",
          "Pharmaceutical Researcher",
        ],
      },
      {
        id: createDegreeId("Bachelor Occupational Therapy WITS"),
        name: "Bachelor of Occupational Therapy",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 34,
        description: "Occupational therapy practice (NBT required)",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Life Sciences", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Occupational Therapist",
          "Rehabilitation Specialist",
          "Community Health Worker",
        ],
      },
      {
        id: createDegreeId("Bachelor Physiotherapy WITS"),
        name: "Bachelor of Physiotherapy",
        faculty: "Health Sciences",
        duration: "4 years",
        apsRequirement: 42,
        description: "Physical therapy and rehabilitation (NBT required)",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Life Sciences", level: 6, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Physiotherapist",
          "Sports Therapist",
          "Rehabilitation Specialist",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Humanities WITS"),
    name: "Faculty of Humanities",
    description: "Arts, education, and social sciences programs",
    degrees: [
      {
        id: createDegreeId("BA General WITS"),
        name: "Bachelor of Arts (BA)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 36,
        description: "General humanities and liberal arts",
        subjects: [{ name: "English", level: 5, isRequired: true }],
        careerProspects: [
          "Administrative Officer",
          "Communications Officer",
          "Research Assistant",
        ],
      },
      {
        id: createDegreeId("BA Law WITS"),
        name: "Bachelor of Arts (Law)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 43,
        description: "Liberal arts with legal foundation",
        subjects: [
          { name: "English", level: 6, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: ["Legal Assistant", "Paralegal", "Legal Researcher"],
      },
      {
        id: createDegreeId("BA Digital Arts WITS"),
        name: "Bachelor of Arts (Digital Arts)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 36,
        description:
          "Digital media and interactive arts (Portfolio/audition required)",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Visual Arts", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Digital Artist",
          "Multimedia Designer",
          "Creative Director",
        ],
      },
      {
        id: createDegreeId("BA Theatre Performance WITS"),
        name: "Bachelor of Arts (Theatre and Performance)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 34,
        description: "Theatre and performance arts (Audition required)",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Dramatic Arts", level: 4, isRequired: true },
        ],
        careerProspects: ["Actor", "Theatre Director", "Performance Artist"],
      },
      {
        id: createDegreeId("BA Film Television WITS"),
        name: "Bachelor of Arts (Film and Television)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 34,
        description:
          "Film and television production (Written assignment required)",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Dramatic Arts", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Film Director",
          "Television Producer",
          "Media Producer",
        ],
      },
      {
        id: createDegreeId("BA Fine Arts WITS"),
        name: "Bachelor of Arts (Fine Arts)",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 34,
        description: "Visual and creative arts (Portfolio required)",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Visual Arts", level: 4, isRequired: true },
        ],
        careerProspects: ["Artist", "Art Teacher", "Gallery Curator"],
      },
      {
        id: createDegreeId("Bachelor Music WITS"),
        name: "Bachelor of Music",
        faculty: "Humanities",
        duration: "3 years",
        apsRequirement: 34,
        description: "Music performance and theory (Audition required)",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Music", level: 5, isRequired: true },
        ],
        careerProspects: ["Musician", "Music Teacher", "Composer"],
      },
      {
        id: createDegreeId("BEd Foundation Phase WITS"),
        name: "Bachelor of Education (Foundation Phase Teaching)",
        faculty: "Humanities",
        duration: "4 years",
        apsRequirement: 37,
        description: "Foundation phase teaching (Grades R-3)",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Foundation Phase Teacher",
          "Primary School Teacher",
          "Educational Specialist",
        ],
      },
      {
        id: createDegreeId("BEd Intermediate Phase WITS"),
        name: "Bachelor of Education (Intermediate Phase Teaching)",
        faculty: "Humanities",
        duration: "4 years",
        apsRequirement: 37,
        description: "Intermediate phase teaching (Grades 4-6)",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Intermediate Phase Teacher",
          "Primary School Teacher",
          "Subject Specialist",
        ],
      },
      {
        id: createDegreeId("BEd Senior Phase FET WITS"),
        name: "Bachelor of Education (Senior Phase & FET Teaching)",
        faculty: "Humanities",
        duration: "4 years",
        apsRequirement: 37,
        description: "Senior phase and FET teaching (Grades 7-12)",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "High School Teacher",
          "Subject Specialist",
          "Educational Consultant",
        ],
      },
      {
        id: createDegreeId("BA Speech Language Pathology WITS"),
        name: "Bachelor of Arts (Speech-Language Pathology)",
        faculty: "Humanities",
        duration: "4 years",
        apsRequirement: 34,
        description: "Speech and language therapy (NBT required)",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Speech Therapist",
          "Language Therapist",
          "Communication Specialist",
        ],
      },
      {
        id: createDegreeId("BA Audiology WITS"),
        name: "Bachelor of Arts (Audiology)",
        faculty: "Humanities",
        duration: "4 years",
        apsRequirement: 34,
        description: "Hearing and auditory rehabilitation (NBT required)",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Audiologist",
          "Hearing Aid Specialist",
          "Auditory Therapist",
        ],
      },
      {
        id: createDegreeId("Bachelor Social Work WITS"),
        name: "Bachelor of Social Work",
        faculty: "Humanities",
        duration: "4 years",
        apsRequirement: 34,
        description: "Social work practice and community development",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Social Worker",
          "Community Developer",
          "Family Counselor",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Science WITS"),
    name: "Faculty of Science",
    description: "Natural sciences, mathematics, and computer science programs",
    degrees: [
      {
        id: createDegreeId("BSc General WITS"),
        name: "Bachelor of Science (General)",
        faculty: "Science",
        duration: "3 years",
        apsRequirement: 42,
        description: "General science foundation",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Science Officer",
          "Research Assistant",
          "Laboratory Technician",
        ],
      },
      {
        id: createDegreeId("BSc Biological Sciences WITS"),
        name: "Bachelor of Science (Biological Sciences)",
        faculty: "Science",
        duration: "3 years",
        apsRequirement: 43,
        description: "Biological and life sciences",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Life Sciences", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Biologist",
          "Research Scientist",
          "Environmental Consultant",
        ],
      },
      {
        id: createDegreeId("BSc Geographical Archaeological Sciences WITS"),
        name: "Bachelor of Science (Geographical and Archaeological Sciences)",
        faculty: "Science",
        duration: "3 years",
        apsRequirement: 42,
        description: "Geography and archaeological sciences",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Geography", level: 4, isRequired: true },
        ],
        careerProspects: ["Geographer", "Archaeologist", "GIS Specialist"],
      },
      {
        id: createDegreeId("BSc Geospatial Sciences WITS"),
        name: "Bachelor of Science (Geospatial Sciences)",
        faculty: "Science",
        duration: "3 years",
        apsRequirement: 42,
        description: "Geographic information systems and spatial analysis",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Geography", level: 4, isRequired: true },
        ],
        careerProspects: ["GIS Specialist", "Spatial Analyst", "Cartographer"],
      },
      {
        id: createDegreeId("BSc Environmental Studies WITS"),
        name: "Bachelor of Science (Environmental Studies)",
        faculty: "Science",
        duration: "3 years",
        apsRequirement: 42,
        description: "Environmental science and management",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Environmental Scientist",
          "Conservation Officer",
          "Environmental Consultant",
        ],
      },
      {
        id: createDegreeId("BSc Geological Sciences WITS"),
        name: "Bachelor of Science (Geological Sciences)",
        faculty: "Science",
        duration: "3 years",
        apsRequirement: 42,
        description: "Earth sciences and geological processes",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: ["Geologist", "Mining Specialist", "Earth Scientist"],
      },
      {
        id: createDegreeId("BSc Actuarial Science WITS"),
        name: "Bachelor of Science (Actuarial Science)",
        faculty: "Science",
        duration: "3 years",
        apsRequirement: 42,
        description: "Actuarial mathematics and risk management",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
        ],
        careerProspects: ["Actuary", "Risk Analyst", "Financial Analyst"],
      },
      {
        id: createDegreeId("BSc Computational Applied Mathematics WITS"),
        name: "Bachelor of Science (Computational and Applied Mathematics)",
        faculty: "Science",
        duration: "3 years",
        apsRequirement: 44,
        description: "Advanced mathematical applications and computation",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Applied Mathematician",
          "Data Scientist",
          "Systems Analyst",
        ],
      },
      {
        id: createDegreeId("BSc Computer Science WITS"),
        name: "Bachelor of Science (Computer Science)",
        faculty: "Science",
        duration: "3 years",
        apsRequirement: 44,
        description: "Computer science and programming",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Software Developer",
          "Computer Scientist",
          "Systems Analyst",
        ],
      },
      {
        id: createDegreeId("BSc Mathematical Sciences WITS"),
        name: "Bachelor of Science (Mathematical Sciences)",
        faculty: "Science",
        duration: "3 years",
        apsRequirement: 42,
        description: "Pure and applied mathematics",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
        ],
        careerProspects: ["Mathematician", "Statistician", "Data Analyst"],
      },
      {
        id: createDegreeId("BSc Physical Sciences Chemistry Physics WITS"),
        name: "Bachelor of Science (Physical Sciences: Chemistry/Physics)",
        faculty: "Science",
        duration: "3 years",
        apsRequirement: 42,
        description: "Physical sciences - chemistry and physics",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: ["Physicist", "Chemist", "Research Scientist"],
      },
      {
        id: createDegreeId("BSc Chemistry Chemical Engineering WITS"),
        name: "Bachelor of Science (Chemistry with Chemical Engineering)",
        faculty: "Science",
        duration: "3 years",
        apsRequirement: 43,
        description: "Chemistry with chemical engineering applications",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Chemical Engineer",
          "Process Chemist",
          "Research Scientist",
        ],
      },
      {
        id: createDegreeId("BSc Materials Science WITS"),
        name: "Bachelor of Science (Materials Science)",
        faculty: "Science",
        duration: "3 years",
        apsRequirement: 43,
        description: "Materials science and engineering",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: [
          "Materials Scientist",
          "Materials Engineer",
          "Product Developer",
        ],
      },
      {
        id: createDegreeId("BSc Astronomy Astrophysics WITS"),
        name: "Bachelor of Science (Astronomy and Astrophysics)",
        faculty: "Science",
        duration: "3 years",
        apsRequirement: 43,
        description: "Astronomical and astrophysical sciences",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 6, isRequired: true },
          { name: "Physical Sciences", level: 6, isRequired: true },
        ],
        careerProspects: ["Astronomer", "Astrophysicist", "Space Scientist"],
      },
    ],
  },
];
