import { Faculty } from "@/types/university";
import { createDegreeId, createFacultyId } from "./base";

// Walter Sisulu University (WSU) - Faculty Data
export const WSU_FACULTIES: Faculty[] = [
  {
    id: createFacultyId("Faculty of Education WSU"),
    name: "Faculty of Education",
    description: "Teacher education and educational programs",
    degrees: [
      {
        id: createDegreeId("BEd Foundation Phase Teaching WSU"),
        name: "Bachelor of Education in Foundation Phase Teaching",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description: "Teacher education for foundation phase (Grades R-3)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Foundation Phase Teacher",
          "Early Childhood Educator",
        ],
      },
      {
        id: createDegreeId("BEd Senior Phase FET EMS WSU"),
        name: "Bachelor of Education in Senior Phase and Further Education and Training Teaching (Economic & Management Sciences)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description: "Teacher education for EMS subjects",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Economics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "High School Teacher",
          "EMS Specialist",
          "Education Coordinator",
        ],
      },
      {
        id: createDegreeId("BEd Senior Phase FET Consumer Management WSU"),
        name: "Bachelor of Education in Senior Phase and Further Education and Training Teaching (Consumer & Management Sciences)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description: "Teacher education for consumer and management sciences",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: false },
        ],
        careerProspects: [
          "High School Teacher",
          "Consumer Sciences Teacher",
          "Education Coordinator",
        ],
      },
      {
        id: createDegreeId("BEd Senior Phase FET Creative Arts WSU"),
        name: "Bachelor of Education in Senior Phase and Further Education and Training Teaching (Creative Arts)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description: "Teacher education for creative arts subjects",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Visual Arts", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Arts Teacher",
          "Creative Arts Educator",
          "Education Coordinator",
        ],
      },
      {
        id: createDegreeId("BEd Senior Phase FET Humanities WSU"),
        name: "Bachelor of Education in Senior Phase and Further Education and Training Teaching (Humanities)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description: "Teacher education for humanities subjects",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "History", level: 4, isRequired: true },
          { name: "Geography", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Humanities Teacher",
          "History Teacher",
          "Education Coordinator",
        ],
      },
      {
        id: createDegreeId("BEd Senior Phase FET Languages WSU"),
        name: "Bachelor of Education in Senior Phase and Further Education and Training Teaching (Languages)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description: "Teacher education for language subjects",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Additional Language", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Language Teacher",
          "English Teacher",
          "Education Coordinator",
        ],
      },
      {
        id: createDegreeId(
          "BEd Senior Phase FET Mathematics Science Technology WSU",
        ),
        name: "Bachelor of Education in Senior Phase and Further Education and Training Teaching (Mathematics, Science & Technology)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description:
          "Teacher education for mathematics, science and technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Mathematics Teacher",
          "Science Teacher",
          "Technology Teacher",
        ],
      },
      {
        id: createDegreeId("BEd Senior Phase FET Technical Vocational WSU"),
        name: "Bachelor of Education in Senior Phase and Further Education and Training Teaching (Technical and Vocational Education)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description: "Teacher education for technical and vocational subjects",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Technology", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Technical Education Teacher",
          "Vocational Training Instructor",
          "Skills Development Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma Adult Community Education Training WSU"),
        name: "Diploma in Adult and Community Education and Training (ACET)",
        faculty: "Education",
        duration: "3 years",
        apsRequirement: 21,
        description: "Adult and community education training",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Adult Educator",
          "Community Education Coordinator",
          "Training Specialist",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Law Humanities and Social Sciences WSU"),
    name: "Faculty of Law, Humanities and Social Sciences",
    description: "Law, arts, social sciences, and creative programs",
    degrees: [
      {
        id: createDegreeId("Diploma Fine Art WSU"),
        name: "Diploma in Fine Art",
        faculty: "Law, Humanities and Social Sciences",
        duration: "3 years",
        apsRequirement: 20,
        description: "Fine arts and visual arts program",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Visual Arts", level: 4, isRequired: true },
        ],
        careerProspects: ["Artist", "Art Teacher", "Gallery Curator"],
      },
      {
        id: createDegreeId("Advanced Diploma Fine Art WSU"),
        name: "Advanced Diploma in Fine Art",
        faculty: "Law, Humanities and Social Sciences",
        duration: "1 year",
        apsRequirement: 20,
        description: "Advanced fine arts specialization",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Visual Arts", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Professional Artist",
          "Art Director",
          "Creative Consultant",
        ],
      },
      {
        id: createDegreeId("Diploma Fashion WSU"),
        name: "Diploma in Fashion",
        faculty: "Law, Humanities and Social Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Fashion design and garment technology",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Visual Arts", level: 3, isRequired: false },
        ],
        careerProspects: ["Fashion Designer", "Pattern Maker", "Stylist"],
      },
      {
        id: createDegreeId("Bachelor of Arts WSU"),
        name: "Bachelor of Arts",
        faculty: "Law, Humanities and Social Sciences",
        duration: "3 years",
        apsRequirement: 27,
        description: "Liberal arts and humanities program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: false },
        ],
        careerProspects: ["Social Worker", "Researcher", "Community Developer"],
      },
      {
        id: createDegreeId("Bachelor of Social Science WSU"),
        name: "Bachelor of Social Science",
        faculty: "Law, Humanities and Social Sciences",
        duration: "3 years",
        apsRequirement: 27,
        description: "Social sciences and human behavior studies",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Social Scientist",
          "Research Analyst",
          "Policy Advisor",
        ],
      },
      {
        id: createDegreeId("Bachelor of Social Science Extended WSU"),
        name: "Bachelor of Social Science (Extended Curriculum Programme)",
        faculty: "Law, Humanities and Social Sciences",
        duration: "4 years",
        apsRequirement: 26,
        description: "Extended social sciences program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Social Scientist",
          "Research Analyst",
          "Policy Advisor",
        ],
      },
      {
        id: createDegreeId("Bachelor of Laws LLB WSU"),
        name: "Bachelor of Laws (LLB)",
        faculty: "Law, Humanities and Social Sciences",
        duration: "4 years",
        apsRequirement: 28,
        description: "Professional law degree",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: false },
        ],
        careerProspects: ["Lawyer", "Legal Advisor", "Magistrate"],
      },
      {
        id: createDegreeId("Bachelor of Social Work WSU"),
        name: "Bachelor of Social Work",
        faculty: "Law, Humanities and Social Sciences",
        duration: "4 years",
        apsRequirement: 28,
        description: "Professional social work program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: false },
        ],
        careerProspects: [
          "Social Worker",
          "Community Developer",
          "Case Manager",
        ],
      },
      {
        id: createDegreeId("Bachelor of Psychology WSU"),
        name: "Bachelor of Psychology",
        faculty: "Law, Humanities and Social Sciences",
        duration: "3 years",
        apsRequirement: 28,
        description: "Comprehensive psychology program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: ["Psychologist", "Counselor", "Research Analyst"],
      },
    ],
  },
  {
    id: createFacultyId(
      "Faculty of Management and Public Administration Sciences WSU",
    ),
    name: "Faculty of Management and Public Administration Sciences",
    description:
      "Business management, public administration, and communication programs",
    degrees: [
      {
        id: createDegreeId("Bachelor of Administration WSU"),
        name: "Bachelor of Administration",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "Public and private sector administration",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: ["Administrator", "Government Official", "Manager"],
      },
      {
        id: createDegreeId("Diploma Administrative Management WSU"),
        name: "Diploma in Administrative Management",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Administrative management and office procedures",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Administrative Manager",
          "Office Manager",
          "Executive Assistant",
        ],
      },
      {
        id: createDegreeId("Diploma Journalism WSU"),
        name: "Diploma in Journalism",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Journalism and media studies",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: ["Journalist", "Reporter", "News Editor"],
      },
      {
        id: createDegreeId("Diploma Public Relations WSU"),
        name: "Diploma in Public Relations",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Public relations and communications",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Public Relations Officer",
          "Communications Specialist",
          "Marketing Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma Public Management WSU"),
        name: "Diploma in Public Management",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Public sector management and governance",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Public Manager",
          "Government Official",
          "Municipal Officer",
        ],
      },
      {
        id: createDegreeId("Diploma Policing WSU"),
        name: "Diploma in Policing",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Police studies and law enforcement",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: ["Police Officer", "Detective", "Security Manager"],
      },
      {
        id: createDegreeId("Diploma Local Government Finance WSU"),
        name: "Diploma in Local Government Finance",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Municipal finance and local government",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Municipal Finance Officer",
          "Budget Analyst",
          "Local Government Administrator",
        ],
      },
      {
        id: createDegreeId("Diploma Management WSU"),
        name: "Diploma in Management",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "General management principles and practices",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: ["Manager", "Supervisor", "Team Leader"],
      },
      {
        id: createDegreeId("Diploma Small Business Management WSU"),
        name: "Diploma in Small Business Management",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Small business operations and entrepreneurship",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Entrepreneur",
          "Business Owner",
          "Small Business Consultant",
        ],
      },
      {
        id: createDegreeId("Diploma Office Management Technology WSU"),
        name: "Diploma in Office Management and Technology",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Office management with technology integration",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Information Technology", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Office Manager",
          "Administrative Assistant",
          "Executive Secretary",
        ],
      },
      {
        id: createDegreeId("Diploma Human Resources Management WSU"),
        name: "Diploma in Human Resources Management",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Human resources and personnel management",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "HR Assistant",
          "Recruitment Coordinator",
          "Training Officer",
        ],
      },
      {
        id: createDegreeId("Diploma Tourism Management WSU"),
        name: "Diploma in Tourism Management",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Tourism industry management and operations",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Geography", level: 3, isRequired: false },
        ],
        careerProspects: ["Tourism Manager", "Tour Guide", "Travel Consultant"],
      },
      {
        id: createDegreeId("Diploma Hospitality Management WSU"),
        name: "Diploma in Hospitality Management",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Hospitality industry management",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Hotel Manager",
          "Restaurant Manager",
          "Event Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma Sport Management WSU"),
        name: "Diploma in Sport Management",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Sports industry management and administration",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Sports Manager",
          "Sports Administrator",
          "Event Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma Financial Information Systems WSU"),
        name: "Diploma in Financial Information Systems",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Financial systems and information management",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Information Technology", level: 3, isRequired: false },
        ],
        careerProspects: [
          "Financial Systems Analyst",
          "Data Processor",
          "Information Manager",
        ],
      },
      {
        id: createDegreeId("Diploma Accountancy WSU"),
        name: "Diploma in Accountancy",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Basic accounting principles and practices",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Accounting Clerk",
          "Bookkeeper",
          "Financial Assistant",
        ],
      },
      {
        id: createDegreeId("Diploma Internal Auditing WSU"),
        name: "Diploma in Internal Auditing",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Internal auditing and risk management",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Internal Auditor",
          "Risk Analyst",
          "Compliance Officer",
        ],
      },
      {
        id: createDegreeId("Higher Certificate Versatile Broadcasting WSU"),
        name: "Higher Certificate in Versatile Broadcasting",
        faculty: "Management and Public Administration Sciences",
        duration: "1 year",
        apsRequirement: 20,
        description: "Broadcasting and media production",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Additional Language", level: 3, isRequired: true },
        ],
        careerProspects: ["Broadcaster", "Radio Presenter", "Media Producer"],
      },
    ],
  },
];
