import { Faculty } from "@/types/university";
import { createDegreeId, createFacultyId } from "./base";

// Walter Sisulu University (WSU) - Faculty Data
export const WSU_FACULTIES: Faculty[] = [
  {
    id: createFacultyId("Faculty of Education WSU"),
    name: "Faculty of Education",
    description: "Teacher education and educational development programs",
    degrees: [
      {
        id: createDegreeId("BEd Foundation Phase Teaching WSU"),
        name: "Bachelor of Education in Foundation Phase Teaching",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description: "Foundation phase teaching (Grades R-3)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Foundation Phase Teacher",
          "Early Childhood Educator",
          "Educational Specialist",
        ],
      },
      {
        id: createDegreeId(
          "BEd Senior Phase FET Economic Management Sciences WSU",
        ),
        name: "Bachelor of Education in Senior Phase and Further Education and Training Teaching (Economic & Management Sciences)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description:
          "Senior phase and FET teaching in economic and management sciences",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Accounting", level: 4, isRequired: false },
        ],
        careerProspects: [
          "High School Teacher",
          "Commerce Teacher",
          "Subject Specialist",
        ],
      },
      {
        id: createDegreeId(
          "BEd Senior Phase FET Consumer Management Sciences WSU",
        ),
        name: "Bachelor of Education in Senior Phase and Further Education and Training Teaching (Consumer and Management Sciences)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description:
          "Senior phase and FET teaching in consumer and management sciences",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "High School Teacher",
          "Consumer Studies Teacher",
          "Subject Specialist",
        ],
      },
      {
        id: createDegreeId("BEd Senior Phase FET Creative Arts WSU"),
        name: "Bachelor of Education in Senior Phase and Further Education and Training Teaching (Creative Arts)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description: "Senior phase and FET teaching in creative arts",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Visual Arts", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Art Teacher",
          "Creative Arts Educator",
          "Subject Specialist",
        ],
      },
      {
        id: createDegreeId("BEd Senior Phase FET Humanities WSU"),
        name: "Bachelor of Education in Senior Phase and Further Education and Training Teaching (Humanities)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description: "Senior phase and FET teaching in humanities",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "History", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Humanities Teacher",
          "History Teacher",
          "Subject Specialist",
        ],
      },
      {
        id: createDegreeId("BEd Senior Phase FET Languages WSU"),
        name: "Bachelor of Education in Senior Phase and Further Education and Training Teaching (Languages)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description: "Senior phase and FET teaching in languages",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Home Language", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Language Teacher",
          "English Teacher",
          "Second Language Specialist",
        ],
      },
      {
        id: createDegreeId(
          "BEd Senior Phase FET Mathematics Science Technology WSU",
        ),
        name: "Bachelor of Education in Senior Phase and Further Education and Training Teaching (Mathematics, Science & Technology)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description:
          "Senior phase and FET teaching in mathematics, science and technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Mathematics Teacher",
          "Science Teacher",
          "Technology Teacher",
        ],
      },
      {
        id: createDegreeId(
          "BEd Senior Phase FET Technical Vocational Education WSU",
        ),
        name: "Bachelor of Education in Senior Phase and Further Education and Training Teaching (Technical and Vocational Education)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description:
          "Senior phase and FET teaching in technical and vocational education (complex criteria based on subject combinations)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Technical Teacher",
          "Vocational Educator",
          "Skills Trainer",
        ],
      },
      {
        id: createDegreeId(
          "Diploma Adult Community Education Training ACET WSU",
        ),
        name: "Diploma in Adult and Community Education and Training (ACET)",
        faculty: "Education",
        duration: "3 years",
        apsRequirement: 21,
        description: "Adult and community education training",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Adult Educator",
          "Community Education Coordinator",
          "Training Facilitator",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Law Humanities Social Sciences WSU"),
    name: "Faculty of Law, Humanities and Social Sciences",
    description: "Legal, humanities, and social science programs",
    degrees: [
      {
        id: createDegreeId("Diploma Fine Art WSU"),
        name: "Diploma in Fine Art",
        faculty: "Law, Humanities and Social Sciences",
        duration: "3 years",
        apsRequirement: 20,
        description: "Fine arts and visual expression",
        subjects: [
          { name: "English", level: 3, isRequired: true },
          { name: "Visual Arts", level: 4, isRequired: true },
        ],
        careerProspects: ["Artist", "Art Teacher", "Gallery Assistant"],
      },
      {
        id: createDegreeId("Advanced Diploma Fine Art WSU"),
        name: "Advanced Diploma in Fine Art",
        faculty: "Law, Humanities and Social Sciences",
        duration: "1 year",
        apsRequirement: 20,
        description: "Advanced fine arts qualification",
        subjects: [{ name: "Fine Arts Diploma", level: 5, isRequired: true }],
        careerProspects: [
          "Professional Artist",
          "Art Instructor",
          "Creative Director",
        ],
      },
      {
        id: createDegreeId("Diploma Fashion WSU"),
        name: "Diploma in Fashion",
        faculty: "Law, Humanities and Social Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Fashion design and production",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Visual Arts", level: 4, isRequired: false },
        ],
        careerProspects: ["Fashion Designer", "Fashion Producer", "Stylist"],
      },
      {
        id: createDegreeId("Bachelor Arts WSU"),
        name: "Bachelor of Arts",
        faculty: "Law, Humanities and Social Sciences",
        duration: "3 years",
        apsRequirement: 27,
        description: "General arts and humanities",
        subjects: [{ name: "English", level: 4, isRequired: true }],
        careerProspects: [
          "Administrative Officer",
          "Communications Officer",
          "Research Assistant",
        ],
      },
      {
        id: createDegreeId("Bachelor Social Science WSU"),
        name: "Bachelor of Social Science",
        faculty: "Law, Humanities and Social Sciences",
        duration: "3 years",
        apsRequirement: 27,
        description: "Social sciences and community studies",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Social Researcher",
          "Community Worker",
          "Social Services Officer",
        ],
      },
      {
        id: createDegreeId("Bachelor Social Science Extended WSU"),
        name: "Bachelor of Social Science (Extended Curriculum Programme)",
        faculty: "Law, Humanities and Social Sciences",
        duration: "4 years",
        apsRequirement: 26,
        description: "Extended social sciences program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Social Researcher",
          "Community Worker",
          "Social Services Officer",
        ],
      },
      {
        id: createDegreeId("LLB WSU"),
        name: "Bachelor of Laws (LLB)",
        faculty: "Law, Humanities and Social Sciences",
        duration: "4 years",
        apsRequirement: 28,
        description: "Professional legal qualification",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: ["Lawyer", "Attorney", "Legal Consultant"],
      },
      {
        id: createDegreeId("Bachelor Social Work WSU"),
        name: "Bachelor of Social Work",
        faculty: "Law, Humanities and Social Sciences",
        duration: "4 years",
        apsRequirement: 28,
        description: "Social work practice and community development",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Social Worker",
          "Community Developer",
          "Family Counselor",
        ],
      },
      {
        id: createDegreeId("Bachelor Psychology WSU"),
        name: "Bachelor of Psychology",
        faculty: "Law, Humanities and Social Sciences",
        duration: "3 years",
        apsRequirement: 28,
        description: "Psychology studies and mental health",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: ["Psychologist", "Counselor", "Researcher"],
      },
    ],
  },
  {
    id: createFacultyId(
      "Faculty of Management Public Administration Sciences WSU",
    ),
    name: "Faculty of Management and Public Administration Sciences",
    description: "Management, administration, and business programs",
    degrees: [
      {
        id: createDegreeId("Bachelor Administration WSU"),
        name: "Bachelor of Administration",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "Public and business administration",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Administrator",
          "Public Service Officer",
          "Management Trainee",
        ],
      },
      {
        id: createDegreeId("Diploma Administrative Management WSU"),
        name: "Diploma in Administrative Management",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Administrative management and office administration",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Administrative Manager",
          "Office Manager",
          "Executive Assistant",
        ],
      },
      {
        id: createDegreeId("Diploma Journalism WSU"),
        name: "Diploma in Journalism",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Journalism and media communication",
        subjects: [{ name: "English", level: 4, isRequired: true }],
        careerProspects: ["Journalist", "Reporter", "News Writer"],
      },
      {
        id: createDegreeId("Diploma Public Relations WSU"),
        name: "Diploma in Public Relations",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Public relations and communication",
        subjects: [{ name: "English", level: 4, isRequired: true }],
        careerProspects: [
          "Public Relations Officer",
          "Communications Coordinator",
          "Media Liaison",
        ],
      },
      {
        id: createDegreeId("Diploma Public Management WSU"),
        name: "Diploma in Public Management",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Public sector management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Public Manager",
          "Government Officer",
          "Municipal Administrator",
        ],
      },
      {
        id: createDegreeId("Diploma Policing WSU"),
        name: "Diploma in Policing",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Policing and law enforcement",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: ["Police Officer", "Detective", "Security Manager"],
      },
      {
        id: createDegreeId("Diploma Local Government Finance WSU"),
        name: "Diploma in Local Government Finance",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Local government financial management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Municipal Finance Officer",
          "Local Government Accountant",
          "Budget Analyst",
        ],
      },
      {
        id: createDegreeId("Diploma Management WSU"),
        name: "Diploma in Management",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "General management principles",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: ["Manager", "Supervisor", "Team Leader"],
      },
      {
        id: createDegreeId("Diploma Small Business Management WSU"),
        name: "Diploma in Small Business Management",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Small business management and entrepreneurship",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Small Business Owner",
          "Business Consultant",
          "Entrepreneur",
        ],
      },
      {
        id: createDegreeId("Diploma Office Management Technology WSU"),
        name: "Diploma in Office Management and Technology",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Office management with technology integration",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Office Manager",
          "Administrative Coordinator",
          "Executive Assistant",
        ],
      },
      {
        id: createDegreeId("Diploma Human Resources Management WSU"),
        name: "Diploma in Human Resources Management",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Human resource management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "HR Officer",
          "Recruitment Coordinator",
          "Personnel Administrator",
        ],
      },
      {
        id: createDegreeId("Diploma Tourism Management WSU"),
        name: "Diploma in Tourism Management",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Tourism management and hospitality",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: ["Tourism Manager", "Travel Agent", "Tour Guide"],
      },
      {
        id: createDegreeId("Diploma Hospitality Management WSU"),
        name: "Diploma in Hospitality Management",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Hospitality and hotel management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Hotel Manager",
          "Restaurant Manager",
          "Event Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma Sport Management WSU"),
        name: "Diploma in Sport Management",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Sports management and administration",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Sports Manager",
          "Event Coordinator",
          "Recreation Officer",
        ],
      },
      {
        id: createDegreeId("Diploma Financial Information Systems WSU"),
        name: "Diploma in Financial Information Systems",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Financial information systems",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Financial Systems Analyst",
          "Database Administrator",
          "Financial Officer",
        ],
      },
      {
        id: createDegreeId("Diploma Accountancy WSU"),
        name: "Diploma in Accountancy",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Accounting and financial management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Accounting", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Bookkeeper",
          "Accounting Clerk",
          "Junior Accountant",
        ],
      },
      {
        id: createDegreeId("Diploma Internal Auditing WSU"),
        name: "Diploma in Internal Auditing",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Internal auditing and financial control",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Accounting", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Internal Auditor",
          "Compliance Officer",
          "Risk Analyst",
        ],
      },
      // Extended Curriculum Programmes
      {
        id: createDegreeId("Diploma Office Management Technology ECP WSU"),
        name: "Diploma in Office Management and Technology (ECP)",
        faculty: "Management and Public Administration Sciences",
        duration: "4 years",
        apsRequirement: 21,
        description: "Extended office management program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Office Manager",
          "Administrative Coordinator",
          "Executive Assistant",
        ],
      },
      {
        id: createDegreeId("Diploma Local Government Finance ECP WSU"),
        name: "Diploma in Local Government Finance (ECP)",
        faculty: "Management and Public Administration Sciences",
        duration: "4 years",
        apsRequirement: 21,
        description: "Extended local government finance program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Municipal Finance Officer",
          "Local Government Accountant",
          "Budget Analyst",
        ],
      },
      {
        id: createDegreeId("Diploma Management ECP WSU"),
        name: "Diploma in Management (ECP)",
        faculty: "Management and Public Administration Sciences",
        duration: "4 years",
        apsRequirement: 21,
        description: "Extended management program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: ["Manager", "Supervisor", "Team Leader"],
      },
      {
        id: createDegreeId("Diploma Human Resources Management ECP WSU"),
        name: "Diploma in Human Resources Management (ECP)",
        faculty: "Management and Public Administration Sciences",
        duration: "4 years",
        apsRequirement: 21,
        description: "Extended human resources management program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "HR Officer",
          "Recruitment Coordinator",
          "Personnel Administrator",
        ],
      },
      {
        id: createDegreeId("Diploma Public Relations ECP WSU"),
        name: "Diploma in Public Relations (ECP)",
        faculty: "Management and Public Administration Sciences",
        duration: "4 years",
        apsRequirement: 21,
        description: "Extended public relations program",
        subjects: [{ name: "English", level: 4, isRequired: true }],
        careerProspects: [
          "Public Relations Officer",
          "Communications Coordinator",
          "Media Liaison",
        ],
      },
      {
        id: createDegreeId("Diploma Internal Auditing ECP WSU"),
        name: "Diploma in Internal Auditing (ECP)",
        faculty: "Management and Public Administration Sciences",
        duration: "4 years",
        apsRequirement: 21,
        description: "Extended internal auditing program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
          { name: "Accounting", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Internal Auditor",
          "Compliance Officer",
          "Risk Analyst",
        ],
      },
      {
        id: createDegreeId("Higher Certificate Versatile Broadcasting WSU"),
        name: "Higher Certificate in Versatile Broadcasting",
        faculty: "Management and Public Administration Sciences",
        duration: "1 year",
        apsRequirement: 18,
        description:
          "Broadcasting and media production (requires English level 4 & one additional language level 3)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Home Language", level: 3, isRequired: true },
        ],
        careerProspects: ["Radio Presenter", "TV Producer", "Media Technician"],
      },
    ],
  },
];
