import { Faculty } from "@/types/university";
import { createDegreeId, createFacultyId } from "./base";

// Walter Sisulu University (WSU) - Faculty Data - Comprehensive Update
export const WSU_FACULTIES: Faculty[] = [
  {
    id: createFacultyId("Faculty of Education WSU"),
    name: "Faculty of Education",
    description: "Teacher education and educational programs",
    degrees: [
      {
        id: createDegreeId("BEd Foundation Phase Teaching WSU"),
        name: "Bachelor of Education in Foundation Phase Teaching",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description: "Foundation phase teaching (Grades R-3)",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Foundation Phase Teacher",
          "Primary School Teacher",
          "Educational Coordinator",
        ],
      },
      {
        id: createDegreeId(
          "BEd Senior Phase FET Economic Management Sciences WSU",
        ),
        name: "Bachelor of Education in Senior Phase and Further Education and Training Teaching (Economic & Management Sciences)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description:
          "Senior and FET phase teaching in Economic & Management Sciences",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Accounting", level: 4, isRequired: true },
        ],
        careerProspects: [
          "High School Teacher",
          "Business Studies Teacher",
          "Economics Teacher",
        ],
      },
      {
        id: createDegreeId(
          "BEd Senior Phase FET Consumer Management Sciences WSU",
        ),
        name: "Bachelor of Education in Senior Phase and Further Education and Training Teaching (Consumer and Management Sciences)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description:
          "Senior and FET phase teaching in Consumer and Management Sciences",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Consumer Studies", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Consumer Studies Teacher",
          "Management Sciences Teacher",
          "Life Skills Teacher",
        ],
      },
      {
        id: createDegreeId("BEd Senior Phase FET Creative Arts WSU"),
        name: "Bachelor of Education in Senior Phase and Further Education and Training Teaching (Creative Arts)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description: "Senior and FET phase teaching in Creative Arts",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Visual Arts", level: 4, isRequired: true },
        ],
        careerProspects: ["Arts Teacher", "Drama Teacher", "Music Teacher"],
      },
      {
        id: createDegreeId("BEd Senior Phase FET Humanities WSU"),
        name: "Bachelor of Education in Senior Phase and Further Education and Training Teaching (Humanities)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description: "Senior and FET phase teaching in Humanities",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "History", level: 4, isRequired: true },
          { name: "Geography", level: 4, isRequired: true },
        ],
        careerProspects: [
          "History Teacher",
          "Geography Teacher",
          "Social Sciences Teacher",
        ],
      },
      {
        id: createDegreeId("BEd Senior Phase FET Languages WSU"),
        name: "Bachelor of Education in Senior Phase and Further Education and Training Teaching (Languages)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description: "Senior and FET phase teaching in Languages",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Home Language", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Language Teacher",
          "English Teacher",
          "Literature Teacher",
        ],
      },
      {
        id: createDegreeId(
          "BEd Senior Phase FET Mathematics Science Technology WSU",
        ),
        name: "Bachelor of Education in Senior Phase and Further Education and Training Teaching (Mathematics, Science & Technology)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description:
          "Senior and FET phase teaching in Mathematics, Science & Technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 5, isRequired: true },
          { name: "Physical Sciences", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Mathematics Teacher",
          "Science Teacher",
          "Technology Teacher",
        ],
      },
      {
        id: createDegreeId(
          "BEd Senior Phase FET Technical Vocational Education WSU",
        ),
        name: "Bachelor of Education in Senior Phase and Further Education and Training Teaching (Technical and Vocational Education)",
        faculty: "Education",
        duration: "4 years",
        apsRequirement: 26,
        description:
          "Senior and FET phase teaching in Technical and Vocational Education",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          {
            name: "Engineering Graphics and Design",
            level: 4,
            isRequired: true,
          },
        ],
        careerProspects: [
          "Technical Education Teacher",
          "Vocational Training Instructor",
          "Skills Development Facilitator",
        ],
      },
      {
        id: createDegreeId("Diploma Adult Community Education Training WSU"),
        name: "Diploma in Adult and Community Education and Training (ACET)",
        faculty: "Education",
        duration: "3 years",
        apsRequirement: 21,
        description: "Adult and community education and training",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Adult Education Facilitator",
          "Community Education Officer",
          "Training Coordinator",
        ],
      },
    ],
  },
  {
    id: createFacultyId("Faculty of Law Humanities Social Sciences WSU"),
    name: "Faculty of Law, Humanities and Social Sciences",
    description: "Legal, humanities, and social science programs",
    degrees: [
      {
        id: createDegreeId("Diploma Fine Art WSU"),
        name: "Diploma in Fine Art",
        faculty: "Law, Humanities and Social Sciences",
        duration: "3 years",
        apsRequirement: 20,
        description: "Fine art and visual arts",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Visual Arts", level: 4, isRequired: true },
        ],
        careerProspects: ["Artist", "Art Teacher", "Art Therapist"],
      },
      {
        id: createDegreeId("Advanced Diploma Fine Art WSU"),
        name: "Advanced Diploma in Fine Art",
        faculty: "Law, Humanities and Social Sciences",
        duration: "1 year",
        apsRequirement: 20,
        description: "Advanced fine art specialization",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Visual Arts", level: 5, isRequired: true },
        ],
        careerProspects: [
          "Professional Artist",
          "Art Director",
          "Gallery Curator",
        ],
      },
      {
        id: createDegreeId("Diploma Fashion WSU"),
        name: "Diploma in Fashion",
        faculty: "Law, Humanities and Social Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Fashion design and merchandising",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Visual Arts", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Fashion Designer",
          "Fashion Merchandiser",
          "Textile Designer",
        ],
      },
      {
        id: createDegreeId("BA WSU"),
        name: "Bachelor of Arts",
        faculty: "Law, Humanities and Social Sciences",
        duration: "3 years",
        apsRequirement: 27,
        description: "General arts and humanities",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Home Language", level: 4, isRequired: true },
        ],
        careerProspects: ["Social Worker", "Journalist", "Government Official"],
      },
      {
        id: createDegreeId("BSocSc WSU"),
        name: "Bachelor of Social Science",
        faculty: "Law, Humanities and Social Sciences",
        duration: "3 years",
        apsRequirement: 27,
        description: "Social sciences and community studies",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "History", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Social Researcher",
          "Community Worker",
          "Policy Analyst",
        ],
      },
      {
        id: createDegreeId("BSocSc Extended WSU"),
        name: "Bachelor of Social Science (Extended Curriculum Programme)",
        faculty: "Law, Humanities and Social Sciences",
        duration: "4 years",
        apsRequirement: 26,
        description: "Extended social sciences program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "History", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Social Researcher",
          "Community Worker",
          "Policy Analyst",
        ],
      },
      {
        id: createDegreeId("LLB WSU"),
        name: "Bachelor of Laws (LLB)",
        faculty: "Law, Humanities and Social Sciences",
        duration: "4 years",
        apsRequirement: 28,
        description: "Professional legal qualification",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: ["Lawyer", "Attorney", "Legal Consultant"],
      },
      {
        id: createDegreeId("Bachelor Social Work WSU"),
        name: "Bachelor of Social Work",
        faculty: "Law, Humanities and Social Sciences",
        duration: "4 years",
        apsRequirement: 28,
        description: "Professional social work practice",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Social Worker",
          "Community Developer",
          "Family Counselor",
        ],
      },
      {
        id: createDegreeId("Bachelor Psychology WSU"),
        name: "Bachelor of Psychology",
        faculty: "Law, Humanities and Social Sciences",
        duration: "3 years",
        apsRequirement: 28,
        description: "Psychology theory and practice",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Sciences", level: 4, isRequired: true },
        ],
        careerProspects: ["Psychologist", "Counselor", "Researcher"],
      },
    ],
  },
  {
    id: createFacultyId(
      "Faculty of Management Public Administration Sciences WSU",
    ),
    name: "Faculty of Management and Public Administration Sciences",
    description: "Management, administration, and business programs",
    degrees: [
      {
        id: createDegreeId("Bachelor Administration WSU"),
        name: "Bachelor of Administration",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 30,
        description: "Public and business administration",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Administrator",
          "Public Service Officer",
          "Management Trainee",
        ],
      },
      {
        id: createDegreeId("Diploma Administrative Management WSU"),
        name: "Diploma in Administrative Management",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Administrative management and coordination",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Administrative Manager",
          "Office Manager",
          "Administrative Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma Journalism WSU"),
        name: "Diploma in Journalism",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Journalism and media reporting",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Home Language", level: 4, isRequired: true },
        ],
        careerProspects: ["Journalist", "Reporter", "Media Correspondent"],
      },
      {
        id: createDegreeId("Diploma Public Relations WSU"),
        name: "Diploma in Public Relations",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Public relations and communications",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Public Relations Officer",
          "Communications Specialist",
          "Media Liaison",
        ],
      },
      {
        id: createDegreeId("Diploma Public Management WSU"),
        name: "Diploma in Public Management",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Public sector management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Public Manager",
          "Government Official",
          "Municipal Officer",
        ],
      },
      {
        id: createDegreeId("Diploma Policing WSU"),
        name: "Diploma in Policing",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Police science and law enforcement",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: ["Police Officer", "Detective", "Security Manager"],
      },
      {
        id: createDegreeId("Diploma Local Government Finance WSU"),
        name: "Diploma in Local Government Finance",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Local government financial management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Municipal Financial Officer",
          "Local Government Accountant",
          "Budget Analyst",
        ],
      },
      {
        id: createDegreeId("Diploma Management WSU"),
        name: "Diploma in Management",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "General management principles",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: ["Manager", "Supervisor", "Operations Coordinator"],
      },
      {
        id: createDegreeId("Diploma Small Business Management WSU"),
        name: "Diploma in Small Business Management",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Small business and entrepreneurship",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Small Business Owner",
          "Entrepreneur",
          "Business Consultant",
        ],
      },
      {
        id: createDegreeId("Diploma Office Management Technology WSU"),
        name: "Diploma in Office Management and Technology",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Office management and technology systems",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Office Manager",
          "Administrative Assistant",
          "Executive Secretary",
        ],
      },
      {
        id: createDegreeId("Diploma Human Resources Management WSU"),
        name: "Diploma in Human Resources Management",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Human resource management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "HR Officer",
          "Recruitment Specialist",
          "Training Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma Tourism Management WSU"),
        name: "Diploma in Tourism Management",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Tourism and hospitality management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Geography", level: 4, isRequired: true },
        ],
        careerProspects: ["Tourism Manager", "Travel Consultant", "Tour Guide"],
      },
      {
        id: createDegreeId("Diploma Hospitality Management WSU"),
        name: "Diploma in Hospitality Management",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Hospitality and hotel management",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Consumer Studies", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Hotel Manager",
          "Restaurant Manager",
          "Event Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma Sport Management WSU"),
        name: "Diploma in Sport Management",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 22,
        description: "Sports management and administration",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Sports Manager",
          "Sports Administrator",
          "Recreation Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma Financial Information Systems WSU"),
        name: "Diploma in Financial Information Systems",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Financial information systems and technology",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Financial Systems Analyst",
          "Information Systems Officer",
          "Financial Technician",
        ],
      },
      {
        id: createDegreeId("Diploma Accountancy WSU"),
        name: "Diploma in Accountancy",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Basic accounting and bookkeeping",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Accounting", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Bookkeeper",
          "Accounting Clerk",
          "Financial Assistant",
        ],
      },
      {
        id: createDegreeId("Diploma Internal Auditing WSU"),
        name: "Diploma in Internal Auditing",
        faculty: "Management and Public Administration Sciences",
        duration: "3 years",
        apsRequirement: 21,
        description: "Internal auditing and compliance",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Accounting", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Internal Auditor",
          "Compliance Officer",
          "Risk Analyst",
        ],
      },
      {
        id: createDegreeId("Diploma Office Management Technology Extended WSU"),
        name: "Diploma in Office Management and Technology (ECP)",
        faculty: "Management and Public Administration Sciences",
        duration: "4 years",
        apsRequirement: 21,
        description: "Extended office management and technology program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "Office Manager",
          "Administrative Assistant",
          "Executive Secretary",
        ],
      },
      {
        id: createDegreeId("Diploma Local Government Finance Extended WSU"),
        name: "Diploma in Local Government Finance (ECP)",
        faculty: "Management and Public Administration Sciences",
        duration: "4 years",
        apsRequirement: 21,
        description: "Extended local government finance program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Municipal Financial Officer",
          "Local Government Accountant",
          "Budget Analyst",
        ],
      },
      {
        id: createDegreeId("Diploma Management Extended WSU"),
        name: "Diploma in Management (ECP)",
        faculty: "Management and Public Administration Sciences",
        duration: "4 years",
        apsRequirement: 21,
        description: "Extended management program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: ["Manager", "Supervisor", "Operations Coordinator"],
      },
      {
        id: createDegreeId("Diploma Human Resources Management Extended WSU"),
        name: "Diploma in Human Resources Management (ECP)",
        faculty: "Management and Public Administration Sciences",
        duration: "4 years",
        apsRequirement: 21,
        description: "Extended human resources management program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 3, isRequired: true },
        ],
        careerProspects: [
          "HR Officer",
          "Recruitment Specialist",
          "Training Coordinator",
        ],
      },
      {
        id: createDegreeId("Diploma Public Relations Extended WSU"),
        name: "Diploma in Public Relations (ECP)",
        faculty: "Management and Public Administration Sciences",
        duration: "4 years",
        apsRequirement: 21,
        description: "Extended public relations program",
        subjects: [
          { name: "English", level: 5, isRequired: true },
          { name: "Life Orientation", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Public Relations Officer",
          "Communications Specialist",
          "Media Liaison",
        ],
      },
      {
        id: createDegreeId("Diploma Internal Auditing Extended WSU"),
        name: "Diploma in Internal Auditing (ECP)",
        faculty: "Management and Public Administration Sciences",
        duration: "4 years",
        apsRequirement: 21,
        description: "Extended internal auditing program",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Mathematics", level: 4, isRequired: true },
          { name: "Accounting", level: 4, isRequired: true },
        ],
        careerProspects: [
          "Internal Auditor",
          "Compliance Officer",
          "Risk Analyst",
        ],
      },
      {
        id: createDegreeId("Higher Certificate Versatile Broadcasting WSU"),
        name: "Higher Certificate in Versatile Broadcasting",
        faculty: "Management and Public Administration Sciences",
        duration: "1 year",
        apsRequirement: 18,
        description: "Broadcasting and media production",
        subjects: [
          { name: "English", level: 4, isRequired: true },
          { name: "Home Language", level: 3, isRequired: true },
        ],
        careerProspects: ["Radio Presenter", "TV Producer", "Media Technician"],
      },
    ],
  },
];
