// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

import { ENV, validateEnvironment } from "@/config/environment";

// Validate environment configuration (non-blocking)
const isValidEnvironment = validateEnvironment();

// Log configuration status
if (!isValidEnvironment) {
  console.warn(
    "⚠️ Supabase client initialized with default/fallback configuration",
  );
} else {
  console.log("✅ Supabase client initialized successfully");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  ENV.VITE_SUPABASE_URL,
  ENV.VITE_SUPABASE_ANON_KEY,
);
